// @gen3-stub
// Not ported yet: gen1recomp src/world/OverworldController.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class OverworldState {
  [key: string]: any;
  static [key: string]: any;
  static withOverrideMirror: any = undefined;
  static objectVisible: any = undefined;
  static pooledNPC: any = undefined;
  static computeNeighbors(..._a: any[]): any { return notPorted("OverworldState.computeNeighbors"); }
  static perMapWorldPalettes(..._a: any[]): any { return notPorted("OverworldState.perMapWorldPalettes"); }
  static fishAnimFrames(..._a: any[]): any { return notPorted("OverworldState.fishAnimFrames"); }
  static stepFishAnim(..._a: any[]): any { return notPorted("OverworldState.stepFishAnim"); }
  static benchGuyText(..._a: any[]): any { return notPorted("OverworldState.benchGuyText"); }
  static hiddenCoinPayout(..._a: any[]): any { return notPorted("OverworldState.hiddenCoinPayout"); }
  static stepHealAnim(..._a: any[]): any { return notPorted("OverworldState.stepHealAnim"); }
  static prepareTrainerBattle(..._a: any[]): any { return notPorted("OverworldState.prepareTrainerBattle"); }
  static rewrittenLastMap(..._a: any[]): any { return notPorted("OverworldState.rewrittenLastMap"); }
  static warpFade(..._a: any[]): any { return notPorted("OverworldState.warpFade"); }
  exit(..._a: any[]): any { return notPorted("OverworldState:exit"); }
  enter(..._a: any[]): any { return notPorted("OverworldState:enter"); }
  stampClosedDoors(..._a: any[]): any { return notPorted("OverworldState:stampClosedDoors"); }
  setMap(..._a: any[]): any { return notPorted("OverworldState:setMap"); }
  rebuildNeighbors(..._a: any[]): any { return notPorted("OverworldState:rebuildNeighbors"); }
  liveMaps(..._a: any[]): any { return notPorted("OverworldState:liveMaps"); }
  isNeighborMap(..._a: any[]): any { return notPorted("OverworldState:isNeighborMap"); }
  rebuildGhosts(..._a: any[]): any { return notPorted("OverworldState:rebuildGhosts"); }
  applyPendingSpawnResets(..._a: any[]): any { return notPorted("OverworldState:applyPendingSpawnResets"); }
  timeOfDay(..._a: any[]): any { return notPorted("OverworldState:timeOfDay"); }
  paletteNameFor(..._a: any[]): any { return notPorted("OverworldState:paletteNameFor"); }
  screenPaletteName(..._a: any[]): any { return notPorted("OverworldState:screenPaletteName"); }
  sgbPalettes(..._a: any[]): any { return notPorted("OverworldState:sgbPalettes"); }
  sgbWorldZones(..._a: any[]): any { return notPorted("OverworldState:sgbWorldZones"); }
  setDark(..._a: any[]): any { return notPorted("OverworldState:setDark"); }
  npcByIndex(..._a: any[]): any { return notPorted("OverworldState:npcByIndex"); }
  bikeAllowed(..._a: any[]): any { return notPorted("OverworldState:bikeAllowed"); }
  useBicycle(..._a: any[]): any { return notPorted("OverworldState:useBicycle"); }
  useFlashFieldMove(..._a: any[]): any { return notPorted("OverworldState:useFlashFieldMove"); }
  useStrengthFieldMove(..._a: any[]): any { return notPorted("OverworldState:useStrengthFieldMove"); }
  useSoftboiledFieldMove(..._a: any[]): any { return notPorted("OverworldState:useSoftboiledFieldMove"); }
  isDungeonTransitionMap(..._a: any[]): any { return notPorted("OverworldState:isDungeonTransitionMap"); }
  pushBattle(..._a: any[]): any { return notPorted("OverworldState:pushBattle"); }
  oamCulled(..._a: any[]): any { return notPorted("OverworldState:oamCulled"); }
  queueScript(..._a: any[]): any { return notPorted("OverworldState:queueScript"); }
  drainPendingScripts(..._a: any[]): any { return notPorted("OverworldState:drainPendingScripts"); }
  startParallel(..._a: any[]): any { return notPorted("OverworldState:startParallel"); }
  killParallel(..._a: any[]): any { return notPorted("OverworldState:killParallel"); }
  updateParallel(..._a: any[]): any { return notPorted("OverworldState:updateParallel"); }
  update(..._a: any[]): any { return notPorted("OverworldState:update"); }
  dirHeld(..._a: any[]): any { return notPorted("OverworldState:dirHeld"); }
  canCollisionWarp(..._a: any[]): any { return notPorted("OverworldState:canCollisionWarp"); }
  refreshStandingOnWarp(..._a: any[]): any { return notPorted("OverworldState:refreshStandingOnWarp"); }
  handleInput(..._a: any[]): any { return notPorted("OverworldState:handleInput"); }
  onSlopeMap(..._a: any[]): any { return notPorted("OverworldState:onSlopeMap"); }
  checkBoulderPush(..._a: any[]): any { return notPorted("OverworldState:checkBoulderPush"); }
  startDustAnim(..._a: any[]): any { return notPorted("OverworldState:startDustAnim"); }
  startSsAnneDeparture(..._a: any[]): any { return notPorted("OverworldState:startSsAnneDeparture"); }
  tickShipAnim(..._a: any[]): any { return notPorted("OverworldState:tickShipAnim"); }
  drawShipAnim(..._a: any[]): any { return notPorted("OverworldState:drawShipAnim"); }
  checkLedgeHop(..._a: any[]): any { return notPorted("OverworldState:checkLedgeHop"); }
  finishLedgeHop(..._a: any[]): any { return notPorted("OverworldState:finishLedgeHop"); }
  checkEdgeExit(..._a: any[]): any { return notPorted("OverworldState:checkEdgeExit"); }
  connectionLanding(..._a: any[]): any { return notPorted("OverworldState:connectionLanding"); }
  crossConnection(..._a: any[]): any { return notPorted("OverworldState:crossConnection"); }
  stepForwardOrCrossEdge(..._a: any[]): any { return notPorted("OverworldState:stepForwardOrCrossEdge"); }
  facingIsShoreOrWater(..._a: any[]): any { return notPorted("OverworldState:facingIsShoreOrWater"); }
  facingIsLandDismount(..._a: any[]): any { return notPorted("OverworldState:facingIsLandDismount"); }
  partyKnows(..._a: any[]): any { return notPorted("OverworldState:partyKnows"); }
  syncSurfingPikachu(..._a: any[]): any { return notPorted("OverworldState:syncSurfingPikachu"); }
  hidePikachuForWarp(..._a: any[]): any { return notPorted("OverworldState:hidePikachuForWarp"); }
  showPikachuAfterWarp(..._a: any[]): any { return notPorted("OverworldState:showPikachuAfterWarp"); }
  tickFishAnim(..._a: any[]): any { return notPorted("OverworldState:tickFishAnim"); }
  goFishing(..._a: any[]): any { return notPorted("OverworldState:goFishing"); }
  fishVerdict(..._a: any[]): any { return notPorted("OverworldState:fishVerdict"); }
  useFishingRod(..._a: any[]): any { return notPorted("OverworldState:useFishingRod"); }
  flyTo(..._a: any[]): any { return notPorted("OverworldState:flyTo"); }
  beginTeleportOut(..._a: any[]): any { return notPorted("OverworldState:beginTeleportOut"); }
  npcAtCell(..._a: any[]): any { return notPorted("OverworldState:npcAtCell"); }
  pushableAtCell(..._a: any[]): any { return notPorted("OverworldState:pushableAtCell"); }
  interact(..._a: any[]): any { return notPorted("OverworldState:interact"); }
  tryBookshelf(..._a: any[]): any { return notPorted("OverworldState:tryBookshelf"); }
  tryHiddenObject(..._a: any[]): any { return notPorted("OverworldState:tryHiddenObject"); }
  tryCardKeyDoor(..._a: any[]): any { return notPorted("OverworldState:tryCardKeyDoor"); }
  trashCanSwitch(..._a: any[]): any { return notPorted("OverworldState:trashCanSwitch"); }
  billsHousePC(..._a: any[]): any { return notPorted("OverworldState:billsHousePC"); }
  billsHousePokemonList(..._a: any[]): any { return notPorted("OverworldState:billsHousePokemonList"); }
  billsHouseBillExits(..._a: any[]): any { return notPorted("OverworldState:billsHouseBillExits"); }
  billsHouseSSTicketScene(..._a: any[]): any { return notPorted("OverworldState:billsHouseSSTicketScene"); }
  hasHiddenItemLeft(..._a: any[]): any { return notPorted("OverworldState:hasHiddenItemLeft"); }
  tilesetHasWater(..._a: any[]): any { return notPorted("OverworldState:tilesetHasWater"); }
  surfBlockedHere(..._a: any[]): any { return notPorted("OverworldState:surfBlockedHere"); }
  trySurf(..._a: any[]): any { return notPorted("OverworldState:trySurf"); }
  stopSurfing(..._a: any[]): any { return notPorted("OverworldState:stopSurfing"); }
  stopSurfingOntoLand(..._a: any[]): any { return notPorted("OverworldState:stopSurfingOntoLand"); }
  tryCut(..._a: any[]): any { return notPorted("OverworldState:tryCut"); }
  startCutTreeAnim(..._a: any[]): any { return notPorted("OverworldState:startCutTreeAnim"); }
  useSurfFieldMove(..._a: any[]): any { return notPorted("OverworldState:useSurfFieldMove"); }
  useCutFieldMove(..._a: any[]): any { return notPorted("OverworldState:useCutFieldMove"); }
  talkTo(..._a: any[]): any { return notPorted("OverworldState:talkTo"); }
  openPC(..._a: any[]): any { return notPorted("OverworldState:openPC"); }
  openOaksPC(..._a: any[]): any { return notPorted("OverworldState:openOaksPC"); }
  dexRating(..._a: any[]): any { return notPorted("OverworldState:dexRating"); }
  nurseHeal(..._a: any[]): any { return notPorted("OverworldState:nurseHeal"); }
  finishNurseHeal(..._a: any[]): any { return notPorted("OverworldState:finishNurseHeal"); }
  cableClubReceptionist(..._a: any[]): any { return notPorted("OverworldState:cableClubReceptionist"); }
  trainerDefeated(..._a: any[]): any { return notPorted("OverworldState:trainerDefeated"); }
  playTrainerMusic(..._a: any[]): any { return notPorted("OverworldState:playTrainerMusic"); }
  engageTrainer(..._a: any[]): any { return notPorted("OverworldState:engageTrainer"); }
  checkVictoryRewards(..._a: any[]): any { return notPorted("OverworldState:checkVictoryRewards"); }
  offerGymTm(..._a: any[]): any { return notPorted("OverworldState:offerGymTm"); }
  runVictoryHook(..._a: any[]): any { return notPorted("OverworldState:runVictoryHook"); }
  checkTrainerSight(..._a: any[]): any { return notPorted("OverworldState:checkTrainerSight"); }
  startTrainerApproach(..._a: any[]): any { return notPorted("OverworldState:startTrainerApproach"); }
  makeNpcFacePlayer(..._a: any[]): any { return notPorted("OverworldState:makeNpcFacePlayer"); }
  applyPendingFace(..._a: any[]): any { return notPorted("OverworldState:applyPendingFace"); }
  showMapText(..._a: any[]): any { return notPorted("OverworldState:showMapText"); }
  tickPoisonFlash(..._a: any[]): any { return notPorted("OverworldState:tickPoisonFlash"); }
  poisonFlashLive(..._a: any[]): any { return notPorted("OverworldState:poisonFlashLive"); }
  poisonShadeMap(..._a: any[]): any { return notPorted("OverworldState:poisonShadeMap"); }
  applyFieldPoison(..._a: any[]): any { return notPorted("OverworldState:applyFieldPoison"); }
  rollEncounter(..._a: any[]): any { return notPorted("OverworldState:rollEncounter"); }
  onStepComplete(..._a: any[]): any { return notPorted("OverworldState:onStepComplete"); }
  checkSpinner(..._a: any[]): any { return notPorted("OverworldState:checkSpinner"); }
  runSpinnerMoves(..._a: any[]): any { return notPorted("OverworldState:runSpinnerMoves"); }
  syncLastMapRewrite(..._a: any[]): any { return notPorted("OverworldState:syncLastMapRewrite"); }
  checkBadgeGate(..._a: any[]): any { return notPorted("OverworldState:checkBadgeGate"); }
  checkForcedMovement(..._a: any[]): any { return notPorted("OverworldState:checkForcedMovement"); }
  checkSeafoamCurrent(..._a: any[]): any { return notPorted("OverworldState:checkSeafoamCurrent"); }
  seafoamHolesFor(..._a: any[]): any { return notPorted("OverworldState:seafoamHolesFor"); }
  boulderIntoHole(..._a: any[]): any { return notPorted("OverworldState:boulderIntoHole"); }
  inSafariStepZone(..._a: any[]): any { return notPorted("OverworldState:inSafariStepZone"); }
  safariStep(..._a: any[]): any { return notPorted("OverworldState:safariStep"); }
  safariGameOver(..._a: any[]): any { return notPorted("OverworldState:safariGameOver"); }
  afterBattle(..._a: any[]): any { return notPorted("OverworldState:afterBattle"); }
  restoreBattleContinuation(..._a: any[]): any { return notPorted("OverworldState:restoreBattleContinuation"); }
  healPoint(..._a: any[]): any { return notPorted("OverworldState:healPoint"); }
  takeWarp(..._a: any[]): any { return notPorted("OverworldState:takeWarp"); }
  fallThroughHole(..._a: any[]): any { return notPorted("OverworldState:fallThroughHole"); }
  rememberOutdoor(..._a: any[]): any { return notPorted("OverworldState:rememberOutdoor"); }
  escapeWarpTarget(..._a: any[]): any { return notPorted("OverworldState:escapeWarpTarget"); }
  warpToHealPoint(..._a: any[]): any { return notPorted("OverworldState:warpToHealPoint"); }
  startWarpTo(..._a: any[]): any { return notPorted("OverworldState:startWarpTo"); }
  reloadMap(..._a: any[]): any { return notPorted("OverworldState:reloadMap"); }
  addRuntimeObject(..._a: any[]): any { return notPorted("OverworldState:addRuntimeObject"); }
  removeRuntimeObject(..._a: any[]): any { return notPorted("OverworldState:removeRuntimeObject"); }
  replaceBlock(..._a: any[]): any { return notPorted("OverworldState:replaceBlock"); }
  scriptMove(..._a: any[]): any { return notPorted("OverworldState:scriptMove"); }
  marchInPlace(..._a: any[]): any { return notPorted("OverworldState:marchInPlace"); }
  updateScriptMoves(..._a: any[]): any { return notPorted("OverworldState:updateScriptMoves"); }
  bakedWorldColors(..._a: any[]): any { return notPorted("OverworldState:bakedWorldColors"); }
  warpFadeUniforms(..._a: any[]): any { return notPorted("OverworldState:warpFadeUniforms"); }
  drawWorldFaded(..._a: any[]): any { return notPorted("OverworldState:drawWorldFaded"); }
  draw(..._a: any[]): any { return notPorted("OverworldState:draw"); }
  drawWipeSprites(..._a: any[]): any { return notPorted("OverworldState:drawWipeSprites"); }
  billboard(..._a: any[]): any { return notPorted("OverworldState:billboard"); }
  drawWorld(..._a: any[]): any { return notPorted("OverworldState:drawWorld"); }
  drawUI(..._a: any[]): any { return notPorted("OverworldState:drawUI"); }
  captureSave(..._a: any[]): any { return notPorted("OverworldState:captureSave"); }
}
export default OverworldState;
