// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/healing.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Healing: Record<string, any> = {
  refresh: (..._a: any[]): any => { return notPorted("Healing.refresh"); },
  ingrain: (..._a: any[]): any => { return notPorted("Healing.ingrain"); },
  recover: (..._a: any[]): any => { return notPorted("Healing.recover"); },
  softboiled: (..._a: any[]): any => { return notPorted("Healing.softboiled"); },
  morningSun: (..._a: any[]): any => { return notPorted("Healing.morningSun"); },
  rest: (..._a: any[]): any => { return notPorted("Healing.rest"); },
  bellyDrum: (..._a: any[]): any => { return notPorted("Healing.bellyDrum"); },
  wish: (..._a: any[]): any => { return notPorted("Healing.wish"); },
  healBell: (..._a: any[]): any => { return notPorted("Healing.healBell"); },
  painSplit: (..._a: any[]): any => { return notPorted("Healing.painSplit"); },
  swallow: (..._a: any[]): any => { return notPorted("Healing.swallow"); },
};
export default Healing;
