// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/init.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Effects: Record<string, any> = {
  get: (..._a: any[]): any => { return notPorted("Effects.get"); },
  run: (..._a: any[]): any => { return notPorted("Effects.run"); },
  runForMove: (..._a: any[]): any => { return notPorted("Effects.runForMove"); },
  ids: (..._a: any[]): any => { return notPorted("Effects.ids"); },
};
export default Effects;
