// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/screens.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Screens: Record<string, any> = {
  safeguard: (..._a: any[]): any => { return notPorted("Screens.safeguard"); },
  reflect: (..._a: any[]): any => { return notPorted("Screens.reflect"); },
  lightScreen: (..._a: any[]): any => { return notPorted("Screens.lightScreen"); },
  mist: (..._a: any[]): any => { return notPorted("Screens.mist"); },
};
export default Screens;
