// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/setup.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Setup: Record<string, any> = {
  TERRAIN_TYPE: undefined,
  meanLook: (..._a: any[]): any => { return notPorted("Setup.meanLook"); },
  leechSeed: (..._a: any[]): any => { return notPorted("Setup.leechSeed"); },
  destinyBond: (..._a: any[]): any => { return notPorted("Setup.destinyBond"); },
  nightmare: (..._a: any[]): any => { return notPorted("Setup.nightmare"); },
  focusEnergy: (..._a: any[]): any => { return notPorted("Setup.focusEnergy"); },
  foresight: (..._a: any[]): any => { return notPorted("Setup.foresight"); },
  lockOn: (..._a: any[]): any => { return notPorted("Setup.lockOn"); },
  magicCoat: (..._a: any[]): any => { return notPorted("Setup.magicCoat"); },
  grudge: (..._a: any[]): any => { return notPorted("Setup.grudge"); },
  imprison: (..._a: any[]): any => { return notPorted("Setup.imprison"); },
  snatch: (..._a: any[]): any => { return notPorted("Setup.snatch"); },
  mudSport: (..._a: any[]): any => { return notPorted("Setup.mudSport"); },
  waterSport: (..._a: any[]): any => { return notPorted("Setup.waterSport"); },
  camouflage: (..._a: any[]): any => { return notPorted("Setup.camouflage"); },
  rolePlay: (..._a: any[]): any => { return notPorted("Setup.rolePlay"); },
  skillSwap: (..._a: any[]): any => { return notPorted("Setup.skillSwap"); },
  futureSight: (..._a: any[]): any => { return notPorted("Setup.futureSight"); },
  curse: (..._a: any[]): any => { return notPorted("Setup.curse"); },
  batonPass: (..._a: any[]): any => { return notPorted("Setup.batonPass"); },
  helpingHand: (..._a: any[]): any => { return notPorted("Setup.helpingHand"); },
  splash: (..._a: any[]): any => { return notPorted("Setup.splash"); },
  confuse: (..._a: any[]): any => { return notPorted("Setup.confuse"); },
  haze: (..._a: any[]): any => { return notPorted("Setup.haze"); },
  substitute: (..._a: any[]): any => { return notPorted("Setup.substitute"); },
  teeterDance: (..._a: any[]): any => { return notPorted("Setup.teeterDance"); },
};
export default Setup;
