// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/special.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Special: Record<string, any> = {
  roar: (..._a: any[]): any => { return notPorted("Special.roar"); },
  conversion: (..._a: any[]): any => { return notPorted("Special.conversion"); },
  conversion2: (..._a: any[]): any => { return notPorted("Special.conversion2"); },
  transform: (..._a: any[]): any => { return notPorted("Special.transform"); },
  mimic: (..._a: any[]): any => { return notPorted("Special.mimic"); },
  disable: (..._a: any[]): any => { return notPorted("Special.disable"); },
  sketch: (..._a: any[]): any => { return notPorted("Special.sketch"); },
  batonPass: (..._a: any[]): any => { return notPorted("Special.batonPass"); },
  teleport: (..._a: any[]): any => { return notPorted("Special.teleport"); },
  followMe: (..._a: any[]): any => { return notPorted("Special.followMe"); },
  trick: (..._a: any[]): any => { return notPorted("Special.trick"); },
  recycle: (..._a: any[]): any => { return notPorted("Special.recycle"); },
};
export default Special;
