// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/volatiles.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Volatiles: Record<string, any> = {
  protect: (..._a: any[]): any => { return notPorted("Volatiles.protect"); },
  endure: (..._a: any[]): any => { return notPorted("Volatiles.endure"); },
  encore: (..._a: any[]): any => { return notPorted("Volatiles.encore"); },
  perishSong: (..._a: any[]): any => { return notPorted("Volatiles.perishSong"); },
  attract: (..._a: any[]): any => { return notPorted("Volatiles.attract"); },
  spite: (..._a: any[]): any => { return notPorted("Volatiles.spite"); },
  torment: (..._a: any[]): any => { return notPorted("Volatiles.torment"); },
};
export default Volatiles;
