// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/effects/weather.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Weather: Record<string, any> = {
  sunny: (..._a: any[]): any => { return notPorted("Weather.sunny"); },
  rainy: (..._a: any[]): any => { return notPorted("Weather.rainy"); },
  sandstorm: (..._a: any[]): any => { return notPorted("Weather.sandstorm"); },
  hail: (..._a: any[]): any => { return notPorted("Weather.hail"); },
};
export default Weather;
