// @gen2-stub
// Not ported yet: gen1recomp src/ui/Marquee.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Marquee: Record<string, any> = {
  HOLD: undefined,
  STEP: undefined,
  at: (..._a: any[]): any => notPorted("Marquee.at"),
  scroll: (..._a: any[]): any => notPorted("Marquee.scroll"),
  clip: (..._a: any[]): any => notPorted("Marquee.clip"),
};
export default Marquee;
