// @gen2-stub
// Not ported yet: gen1recomp src/ui/MenuRepeat.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const MenuRepeat: Record<string, any> = {
  new: (..._a: any[]): any => notPorted("MenuRepeat.new"),
  reset: (..._a: any[]): any => notPorted("MenuRepeat.reset"),
  direction: (..._a: any[]): any => notPorted("MenuRepeat.direction"),
};
export default MenuRepeat;
