// @gen2-stub
// Not ported yet: gen1recomp src/ui/Screens.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Screens: Record<string, any> = {
  GEN2_IDS: undefined,
  get: (..._a: any[]): any => notPorted("Screens.get"),
  build: (..._a: any[]): any => notPorted("Screens.build"),
  push: (..._a: any[]): any => notPorted("Screens.push"),
  invalidate: (..._a: any[]): any => notPorted("Screens.invalidate"),
};
export default Screens;
