// @gen2-stub
// Not ported yet: gen1recomp src/online/ArenaBoot.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const ArenaBoot: Record<string, any> = {
  profile: (..._a: any[]): any => notPorted("ArenaBoot.profile"),
  spec: (..._a: any[]): any => notPorted("ArenaBoot.spec"),
  battleOpts: (..._a: any[]): any => notPorted("ArenaBoot.battleOpts"),
  packOwnParty: (..._a: any[]): any => notPorted("ArenaBoot.packOwnParty"),
};
export default ArenaBoot;
