// @gen3-stub
// Not ported yet: gen1recomp src/ui/NamingScreen.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class NamingScreen {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static invalidate(..._a: any[]): any { return notPorted("NamingScreen.invalidate"); }
  static new(..._a: any[]): any { return notPorted("NamingScreen.new"); }
  sgbPalettes(..._a: any[]): any { return notPorted("NamingScreen:sgbPalettes"); }
  enter(..._a: any[]): any { return notPorted("NamingScreen:enter"); }
  confirm(..._a: any[]): any { return notPorted("NamingScreen:confirm"); }
  grid(..._a: any[]): any { return notPorted("NamingScreen:grid"); }
  jumpToEnd(..._a: any[]): any { return notPorted("NamingScreen:jumpToEnd"); }
  update(..._a: any[]): any { return notPorted("NamingScreen:update"); }
  draw(..._a: any[]): any { return notPorted("NamingScreen:draw"); }
}
export default NamingScreen;
