// @gen3-stub
// Not ported yet: gen1recomp src/ui/Theme.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Theme: Record<string, any> = {
  load: (..._a: any[]): any => { return notPorted("Theme.load"); },
};
export default Theme;
