// @gen2-stub
// Not ported yet: gen1recomp src/core/DiscordPresence.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const DiscordPresence: Record<string, any> = {
  _state: undefined,
  locationName: undefined,
  handleJoinRequest: undefined,
  setJoinCode: (..._a: any[]): any => notPorted("DiscordPresence.setJoinCode"),
  init: (..._a: any[]): any => notPorted("DiscordPresence.init"),
  update: (..._a: any[]): any => notPorted("DiscordPresence.update"),
  shutdown: (..._a: any[]): any => notPorted("DiscordPresence.shutdown"),
};
export default DiscordPresence;
