// @gen2-stub
// Not ported yet: gen1recomp src/core/FaithfulRes.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const FaithfulRes: Record<string, any> = {
  LEVELS: undefined,
  DEFAULT: undefined,
  mobileScale: undefined,
  locked: undefined,
  prevSize: undefined,
  isMobile: undefined,
  setNativeSize: (..._a: any[]): any => notPorted("FaithfulRes.setNativeSize"),
  maxLevel: (..._a: any[]): any => notPorted("FaithfulRes.maxLevel"),
  levels: (..._a: any[]): any => notPorted("FaithfulRes.levels"),
  normalize: (..._a: any[]): any => notPorted("FaithfulRes.normalize"),
  label: (..._a: any[]): any => notPorted("FaithfulRes.label"),
  cycle: (..._a: any[]): any => notPorted("FaithfulRes.cycle"),
  fixedDisplay: (..._a: any[]): any => notPorted("FaithfulRes.fixedDisplay"),
  size: (..._a: any[]): any => notPorted("FaithfulRes.size"),
  deviceScale: (..._a: any[]): any => notPorted("FaithfulRes.deviceScale"),
  scaleCap: (..._a: any[]): any => notPorted("FaithfulRes.scaleCap"),
  apply: (..._a: any[]): any => notPorted("FaithfulRes.apply"),
  applyOptions: (..._a: any[]): any => notPorted("FaithfulRes.applyOptions"),
};
export default FaithfulRes;
