// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/FrameCap.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const FrameCap: Record<string, any> = {
  STEPS: undefined,
  MIN: undefined,
  MAX: undefined,
  DEFAULT: undefined,
  DISPLAY: undefined,
  CYCLE: undefined,
  current: undefined,
  bootHandheld: undefined,
  loopSupportsPanelSync: (..._a: any[]): any => undefined,
  prefersPanelSync: (..._a: any[]): any => undefined,
  normalize: (..._a: any[]): any => undefined,
  label: (..._a: any[]): any => undefined,
  cycle: (..._a: any[]): any => undefined,
  apply: (..._a: any[]): any => undefined,
  applyOptions: (..._a: any[]): any => undefined,
  bootPanelSync: (..._a: any[]): any => undefined,
  clampToPerformance: (..._a: any[]): any => undefined,
};
export default FrameCap;
