// @gen2-stub
// Not ported yet: gen1recomp src/core/FrameCap.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const FrameCap: Record<string, any> = {
  STEPS: undefined,
  MIN: undefined,
  MAX: undefined,
  DEFAULT: undefined,
  DISPLAY: undefined,
  CYCLE: undefined,
  current: undefined,
  bootHandheld: undefined,
  loopSupportsPanelSync: (..._a: any[]): any => notPorted("FrameCap.loopSupportsPanelSync"),
  prefersPanelSync: (..._a: any[]): any => notPorted("FrameCap.prefersPanelSync"),
  normalize: (..._a: any[]): any => notPorted("FrameCap.normalize"),
  label: (..._a: any[]): any => notPorted("FrameCap.label"),
  cycle: (..._a: any[]): any => notPorted("FrameCap.cycle"),
  apply: (..._a: any[]): any => notPorted("FrameCap.apply"),
  applyOptions: (..._a: any[]): any => notPorted("FrameCap.applyOptions"),
  bootPanelSync: (..._a: any[]): any => notPorted("FrameCap.bootPanelSync"),
  clampToPerformance: (..._a: any[]): any => notPorted("FrameCap.clampToPerformance"),
};
export default FrameCap;
