// @gen2-stub
// Not ported yet: gen1recomp src/core/GameSpeed.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const GameSpeed: Record<string, any> = {
  LEVELS: undefined,
  DEFAULT: undefined,
  CATEGORIES: undefined,
  levelLabel: (..._a: any[]): any => notPorted("GameSpeed.levelLabel"),
  setAllowed: (..._a: any[]): any => notPorted("GameSpeed.setAllowed"),
  allowed: (..._a: any[]): any => notPorted("GameSpeed.allowed"),
  isLocked: (..._a: any[]): any => notPorted("GameSpeed.isLocked"),
  clamp: (..._a: any[]): any => notPorted("GameSpeed.clamp"),
  cycle: (..._a: any[]): any => notPorted("GameSpeed.cycle"),
  optionKey: (..._a: any[]): any => notPorted("GameSpeed.optionKey"),
};
export default GameSpeed;
