// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/GamepadMap.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const GamepadMap: Record<string, any> = {
  DEFAULT_GAMEPAD_BINDINGS: undefined,
  TRIGGER_AXES: undefined,
  TRIGGER_ON: undefined,
  TRIGGER_OFF: undefined,
  DEFAULT_PAD_ACTIONS: undefined,
  NX_GAMEPAD_BINDINGS: undefined,
  RAW_BUTTON_BINDINGS: undefined,
  NX_RAW_BUTTON_BINDINGS: undefined,
  RAW_TO_GAMEPAD_BUTTON: undefined,
  NX_RAW_TO_GAMEPAD_BUTTON: undefined,
  _forceNXForTests: undefined,
  _setForceNXForTests: (..._a: any[]): any => undefined,
  gamepadBindings: (..._a: any[]): any => undefined,
  rawBindings: (..._a: any[]): any => undefined,
  mapGamepadButton: (..._a: any[]): any => undefined,
  mapLauncherButton: (..._a: any[]): any => undefined,
  displayChordDigit: (..._a: any[]): any => undefined,
  ignoreRawForJoystick: (..._a: any[]): any => undefined,
  isAccelerometer: (..._a: any[]): any => undefined,
  mapRawButton: (..._a: any[]): any => undefined,
  mapRawToGamepadButton: (..._a: any[]): any => undefined,
};
export default GamepadMap;
