// @gen2-stub
// Not ported yet: gen1recomp src/core/Input.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class Input {
  [key: string]: any;
  static [key: string]: any;
  static PAD_ACTIONS: any = undefined;
  init(..._a: any[]): any { return notPorted("Input:init"); }
  applyBindings(..._a: any[]): any { return notPorted("Input:applyBindings"); }
  padAction(..._a: any[]): any { return notPorted("Input:padAction"); }
  joyAction(..._a: any[]): any { return notPorted("Input:joyAction"); }
  reset(..._a: any[]): any { return notPorted("Input:reset"); }
  setButtonAlias(..._a: any[]): any { return notPorted("Input:setButtonAlias"); }
  armCapture(..._a: any[]): any { return notPorted("Input:armCapture"); }
  disarmCapture(..._a: any[]): any { return notPorted("Input:disarmCapture"); }
  takeCaptureEvents(..._a: any[]): any { return notPorted("Input:takeCaptureEvents"); }
  keypressed(..._a: any[]): any { return notPorted("Input:keypressed"); }
  keyreleased(..._a: any[]): any { return notPorted("Input:keyreleased"); }
  step(..._a: any[]): any { return notPorted("Input:step"); }
  overlayPressed(..._a: any[]): any { return notPorted("Input:overlayPressed"); }
  overlayReleased(..._a: any[]): any { return notPorted("Input:overlayReleased"); }
  sourcePress(..._a: any[]): any { return notPorted("Input:sourcePress"); }
  sourceRelease(..._a: any[]): any { return notPorted("Input:sourceRelease"); }
  gamepadpressed(..._a: any[]): any { return notPorted("Input:gamepadpressed"); }
  gamepadreleased(..._a: any[]): any { return notPorted("Input:gamepadreleased"); }
  joystickpressed(..._a: any[]): any { return notPorted("Input:joystickpressed"); }
  joystickreleased(..._a: any[]): any { return notPorted("Input:joystickreleased"); }
  triggerAxis(..._a: any[]): any { return notPorted("Input:triggerAxis"); }
  gamepadaxis(..._a: any[]): any { return notPorted("Input:gamepadaxis"); }
  joystickaxis(..._a: any[]): any { return notPorted("Input:joystickaxis"); }
  joystickhat(..._a: any[]): any { return notPorted("Input:joystickhat"); }
  reconcile(..._a: any[]): any { return notPorted("Input:reconcile"); }
  isDown(..._a: any[]): any { return notPorted("Input:isDown"); }
  isTouchDown(..._a: any[]): any { return notPorted("Input:isTouchDown"); }
  wasPressed(..._a: any[]): any { return notPorted("Input:wasPressed"); }
  softResetHeld(..._a: any[]): any { return notPorted("Input:softResetHeld"); }
  softResetStep(..._a: any[]): any { return notPorted("Input:softResetStep"); }
}
export default Input;
