// @gen2-stub
// Not ported yet: gen1recomp src/core/Logger.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Logger: Record<string, any> = {
  info: (..._a: any[]): any => notPorted("Logger.info"),
  warn: (..._a: any[]): any => notPorted("Logger.warn"),
  error: (..._a: any[]): any => notPorted("Logger.error"),
};
export default Logger;
