// @gen2-stub
// Not ported yet: gen1recomp src/core/Performance.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Performance: Record<string, any> = {
  TIERS: undefined,
  LABELS: undefined,
  CAPS: undefined,
  tier: undefined,
  detect: (..._a: any[]): any => notPorted("Performance.detect"),
  resolve: (..._a: any[]): any => notPorted("Performance.resolve"),
  normalize: (..._a: any[]): any => notPorted("Performance.normalize"),
  label: (..._a: any[]): any => notPorted("Performance.label"),
  caps: (..._a: any[]): any => notPorted("Performance.caps"),
  applyOptions: (..._a: any[]): any => notPorted("Performance.applyOptions"),
  cycle: (..._a: any[]): any => notPorted("Performance.cycle"),
};
export default Performance;
