// @gen2-stub
// Not ported yet: gen1recomp src/core/PresentSync.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const PresentSync: Record<string, any> = {
  waitBeforePresent: (..._a: any[]): any => notPorted("PresentSync.waitBeforePresent"),
  notePresent: (..._a: any[]): any => notPorted("PresentSync.notePresent"),
  probingDisplaySync: (..._a: any[]): any => notPorted("PresentSync.probingDisplaySync"),
  needsSoftwareCap: (..._a: any[]): any => notPorted("PresentSync.needsSoftwareCap"),
  displaySyncConfirmed: (..._a: any[]): any => notPorted("PresentSync.displaySyncConfirmed"),
  hardwarePacesCap: (..._a: any[]): any => notPorted("PresentSync.hardwarePacesCap"),
  vsyncEnableBlocked: (..._a: any[]): any => notPorted("PresentSync.vsyncEnableBlocked"),
  vsyncStepAllowed: (..._a: any[]): any => notPorted("PresentSync.vsyncStepAllowed"),
  onDisplayChange: (..._a: any[]): any => notPorted("PresentSync.onDisplayChange"),
  reprobe: (..._a: any[]): any => notPorted("PresentSync.reprobe"),
  reset: (..._a: any[]): any => notPorted("PresentSync.reset"),
  status: (..._a: any[]): any => notPorted("PresentSync.status"),
  logicRefreshPeriod: (..._a: any[]): any => notPorted("PresentSync.logicRefreshPeriod"),
  applyFixedStepPeriod: (..._a: any[]): any => notPorted("PresentSync.applyFixedStepPeriod"),
};
export default PresentSync;
