// @gen2-stub
// Not ported yet: gen1recomp src/core/Printer.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Printer: Record<string, any> = {
  lastAlbumPath: undefined,
  save: (..._a: any[]): any => notPorted("Printer.save"),
  savedWhereText: (..._a: any[]): any => notPorted("Printer.savedWhereText"),
};
export default Printer;
