// @gen2-stub
// Not ported yet: gen1recomp src/core/RomText.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const RomText: Record<string, any> = {
};
export default RomText;
