// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/ScreenPosition.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const ScreenPosition: Record<string, any> = {
  MODES: undefined,
  DEFAULT: undefined,
  mode: undefined,
  normalize: (..._a: any[]): any => undefined,
  label: (..._a: any[]): any => undefined,
  cycle: (..._a: any[]): any => undefined,
  setMode: (..._a: any[]): any => undefined,
  applyOptions: (..._a: any[]): any => undefined,
  safeTop: (..._a: any[]): any => undefined,
  skinActive: (..._a: any[]): any => undefined,
  lift: (..._a: any[]): any => undefined,
};
export default ScreenPosition;
