// @gen2-stub
// Not ported yet: gen1recomp src/core/StateStack.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class StateStack {
  [key: string]: any;
  static [key: string]: any;
  init(..._a: any[]): any { return notPorted("StateStack:init"); }
  push(..._a: any[]): any { return notPorted("StateStack:push"); }
  pop(..._a: any[]): any { return notPorted("StateStack:pop"); }
  top(..._a: any[]): any { return notPorted("StateStack:top"); }
  clear(..._a: any[]): any { return notPorted("StateStack:clear"); }
  update(..._a: any[]): any { return notPorted("StateStack:update"); }
  renderVisible(..._a: any[]): any { return notPorted("StateStack:renderVisible"); }
  visibleBase(..._a: any[]): any { return notPorted("StateStack:visibleBase"); }
  draw(..._a: any[]): any { return notPorted("StateStack:draw"); }
}
export default StateStack;
