// @gen2-stub
// Not ported yet: gen1recomp src/core/Strings.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Strings: Record<string, any> = {
  load: (..._a: any[]): any => notPorted("Strings.load"),
  active: (..._a: any[]): any => notPorted("Strings.active"),
  lookup: (..._a: any[]): any => notPorted("Strings.lookup"),
  get: (..._a: any[]): any => notPorted("Strings.get"),
  source: (..._a: any[]): any => notPorted("Strings.source"),
};
export default Strings;
