// @gen2-stub
// Not ported yet: gen1recomp src/core/TouchControls.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class TouchControls {
  [key: string]: any;
  static [key: string]: any;
  static HAPTICS: any = undefined;
  static HAPTIC_DEFAULT: any = undefined;
  static surfaceRect: any = undefined;
  static CONTROLS: any = undefined;
  static ORIENTATIONS: any = undefined;
  static SCALE_STEP: any = undefined;
  static normalizeHaptics(..._a: any[]): any { return notPorted("TouchControls.normalizeHaptics"); }
  static hapticLabel(..._a: any[]): any { return notPorted("TouchControls.hapticLabel"); }
  static cycleHaptics(..._a: any[]): any { return notPorted("TouchControls.cycleHaptics"); }
  static buzz(..._a: any[]): any { return notPorted("TouchControls.buzz"); }
  static normalizeConfig(..._a: any[]): any { return notPorted("TouchControls.normalizeConfig"); }
  static defaultLayout(..._a: any[]): any { return notPorted("TouchControls.defaultLayout"); }
  init(..._a: any[]): any { return notPorted("TouchControls:init"); }
  ensureImages(..._a: any[]): any { return notPorted("TouchControls:ensureImages"); }
  applyOptions(..._a: any[]): any { return notPorted("TouchControls:applyOptions"); }
  config(..._a: any[]): any { return notPorted("TouchControls:config"); }
  setPreview(..._a: any[]): any { return notPorted("TouchControls:setPreview"); }
  visible(..._a: any[]): any { return notPorted("TouchControls:visible"); }
  selectSkin(..._a: any[]): any { return notPorted("TouchControls:selectSkin"); }
  skin(..._a: any[]): any { return notPorted("TouchControls:skin"); }
  setHotkeyHandler(..._a: any[]): any { return notPorted("TouchControls:setHotkeyHandler"); }
  currentBucket(..._a: any[]): any { return notPorted("TouchControls:currentBucket"); }
  layout(..._a: any[]): any { return notPorted("TouchControls:layout"); }
  setControlCenter(..._a: any[]): any { return notPorted("TouchControls:setControlCenter"); }
  clearPositions(..._a: any[]): any { return notPorted("TouchControls:clearPositions"); }
  setScale(..._a: any[]): any { return notPorted("TouchControls:setScale"); }
  nudgeScale(..._a: any[]): any { return notPorted("TouchControls:nudgeScale"); }
  hotbarItems(..._a: any[]): any { return notPorted("TouchControls:hotbarItems"); }
  hotbarShown(..._a: any[]): any { return notPorted("TouchControls:hotbarShown"); }
  hotbarStrip(..._a: any[]): any { return notPorted("TouchControls:hotbarStrip"); }
  hotbarCellAt(..._a: any[]): any { return notPorted("TouchControls:hotbarCellAt"); }
  hitTest(..._a: any[]): any { return notPorted("TouchControls:hitTest"); }
  touchpressed(..._a: any[]): any { return notPorted("TouchControls:touchpressed"); }
  touchmoved(..._a: any[]): any { return notPorted("TouchControls:touchmoved"); }
  touchreleased(..._a: any[]): any { return notPorted("TouchControls:touchreleased"); }
  reset(..._a: any[]): any { return notPorted("TouchControls:reset"); }
  noteGamepad(..._a: any[]): any { return notPorted("TouchControls:noteGamepad"); }
  joystickremoved(..._a: any[]): any { return notPorted("TouchControls:joystickremoved"); }
  drawSkin(..._a: any[]): any { return notPorted("TouchControls:drawSkin"); }
  draw(..._a: any[]): any { return notPorted("TouchControls:draw"); }
}
export default TouchControls;
