// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/VSync.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const VSync: Record<string, any> = {
  MODES: undefined,
  default: (..._a: any[]): any => undefined,
  normalize: (..._a: any[]): any => undefined,
  label: (..._a: any[]): any => undefined,
  cycle: (..._a: any[]): any => undefined,
  apply: (..._a: any[]): any => undefined,
  applyOptions: (..._a: any[]): any => undefined,
  silenceDriver: (..._a: any[]): any => undefined,
  isOn: (..._a: any[]): any => undefined,
  effective: (..._a: any[]): any => undefined,
  reset: (..._a: any[]): any => undefined,
};
export default VSync;
