// @gen2-stub
// Not ported yet: gen1recomp src/core/VSync.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const VSync: Record<string, any> = {
  MODES: undefined,
  default: (..._a: any[]): any => notPorted("VSync.default"),
  normalize: (..._a: any[]): any => notPorted("VSync.normalize"),
  label: (..._a: any[]): any => notPorted("VSync.label"),
  cycle: (..._a: any[]): any => notPorted("VSync.cycle"),
  apply: (..._a: any[]): any => notPorted("VSync.apply"),
  applyOptions: (..._a: any[]): any => notPorted("VSync.applyOptions"),
  silenceDriver: (..._a: any[]): any => notPorted("VSync.silenceDriver"),
  isOn: (..._a: any[]): any => notPorted("VSync.isOn"),
  effective: (..._a: any[]): any => notPorted("VSync.effective"),
  reset: (..._a: any[]): any => notPorted("VSync.reset"),
};
export default VSync;
