// @gen2-stub
// Not ported yet: gen1recomp src/script/gen2/Movement.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Movement: Record<string, any> = {
  DIR: undefined,
  FACING: undefined,
  STEP_END: undefined,
  STEP_WAIT_END: undefined,
  TELEPORT_FROM: undefined,
  TELEPORT_TO: undefined,
  TELEPORT_BEAT_FRAMES: undefined,
  REMOVE_SLIDING: undefined,
  SET_SLIDING: undefined,
  REMOVE_FIXED_FACING: undefined,
  FIX_FACING: undefined,
  TREE_SHAKE: undefined,
  TREE_SHAKE_FRAMES: undefined,
  STEP_DIG: undefined,
  STEP_DIG_FRAMES: undefined,
  SHOW_OBJECT: undefined,
  HIDE_OBJECT: undefined,
  RETURN_DIG: undefined,
  DIG_SPIN_FRAMES: undefined,
  SKYFALL: undefined,
  SKYFALL_TOP: undefined,
  SKYFALL_BEAT_FRAMES: undefined,
  TELEPORT_RISE_HEIGHT: undefined,
  TELEPORT_FALL_HEIGHT: undefined,
  JUMP_Y: undefined,
  dir: (..._a: any[]): any => notPorted("Movement.dir"),
  decodeByte: (..._a: any[]): any => notPorted("Movement.decodeByte"),
  isEnd: (..._a: any[]): any => notPorted("Movement.isEnd"),
  treeShakeIndex: (..._a: any[]): any => notPorted("Movement.treeShakeIndex"),
  teleportYOffset: (..._a: any[]): any => notPorted("Movement.teleportYOffset"),
  jumpYOffset: (..._a: any[]): any => notPorted("Movement.jumpYOffset"),
  stepByte: (..._a: any[]): any => notPorted("Movement.stepByte"),
  forcedMovementBytes: (..._a: any[]): any => notPorted("Movement.forcedMovementBytes"),
  digOutBytes: (..._a: any[]): any => notPorted("Movement.digOutBytes"),
  digReturnBytes: (..._a: any[]): any => notPorted("Movement.digReturnBytes"),
};
export default Movement;
