// @gen2-stub
// Not ported yet: gen1recomp src/script/gen2/specials/crystal_extras.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const crystal_extras: Record<string, any> = {
  MoveTutor: undefined,
  AskRememberPassword: undefined,
  BuenasPassword: undefined,
  BuenaPrize: undefined,
  PokeSeer: undefined,
  UnusedFindItemInPCOrBag: undefined,
  OverworldTownMap: undefined,
  PrintDiploma: undefined,
};
export default crystal_extras;
