// @gen2-stub
// Not ported yet: gen1recomp src/script/gen2/specials/unown_words.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const unown_words: Record<string, any> = {
  DisplayUnownWords: undefined,
};
export default unown_words;
