#!/usr/bin/env python3
"""Pocket Voxel cooker: drop your Red, Blue, Yellow, Gold, Silver or Crystal ROM on it, get an SD card folder.

    Windows:  drag your .gb (or Yellow / Gold / Silver / Crystal .gbc) file onto "Cook Pocket Voxel.bat"
    Mac:      double-click "Cook Pocket Voxel.command", then drag the .gb
              file into the window it opens and press Return
    Linux:    ./cook.sh /path/to/red.gb

Everything this does is in this one file, on purpose, so that anyone can
read it before they run it. There is no installer and nothing is written
outside this folder: tools go in `_work/`, the result goes in `output/`.
Delete the folder and the machine is exactly as it was.

What it does, in order:

  1. Checks the ROM is the real US Red, Blue, Yellow, Gold, Silver or Crystal (by SHA-1) and refuses
     anything else. The ROM never leaves your machine and nothing from it
     is in this folder or on GitHub -- that is the whole point of cooking
     on YOUR computer.
  2. Shows you exactly what it wants to download (the Bun runtime the game
     tools run on, the game's own source, and three data files from the
     projects it builds on), with the URL and license of each, and asks.
     Every download is checked against a checksum pinned below.
  3. Asks which colours you want. Red and Blue: black and white, as the
     original handheld showed them, or the community colourisation.
     Yellow: black and white, its own colours from the ROM,
     or the community colours. (Gold, Silver and Crystal have only their
     own colours: nothing to ask.)
  4. Runs the importer (your ROM -> data, seconds) and the cooker (data ->
     222 map paks, two to fifteen minutes depending on the machine).
  5. Puts the finished `3ds` folder in `output/`, writes `SOURCES.txt`
     beside it listing everything that went in, and offers to copy it
     straight onto an SD card if it can see one.

Options, for people who want them:  --yes  (accept every default, no
questions)  --palette dmg|gbc|community  (--grayscale = dmg, --colour =
community)  --no-sd  --no-open  --rom PATH

Needs Python 3.8 or newer and an internet connection for the first run.
Budget up to 20 minutes, 3 GB of free disk while it runs, and 400 MB on the card.
"""
import argparse
import hashlib
import os
import platform
import shutil
import stat
import subprocess
import sys
import time
import urllib.request
import zipfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Everything that gets downloaded, pinned. Change a version here and nowhere
# else. A checksum mismatch is fatal: the file is deleted and the run stops.
# ---------------------------------------------------------------------------

# The game's own source. When this file is run from inside a checkout of it
# (the `cooker/` folder of the repository) that checkout is used and nothing
# is fetched; on its own, it fetches this ref as a zip (about 2 MB).
POCKET_VOXEL_REPO = "imantheman/pocket-voxel3d"
# The release this cooker ships with: its source is what the .3dsx and .cia
# files beside it were built from.
POCKET_VOXEL_REF = "v2.1.0"

# Bun runs the importer and the cooker. MIT. https://bun.sh
BUN_VERSION = "1.4.2"
BUN_SHA256 = {
    "windows-x64": "ce4c17497b2f29712a99d3d53f028de28cd42e3bacb8589599e7f000e49b6405",
    "windows-x64-baseline": "78c221c2376f79731ccf4e4af0b3bb46d81fefa3296c5abee09ad8a1b21e68c6",
    "linux-x64": "36368faef7527875d5ffa52e53cd48021741f2a83eb6208a8dd64068d422a913",
    "linux-x64-baseline": "c678040f14fe0440eb839d37cbd0ce4c051a32da72806ac97de6a6aab6bf728f",
    "linux-aarch64": "54328bbc2d9c8e0c9f892c544d66c57a83b84139e34909e5ee81758f1ac8fda7",
    "darwin-x64": "80520d7e17526308c9185d261679ac6d27798d3803a0e9f7ff9121ab8affb012",
    "darwin-x64-baseline": "bad5bbd6cf14d0980d115f5954c9ff904df619d5e994d2da1ffccd3f316300b0",
    "darwin-aarch64": "90987a3a16d7db556d886ac3d551e7b6d3edf0a1cf43acaed622e8676be1d12f",
}

# The three data files the cook reads that are not in the game's repository,
# each fetched from the project that authored it, at a pinned commit.
#
#   gen1recomp  (MIT, Copyright 2026 BOIS CLUB GAMES, LLC)
#     tools/rom_manifest.json   the symbol table the importer follows: which
#                               bytes of the ROM are what. 3274 names.
#     data/palettes_gbc.lua     THE COLOUR. Generated by gen1recomp from
#                               pokered-gbc (github.com/Stewmath/pokered-gbc),
#                               a community colourisation of the Red
#                               disassembly. Only fetched if you say yes to
#                               colour.
#   potato_voxel  (used with its author's permission, September 2026)
#     data/voxel_heights.lua    hand-authored shape pins: which tile is a
#                               roof, a wall, a ledge, and the building
#                               templates. Nothing in it comes from a ROM.
#                               Without it every building cooks flat.
GEN1RECOMP = ("bryanthaboi/gen1recomp", "943ba5dcbfa62cf831e881684857ffd4867fe774")
# Gold's import manifest exists only later in gen1recomp's history; it is
# taken from bdfac727, the last commit under the MIT licence.
GEN1RECOMP_GEN2 = ("bryanthaboi/gen1recomp", "bdfac727aaccfea696be49a23c5f501451be50d5")
POTATO_VOXEL = ("ShaneMcGovernIE/potato_voxel", "3c939a5988cfc0343cc9770873267bdd572af595")
DATA_FILES = {
    # local folder, path in repo, (owner/repo, commit), sha256, size, license
    "manifest": ("gen1recomp", "tools/rom_manifest.json", GEN1RECOMP,
                 "e32037dd9bd72bb14ac2449fc964f385732ae5429c37de861426fd168586962d", 1061899, "MIT"),
    "colour": ("gen1recomp", "data/palettes_gbc.lua", GEN1RECOMP,
               "e194c72de82a0a520aced960b04d95325735b4ee63e9b071ad3e96bcf6615b0c", 109470, "MIT"),
    # Blue's import manifest, fetched only for a Blue ROM.
    "manifest_blue": ("gen1recomp", "tools/rom_manifest_blue.json", GEN1RECOMP,
                      "85eee6abc21df45b0528ab31ae05d933bac7f1d4c080769eec3fd5fae65cf5dd", 1061465, "MIT"),
    # Yellow's, fetched only for a Yellow ROM.
    "manifest_yellow": ("gen1recomp", "tools/rom_manifest_yellow.json", GEN1RECOMP,
                        "6c03dce038b6406ad51d55726cb05e97875ba2532acdd6e7da16e868f85be003", 1152646, "MIT"),
    # Gold's, fetched only for a Gold ROM (from the last MIT commit, above).
    "manifest_gold": ("gen1recomp-gen2", "tools/rom_manifest_gold.json", GEN1RECOMP_GEN2,
                      "61485a7a445bb61990a46a5abeab3a2e0fb0e42c91c0ccd9283b110ed1100179", 420887, "MIT"),
    # Silver's, fetched only for a Silver ROM (same commit: it is an ancestor).
    "manifest_silver": ("gen1recomp-gen2", "tools/rom_manifest_silver.json", GEN1RECOMP_GEN2,
                        "6ceb7506c6590fbfcb96f854eb092769a001c02e8664cd85a5446f9e75f1475a", 420887, "MIT"),
    # Crystal's, fetched only for a Crystal ROM (same commit). One manifest
    # serves both of its US revisions.
    "manifest_crystal": ("gen1recomp-gen2", "tools/rom_manifest_crystal.json", GEN1RECOMP_GEN2,
                         "9c4c5826d440c58fa47d4097a8a7b882af6fa928bba89b1b66b0728b8e177932", 500013, "MIT"),
    "shapes": ("potato_voxel", "data/voxel_heights.lua", POTATO_VOXEL,
               "20e0f26e1163e4861da760d21b6f71e41a66a52813119b2a1b15ae3a8c78f934", 255629, "used with the author's permission"),
}

# The only ROMs this works with. The importer checks again before decoding.
RED_SHA1 = "ea9bcae617fdf159b045185467ae58b2e4a48b9a"
BLUE_SHA1 = "d7037c83e1ae5b39bde3c30787637ba1d4c48ce2"
YELLOW_SHA1 = "cc7d03262ebfaf2f06772c1a480c7d9d5f4a38e1"
GOLD_SHA1 = "d8b8a3600a465308c9953dfa04f0081c05bdcb94"
SILVER_SHA1 = "49b163f7e57702bc939d642a18f591de55d92dae"
# Crystal was sold as 1.0 and 1.1; both are the same game to the importer.
CRYSTAL_SHA1 = "f4cd194bdee0d04ca4eac29e09b8e4e9d818c133"
CRYSTAL_11_SHA1 = "f2f52230b536214ef7c9924f483392993e226cfb"
CRYSTAL = {"id": "crystal", "label": "Crystal", "manifest": "manifest_crystal", "paks": "paks_crystal",
           "maps": 388, "gamedata": "gamedata.json", "overlay": "version_crystal.vxat",
           "dsx": "pocketvoxel-3ds-crystal.3dsx", "cia": "PocketVoxel3DCrystal.cia"}
# Red and Blue share one paks folder (their maps line up); Yellow's maps and
# monsters are redrawn, so it has a folder of its own beside theirs, and Gold
# (Gen 2, a different engine) has one too.
GAMES = {
    RED_SHA1: {"id": "red", "label": "Red", "manifest": "manifest", "paks": "paks", "maps": 222,
               "gamedata": "gamedata.json", "overlay": "version_red.vxat",
               "dsx": "pocketvoxel-3ds.3dsx", "cia": "PocketVoxel3DRed.cia"},
    BLUE_SHA1: {"id": "blue", "label": "Blue", "manifest": "manifest_blue", "paks": "paks", "maps": 222,
                "gamedata": "gamedata_blue.json", "overlay": "version_blue.vxat",
                "dsx": "pocketvoxel-3ds-blue.3dsx", "cia": "PocketVoxel3DBlue.cia"},
    YELLOW_SHA1: {"id": "yellow", "label": "Yellow", "manifest": "manifest_yellow", "paks": "paks_yellow",
                  "maps": 223, "gamedata": "gamedata.json", "overlay": "version_yellow.vxat",
                  "dsx": "pocketvoxel-3ds-yellow.3dsx", "cia": "PocketVoxel3DYellow.cia"},
    GOLD_SHA1: {"id": "gold", "label": "Gold", "manifest": "manifest_gold", "paks": "paks_gold",
                "maps": 368, "gamedata": "gamedata.json", "overlay": "version_gold.vxat",
                "dsx": "pocketvoxel-3ds-gold.3dsx", "cia": "PocketVoxel3DGold.cia"},
    # Silver shares Gold's paks folder the way Blue shares Red's: every map
    # is the same; its own dataset and overlay sit beside Gold's.
    SILVER_SHA1: {"id": "silver", "label": "Silver", "manifest": "manifest_silver", "paks": "paks_gold",
                  "maps": 368, "gamedata": "gamedata_silver.json", "overlay": "version_silver.vxat",
                  "dsx": "pocketvoxel-3ds-silver.3dsx", "cia": "PocketVoxel3DSilver.cia"},
    # Crystal's maps and tiles are its own, so it has a folder of its own.
    CRYSTAL_SHA1: CRYSTAL,
    CRYSTAL_11_SHA1: CRYSTAL,
}
# The games whose colours come out of the ROM itself (colour-handheld games).
GBC_GAMES = ("yellow", "gold", "silver", "crystal")
# Gen 2: one engine, shapes from the game source, colours only from the ROM.
GEN2_GAMES = ("gold", "silver", "crystal")
# The colours each Gen 1 game can be cooked in (--palette), default first:
#   dmg        black and white, the original handheld's four greys
#   gbc        the game's own colours (Yellow only: Red and
#              Blue are black-and-white games and have none)
#   community  pokered-gbc's colourisation, fetched from gen1recomp
PALETTES = {
    "red": ("community", "dmg"),
    "blue": ("community", "dmg"),
    "yellow": ("gbc", "dmg", "community"),
}
PALETTE_LABELS = {
    "dmg": "black and white (the original greys)",
    "gbc": "the game's own colours, from your ROM",
    "community": "the community colours (pokered-gbc)",
}

# ---------------------------------------------------------------------------

HERE = Path(__file__).resolve().parent
WORK = HERE / "_work"
OUTPUT = HERE / "output"
LOG = WORK / "cooker.log"

_log = None


def say(*parts):
    """Print, and keep a copy in _work/cooker.log for when something goes wrong."""
    line = " ".join(str(p) for p in parts)
    print(line, flush=True)
    if _log:
        _log.write(line + "\n")
        _log.flush()


def die(*parts):
    say()
    say("STOPPED:", *parts)
    say(f"(the full log is in {LOG})")
    sys.exit(1)


def ask(question, default_yes=True, yes_to_all=False):
    if yes_to_all:
        say(f"{question} [{'Y/n' if default_yes else 'y/N'}] -> {'y' if default_yes else 'n'} (--yes)")
        return default_yes
    try:
        answer = input(f"{question} [{'Y/n' if default_yes else 'y/N'}] ").strip().lower()
    except EOFError:
        answer = ""
    if _log:
        _log.write(f"{question} -> {answer or '(default)'}\n")
    if not answer:
        return default_yes
    return answer[0] == "y"


def mb(n):
    return f"{n / 1024 / 1024:.1f} MB"


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def sha1_of(path):
    h = hashlib.sha1()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def download(url, dest, sha256=None, label=None):
    """Fetch url to dest with a progress line; verify the checksum if given."""
    dest = Path(dest)
    dest.parent.mkdir(parents=True, exist_ok=True)
    label = label or dest.name
    part = dest.with_suffix(dest.suffix + ".part")
    say(f"  fetching {label}")
    say(f"    {url}")
    req = urllib.request.Request(url, headers={"User-Agent": "pocket-voxel-cooker"})
    with urllib.request.urlopen(req, timeout=60) as r, open(part, "wb") as f:
        total = int(r.headers.get("Content-Length") or 0)
        got = 0
        last = -1
        while True:
            chunk = r.read(1 << 16)
            if not chunk:
                break
            f.write(chunk)
            got += len(chunk)
            if total:
                pct = got * 100 // total
                if pct // 10 != last // 10:
                    print(f"    {pct:3d}%  {mb(got)} of {mb(total)}", end="\r", flush=True)
                    last = pct
        print(" " * 60, end="\r")
    if sha256:
        actual = sha256_of(part)
        if actual != sha256:
            part.unlink()
            die(f"{label} did not match its pinned checksum.",
                f"\n  expected {sha256}\n  got      {actual}",
                "\nThe download may be corrupt, or the file at that URL changed. Nothing was kept.")
    part.replace(dest)
    say(f"    ok, {mb(dest.stat().st_size)}" + (", checksum verified" if sha256 else ""))
    return dest


# ---------------------------------------------------------------------------
# the pieces
# ---------------------------------------------------------------------------

def platform_key():
    system = platform.system()
    machine = platform.machine().lower()
    arch = "x64" if machine in ("amd64", "x86_64") else "aarch64" if machine in ("arm64", "aarch64") else machine
    os_name = {"Windows": "windows", "Linux": "linux", "Darwin": "darwin"}.get(system)
    if not os_name:
        die(f"unsupported operating system: {system}")
    return os_name, arch


def bun_path():
    os_name, _ = platform_key()
    return WORK / "bun" / ("bun.exe" if os_name == "windows" else "bun")


def bun_works(exe):
    try:
        r = subprocess.run([str(exe), "--version"], capture_output=True, text=True, timeout=30)
        return r.returncode == 0 and r.stdout.strip() != ""
    except (OSError, subprocess.SubprocessError):
        return False


def fetch_bun(variant):
    """variant: e.g. 'windows-x64' or 'windows-x64-baseline'."""
    if variant not in BUN_SHA256:
        die(f"no pinned Bun build for {variant}. Install Bun from https://bun.sh and put it on PATH.")
    url = f"https://github.com/oven-sh/bun/releases/download/bun-v{BUN_VERSION}/bun-{variant}.zip"
    z = download(url, WORK / f"bun-{variant}.zip", BUN_SHA256[variant], f"Bun {BUN_VERSION} ({variant})")
    target = WORK / "bun"
    shutil.rmtree(target, ignore_errors=True)
    target.mkdir(parents=True)
    with zipfile.ZipFile(z) as zf:
        for info in zf.infolist():
            name = Path(info.filename).name
            if info.is_dir() or name not in ("bun", "bun.exe"):
                continue
            with zf.open(info) as src, open(target / name, "wb") as dst:
                shutil.copyfileobj(src, dst)
    exe = bun_path()
    exe.chmod(exe.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    z.unlink()
    return exe


def ensure_bun():
    """Bun in _work/, or the one already on PATH if it is new enough."""
    exe = bun_path()
    if exe.exists() and bun_works(exe):
        return exe
    on_path = shutil.which("bun")
    if on_path and bun_works(on_path):
        say(f"  using the Bun already on this machine: {on_path}")
        return Path(on_path)
    os_name, arch = platform_key()
    exe = fetch_bun(f"{os_name}-{arch}")
    if not bun_works(exe):
        # Bun's main build wants a CPU with AVX2 (2013 and newer). Older ones
        # crash on the first instruction; the baseline build runs anywhere.
        say("  that Bun build will not start on this CPU; fetching the baseline build")
        exe = fetch_bun(f"{os_name}-{arch}-baseline")
        if not bun_works(exe):
            die("Bun will not run on this machine.")
    return exe


def ensure_repo():
    """The game's source: the checkout this file lives in, or a fetched zip."""
    checkout = HERE.parent
    if (checkout / "tools" / "cook3ds.ts").exists():
        return checkout, "the checkout this cooker is part of"
    repo = WORK / "pocket-voxel"
    # A fetched copy is used again only if it is this cooker's release: a new
    # cooker unzipped over an old folder must not cook with the old source.
    stamp = repo / ".pocket-voxel-ref"
    fetched = stamp.read_text(encoding="utf-8").strip() if stamp.exists() else ""
    if (repo / "tools" / "cook3ds.ts").exists() and fetched == POCKET_VOXEL_REF:
        return repo, f"{POCKET_VOXEL_REPO} @ {POCKET_VOXEL_REF} (already fetched)"
    # (POCKET_VOXEL_ZIP in the environment names another zip -- a file://
    # one, say -- which is how the repository's tests exercise this path.)
    url = os.environ.get("POCKET_VOXEL_ZIP") or f"https://github.com/{POCKET_VOXEL_REPO}/archive/{POCKET_VOXEL_REF}.zip"
    z = download(url, WORK / "pocket-voxel.zip", None, f"pocket-voxel source ({POCKET_VOXEL_REF})")
    shutil.rmtree(repo, ignore_errors=True)
    with zipfile.ZipFile(z) as zf:
        top = {n.split("/", 1)[0] for n in zf.namelist()}
        if len(top) != 1:
            die("the source zip does not have the shape a GitHub archive has")
        zf.extractall(WORK)
    (WORK / top.pop()).rename(repo)
    z.unlink()
    stamp.write_text(POCKET_VOXEL_REF + "\n", encoding="utf-8")
    return repo, f"{POCKET_VOXEL_REPO} @ {POCKET_VOXEL_REF}"


def data_file_path(key):
    folder, rel, _, _, _, _ = DATA_FILES[key]
    return WORK / folder / rel


def data_file_url(key):
    _, rel, (repo, commit), _, _, _ = DATA_FILES[key]
    return f"https://raw.githubusercontent.com/{repo}/{commit}/{rel}"


def ensure_data_file(key):
    path = data_file_path(key)
    _, rel, _, sha, _, _ = DATA_FILES[key]
    if path.exists() and sha256_of(path) == sha:
        return path
    return download(data_file_url(key), path, sha, rel)


# ---------------------------------------------------------------------------
# the SD card
# ---------------------------------------------------------------------------

def removable_drives():
    """[(root, looks_like_3ds_card)] for every removable volume we can see."""
    found = []
    os_name, _ = platform_key()
    if os_name == "windows":
        import ctypes
        import string
        mask = ctypes.windll.kernel32.GetLogicalDrives()
        for i, letter in enumerate(string.ascii_uppercase):
            if not (mask >> i) & 1:
                continue
            root = f"{letter}:\\"
            if ctypes.windll.kernel32.GetDriveTypeW(root) == 2:  # DRIVE_REMOVABLE
                found.append(root)
    elif os_name == "darwin":
        for v in Path("/Volumes").iterdir():
            if v.is_dir() and os.path.ismount(v) and not os.path.samefile(v, "/"):
                found.append(str(v))
    else:
        for base in (Path("/media"), Path("/run/media")):
            if not base.exists():
                continue
            for user in base.iterdir():
                for v in user.iterdir() if user.is_dir() else []:
                    if v.is_dir() and os.path.ismount(v):
                        found.append(str(v))
    return [(root, (Path(root) / "3ds").is_dir()) for root in found]


def copy_tree_with_progress(src, dst, label):
    files = [p for p in Path(src).rglob("*") if p.is_file()]
    total = sum(p.stat().st_size for p in files)
    done = 0
    for i, p in enumerate(files, 1):
        rel = p.relative_to(src)
        target = Path(dst) / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(p, target)
        done += p.stat().st_size
        print(f"  {label}: {i}/{len(files)} files, {mb(done)} of {mb(total)}", end="\r", flush=True)
    print(" " * 70, end="\r")
    say(f"  {label}: {len(files)} files, {mb(total)}")


def install_to_card(root, card_dir, game):
    """Merge output/3ds into <root>/3ds the way the docs say to."""
    dest = Path(root) / "3ds"
    paks = dest / "voxelmon" / game["paks"]
    # The map paks, common.vxat, index.txt and THIS game's dataset and
    # overlay are one artifact: clear them first so nothing from a previous
    # build survives beside the new one. The OTHER game's own files in the
    # same folder stay -- Red and Blue share the map paks, so a card with
    # both keeps both; Yellow's folder is its own. Saves live one folder up
    # and are untouched.
    others = {f for g in GAMES.values() if g["id"] != game["id"] and g["paks"] == game["paks"]
              for f in (g["gamedata"], g["overlay"])}
    if paks.exists():
        for p in paks.iterdir():
            if p.is_file() and p.name not in others:
                p.unlink()
    copy_tree_with_progress(card_dir, dest, "copying to the card")
    say(f"  done: {dest}")


# ---------------------------------------------------------------------------

def open_folder(path):
    try:
        os_name, _ = platform_key()
        if os_name == "windows":
            os.startfile(str(path))  # type: ignore[attr-defined]
        elif os_name == "darwin":
            subprocess.Popen(["open", str(path)])
        else:
            subprocess.Popen(["xdg-open", str(path)])
    except OSError:
        pass


def find_rom(arg, yes):
    path = arg
    if not path:
        say("Which ROM? Drag your Red, Blue, Yellow, Gold, Silver or Crystal file into this window and press Return.")
        if yes:
            die("no ROM given (pass --rom PATH with --yes)")
        try:
            path = input("> ").strip()
        except EOFError:
            path = ""
    path = path.strip().strip('"').strip("'")
    if not path:
        die("no ROM given")
    rom = Path(path).expanduser()
    if not rom.is_file():
        die(f"not a file: {rom}")
    say(f"Checking {rom.name} ...")
    digest = sha1_of(rom)
    game = GAMES.get(digest)
    if not game:
        die(f"that is not the US Red, Blue, Yellow, Gold, Silver or Crystal ROM.",
            f"\n  its SHA-1 is  {digest}\n  Red's is      {RED_SHA1}\n  Blue's is     {BLUE_SHA1}",
            f"\n  Yellow's is   {YELLOW_SHA1}\n  Gold's is     {GOLD_SHA1}\n  Silver's is   {SILVER_SHA1}",
            f"\n  Crystal's is  {CRYSTAL_SHA1} (1.0) or {CRYSTAL_11_SHA1} (1.1)",
            "\nOnly those work. Other regions, colour hacks, ROM hacks, and",
            "files with a header or trailing bytes will all be refused here. Nothing was read from it.")
    say(f"  it is {game['label']} (US). Good.")
    # which of the game's ROMs it was (Crystal has two), for SOURCES.txt
    return rom, dict(game, sha1=digest)


def write_sources(repo_desc, rom, palette, downloads, game):
    lines = [
        "Pocket Voxel -- what went into this build",
        "=" * 44,
        "",
        f"Built {time.strftime('%Y-%m-%d %H:%M')} on {platform.system()} {platform.machine()} by cooker.py.",
        "",
        "YOUR ROM (never copied, never uploaded; read on this machine only):",
        f"  {rom}",
        f"  SHA-1 {game['sha1']}  ({game['label']}, US)",
        "",
        "GAME SOURCE:",
        f"  {repo_desc}",
        f"  https://github.com/{POCKET_VOXEL_REPO}  (MIT)",
        "",
        "RUNTIME:",
        f"  Bun {BUN_VERSION}  https://bun.sh  (MIT)",
        "",
        "DATA FILES FETCHED FROM THE PROJECTS THIS BUILDS ON:",
    ]
    keys = (game["manifest"],) if game["id"] in GEN2_GAMES else (game["manifest"], "colour", "shapes")
    for key in keys:
        folder, rel, (repo, commit), sha, size, lic = DATA_FILES[key]
        if key == "colour" and palette != "community":
            lines.append(f"  (colour pack NOT fetched -- this build's colours: {PALETTE_LABELS.get(palette, palette)})")
            continue
        lines += [
            f"  {rel}",
            f"    from   https://github.com/{repo}  commit {commit}  ({lic})",
            f"    url    {data_file_url(key)}",
            f"    sha256 {sha}",
        ]
    if game["id"] in GEN2_GAMES:
        lines += [
            "  voxelmon/cook/gen2-profile.json  (in the game source above)",
            "    the Gen 2 shapes: a snapshot of data/voxel_heights.lua from",
            "    https://github.com/UNDERdecoded/Gen2Recomped-DramaticShapes  commit 726782f  (MIT)",
        ]
    if game["id"] in GBC_GAMES:
        lines += [
            "",
            "ABOUT THE COLOUR:",
            f"  {game['label']} is a colour game; every colour in this",
            "  build was read out of your ROM on this machine.",
            "",
            "EVERYTHING ELSE in the `3ds` folder was computed on this machine from",
            "the inputs above. Nothing playable was downloaded.",
            "",
        ]
        (OUTPUT / "SOURCES.txt").write_text("\n".join(lines), encoding="utf-8")
        return
    lines += [
        "",
        "ABOUT THE COLOUR:" if colour else "ABOUT THE (ABSENCE OF) COLOUR:",
    ]
    if colour:
        lines += [
            "  Red has no colour in it. The palettes here come from",
            "  pokered-gbc (https://github.com/Stewmath/pokered-gbc), a community",
            "  colourisation of the Red disassembly, as generated into",
            "  palettes_gbc.lua by gen1recomp. Its creature colours follow Gen 2's",
            "  MonsterPalettes. Every colour in this build was assembled on this",
            "  machine from that file; none of it is in the game's repository.",
        ]
    else:
        lines += [
            "  You chose grayscale, so the colour pack was not fetched and the maps",
            "  render the way the original handheld showed them.",
        ]
    lines += [
        "",
        "EVERYTHING ELSE in the `3ds` folder was computed on this machine from",
        "the inputs above. Nothing playable was downloaded.",
        "",
    ]
    (OUTPUT / "SOURCES.txt").write_text("\n".join(lines), encoding="utf-8")


def main():
    global _log
    ap = argparse.ArgumentParser(add_help=True)
    ap.add_argument("rom", nargs="?", help="your Red, Blue, Yellow, Gold, Silver or Crystal ROM file")
    ap.add_argument("--rom", dest="rom_opt")
    ap.add_argument("--yes", action="store_true", help="accept every default without asking")
    ap.add_argument("--palette", choices=("dmg", "gbc", "community"),
                    help="the colours: dmg (black and white), gbc (Yellow's own), community (pokered-gbc)")
    ap.add_argument("--colour", "--color", dest="colour", action="store_true", help="= --palette community")
    ap.add_argument("--grayscale", dest="grayscale", action="store_true", help="= --palette dmg")
    ap.add_argument("--no-sd", action="store_true", help="do not look for or write to an SD card")
    ap.add_argument("--no-open", action="store_true", help="do not open the output folder at the end")
    args = ap.parse_args()

    WORK.mkdir(exist_ok=True)
    _log = open(LOG, "a", encoding="utf-8")
    _log.write(f"\n=== {time.strftime('%Y-%m-%d %H:%M:%S')} {sys.argv}\n")

    say()
    say("Pocket Voxel cooker")
    say("-------------------")
    say(f"folder: {HERE}")
    if "OneDrive" in str(HERE) or "Dropbox" in str(HERE):
        say("  (this folder is inside a cloud-synced drive; that works, but it will")
        say("   sync 2 GB of scratch files. Somewhere like C:\\PocketVoxel is kinder.)")
    say()

    # 1. the ROM
    rom, game = find_rom(args.rom_opt or args.rom, args.yes)
    # Gold's shapes are in the game source (gen2-profile.json); the Gen 1
    # games' come from potato_voxel
    wanted = (game["manifest"],) if game["id"] in GEN2_GAMES else (game["manifest"], "shapes")
    say()

    # 2. the plan
    repo_ready = (HERE.parent / "tools" / "cook3ds.ts").exists() or (WORK / "pocket-voxel" / "tools" / "cook3ds.ts").exists()
    bun_ready = (bun_path().exists() and bun_works(bun_path())) or (shutil.which("bun") and bun_works(shutil.which("bun")))
    say("This will download, into the _work folder next to this file:")
    if not bun_ready:
        say(f"  * Bun {BUN_VERSION}, the runtime the game's tools run on  (~40 MB, MIT)")
        say(f"      github.com/oven-sh/bun/releases  -- checksum pinned in cooker.py")
    if not repo_ready:
        say(f"  * the game's source, {POCKET_VOXEL_REPO} @ {POCKET_VOXEL_REF}  (~2 MB, MIT)")
    for key in wanted:
        folder, rel, (repo, commit), sha, size, lic = DATA_FILES[key]
        if data_file_path(key).exists():
            continue
        say(f"  * {rel} from {repo}  ({mb(size)}, {lic})")
        say(f"      commit {commit[:12]} -- checksum pinned in cooker.py")
    if bun_ready and repo_ready and all(data_file_path(k).exists() for k in wanted):
        say("  (nothing -- everything is already here from a previous run)")
    say()
    say("It does not download a game. It builds one, on this machine, out of your ROM.")
    if not ask("Continue?", True, args.yes):
        die("you said no. Nothing was downloaded.")
    say()

    # 3. colour
    asked = args.palette or ("community" if args.colour else "dmg" if args.grayscale else None)
    if game["id"] in GEN2_GAMES:
        # Gold, Silver and Crystal have only their own colours, read from the ROM.
        palette = "gbc"
        say(f"Colour: {game['label']}'s own colour palettes, from your ROM.")
        if asked and asked != "gbc":
            say(f"  (--palette {asked} does nothing for {game['label']}: it has only its own colours.)")
    else:
        choices = PALETTES[game["id"]]
        if asked and asked not in choices:
            die(f"{game['label']} has no {asked} colours to cook with: choose "
                + " or ".join(choices) + ".")
        if asked:
            palette = asked
        elif args.yes:
            palette = choices[0]
            say(f"Colour: {PALETTE_LABELS[palette]} (--yes)")
        else:
            say("Colour?")
            if game["id"] == "yellow":
                say("  Yellow is a colour game. Pocket Voxel can show its own")
                say("  colours, read from your ROM, or the original black and white, or the")
                say("  community colourisation of Red (pokered-gbc), fetched as one")
                say(f"  {mb(DATA_FILES['colour'][4])} file from gen1recomp (MIT).")
            else:
                say(f"  {game['label']} is a black-and-white game. The colour Pocket Voxel can show")
                say("  comes from pokered-gbc, a community colourisation of the Red disassembly,")
                say(f"  fetched as one {mb(DATA_FILES['colour'][4])} file from gen1recomp (MIT).")
            for n, key in enumerate(choices, 1):
                say(f"    {n}. {PALETTE_LABELS[key]}{'  (default)' if n == 1 else ''}")
            palette = choices[0]
            try:
                answer = input(f"Which? [1-{len(choices)}] ").strip()
            except EOFError:
                answer = ""
            if _log:
                _log.write(f"Colour -> {answer or '(default)'}\n")
            if answer.isdigit() and 1 <= int(answer) <= len(choices):
                palette = choices[int(answer) - 1]
        say(f"  -> {PALETTE_LABELS[palette]}")
    colour = palette == "community"
    say()

    # 4. get everything
    say("Getting the tools ...")
    bun = ensure_bun()
    say(f"  bun: {bun}")
    repo, repo_desc = ensure_repo()
    say(f"  source: {repo}")
    for key in wanted:
        ensure_data_file(key)
    colour_file = data_file_path("colour")
    if colour:
        ensure_data_file("colour")
    elif colour_file.exists():
        # Only a community cook uses it (VOXELMON_COLOUR says so either way).
        colour_file.unlink()
    say()

    # 5. cook
    env = dict(os.environ)
    env["VOXELMON_ROM"] = str(rom)
    env["VOXELMON_G1R"] = str(WORK / "gen1recomp")
    env["VOXELMON_G1R_GEN2"] = str(WORK / "gen1recomp-gen2")
    env["VOXELMON_VOXELMOD"] = str(WORK / "potato_voxel")
    env["VOXELMON_PYTHON"] = sys.executable
    env["VOXELMON_VERSION"] = game["id"]
    # the colours to cook in (voxelmon/cook/gbc.ts lists them)
    env["VOXELMON_COLOUR"] = palette
    env["PYTHONIOENCODING"] = "utf-8"
    say(f"Cooking {game['maps']} maps. Two to fifteen minutes depending on the machine,")
    say("and a couple of GB of disk while it works. The lines scrolling past are")
    say("the cooker's own progress.")
    if palette == "dmg":
        say("(Black and white, as you chose.)")
    say()
    started = time.time()
    proc = subprocess.Popen(
        [str(bun), "tools/cook3ds.ts"], cwd=str(repo), env=env,
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, encoding="utf-8", errors="replace",
    )
    assert proc.stdout is not None
    for line in proc.stdout:
        say("  " + line.rstrip())
    code = proc.wait()
    if code != 0:
        die(f"the cook failed (exit code {code}). The lines above say why;",
            f"the log at {LOG} has all of them.")
    say()
    say(f"  cooked in {(time.time() - started) / 60:.1f} minutes")

    # 6. collect
    card_src = repo / "dist" / "voxelmon" / "sdcard" / "3ds"
    if not (card_src / "voxelmon" / game["paks"] / game["gamedata"]).exists():
        die(f"the cook finished but left no card image at {card_src}")
    shutil.rmtree(OUTPUT, ignore_errors=True)
    OUTPUT.mkdir()
    card = OUTPUT / "3ds"
    shutil.move(str(card_src), str(card))
    # the ~930 MB of pre-sharing intermediates and the ~330 MB staging copy:
    # nothing reads either again
    for d in ("paks_orig", "paks", "paks_orig_yellow", "paks_yellow", "paks_orig_gold", "paks_gold", "paks_orig_silver",
              "paks_orig_crystal", "paks_crystal"):
        shutil.rmtree(repo / "dist" / "voxelmon" / d, ignore_errors=True)
    shutil.rmtree(repo / "dist" / "voxelmon" / "sdcard", ignore_errors=True)
    # A release ships the console binary next to this file; a checkout may
    # have built one. Either way the card wants it at /3ds/.
    for stray in card.glob("*.3dsx"):
        stray.unlink()
    for candidate in (HERE / game["dsx"], repo / "dist" / "voxelmon" / game["dsx"],
                      repo / "crates/pocketvoxel-3ds/target/armv6k-nintendo-3ds/release/pocketvoxel-3ds.3dsx"
                      if game["id"] == "red" else HERE / game["dsx"]):
        if candidate.exists():
            shutil.copyfile(candidate, card / game["dsx"])
            break
    write_sources(repo_desc, rom, palette, None, game)
    paks = sorted((card / "voxelmon" / game["paks"]).glob("*.vxpak"))
    size = sum(p.stat().st_size for p in (card / "voxelmon" / game["paks"]).iterdir())
    say(f"  {len(paks)} paks, {mb(size)} -> {card}")
    if not (card / game["dsx"]).exists():
        say(f"  (no {game['dsx']} was next to the cooker; put the one from the")
        say(f"   release into the 3ds folder yourself, or install {game['cia']} instead)")
    say()

    # 7. the card
    say("Done. Open your SD card, open the `3ds` folder that is already on it,")
    say(f"and copy the `voxelmon` folder and `{game['dsx']}` from output/3ds/")
    say("INTO it, beside whatever is there. (Do not drag the whole `3ds` folder onto")
    say("the card; if the PC asks about merging or replacing, you are one level")
    say("too high.) Then launch it from the Homebrew Launcher, or install")
    say(f"{game['cia']} with FBI; it reads the same paks.")
    if game["id"] in GBC_GAMES:
        say(f"{game['label']} keeps its files in its own folder (voxelmon/{game['paks']}), so it")
        say("sits beside the other games on the same card without touching them.")
    else:
        say("Red and Blue share the map files: if the other game is already on the")
        say("card, copying this one over it is fine, and both keep working.")
    if not args.no_sd:
        drives = removable_drives()
        if drives:
            say()
            say("Removable drives I can see:")
            for i, (root, looks) in enumerate(drives, 1):
                free = shutil.disk_usage(root).free
                say(f"  [{i}] {root}  free {mb(free)}" + ("  (has a 3ds folder)" if looks else ""))
            pick = None
            if args.yes:
                say("  (--yes: not writing to any drive)")
            else:
                try:
                    choice = input("Copy onto one of them now? number, or Return to skip: ").strip()
                except EOFError:
                    choice = ""
                if choice.isdigit() and 1 <= int(choice) <= len(drives):
                    pick = drives[int(choice) - 1][0]
            if pick:
                need = sum(p.stat().st_size for p in card.rglob("*") if p.is_file())
                if shutil.disk_usage(pick).free < need + (16 << 20):
                    say(f"  {pick} does not have {mb(need)} free. Skipped.")
                else:
                    install_to_card(pick, card, game)
    if not args.no_open:
        open_folder(OUTPUT)
    say()
    say("SOURCES.txt in output/ lists everything that went into this build.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\ninterrupted")
        sys.exit(130)
