// @gen2-stub
// Not ported yet: gen1recomp src/render/Assets.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Assets: Record<string, any> = {
  loader: undefined,
  exists: undefined,
  flush: undefined,
  resolve: (..._a: any[]): any => notPorted("Assets.resolve"),
  image: (..._a: any[]): any => notPorted("Assets.image"),
  imageData: (..._a: any[]): any => notPorted("Assets.imageData"),
  register: (..._a: any[]): any => notPorted("Assets.register"),
  invalidate: (..._a: any[]): any => notPorted("Assets.invalidate"),
  releaseSession: (..._a: any[]): any => notPorted("Assets.releaseSession"),
  installLoader: (..._a: any[]): any => notPorted("Assets.installLoader"),
};
export default Assets;
