// @gen2-stub
// Not ported yet: gen1recomp src/render/Font.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Font: Record<string, any> = {
  TTF_BASE: undefined,
  PLAINPIXEL: undefined,
  PLAINPIXEL_SIZE: undefined,
  DEFAULT_BORDER: undefined,
  BORDER: undefined,
  load: (..._a: any[]): any => notPorted("Font.load"),
  ttfActive: (..._a: any[]): any => notPorted("Font.ttfActive"),
  invalidate: (..._a: any[]): any => notPorted("Font.invalidate"),
  useBattleExtra: (..._a: any[]): any => notPorted("Font.useBattleExtra"),
  battleExtraActive: (..._a: any[]): any => notPorted("Font.battleExtraActive"),
  setFrame: (..._a: any[]): any => notPorted("Font.setFrame"),
  frameIndex: (..._a: any[]): any => notPorted("Font.frameIndex"),
  split: (..._a: any[]): any => notPorted("Font.split"),
  spansFitting: (..._a: any[]): any => notPorted("Font.spansFitting"),
  encode: (..._a: any[]): any => notPorted("Font.encode"),
  drawCode: (..._a: any[]): any => notPorted("Font.drawCode"),
  advanceOf: (..._a: any[]): any => notPorted("Font.advanceOf"),
  width: (..._a: any[]): any => notPorted("Font.width"),
  draw: (..._a: any[]): any => notPorted("Font.draw"),
  drawBox: (..._a: any[]): any => notPorted("Font.drawBox"),
};
export default Font;
