// @gen2-stub
// Not ported yet: gen1recomp src/render/GameViewport.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Viewport: Record<string, any> = {
  begin: (..._a: any[]): any => notPorted("Viewport.begin"),
  active: (..._a: any[]): any => notPorted("Viewport.active"),
  dimensions: (..._a: any[]): any => notPorted("Viewport.dimensions"),
  pixelDimensions: (..._a: any[]): any => notPorted("Viewport.pixelDimensions"),
  fullDimensions: (..._a: any[]): any => notPorted("Viewport.fullDimensions"),
  target: (..._a: any[]): any => notPorted("Viewport.target"),
  setTarget: (..._a: any[]): any => notPorted("Viewport.setTarget"),
  toLocal: (..._a: any[]): any => notPorted("Viewport.toLocal"),
  localSafeRect: (..._a: any[]): any => notPorted("Viewport.localSafeRect"),
  finish: (..._a: any[]): any => notPorted("Viewport.finish"),
  reset: (..._a: any[]): any => notPorted("Viewport.reset"),
};
export default Viewport;
