// @gen2-stub
// Not ported yet: gen1recomp src/render/GbcPalette.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const GbcPalette: Record<string, any> = {
  MODES: undefined,
  MODE_LABELS: undefined,
  mode: undefined,
  CUSTOM_MODE: undefined,
  DMG_SHADES: undefined,
  REMAP_MAX: undefined,
  REMAP_TOLERANCE: undefined,
  customRamp: undefined,
  BGP_IDENTITY: undefined,
  bgp: undefined,
  shader: (..._a: any[]): any => notPorted("GbcPalette.shader"),
  keyedShader: (..._a: any[]): any => notPorted("GbcPalette.keyedShader"),
  remapShader: (..._a: any[]): any => notPorted("GbcPalette.remapShader"),
  available: (..._a: any[]): any => notPorted("GbcPalette.available"),
  setCustomRamp: (..._a: any[]): any => notPorted("GbcPalette.setCustomRamp"),
  resolve: (..._a: any[]): any => notPorted("GbcPalette.resolve"),
  bgpShades: (..._a: any[]): any => notPorted("GbcPalette.bgpShades"),
  remap: (..._a: any[]): any => notPorted("GbcPalette.remap"),
  setBgp: (..._a: any[]): any => notPorted("GbcPalette.setBgp"),
  color: (..._a: any[]): any => notPorted("GbcPalette.color"),
  presentColors: (..._a: any[]): any => notPorted("GbcPalette.presentColors"),
  setMode: (..._a: any[]): any => notPorted("GbcPalette.setMode"),
  modeLabel: (..._a: any[]): any => notPorted("GbcPalette.modeLabel"),
  cycle: (..._a: any[]): any => notPorted("GbcPalette.cycle"),
  applyOptions: (..._a: any[]): any => notPorted("GbcPalette.applyOptions"),
  use: (..._a: any[]): any => notPorted("GbcPalette.use"),
  useRaw: (..._a: any[]): any => notPorted("GbcPalette.useRaw"),
  useKeyed: (..._a: any[]): any => notPorted("GbcPalette.useKeyed"),
  clear: (..._a: any[]): any => notPorted("GbcPalette.clear"),
  remapTable: (..._a: any[]): any => notPorted("GbcPalette.remapTable"),
  useRemap: (..._a: any[]): any => notPorted("GbcPalette.useRemap"),
  remapUniforms: (..._a: any[]): any => notPorted("GbcPalette.remapUniforms"),
  useRemapUniforms: (..._a: any[]): any => notPorted("GbcPalette.useRemapUniforms"),
  with: (..._a: any[]): any => notPorted("GbcPalette.with"),
  keyedWith: (..._a: any[]): any => notPorted("GbcPalette.keyedWith"),
  withRaw: (..._a: any[]): any => notPorted("GbcPalette.withRaw"),
};
export default GbcPalette;
