// @gen2-stub
// Not ported yet: gen1recomp src/render/Letterbox.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Letterbox: Record<string, any> = {
  mode: undefined,
  MODES: undefined,
  normalize: (..._a: any[]): any => notPorted("Letterbox.normalize"),
  label: (..._a: any[]): any => notPorted("Letterbox.label"),
  cycle: (..._a: any[]): any => notPorted("Letterbox.cycle"),
  color: (..._a: any[]): any => notPorted("Letterbox.color"),
  setMode: (..._a: any[]): any => notPorted("Letterbox.setMode"),
  applyOptions: (..._a: any[]): any => notPorted("Letterbox.applyOptions"),
  fill: (..._a: any[]): any => notPorted("Letterbox.fill"),
};
export default Letterbox;
