// @gen2-stub
// Not ported yet: gen1recomp src/render/MonAnimView.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class MonAnimView {
  [key: string]: any;
  static [key: string]: any;
  static replaced(..._a: any[]): any { return notPorted("MonAnimView.replaced"); }
  static animData(..._a: any[]): any { return notPorted("MonAnimView.animData"); }
  static start(..._a: any[]): any { return notPorted("MonAnimView.start"); }
  step(..._a: any[]): any { return notPorted("MonAnimView:step"); }
  finished(..._a: any[]): any { return notPorted("MonAnimView:finished"); }
  currentFrame(..._a: any[]): any { return notPorted("MonAnimView:currentFrame"); }
  frame(..._a: any[]): any { return notPorted("MonAnimView:frame"); }
}
export default MonAnimView;
