// @gen2-stub
// Not ported yet: gen1recomp src/render/Palette.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Palette: Record<string, any> = {
  MONO_COLOURS: undefined,
  monoRamp: undefined,
  unhex: undefined,
  GREY_CHROMA: undefined,
  HUE_ARC: undefined,
  hueChroma: undefined,
  hueArc: undefined,
  CATEGORIES: undefined,
  findPack: undefined,
  packs: (..._a: any[]): any => notPorted("Palette.packs"),
  packId: (..._a: any[]): any => notPorted("Palette.packId"),
  monoId: (..._a: any[]): any => notPorted("Palette.monoId"),
  categoryOf: (..._a: any[]): any => notPorted("Palette.categoryOf"),
  categories: (..._a: any[]): any => notPorted("Palette.categories"),
  category: (..._a: any[]): any => notPorted("Palette.category"),
  locate: (..._a: any[]): any => notPorted("Palette.locate"),
  label: (..._a: any[]): any => notPorted("Palette.label"),
  ramp: (..._a: any[]): any => notPorted("Palette.ramp"),
  invalidate: (..._a: any[]): any => notPorted("Palette.invalidate"),
  swatch: (..._a: any[]): any => notPorted("Palette.swatch"),
};
export default Palette;
