// @gen2-stub
// Not ported yet: gen1recomp src/render/Pipelines.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Pipelines: Record<string, any> = {
  DEFAULT_LEVELS: undefined,
  install: (..._a: any[]): any => notPorted("Pipelines.install"),
  list: (..._a: any[]): any => notPorted("Pipelines.list"),
  get: (..._a: any[]): any => notPorted("Pipelines.get"),
  levelLabels: (..._a: any[]): any => notPorted("Pipelines.levelLabels"),
  maxLevel: (..._a: any[]): any => notPorted("Pipelines.maxLevel"),
  level: (..._a: any[]): any => notPorted("Pipelines.level"),
  levelLabel: (..._a: any[]): any => notPorted("Pipelines.levelLabel"),
  setLevel: (..._a: any[]): any => notPorted("Pipelines.setLevel"),
  cycle: (..._a: any[]): any => notPorted("Pipelines.cycle"),
  syncOptions: (..._a: any[]): any => notPorted("Pipelines.syncOptions"),
  applyOptions: (..._a: any[]): any => notPorted("Pipelines.applyOptions"),
  reset: (..._a: any[]): any => notPorted("Pipelines.reset"),
  update: (..._a: any[]): any => notPorted("Pipelines.update"),
  eligible: (..._a: any[]): any => notPorted("Pipelines.eligible"),
  canToggle: (..._a: any[]): any => notPorted("Pipelines.canToggle"),
  worldPipeline: (..._a: any[]): any => notPorted("Pipelines.worldPipeline"),
  drawWorld: (..._a: any[]): any => notPorted("Pipelines.drawWorld"),
  worldPresent: (..._a: any[]): any => notPorted("Pipelines.worldPresent"),
  present: (..._a: any[]): any => notPorted("Pipelines.present"),
  wantsPresent: (..._a: any[]): any => notPorted("Pipelines.wantsPresent"),
  hotkey: (..._a: any[]): any => notPorted("Pipelines.hotkey"),
  rows: (..._a: any[]): any => notPorted("Pipelines.rows"),
  invalidate: (..._a: any[]): any => notPorted("Pipelines.invalidate"),
};
export default Pipelines;
