// @gen2-stub
// Not ported yet: gen1recomp src/render/Renderer.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class Renderer {
  [key: string]: any;
  static [key: string]: any;
  static WIDTH: any = undefined;
  static HEIGHT: any = undefined;
  static MAX_UI_WIDTH: any = undefined;
  static MAX_UI_HEIGHT: any = undefined;
  static UPRIGHT_MARGIN: any = undefined;
  static release: any = undefined;
  static clipToView(..._a: any[]): any { return notPorted("Renderer.clipToView"); }
  releaseCanvases(..._a: any[]): any { return notPorted("Renderer:releaseCanvases"); }
  init(..._a: any[]): any { return notPorted("Renderer:init"); }
  setWorldOverride(..._a: any[]): any { return notPorted("Renderer:setWorldOverride"); }
  fitScale(..._a: any[]): any { return notPorted("Renderer:fitScale"); }
  uiScale(..._a: any[]): any { return notPorted("Renderer:uiScale"); }
  uiSize(..._a: any[]): any { return notPorted("Renderer:uiSize"); }
  setUISize(..._a: any[]): any { return notPorted("Renderer:setUISize"); }
  beginBattleHUDPass(..._a: any[]): any { return notPorted("Renderer:beginBattleHUDPass"); }
  endBattleHUDPass(..._a: any[]): any { return notPorted("Renderer:endBattleHUDPass"); }
  drawScaleX(..._a: any[]): any { return notPorted("Renderer:drawScaleX"); }
  drawScaleY(..._a: any[]): any { return notPorted("Renderer:drawScaleY"); }
  drawScale(..._a: any[]): any { return notPorted("Renderer:drawScale"); }
  worldViewSize(..._a: any[]): any { return notPorted("Renderer:worldViewSize"); }
  beginFrame(..._a: any[]): any { return notPorted("Renderer:beginFrame"); }
  drawBattleWipe(..._a: any[]): any { return notPorted("Renderer:drawBattleWipe"); }
  beginWorldPass(..._a: any[]): any { return notPorted("Renderer:beginWorldPass"); }
  endWorldPass(..._a: any[]): any { return notPorted("Renderer:endWorldPass"); }
  beginUprightPass(..._a: any[]): any { return notPorted("Renderer:beginUprightPass"); }
  endUprightPass(..._a: any[]): any { return notPorted("Renderer:endUprightPass"); }
  tiltShader(..._a: any[]): any { return notPorted("Renderer:tiltShader"); }
  tiltMesh(..._a: any[]): any { return notPorted("Renderer:tiltMesh"); }
  drawTiltedWorld(..._a: any[]): any { return notPorted("Renderer:drawTiltedWorld"); }
  blitCanvas(..._a: any[]): any { return notPorted("Renderer:blitCanvas"); }
  setUIAnchor(..._a: any[]): any { return notPorted("Renderer:setUIAnchor"); }
  setBattleUIAnchor(..._a: any[]): any { return notPorted("Renderer:setBattleUIAnchor"); }
  frameRects(..._a: any[]): any { return notPorted("Renderer:frameRects"); }
  playfieldRect(..._a: any[]): any { return notPorted("Renderer:playfieldRect"); }
  endFrame(..._a: any[]): any { return notPorted("Renderer:endFrame"); }
}
export default Renderer;
