// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/render/SecondScreen.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const SecondScreen: Record<string, any> = {
  usable: (..._a: any[]): any => undefined,
  available: (..._a: any[]): any => undefined,
  detected: (..._a: any[]): any => undefined,
  push: (..._a: any[]): any => undefined,
  pollTouch: (..._a: any[]): any => undefined,
  setEnabled: (..._a: any[]): any => undefined,
};
export default SecondScreen;
