// @gen2-stub
// Not ported yet: gen1recomp src/render/SecondScreen.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const SecondScreen: Record<string, any> = {
  usable: (..._a: any[]): any => notPorted("SecondScreen.usable"),
  available: (..._a: any[]): any => notPorted("SecondScreen.available"),
  detected: (..._a: any[]): any => notPorted("SecondScreen.detected"),
  push: (..._a: any[]): any => notPorted("SecondScreen.push"),
  pollTouch: (..._a: any[]): any => notPorted("SecondScreen.pollTouch"),
  setEnabled: (..._a: any[]): any => notPorted("SecondScreen.setEnabled"),
};
export default SecondScreen;
