// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/render/ShaderFX.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const ShaderFX: Record<string, any> = {
  BUILDBOT_URL: undefined,
  BRIDGE_DIR: undefined,
  PROBE_REL: undefined,
  SLOTS: undefined,
  OPTION_KEY: undefined,
  ERROR_LOG_REL: undefined,
  _lastErrors: undefined,
  _gridGeometry: undefined,
  presetDir: (..._a: any[]): any => undefined,
  list: (..._a: any[]): any => undefined,
  artifactPath: (..._a: any[]): any => undefined,
  isConverted: (..._a: any[]): any => undefined,
  downloadPresets: (..._a: any[]): any => undefined,
  downloadStatus: (..._a: any[]): any => undefined,
  installDownloaded: (..._a: any[]): any => undefined,
  clearBridgeQuarantine: (..._a: any[]): any => undefined,
  canConvert: (..._a: any[]): any => undefined,
  bridgeError: (..._a: any[]): any => undefined,
  translate: (..._a: any[]): any => undefined,
  loadImageFromPath: (..._a: any[]): any => undefined,
  runChain: (..._a: any[]): any => undefined,
  load: (..._a: any[]): any => undefined,
  listParams: (..._a: any[]): any => undefined,
  convert: (..._a: any[]): any => undefined,
  recordError: (..._a: any[]): any => undefined,
  lastError: (..._a: any[]): any => undefined,
  activate: (..._a: any[]): any => undefined,
  deactivate: (..._a: any[]): any => undefined,
  active: (..._a: any[]): any => undefined,
  activeEntry: (..._a: any[]): any => undefined,
  findEntry: (..._a: any[]): any => undefined,
  applyOptions: (..._a: any[]): any => undefined,
  render: (..._a: any[]): any => undefined,
};
export default ShaderFX;
