// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/render/SpriteRenderer.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export class SpriteRenderer {
  [key: string]: any;
  static [key: string]: any;
  static obpImage: any = undefined;
  static STAND: any = undefined;
  static WALK: any = undefined;
  static DEFAULT_FRAME_WIDTH: any = undefined;
  static DEFAULT_FRAME_HEIGHT: any = undefined;
  static DEFAULT_ANCHOR_X: any = undefined;
  static DEFAULT_ANCHOR_Y: any = undefined;
  static invalidate(..._a: any[]): any { return undefined; }
  static new(..._a: any[]): any { return undefined; }
  static mirrorCell(..._a: any[]): any { return undefined; }
  getFrameGeometry(..._a: any[]): any { return undefined; }
  getPoseGeometry(..._a: any[]): any { return undefined; }
  getScreenOrigin(..._a: any[]): any { return undefined; }
  setObjPalette(..._a: any[]): any { return undefined; }
  gen2Obp(..._a: any[]): any { return undefined; }
  resolveImage(..._a: any[]): any { return undefined; }
  draw(..._a: any[]): any { return undefined; }
  drawTile(..._a: any[]): any { return undefined; }
}
export default SpriteRenderer;
