// @gen2-stub
// Not ported yet: gen1recomp src/render/TextBox.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class TextBox {
  [key: string]: any;
  static [key: string]: any;
  static isTextBox: any = undefined;
  static PAUSE: any = undefined;
  static TOKENS: any = undefined;
  static ending(..._a: any[]): any { return notPorted("TextBox.ending"); }
  static strip(..._a: any[]): any { return notPorted("TextBox.strip"); }
  static new(..._a: any[]): any { return notPorted("TextBox.new"); }
  static soundOpts(..._a: any[]): any { return notPorted("TextBox.soundOpts"); }
  static registerInto(..._a: any[]): any { return notPorted("TextBox.registerInto"); }
  static substitute(..._a: any[]): any { return notPorted("TextBox.substitute"); }
  static paginate(..._a: any[]): any { return notPorted("TextBox.paginate"); }
  currentLine(..._a: any[]): any { return notPorted("TextBox:currentLine"); }
  beginLine(..._a: any[]): any { return notPorted("TextBox:beginLine"); }
  visibleText(..._a: any[]): any { return notPorted("TextBox:visibleText"); }
  sfxHeld(..._a: any[]): any { return notPorted("TextBox:sfxHeld"); }
  isGold(..._a: any[]): any { return notPorted("TextBox:isGold"); }
  arrowVisible(..._a: any[]): any { return notPorted("TextBox:arrowVisible"); }
  arrowPos(..._a: any[]): any { return notPorted("TextBox:arrowPos"); }
  moneyVisible(..._a: any[]): any { return notPorted("TextBox:moneyVisible"); }
  update(..._a: any[]): any { return notPorted("TextBox:update"); }
  draw(..._a: any[]): any { return notPorted("TextBox:draw"); }
}
export default TextBox;
