// @gen2-stub
// Not ported yet: gen1recomp src/render/Tilt.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Tilt: Record<string, any> = {
  ANGLES_DEG: undefined,
  ANGLE_LABELS: undefined,
  level: undefined,
  angle: undefined,
  from: undefined,
  goal: undefined,
  t: undefined,
  TARGET_ANGLE: undefined,
  enabled: undefined,
  TWEEN_TIME: undefined,
  FOCAL: undefined,
  VIEW_MARGIN: undefined,
  setLevel: (..._a: any[]): any => notPorted("Tilt.setLevel"),
  cycle: (..._a: any[]): any => notPorted("Tilt.cycle"),
  toggle: (..._a: any[]): any => notPorted("Tilt.toggle"),
  reset: (..._a: any[]): any => notPorted("Tilt.reset"),
  applyOptions: (..._a: any[]): any => notPorted("Tilt.applyOptions"),
  levelLabel: (..._a: any[]): any => notPorted("Tilt.levelLabel"),
  update: (..._a: any[]): any => notPorted("Tilt.update"),
  active: (..._a: any[]): any => notPorted("Tilt.active"),
  gateOK: (..._a: any[]): any => notPorted("Tilt.gateOK"),
  groundPoint: (..._a: any[]): any => notPorted("Tilt.groundPoint"),
  onGround: (..._a: any[]): any => notPorted("Tilt.onGround"),
  viewGrowth: (..._a: any[]): any => notPorted("Tilt.viewGrowth"),
  meshCorners: (..._a: any[]): any => notPorted("Tilt.meshCorners"),
};
export default Tilt;
