// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/render/Zoom.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const Zoom: Record<string, any> = {
  offset: undefined,
  allowSurvey: undefined,
  offsetRange: (..._a: any[]): any => undefined,
  scale: (..._a: any[]): any => undefined,
  clampOffset: (..._a: any[]): any => undefined,
  step: (..._a: any[]): any => undefined,
  cycle: (..._a: any[]): any => undefined,
  reset: (..._a: any[]): any => undefined,
  applyOptions: (..._a: any[]): any => undefined,
  windowFitScale: (..._a: any[]): any => undefined,
  nudgeOptions: (..._a: any[]): any => undefined,
  offsetLabel: (..._a: any[]): any => undefined,
  viewSize: (..._a: any[]): any => undefined,
  fillViewSize: (..._a: any[]): any => undefined,
  gateOK: (..._a: any[]): any => undefined,
};
export default Zoom;
