// Read a `return <table>` Lua data module without a Lua interpreter.
//
// The pipeline used to shell out to `luajit` for exactly three files --
// gen1recomp's rom manifest companions, its RED++ colour pack, and the
// VoxelMod's height profile -- which made a Lua runtime a hard prerequisite
// for cooking at all. It is the only prerequisite that existed to read two
// generated data tables, and it is the one nobody expects to need.
//
// So this parses them directly. It is NOT a Lua implementation: these files
// say `-- Generated by tools/build_data.py. DO NOT EDIT.` at the top and are
// pure data -- nested table constructors of numbers, strings and booleans.
// Anything outside that subset throws with a line number rather than being
// quietly mis-read, because a colour table that parses to the WRONG numbers
// is worse than one that fails to parse.
//
// The JSON it produces is byte-identical to what voxelmon/import/lua-dump.lua
// printed, and pinned to that by tests/voxel-import.test.ts -- the two must
// agree or a cached dump from either side would silently differ.
import { check } from "./ctx.ts";

export type LuaValue = number | string | boolean | LuaTable;
type Parsed = LuaValue | typeof NIL;
/** A Lua table keeps its keys in insertion order; the writer sorts them. */
export interface LuaTable {
  /** Dense 1..n integer keys, if any, in order. */
  array: LuaValue[];
  /** Everything else, keyed as the JSON writer will key it. */
  hash: Map<string, LuaValue>;
}

/**
 * An explicit `nil`. These files write `ledge = nil` to say "this one has
 * none" for a reader's benefit; Lua stores no key at all for it, so the
 * dump omitted it and so must we. It is a sentinel rather than `undefined`
 * so that a value which is genuinely absent still reads as a bug.
 */
const NIL = Symbol("lua nil");

const isDigit = (c: string): boolean => c >= "0" && c <= "9";
const isIdentStart = (c: string): boolean =>
  (c >= "a" && c <= "z") || (c >= "A" && c <= "Z") || c === "_";
const isIdent = (c: string): boolean => isIdentStart(c) || isDigit(c);

class Reader {
  private at = 0;
  constructor(private readonly src: string, private readonly path: string) {}

  private line(): number {
    let n = 1;
    for (let i = 0; i < this.at && i < this.src.length; i++) {
      if (this.src[i] === "\n") n++;
    }
    return n;
  }

  fail(why: string): never {
    throw new Error(`${this.path}:${this.line()}: ${why}`);
  }

  /** Whitespace and comments, including the long `--[[ ]]` form. */
  skip(): void {
    for (;;) {
      while (this.at < this.src.length && /\s/.test(this.src[this.at]!)) this.at++;
      if (this.src.startsWith("--", this.at)) {
        this.at += 2;
        if (this.src.startsWith("[[", this.at)) {
          const end = this.src.indexOf("]]", this.at);
          this.at = end < 0 ? this.src.length : end + 2;
        } else {
          const end = this.src.indexOf("\n", this.at);
          this.at = end < 0 ? this.src.length : end + 1;
        }
        continue;
      }
      return;
    }
  }

  eat(text: string): boolean {
    this.skip();
    if (!this.src.startsWith(text, this.at)) return false;
    this.at += text.length;
    return true;
  }

  expect(text: string): void {
    if (!this.eat(text)) this.fail(`expected ${JSON.stringify(text)}`);
  }

  peek(): string {
    this.skip();
    return this.src[this.at] ?? "";
  }

  atEnd(): boolean {
    this.skip();
    return this.at >= this.src.length;
  }

  identifier(): string {
    this.skip();
    const start = this.at;
    while (this.at < this.src.length && isIdent(this.src[this.at]!)) this.at++;
    if (this.at === start) this.fail("expected a name");
    return this.src.slice(start, this.at);
  }

  string(): string {
    this.skip();
    const quote = this.src[this.at];
    if (quote !== '"' && quote !== "'") this.fail("expected a string");
    this.at++;
    let out = "";
    while (this.at < this.src.length) {
      const c = this.src[this.at]!;
      if (c === "\\") {
        const next = this.src[this.at + 1]!;
        const simple: Record<string, string> = {
          n: "\n", r: "\r", t: "\t", f: "\f", b: "\b", a: "\x07", v: "\v",
          "\\": "\\", '"': '"', "'": "'", "\n": "\n",
        };
        if (next in simple) {
          out += simple[next];
          this.at += 2;
          continue;
        }
        if (isDigit(next)) {
          let digits = "";
          this.at++;
          while (digits.length < 3 && isDigit(this.src[this.at] ?? "")) {
            digits += this.src[this.at++];
          }
          out += String.fromCharCode(Number(digits));
          continue;
        }
        this.fail(`unsupported string escape \\${next}`);
      }
      if (c === quote) {
        this.at++;
        return out;
      }
      out += c;
      this.at++;
    }
    this.fail("unterminated string");
  }

  number(): number {
    this.skip();
    const start = this.at;
    if (this.src[this.at] === "-" || this.src[this.at] === "+") this.at++;
    if (this.src.startsWith("0x", this.at) || this.src.startsWith("0X", this.at)) {
      this.at += 2;
      while (/[0-9a-fA-F]/.test(this.src[this.at] ?? "")) this.at++;
      return Number(this.src.slice(start, this.at));
    }
    while (isDigit(this.src[this.at] ?? "")) this.at++;
    if (this.src[this.at] === ".") {
      this.at++;
      while (isDigit(this.src[this.at] ?? "")) this.at++;
    }
    if (this.src[this.at] === "e" || this.src[this.at] === "E") {
      this.at++;
      if (this.src[this.at] === "-" || this.src[this.at] === "+") this.at++;
      while (isDigit(this.src[this.at] ?? "")) this.at++;
    }
    const text = this.src.slice(start, this.at);
    if (text === "" || Number.isNaN(Number(text))) this.fail("expected a number");
    return Number(text);
  }

  value(): Parsed {
    const c = this.peek();
    if (c === "{") return this.table();
    if (c === '"' || c === "'") return this.string();
    if (c === "-" || c === "+" || isDigit(c)) return this.number();
    const word = this.identifier();
    if (word === "true") return true;
    if (word === "false") return false;
    if (word === "nil") return NIL;
    this.fail(`unexpected ${JSON.stringify(word)} -- this reads data tables only`);
  }

  table(): LuaTable {
    this.expect("{");
    const t: LuaTable = { array: [], hash: new Map() };
    // Lua's own rule: a value with no key takes the next integer index.
    let next = 1;
    for (;;) {
      if (this.eat("}")) return t;
      if (this.peek() === "[") {
        this.expect("[");
        const key = this.peek() === '"' || this.peek() === "'" ? this.string() : this.number();
        this.expect("]");
        this.expect("=");
        const v = this.value();
        if (v !== NIL) this.put(t, key, v);
      } else {
        // `name = value` only when the `=` is really there: a bare word is
        // otherwise a positional value (`true`, a constant), and reading it
        // as a key would shift every index after it.
        const save = this.at;
        if (isIdentStart(this.peek())) {
          const name = this.identifier();
          if (this.eat("=")) {
            const v = this.value();
            if (v !== NIL) this.put(t, name, v);
          } else {
            this.at = save;
            t.array[next++ - 1] = this.positional();
          }
        } else {
          t.array[next++ - 1] = this.positional();
        }
      }
      if (!this.eat(",") && !this.eat(";")) {
        this.expect("}");
        return t;
      }
    }
  }

  /** A value in array position: `nil` there would punch a hole whose
   * length Lua itself does not define, so it is refused rather than
   * guessed at. */
  private positional(): LuaValue {
    const v = this.value();
    if (v === NIL) this.fail("nil in array position has no defined length");
    return v;
  }

  private put(t: LuaTable, key: string | number, value: LuaValue): void {
    // An integer key that continues the array belongs in it, the way Lua
    // itself would store it -- `[1] = x, [2] = y` is an array, and the
    // writer has to see it as one.
    if (typeof key === "number" && Number.isInteger(key) && key >= 1) {
      if (key === t.array.length + 1) {
        t.array.push(value);
        return;
      }
    }
    t.hash.set(typeof key === "number" ? formatNumber(key) : key, value);
  }
}

/** Lua's `%d` for integers, `tostring` otherwise -- what lua-dump printed. */
function formatNumber(v: number): string {
  return Number.isInteger(v) ? v.toFixed(0) : String(v);
}

/**
 * The SCHEMA.md normalization lua-dump.lua applied: a dense 1..n table
 * becomes a JSON array, anything else an object with its keys sorted as
 * STRINGS (Lua's `table.sort` on the stringified keys), and an empty table
 * becomes `{}`.
 */
export function toJson(value: LuaValue): string {
  const out: string[] = [];
  const encode = (v: LuaValue): void => {
    if (typeof v === "number") {
      out.push(formatNumber(v));
    } else if (typeof v === "string") {
      out.push(JSON.stringify(v));
    } else if (typeof v === "boolean") {
      out.push(String(v));
    } else {
      if (v.array.length > 0 && v.hash.size === 0) {
        out.push("[");
        v.array.forEach((item, i) => {
          if (i > 0) out.push(",");
          encode(item);
        });
        out.push("]");
        return;
      }
      const keys: string[] = [];
      v.array.forEach((_, i) => keys.push(formatNumber(i + 1)));
      for (const k of v.hash.keys()) keys.push(k);
      keys.sort();
      out.push("{");
      keys.forEach((k, i) => {
        if (i > 0) out.push(",");
        out.push(JSON.stringify(k));
        out.push(":");
        const asIndex = Number(k);
        const fromArray =
          Number.isInteger(asIndex) && asIndex >= 1 && asIndex <= v.array.length
            ? v.array[asIndex - 1]
            : undefined;
        encode(fromArray !== undefined ? fromArray : v.hash.get(k)!);
      });
      out.push("}");
    }
  };
  encode(value);
  return out.join("");
}

/** Parse a `return <table>` module and hand back its value. */
export function parseLuaModule(source: string, path = "<lua>"): LuaValue {
  const r = new Reader(source, path);
  check(r.eat("return"), `${path}: expected a \`return <table>\` data module`);
  const value = r.value();
  if (value === NIL) r.fail("the module returned nil");
  if (!r.atEnd()) r.fail("trailing content after the returned table");
  return value;
}

/** The whole job: a data module in, the dump's own JSON out. */
export function luaModuleToJson(source: string, path = "<lua>"): string {
  return `${toJson(parseLuaModule(source, path))}\n`;
}
