import json, os, re, sys

SRC = os.path.expanduser("~/pocket-voxel/dist/portkit")
OUT = os.path.expanduser("~/pocket-voxel/dist/portkit/mapscripts.gen.ts")

def is_label(s):
    return isinstance(s, str) and (s.startswith("_") or re.fullmatch(r"[A-Z0-9_]+", s or ""))

def map_key(text_const):
    m = re.match(r"TEXT_([A-Z0-9]+?)_", text_const)
    return m.group(1) if m else None

entries, skipped, prose = {}, [], []

for fn in sorted(os.listdir(SRC)):
    if not fn.endswith(".json") or fn.endswith(".gen.ts"):
        continue
    d = json.load(open(os.path.join(SRC, fn)))
    if "error" in d or "talk" not in d:
        continue
    for const, rows in d["talk"].items():
        if not isinstance(rows, list):
            continue
        mk = map_key(const)
        if not mk:
            skipped.append(const); continue
        clean = []
        bad = False
        for row in rows:
            if not isinstance(row, list) or row and row[0] == "__FUNCTION__":
                bad = True; break
            for a in row[1:]:
                if isinstance(a, str) and not is_label(a):
                    prose.append(const); bad = True; break
            if bad: break
            clean.append(row)
        if bad or not clean:
            skipped.append(const); continue
        entries.setdefault(mk, {})[const] = clean

with open(OUT, "w") as f:
    f.write("// GENERATED by tools/portkit/gen.py from gen1recomp data/scripts.\n")
    f.write("// Rows are label-only; any script carrying inline prose or an\n")
    f.write("// imperative body is left out for hand-porting.\n\n")
    f.write('import type { ScriptRow } from "../../voxelmon/game/world/script.ts";\n\n')
    f.write("export const GENERATED_SCRIPTS: Record<string, { talk: Record<string, ScriptRow[]> }> = {\n")
    for mk in sorted(entries):
        f.write(f"  {mk}: {{\n    talk: {{\n")
        for const, rows in entries[mk].items():
            f.write(f"      {const}: [\n")
            for r in rows:
                f.write("        " + json.dumps(r) + ",\n")
            f.write("      ],\n")
        f.write("    },\n  },\n")
    f.write("};\n")

print("maps generated:", len(entries), "->", ", ".join(sorted(entries)))
print("scripts converted:", sum(len(v) for v in entries.values()))
print("skipped (imperative/no map key):", len(set(skipped)))
print("skipped for inline prose:", len(set(prose)))
print("wrote:", OUT)
