// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/core/game3/link/host_rules.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const HostRules: Record<string, any> = {
  MAX_ROWS: undefined,
  encodeRow: (..._a: any[]): any => { return notPorted("HostRules.encodeRow"); },
  decodeRow: (..._a: any[]): any => { return notPorted("HostRules.decodeRow"); },
  block: (..._a: any[]): any => { return notPorted("HostRules.block"); },
  decode: (..._a: any[]): any => { return notPorted("HostRules.decode"); },
  apply: (..._a: any[]): any => { return notPorted("HostRules.apply"); },
  clear: (..._a: any[]): any => { return notPorted("HostRules.clear"); },
};
export default HostRules;
