// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/core/game3/link/relay_transport.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class RelayTransport {
  [key: string]: any;
  static [key: string]: any;
  static new(..._a: any[]): any { return notPorted("RelayTransport.new"); }
  session(..._a: any[]): any { return notPorted("RelayTransport:session"); }
  seat(..._a: any[]): any { return notPorted("RelayTransport:seat"); }
  seats(..._a: any[]): any { return notPorted("RelayTransport:seats"); }
  players(..._a: any[]): any { return notPorted("RelayTransport:players"); }
  role(..._a: any[]): any { return notPorted("RelayTransport:role"); }
  match(..._a: any[]): any { return notPorted("RelayTransport:match"); }
  seed(..._a: any[]): any { return notPorted("RelayTransport:seed"); }
  peerOnline(..._a: any[]): any { return notPorted("RelayTransport:peerOnline"); }
  room(..._a: any[]): any { return notPorted("RelayTransport:room"); }
  _seatGone(..._a: any[]): any { return notPorted("RelayTransport:_seatGone"); }
  update(..._a: any[]): any { return notPorted("RelayTransport:update"); }
  send(..._a: any[]): any { return notPorted("RelayTransport:send"); }
  poll(..._a: any[]): any { return notPorted("RelayTransport:poll"); }
  take(..._a: any[]): any { return notPorted("RelayTransport:take"); }
  close(..._a: any[]): any { return notPorted("RelayTransport:close"); }
  leave(..._a: any[]): any { return notPorted("RelayTransport:leave"); }
}
export default RelayTransport;
