// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/link/Fingerprint.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Fingerprint: Record<string, any> = {
  digest: undefined,
  FIELDS: undefined,
  GEN2_FIELDS: undefined,
  modKey: undefined,
  surfaceGen3: undefined,
  GEN3_MOVE_FIELDS: undefined,
  rulesRowGen3: undefined,
  surface: undefined,
  fnv1a32: (..._a: any[]): any => { return notPorted("Fingerprint.fnv1a32"); },
  generationOf: (..._a: any[]): any => { return notPorted("Fingerprint.generationOf"); },
  gen3Inputs: (..._a: any[]): any => { return notPorted("Fingerprint.gen3Inputs"); },
  coreGen3: (..._a: any[]): any => { return notPorted("Fingerprint.coreGen3"); },
  movesGen3Of: (..._a: any[]): any => { return notPorted("Fingerprint.movesGen3Of"); },
  movesGen3: (..._a: any[]): any => { return notPorted("Fingerprint.movesGen3"); },
  rulesGen3: (..._a: any[]): any => { return notPorted("Fingerprint.rulesGen3"); },
  compute: (..._a: any[]): any => { return notPorted("Fingerprint.compute"); },
  records: (..._a: any[]): any => { return notPorted("Fingerprint.records"); },
  forget: (..._a: any[]): any => { return notPorted("Fingerprint.forget"); },
};
export default Fingerprint;
