// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/link/Game3Link.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class Game3Link {
  [key: string]: any;
  static [key: string]: any;
  static LINKTYPE: any = undefined;
  static GENERATION: any = undefined;
  static HANDSHAKE_SECONDS: any = undefined;
  static BYE: any = undefined;
  static HELLO: any = undefined;
  static SEAT_ROLES: any = undefined;
  static BATTLE_TYPES: any = undefined;
  static TRADE_TYPES: any = undefined;
  static hello: any = undefined;
  static decideOne: any = undefined;
  static rules(..._a: any[]): any { return notPorted("Game3Link.rules"); }
  static attach(..._a: any[]): any { return notPorted("Game3Link.attach"); }
  static loopback(..._a: any[]): any { return notPorted("Game3Link.loopback"); }
  static peerVersionOf(..._a: any[]): any { return notPorted("Game3Link.peerVersionOf"); }
  static crossFamily(..._a: any[]): any { return notPorted("Game3Link.crossFamily"); }
  isOpen(..._a: any[]): any { return notPorted("Game3Link:isOpen"); }
  isReady(..._a: any[]): any { return notPorted("Game3Link:isReady"); }
  getStatus(..._a: any[]): any { return notPorted("Game3Link:getStatus"); }
  getSeat(..._a: any[]): any { return notPorted("Game3Link:getSeat"); }
  seatCount(..._a: any[]): any { return notPorted("Game3Link:seatCount"); }
  peerName(..._a: any[]): any { return notPorted("Game3Link:peerName"); }
  peerLinkType(..._a: any[]): any { return notPorted("Game3Link:peerLinkType"); }
  players(..._a: any[]): any { return notPorted("Game3Link:players"); }
  send(..._a: any[]): any { return notPorted("Game3Link:send"); }
  take(..._a: any[]): any { return notPorted("Game3Link:take"); }
  poll(..._a: any[]): any { return notPorted("Game3Link:poll"); }
  peerGone(..._a: any[]): any { return notPorted("Game3Link:peerGone"); }
  _finish(..._a: any[]): any { return notPorted("Game3Link:_finish"); }
  close(..._a: any[]): any { return notPorted("Game3Link:close"); }
  leave(..._a: any[]): any { return notPorted("Game3Link:leave"); }
  decide(..._a: any[]): any { return notPorted("Game3Link:decide"); }
  hostGame3(..._a: any[]): any { return notPorted("Game3Link:hostGame3"); }
  peerGame(..._a: any[]): any { return notPorted("Game3Link:peerGame"); }
  _helloSeat(..._a: any[]): any { return notPorted("Game3Link:_helloSeat"); }
  _allHellos(..._a: any[]): any { return notPorted("Game3Link:_allHellos"); }
  _primaryHello(..._a: any[]): any { return notPorted("Game3Link:_primaryHello"); }
  update(..._a: any[]): any { return notPorted("Game3Link:update"); }
}
export default Game3Link;
