// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/link/Json.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Json: Record<string, any> = {
  MAX_DEPTH: undefined,
  encode: (..._a: any[]): any => { return notPorted("Json.encode"); },
  decode: (..._a: any[]): any => { return notPorted("Json.decode"); },
  describeUnexpected: (..._a: any[]): any => { return notPorted("Json.describeUnexpected"); },
};
export default Json;
