// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/link/Wire.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Wire: Record<string, any> = {
  code: undefined,
  roomId: undefined,
  tourId: undefined,
  inviteId: undefined,
  inviteToken: undefined,
  playerId: undefined,
  digest: undefined,
  party3: undefined,
  profile: undefined,
  SCHEMAS: undefined,
  sanitize: undefined,
  num: (..._a: any[]): any => { return notPorted("Wire.num"); },
  str: (..._a: any[]): any => { return notPorted("Wire.str"); },
  chars: (..._a: any[]): any => { return notPorted("Wire.chars"); },
  bool: (..._a: any[]): any => { return notPorted("Wire.bool"); },
  list: (..._a: any[]): any => { return notPorted("Wire.list"); },
  records: (..._a: any[]): any => { return notPorted("Wire.records"); },
  plain: (..._a: any[]): any => { return notPorted("Wire.plain"); },
  pin: (..._a: any[]): any => { return notPorted("Wire.pin"); },
  mon3: (..._a: any[]): any => { return notPorted("Wire.mon3"); },
  avatar: (..._a: any[]): any => { return notPorted("Wire.avatar"); },
  member: (..._a: any[]): any => { return notPorted("Wire.member"); },
};
export default Wire;
