// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/FaithfulRes.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const FaithfulRes: Record<string, any> = {
  LEVELS: undefined,
  DEFAULT: undefined,
  mobileScale: undefined,
  locked: undefined,
  prevSize: undefined,
  modeSerial: undefined,
  isMobile: undefined,
  setNativeSize: (..._a: any[]): any => { return undefined; },
  maxLevel: (..._a: any[]): any => { return undefined; },
  levels: (..._a: any[]): any => { return undefined; },
  normalize: (..._a: any[]): any => { return undefined; },
  label: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
  fixedDisplay: (..._a: any[]): any => { return undefined; },
  size: (..._a: any[]): any => { return undefined; },
  deviceScale: (..._a: any[]): any => { return undefined; },
  scaleCap: (..._a: any[]): any => { return undefined; },
  apply: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
};
export default FaithfulRes;
