// @gen3-stub
// Not ported yet: gen1recomp src/core/FixedStep.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class FixedStep {
  [key: string]: any;
  static [key: string]: any;
  static GB_HZ: any = undefined;
  static STEP: any = undefined;
  static MAX_ACCUM: any = undefined;
  static WORK_FRACTION: any = undefined;
  static clock: any = undefined;
  static refreshPeriod: any = undefined;
  static maxAccum: any = undefined;
  static setHz(..._a: any[]): any { return notPorted("FixedStep.setHz"); }
  static catchupLimit(..._a: any[]): any { return notPorted("FixedStep.catchupLimit"); }
  init(..._a: any[]): any { return notPorted("FixedStep:init"); }
  update(..._a: any[]): any { return notPorted("FixedStep:update"); }
  endFrame(..._a: any[]): any { return notPorted("FixedStep:endFrame"); }
  discardCatchup(..._a: any[]): any { return notPorted("FixedStep:discardCatchup"); }
}
export default FixedStep;
