// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/FrameCap.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const FrameCap: Record<string, any> = {
  STEPS: undefined,
  MIN: undefined,
  MAX: undefined,
  DEFAULT: undefined,
  DISPLAY: undefined,
  CYCLE: undefined,
  current: undefined,
  bootHandheld: undefined,
  loopSupportsPanelSync: (..._a: any[]): any => { return undefined; },
  prefersPanelSync: (..._a: any[]): any => { return undefined; },
  normalize: (..._a: any[]): any => { return undefined; },
  label: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
  apply: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
  bootPanelSync: (..._a: any[]): any => { return undefined; },
  clampToPerformance: (..._a: any[]): any => { return undefined; },
};
export default FrameCap;
