// @gen3-stub
// Not ported yet: gen1recomp src/core/GameSpeed.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const GameSpeed: Record<string, any> = {
  LEVELS: undefined,
  DEFAULT: undefined,
  CATEGORIES: undefined,
  levelLabel: (..._a: any[]): any => { return notPorted("GameSpeed.levelLabel"); },
  setAllowed: (..._a: any[]): any => { return notPorted("GameSpeed.setAllowed"); },
  allowed: (..._a: any[]): any => { return notPorted("GameSpeed.allowed"); },
  isLocked: (..._a: any[]): any => { return notPorted("GameSpeed.isLocked"); },
  clamp: (..._a: any[]): any => { return notPorted("GameSpeed.clamp"); },
  cycle: (..._a: any[]): any => { return notPorted("GameSpeed.cycle"); },
  optionKey: (..._a: any[]): any => { return notPorted("GameSpeed.optionKey"); },
};
export default GameSpeed;
