// @gen3-stub
// Not ported yet: gen1recomp src/core/GameVersion.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const GameVersion: Record<string, any> = {
  VERSIONS: undefined,
  ORDER: undefined,
  current: undefined,
  set: (..._a: any[]): any => { return notPorted("GameVersion.set"); },
  get: (..._a: any[]): any => { return notPorted("GameVersion.get"); },
  isBlue: (..._a: any[]): any => { return notPorted("GameVersion.isBlue"); },
  isYellow: (..._a: any[]): any => { return notPorted("GameVersion.isYellow"); },
  isGold: (..._a: any[]): any => { return notPorted("GameVersion.isGold"); },
  generation: (..._a: any[]): any => { return notPorted("GameVersion.generation"); },
  engine: (..._a: any[]): any => { return notPorted("GameVersion.engine"); },
  layout: (..._a: any[]): any => { return notPorted("GameVersion.layout"); },
  gameCode: (..._a: any[]): any => { return notPorted("GameVersion.gameCode"); },
  cartShape: (..._a: any[]): any => { return notPorted("GameVersion.cartShape"); },
  fixes: (..._a: any[]): any => { return notPorted("GameVersion.fixes"); },
  info: (..._a: any[]): any => { return notPorted("GameVersion.info"); },
  saveSuffix: (..._a: any[]): any => { return notPorted("GameVersion.saveSuffix"); },
  cachePrefix: (..._a: any[]): any => { return notPorted("GameVersion.cachePrefix"); },
  revisions: (..._a: any[]): any => { return notPorted("GameVersion.revisions"); },
  acceptsSha1: (..._a: any[]): any => { return notPorted("GameVersion.acceptsSha1"); },
  revisionLabel: (..._a: any[]): any => { return notPorted("GameVersion.revisionLabel"); },
  forSha1: (..._a: any[]): any => { return notPorted("GameVersion.forSha1"); },
};
export default GameVersion;
