// @gen3-stub
// Not ported yet: gen1recomp src/core/Logger.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Logger: Record<string, any> = {
  info: (..._a: any[]): any => { return notPorted("Logger.info"); },
  warn: (..._a: any[]): any => { return notPorted("Logger.warn"); },
  error: (..._a: any[]): any => { return notPorted("Logger.error"); },
};
export default Logger;
