// @gen3-stub
// Not ported yet: gen1recomp src/core/LogicClock.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const LogicClock: Record<string, any> = {
  MODES: undefined,
  DEFAULT: undefined,
  HZ: undefined,
  current: undefined,
  normalize: (..._a: any[]): any => { return notPorted("LogicClock.normalize"); },
  hz: (..._a: any[]): any => { return notPorted("LogicClock.hz"); },
  label: (..._a: any[]): any => { return notPorted("LogicClock.label"); },
  cycle: (..._a: any[]): any => { return notPorted("LogicClock.cycle"); },
  apply: (..._a: any[]): any => { return notPorted("LogicClock.apply"); },
  applyOptions: (..._a: any[]): any => { return notPorted("LogicClock.applyOptions"); },
};
export default LogicClock;
