// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/Orientation.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const Orientation: Record<string, any> = {
  MODES: undefined,
  DEFAULT: undefined,
  normalize: (..._a: any[]): any => { return undefined; },
  modeLabel: (..._a: any[]): any => { return undefined; },
  isAndroid: (..._a: any[]): any => { return undefined; },
  isIOS: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
  apply: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
};
export default Orientation;
