// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/Performance.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const Performance: Record<string, any> = {
  TIERS: undefined,
  LABELS: undefined,
  CAPS: undefined,
  tier: undefined,
  detect: (..._a: any[]): any => { return undefined; },
  resolve: (..._a: any[]): any => { return undefined; },
  normalize: (..._a: any[]): any => { return undefined; },
  label: (..._a: any[]): any => { return undefined; },
  caps: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
};
export default Performance;
