// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/ScreenPosition.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const ScreenPosition: Record<string, any> = {
  MODES: undefined,
  DEFAULT: undefined,
  mode: undefined,
  normalize: (..._a: any[]): any => { return undefined; },
  label: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
  setMode: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
  safeTop: (..._a: any[]): any => { return undefined; },
  skinActive: (..._a: any[]): any => { return undefined; },
  lift: (..._a: any[]): any => { return undefined; },
};
export default ScreenPosition;
