// @gen3-stub
// Not ported yet: gen1recomp src/core/SessionLifecycle.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const SessionLifecycle: Record<string, any> = {
  registerProcessShutdown: (..._a: any[]): any => { return notPorted("SessionLifecycle.registerProcessShutdown"); },
  endMountedSession: (..._a: any[]): any => { return notPorted("SessionLifecycle.endMountedSession"); },
  endEditorSession: (..._a: any[]): any => { return notPorted("SessionLifecycle.endEditorSession"); },
  endGameSession: (..._a: any[]): any => { return notPorted("SessionLifecycle.endGameSession"); },
  endProcess: (..._a: any[]): any => { return notPorted("SessionLifecycle.endProcess"); },
};
export default SessionLifecycle;
