// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/core/VideoMode.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const VideoMode: Record<string, any> = {
  MODES: undefined,
  DEFAULT: undefined,
  isMobile: undefined,
  normalize: (..._a: any[]): any => { return undefined; },
  modeLabel: (..._a: any[]): any => { return undefined; },
  fixedDisplay: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
  apply: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
};
export default VideoMode;
