// @gen2-stub
// Not ported yet: gen1recomp src/import/CacheFs.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const CacheFs: Record<string, any> = {
  prefix: undefined,
  root: (..._a: any[]): any => notPorted("CacheFs.root"),
  write: (..._a: any[]): any => notPorted("CacheFs.write"),
  openWrite: (..._a: any[]): any => notPorted("CacheFs.openWrite"),
  readAt: (..._a: any[]): any => notPorted("CacheFs.readAt"),
  read: (..._a: any[]): any => notPorted("CacheFs.read"),
  readActive: (..._a: any[]): any => notPorted("CacheFs.readActive"),
  loadActive: (..._a: any[]): any => notPorted("CacheFs.loadActive"),
  existsAt: (..._a: any[]): any => notPorted("CacheFs.existsAt"),
  exists: (..._a: any[]): any => notPorted("CacheFs.exists"),
  remove: (..._a: any[]): any => notPorted("CacheFs.remove"),
  removeDir: (..._a: any[]): any => notPorted("CacheFs.removeDir"),
  removeTree: (..._a: any[]): any => notPorted("CacheFs.removeTree"),
  migrateLegacyRedCache: (..._a: any[]): any => notPorted("CacheFs.migrateLegacyRedCache"),
  mountVersion: (..._a: any[]): any => notPorted("CacheFs.mountVersion"),
  unmountVersion: (..._a: any[]): any => notPorted("CacheFs.unmountVersion"),
  withMounted: (..._a: any[]): any => notPorted("CacheFs.withMounted"),
};
export default CacheFs;
