// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/import/CacheFs.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const CacheFs: Record<string, any> = {
  prefix: undefined,
  root: (..._a: any[]): any => undefined,
  write: (..._a: any[]): any => undefined,
  openWrite: (..._a: any[]): any => undefined,
  readAt: (..._a: any[]): any => undefined,
  read: (..._a: any[]): any => undefined,
  readActive: (..._a: any[]): any => undefined,
  loadActive: (..._a: any[]): any => undefined,
  existsAt: (..._a: any[]): any => undefined,
  exists: (..._a: any[]): any => undefined,
  remove: (..._a: any[]): any => undefined,
  removeDir: (..._a: any[]): any => undefined,
  removeTree: (..._a: any[]): any => undefined,
  migrateLegacyRedCache: (..._a: any[]): any => undefined,
  mountVersion: (..._a: any[]): any => undefined,
  unmountVersion: (..._a: any[]): any => undefined,
  withMounted: (..._a: any[]): any => undefined,
};
export default CacheFs;
