// GENERATED by tools/gen3/lua2ts.lua from gen1recomp src/import/gba/families/frlg.lua.
// Port of gen1recomp data (GPLv3 + additional terms; see LICENSE.md). Do not edit.
/* eslint-disable */
const data = {
  aliases: true,
  attrBytes: 4,
  cloneObjects: true,
  connDirs: {
    1: "south",
    2: "north",
    3: "west",
    4: "east",
    5: "dive",
    6: "emerge",
  },
  encounterSource: "attr",
  groupsModule: "src.import.gba.map_groups_firered",
  hiddenItemBgKind: 7,
  layoutSize: 28,
  metatileBytes: 16,
  name: "frlg",
  numMetatilesTotal: 1024,
  numPalsInPrimary: 7,
  numPalsTotal: 13,
  numPrimaryMetatiles: 640,
  numPrimaryTiles: 640,
  numTilesTotal: 1024,
  tilesetOffsets: {
    attributes: 20,
    callback: 16,
    metatiles: 12,
    palettes: 8,
    tiles: 4,
  },
};
export default data;
