// GENERATED by tools/gen3/lua2ts.lua from gen1recomp src/import/gba/tileset_anims_firered.lua.
// Port of gen1recomp data (GPLv3 + additional terms; see LICENSE.md). Do not edit.
/* eslint-disable */
const data = {
  COUNTER_MAX: 640,
  DEFAULT_FRAMES: {
    flower: {
      base: 3830752,
      bytes: 128,
      count: 5,
      stride: 128,
    },
    sand: {
      base: 3843700,
      bytes: 576,
      count: 8,
      stride: 576,
    },
    water: {
      base: 3831412,
      bytes: 1536,
      count: 8,
      stride: 1536,
    },
  },
  KINDS: {
    1: "water",
    2: "sand",
    3: "flower",
  },
  SCHEDULE: {
    flower: {
      frames: 5,
      period: 16,
      phase: 2,
    },
    sand: {
      frames: 8,
      period: 8,
      phase: 0,
    },
    water: {
      frames: 8,
      period: 16,
      phase: 1,
    },
  },
  TILES: {
    flower: {
      count: 4,
      tile: 508,
    },
    sand: {
      count: 18,
      tile: 464,
    },
    water: {
      count: 48,
      tile: 416,
    },
  },
};
export default data;
