// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/bag_chrome.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const BagChrome: Record<string, any> = {
  _cache: undefined,
  _bg: undefined,
  _bagMale: undefined,
  _bagFemale: undefined,
  _bagQuads: undefined,
  _bagData: undefined,
  _rotated: undefined,
  _images: undefined,
  _icons: undefined,
  _manifest: undefined,
  _logged: undefined,
  install: (..._a: any[]): any => { return notPorted("BagChrome.install"); },
  ready: (..._a: any[]): any => { return notPorted("BagChrome.ready"); },
  frameForPocket: (..._a: any[]): any => { return notPorted("BagChrome.frameForPocket"); },
  drawBg: (..._a: any[]): any => { return notPorted("BagChrome.drawBg"); },
  drawListFrame: (..._a: any[]): any => { return notPorted("BagChrome.drawListFrame"); },
  drawDescSelected: (..._a: any[]): any => { return notPorted("BagChrome.drawDescSelected"); },
  drawSwapLine: (..._a: any[]): any => { return notPorted("BagChrome.drawSwapLine"); },
  drawArrow: (..._a: any[]): any => { return notPorted("BagChrome.drawArrow"); },
  drawBag: (..._a: any[]): any => { return notPorted("BagChrome.drawBag"); },
  iconImage: (..._a: any[]): any => { return notPorted("BagChrome.iconImage"); },
  drawItemIcon: (..._a: any[]): any => { return notPorted("BagChrome.drawItemIcon"); },
};
export default BagChrome;
