// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/berry_pouch.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const BerryPouch: Record<string, any> = {
  open: undefined,
  cursor: undefined,
  scroll: undefined,
  mode: undefined,
  actionCursor: undefined,
  yesNoCursor: undefined,
  tossQty: undefined,
  messageText: undefined,
  wobbleTimer: undefined,
  isOpen: (..._a: any[]): any => { return notPorted("BerryPouch.isOpen"); },
  list: (..._a: any[]): any => { return notPorted("BerryPouch.list"); },
  show: (..._a: any[]): any => { return notPorted("BerryPouch.show"); },
  close: (..._a: any[]): any => { return notPorted("BerryPouch.close"); },
  update: (..._a: any[]): any => { return notPorted("BerryPouch.update"); },
  handleInput: (..._a: any[]): any => { return notPorted("BerryPouch.handleInput"); },
  draw: (..._a: any[]): any => { return notPorted("BerryPouch.draw"); },
};
export default BerryPouch;
