// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/boot_modules.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const BootModules: Record<string, any> = {
  COMBO_PHASE: undefined,
  resolve: (..._a: any[]): any => { return notPorted("BootModules.resolve"); },
  load: (..._a: any[]): any => { return notPorted("BootModules.load"); },
  available: (..._a: any[]): any => { return notPorted("BootModules.available"); },
  newState: (..._a: any[]): any => { return notPorted("BootModules.newState"); },
  startIntro: (..._a: any[]): any => { return notPorted("BootModules.startIntro"); },
  enterTitle: (..._a: any[]): any => { return notPorted("BootModules.enterTitle"); },
  startMenu: (..._a: any[]): any => { return notPorted("BootModules.startMenu"); },
  startNewGame: (..._a: any[]): any => { return notPorted("BootModules.startNewGame"); },
  startCombo: (..._a: any[]): any => { return notPorted("BootModules.startCombo"); },
  update: (..._a: any[]): any => { return notPorted("BootModules.update"); },
  active: (..._a: any[]): any => { return notPorted("BootModules.active"); },
  draw: (..._a: any[]): any => { return notPorted("BootModules.draw"); },
};
export default BootModules;
