// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/boot.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Boot: Record<string, any> = {
  PHASE: undefined,
  hasMysteryGift: undefined,
  menuItems: undefined,
  openMysteryGift: undefined,
  new: (..._a: any[]): any => { return notPorted("Boot.new"); },
  setHasContinue: (..._a: any[]): any => { return notPorted("Boot.setHasContinue"); },
  setContinueInfo: (..._a: any[]): any => { return notPorted("Boot.setContinueInfo"); },
  setSaveStatus: (..._a: any[]): any => { return notPorted("Boot.setSaveStatus"); },
  continueInfoFromSave: (..._a: any[]): any => { return notPorted("Boot.continueInfoFromSave"); },
  setTextSpeed: (..._a: any[]): any => { return notPorted("Boot.setTextSpeed"); },
  enterTitle: (..._a: any[]): any => { return notPorted("Boot.enterTitle"); },
  update: (..._a: any[]): any => { return notPorted("Boot.update"); },
  draw: (..._a: any[]): any => { return notPorted("Boot.draw"); },
};
export default Boot;
