// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/braille.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Braille: Record<string, any> = {
  GLYPH_WIDTH: undefined,
  GLYPH_HEIGHT: undefined,
  LINE_PITCH: undefined,
  NUM_CHARS: undefined,
  CODE: undefined,
  NUMBER: undefined,
  DIGIT: undefined,
  _fg: undefined,
  _sh: undefined,
  _quads: undefined,
  _tried: undefined,
  _logged: undefined,
  _cursor: undefined,
  unicodeCell: undefined,
  sheetCols: (..._a: any[]): any => { return notPorted("Braille.sheetCols"); },
  glyphCell: (..._a: any[]): any => { return notPorted("Braille.glyphCell"); },
  hasSheet: (..._a: any[]): any => { return notPorted("Braille.hasSheet"); },
  invalidate: (..._a: any[]): any => { return notPorted("Braille.invalidate"); },
  encode: (..._a: any[]): any => { return notPorted("Braille.encode"); },
  width: (..._a: any[]): any => { return notPorted("Braille.width"); },
  countGlyphs: (..._a: any[]): any => { return notPorted("Braille.countGlyphs"); },
  setCursor: (..._a: any[]): any => { return notPorted("Braille.setCursor"); },
  clearCursor: (..._a: any[]): any => { return notPorted("Braille.clearCursor"); },
  cursor: (..._a: any[]): any => { return notPorted("Braille.cursor"); },
  show: (..._a: any[]): any => { return notPorted("Braille.show"); },
  isOpen: (..._a: any[]): any => { return notPorted("Braille.isOpen"); },
  hide: (..._a: any[]): any => { return notPorted("Braille.hide"); },
  drawText: (..._a: any[]): any => { return notPorted("Braille.drawText"); },
  drawCursor: (..._a: any[]): any => { return notPorted("Braille.drawCursor"); },
};
export default Braille;
