// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/cave_transition.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const CaveTransition: Record<string, any> = {
  _run: undefined,
  _assets: undefined,
  start: (..._a: any[]): any => { return notPorted("CaveTransition.start"); },
  isActive: (..._a: any[]): any => { return notPorted("CaveTransition.isActive"); },
  update: (..._a: any[]): any => { return notPorted("CaveTransition.update"); },
  colorAt: (..._a: any[]): any => { return notPorted("CaveTransition.colorAt"); },
  surroundColor: (..._a: any[]): any => { return notPorted("CaveTransition.surroundColor"); },
  draw: (..._a: any[]): any => { return notPorted("CaveTransition.draw"); },
  clear: (..._a: any[]): any => { return notPorted("CaveTransition.clear"); },
};
export default CaveTransition;
