// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/choice.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Choice: Record<string, any> = {
  active: undefined,
  kind: undefined,
  options: undefined,
  cursor: undefined,
  done: undefined,
  left: undefined,
  top: undefined,
  cols: undefined,
  ignoreBPress: undefined,
  isOpen: (..._a: any[]): any => { return notPorted("Choice.isOpen"); },
  reset: (..._a: any[]): any => { return notPorted("Choice.reset"); },
  yesNo: (..._a: any[]): any => { return notPorted("Choice.yesNo"); },
  multi: (..._a: any[]): any => { return notPorted("Choice.multi"); },
  move: (..._a: any[]): any => { return notPorted("Choice.move"); },
  confirm: (..._a: any[]): any => { return notPorted("Choice.confirm"); },
  cancel: (..._a: any[]): any => { return notPorted("Choice.cancel"); },
  autoPick: (..._a: any[]): any => { return notPorted("Choice.autoPick"); },
  draw: (..._a: any[]): any => { return notPorted("Choice.draw"); },
};
export default Choice;
