// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/easy_chat.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const EasyChat: Record<string, any> = {
  openFlag: undefined,
  _state: undefined,
  FOOTER_BTNS: undefined,
  rseTemplate: undefined,
  footerLabels: (..._a: any[]): any => { return notPorted("EasyChat.footerLabels"); },
  populateGroups: (..._a: any[]): any => { return notPorted("EasyChat.populateGroups"); },
  open: (..._a: any[]): any => { return notPorted("EasyChat.open"); },
  isOpen: (..._a: any[]): any => { return notPorted("EasyChat.isOpen"); },
  close: (..._a: any[]): any => { return notPorted("EasyChat.close"); },
  update: (..._a: any[]): any => { return notPorted("EasyChat.update"); },
  handleInput: (..._a: any[]): any => { return notPorted("EasyChat.handleInput"); },
  draw: (..._a: any[]): any => { return notPorted("EasyChat.draw"); },
};
export default EasyChat;
