// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/evolution_scene.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const EvolutionScene: Record<string, any> = {
  open: undefined,
  _mon: undefined,
  _preSpecies: undefined,
  _postSpecies: undefined,
  _canStop: undefined,
  _session: undefined,
  _bag: undefined,
  _onDone: undefined,
  _state: undefined,
  _timer: undefined,
  _frame: undefined,
  _speed: undefined,
  _direction: undefined,
  _preScale: undefined,
  _postScale: undefined,
  _particles: undefined,
  _flashAlpha: undefined,
  _bgAngle: undefined,
  _bgBrightness: undefined,
  _savedSong: undefined,
  _isBattle: undefined,
  isOpen: (..._a: any[]): any => { return notPorted("EvolutionScene.isOpen"); },
  start: (..._a: any[]): any => { return notPorted("EvolutionScene.start"); },
  handleInput: (..._a: any[]): any => { return notPorted("EvolutionScene.handleInput"); },
  update: (..._a: any[]): any => { return notPorted("EvolutionScene.update"); },
  draw: (..._a: any[]): any => { return notPorted("EvolutionScene.draw"); },
};
export default EvolutionScene;
