// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/hall_of_fame.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const HallOfFame: Record<string, any> = {
  open: undefined,
  _session: undefined,
  _onDone: undefined,
  _mons: undefined,
  _currentIndex: undefined,
  _phase: undefined,
  _timer: undefined,
  _commitClearAndSave: undefined,
  start: (..._a: any[]): any => { return notPorted("HallOfFame.start"); },
  setWarpsToRollCredits: (..._a: any[]): any => { return notPorted("HallOfFame.setWarpsToRollCredits"); },
  close: (..._a: any[]): any => { return notPorted("HallOfFame.close"); },
  reset: (..._a: any[]): any => { return notPorted("HallOfFame.reset"); },
  isOpen: (..._a: any[]): any => { return notPorted("HallOfFame.isOpen"); },
  phase: (..._a: any[]): any => { return notPorted("HallOfFame.phase"); },
  getCurrentMon: (..._a: any[]): any => { return notPorted("HallOfFame.getCurrentMon"); },
  update: (..._a: any[]): any => { return notPorted("HallOfFame.update"); },
  handleInput: (..._a: any[]): any => { return notPorted("HallOfFame.handleInput"); },
  draw: (..._a: any[]): any => { return notPorted("HallOfFame.draw"); },
};
export default HallOfFame;
