// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/hall_of_fame_gfx.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const HofGfx: Record<string, any> = {
  drawStripes: (..._a: any[]): any => { return notPorted("HofGfx.drawStripes"); },
  drawBands: (..._a: any[]): any => { return notPorted("HofGfx.drawBands"); },
  confetti: (..._a: any[]): any => { return notPorted("HofGfx.confetti"); },
  reset: (..._a: any[]): any => { return notPorted("HofGfx.reset"); },
};
export default HofGfx;
