// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/hall_of_fame_pc.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const HofPc: Record<string, any> = {
  open: undefined,
  _teams: undefined,
  _team: undefined,
  _number: undefined,
  _mon: undefined,
  _corrupted: undefined,
  show: (..._a: any[]): any => { return notPorted("HofPc.show"); },
  isOpen: (..._a: any[]): any => { return notPorted("HofPc.isOpen"); },
  close: (..._a: any[]): any => { return notPorted("HofPc.close"); },
  reset: (..._a: any[]): any => { return notPorted("HofPc.reset"); },
  handleInput: (..._a: any[]): any => { return notPorted("HofPc.handleInput"); },
  draw: (..._a: any[]): any => { return notPorted("HofPc.draw"); },
};
export default HofPc;
