// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/help_system.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Help: Record<string, any> = {
  installPack: (..._a: any[]): any => { return notPorted("Help.installPack"); },
  install: (..._a: any[]): any => { return notPorted("Help.install"); },
  reset: (..._a: any[]): any => { return notPorted("Help.reset"); },
  isOpen: (..._a: any[]): any => { return notPorted("Help.isOpen"); },
  setContext: (..._a: any[]): any => { return notPorted("Help.setContext"); },
  context: (..._a: any[]): any => { return notPorted("Help.context"); },
  close: (..._a: any[]): any => { return notPorted("Help.close"); },
  show: (..._a: any[]): any => { return notPorted("Help.show"); },
  handleInput: (..._a: any[]): any => { return notPorted("Help.handleInput"); },
  update: (..._a: any[]): any => { return notPorted("Help.update"); },
  draw: (..._a: any[]): any => { return notPorted("Help.draw"); },
};
export default Help;
