// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/help_window.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const HelpWindow: Record<string, any> = {
  OUTER: undefined,
  CONTENT: undefined,
  TEXT_OFFSET: undefined,
  show: (..._a: any[]): any => { return notPorted("HelpWindow.show"); },
  close: (..._a: any[]): any => { return notPorted("HelpWindow.close"); },
  isOpen: (..._a: any[]): any => { return notPorted("HelpWindow.isOpen"); },
  getText: (..._a: any[]): any => { return notPorted("HelpWindow.getText"); },
  draw: (..._a: any[]): any => { return notPorted("HelpWindow.draw"); },
  reset: (..._a: any[]): any => { return notPorted("HelpWindow.reset"); },
};
export default HelpWindow;
