// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/hud.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Hud: Record<string, any> = {
  startButtonAllowed: undefined,
  isMenuOpen: (..._a: any[]): any => { return notPorted("Hud.isMenuOpen"); },
  busy: (..._a: any[]): any => { return notPorted("Hud.busy"); },
  armWaitButton: (..._a: any[]): any => { return notPorted("Hud.armWaitButton"); },
  clearWaitButton: (..._a: any[]): any => { return notPorted("Hud.clearWaitButton"); },
  clearFieldInput: (..._a: any[]): any => { return notPorted("Hud.clearFieldInput"); },
  sampleFieldInput: (..._a: any[]): any => { return notPorted("Hud.sampleFieldInput"); },
  update: (..._a: any[]): any => { return notPorted("Hud.update"); },
  openStartMenu: (..._a: any[]): any => { return notPorted("Hud.openStartMenu"); },
  openMessage: (..._a: any[]): any => { return notPorted("Hud.openMessage"); },
  openMessageStay: (..._a: any[]): any => { return notPorted("Hud.openMessageStay"); },
  openPc: (..._a: any[]): any => { return notPorted("Hud.openPc"); },
  ensure: (..._a: any[]): any => { return notPorted("Hud.ensure"); },
  new: (..._a: any[]): any => { return notPorted("Hud.new"); },
};
export default Hud;
