// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/intro_movie.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class IntroMovie {
  [key: string]: any;
  static [key: string]: any;
  static GBA_HZ: any = undefined;
  static new(..._a: any[]): any { return notPorted("IntroMovie.new"); }
  static Task_CallIntroCallback(..._a: any[]): any { return notPorted("IntroMovie.Task_CallIntroCallback"); }
  static IntroCB_Init(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_Init"); }
  static IntroCB_GF_OpenWindow(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_GF_OpenWindow"); }
  static IntroCB_GF_Star(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_GF_Star"); }
  static IntroCB_GF_RevealName(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_GF_RevealName"); }
  static IntroCB_GF_RevealLogo(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_GF_RevealLogo"); }
  static IntroCB_Scene1(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_Scene1"); }
  static IntroCB_Scene2(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_Scene2"); }
  static IntroCB_Scene3_Entrance(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_Scene3_Entrance"); }
  static IntroCB_Scene3_Fight(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_Scene3_Fight"); }
  static IntroCB_ExitToTitleScreen(..._a: any[]): any { return notPorted("IntroMovie.IntroCB_ExitToTitleScreen"); }
  destroy(..._a: any[]): any { return notPorted("IntroMovie:destroy"); }
  createTask(..._a: any[]): any { return notPorted("IntroMovie:createTask"); }
  findTask(..._a: any[]): any { return notPorted("IntroMovie:findTask"); }
  destroyTask(..._a: any[]): any { return notPorted("IntroMovie:destroyTask"); }
  runTasks(..._a: any[]): any { return notPorted("IntroMovie:runTasks"); }
  startBlendTask(..._a: any[]): any { return notPorted("IntroMovie:startBlendTask"); }
  isBlendTaskActive(..._a: any[]): any { return notPorted("IntroMovie:isBlendTaskActive"); }
  copyrightFrame(..._a: any[]): any { return notPorted("IntroMovie:copyrightFrame"); }
  setupFrame(..._a: any[]): any { return notPorted("IntroMovie:setupFrame"); }
  setCB(..._a: any[]): any { return notPorted("IntroMovie:setCB"); }
  createStarSparkle(..._a: any[]): any { return notPorted("IntroMovie:createStarSparkle"); }
  loadGfxCreateStar(..._a: any[]): any { return notPorted("IntroMovie:loadGfxCreateStar"); }
  createRecoilDust(..._a: any[]): any { return notPorted("IntroMovie:createRecoilDust"); }
  createGengarSwipeSprites(..._a: any[]): any { return notPorted("IntroMovie:createGengarSwipeSprites"); }
  createGengarSprites(..._a: any[]): any { return notPorted("IntroMovie:createGengarSprites"); }
  frame(..._a: any[]): any { return notPorted("IntroMovie:frame"); }
  update(..._a: any[]): any { return notPorted("IntroMovie:update"); }
  applyFx(..._a: any[]): any { return notPorted("IntroMovie:applyFx"); }
  bgClip(..._a: any[]): any { return notPorted("IntroMovie:bgClip"); }
  draw(..._a: any[]): any { return notPorted("IntroMovie:draw"); }
}
export default IntroMovie;
