// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/message.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Message: Record<string, any> = {
  open: undefined,
  _pages: undefined,
  _page: undefined,
  _done: undefined,
  _stay: undefined,
  _choice: undefined,
  _frame: undefined,
  _revealed: undefined,
  _total: undefined,
  _delay: undefined,
  _waiting: undefined,
  _speedIdx: undefined,
  _speedUp: undefined,
  setFrame: (..._a: any[]): any => { return notPorted("Message.setFrame"); },
  frameKind: (..._a: any[]): any => { return notPorted("Message.frameKind"); },
  show: (..._a: any[]): any => { return notPorted("Message.show"); },
  showStay: (..._a: any[]): any => { return notPorted("Message.showStay"); },
  currentPage: (..._a: any[]): any => { return notPorted("Message.currentPage"); },
  isOpen: (..._a: any[]): any => { return notPorted("Message.isOpen"); },
  isWaiting: (..._a: any[]): any => { return notPorted("Message.isWaiting"); },
  isTyping: (..._a: any[]): any => { return notPorted("Message.isTyping"); },
  skipReveal: (..._a: any[]): any => { return notPorted("Message.skipReveal"); },
  advance: (..._a: any[]): any => { return notPorted("Message.advance"); },
  isHeld: (..._a: any[]): any => { return notPorted("Message.isHeld"); },
  close: (..._a: any[]): any => { return notPorted("Message.close"); },
  closeStay: (..._a: any[]): any => { return notPorted("Message.closeStay"); },
  reset: (..._a: any[]): any => { return notPorted("Message.reset"); },
  tick: (..._a: any[]): any => { return notPorted("Message.tick"); },
  setSpeedUp: (..._a: any[]): any => { return notPorted("Message.setSpeedUp"); },
  draw: (..._a: any[]): any => { return notPorted("Message.draw"); },
  drawText: (..._a: any[]): any => { return notPorted("Message.drawText"); },
};
export default Message;
