// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/mon_pic.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const MonPic: Record<string, any> = {
  active: undefined,
  species: undefined,
  left: undefined,
  top: undefined,
  _img: undefined,
  _w: undefined,
  _h: undefined,
  _animTransform: undefined,
  show: (..._a: any[]): any => { return notPorted("MonPic.show"); },
  hide: (..._a: any[]): any => { return notPorted("MonPic.hide"); },
  isActive: (..._a: any[]): any => { return notPorted("MonPic.isActive"); },
  draw: (..._a: any[]): any => { return notPorted("MonPic.draw"); },
};
export default MonPic;
