// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/money_box.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const MoneyBox: Record<string, any> = {
  visible: undefined,
  x: undefined,
  y: undefined,
  _amount: undefined,
  show: (..._a: any[]): any => { return notPorted("MoneyBox.show"); },
  hide: (..._a: any[]): any => { return notPorted("MoneyBox.hide"); },
  update: (..._a: any[]): any => { return notPorted("MoneyBox.update"); },
  isVisible: (..._a: any[]): any => { return notPorted("MoneyBox.isVisible"); },
  draw: (..._a: any[]): any => { return notPorted("MoneyBox.draw"); },
};
export default MoneyBox;
