// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/ui/game3/mystery_gift.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Ui: Record<string, any> = {
  SUCCESS_FRAMES: undefined,
  STATE: undefined,
  _images: undefined,
  _manifest: undefined,
  manifest: (..._a: any[]): any => { return notPorted("Ui.manifest"); },
  reloadAssets: (..._a: any[]): any => { return notPorted("Ui.reloadAssets"); },
  cardBackground: (..._a: any[]): any => { return notPorted("Ui.cardBackground"); },
  textColors: (..._a: any[]): any => { return notPorted("Ui.textColors"); },
  stamps: (..._a: any[]): any => { return notPorted("Ui.stamps"); },
  stampShadow: (..._a: any[]): any => { return notPorted("Ui.stampShadow"); },
  newsBackground: (..._a: any[]): any => { return notPorted("Ui.newsBackground"); },
  mainRows: (..._a: any[]): any => { return notPorted("Ui.mainRows"); },
  threeOptionTemplate: (..._a: any[]): any => { return notPorted("Ui.threeOptionTemplate"); },
  new: (..._a: any[]): any => { return notPorted("Ui.new"); },
  card: (..._a: any[]): any => { return notPorted("Ui.card"); },
  cardMetadata: (..._a: any[]): any => { return notPorted("Ui.cardMetadata"); },
  news: (..._a: any[]): any => { return notPorted("Ui.news"); },
  offerRows: (..._a: any[]): any => { return notPorted("Ui.offerRows"); },
  listPrompt: (..._a: any[]): any => { return notPorted("Ui.listPrompt"); },
  isHeldCard: (..._a: any[]): any => { return notPorted("Ui.isHeldCard"); },
  close: (..._a: any[]): any => { return notPorted("Ui.close"); },
  update: (..._a: any[]): any => { return notPorted("Ui.update"); },
  drawCard: (..._a: any[]): any => { return notPorted("Ui.drawCard"); },
  drawNews: (..._a: any[]): any => { return notPorted("Ui.drawNews"); },
  draw: (..._a: any[]): any => { return notPorted("Ui.draw"); },
};
export default Ui;
