// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/new_game_scene.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class Scene {
  [key: string]: any;
  static [key: string]: any;
  static GBA_HZ: any = undefined;
  static nameChoices: any = undefined;
  static new(..._a: any[]): any { return notPorted("Scene.new"); }
  static Task_NewGameScene(..._a: any[]): any { return notPorted("Scene.Task_NewGameScene"); }
  static Task_ControlsGuide_LoadPage(..._a: any[]): any { return notPorted("Scene.Task_ControlsGuide_LoadPage"); }
  static Task_ControlsGuide_HandleInput(..._a: any[]): any { return notPorted("Scene.Task_ControlsGuide_HandleInput"); }
  static Task_ControlsGuide_ChangePage(..._a: any[]): any { return notPorted("Scene.Task_ControlsGuide_ChangePage"); }
  static Task_ControlsGuide_Clear(..._a: any[]): any { return notPorted("Scene.Task_ControlsGuide_Clear"); }
  static Task_PikachuIntro_LoadPage1(..._a: any[]): any { return notPorted("Scene.Task_PikachuIntro_LoadPage1"); }
  static Task_PikachuIntro_HandleInput(..._a: any[]): any { return notPorted("Scene.Task_PikachuIntro_HandleInput"); }
  static Task_PikachuIntro_Clear(..._a: any[]): any { return notPorted("Scene.Task_PikachuIntro_Clear"); }
  static Task_OakSpeech_Init(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_Init"); }
  static Task_OakSpeech_WelcomeToTheWorld(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_WelcomeToTheWorld"); }
  static Task_OakSpeech_ThisWorld(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ThisWorld"); }
  static Task_OakSpeech_ReleaseNidoranFFromPokeBall(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ReleaseNidoranFFromPokeBall"); }
  static Task_OakSpeech_IsInhabitedFarAndWide(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_IsInhabitedFarAndWide"); }
  static Task_OakSpeech_IStudyPokemon(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_IStudyPokemon"); }
  static Task_OakSpeech_ReturnNidoranFToPokeBall(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ReturnNidoranFToPokeBall"); }
  static Task_OakSpeech_TellMeALittleAboutYourself(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_TellMeALittleAboutYourself"); }
  static Task_OakSpeech_FadeOutOak(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadeOutOak"); }
  static Task_OakSpeech_AskPlayerGender(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_AskPlayerGender"); }
  static Task_OakSpeech_ShowGenderOptions(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ShowGenderOptions"); }
  static Task_OakSpeech_HandleGenderInput(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_HandleGenderInput"); }
  static Task_OakSpeech_ClearGenderWindows(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ClearGenderWindows"); }
  static Task_OakSpeech_LoadPlayerPic(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_LoadPlayerPic"); }
  static Task_OakSpeech_YourNameWhatIsIt(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_YourNameWhatIsIt"); }
  static Task_OakSpeech_FadeOutForPlayerNamingScreen(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadeOutForPlayerNamingScreen"); }
  static Task_OakSpeech_MoveRivalDisplayNameOptions(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_MoveRivalDisplayNameOptions"); }
  static Task_OakSpeech_RepeatNameQuestion(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_RepeatNameQuestion"); }
  static Task_OakSpeech_HandleRivalNameInput(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_HandleRivalNameInput"); }
  static Task_OakSpeech_DoNamingScreen(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_DoNamingScreen"); }
  static Task_OakSpeech_ConfirmName(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ConfirmName"); }
  static Task_OakSpeech_HandleConfirmNameInput(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_HandleConfirmNameInput"); }
  static Task_OakSpeech_FadeOutPlayerPic(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadeOutPlayerPic"); }
  static Task_OakSpeech_FadeOutRivalPic(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadeOutRivalPic"); }
  static Task_OakSpeech_FadeInRivalPic(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadeInRivalPic"); }
  static Task_OakSpeech_AskRivalsName(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_AskRivalsName"); }
  static Task_OakSpeech_ReshowPlayersPic(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ReshowPlayersPic"); }
  static Task_OakSpeech_LetsGo(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_LetsGo"); }
  static Task_OakSpeech_FadeOutBGM(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadeOutBGM"); }
  static Task_OakSpeech_SetUpExitAnimation(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_SetUpExitAnimation"); }
  static Task_OakSpeech_ShrinkPlayerPic(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_ShrinkPlayerPic"); }
  static Task_OakSpeech_FadePlayerPicToBlack(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FadePlayerPicToBlack"); }
  static Task_OakSpeech_WaitForFade(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_WaitForFade"); }
  static Task_OakSpeech_FreeResources(..._a: any[]): any { return notPorted("Scene.Task_OakSpeech_FreeResources"); }
  destroy(..._a: any[]): any { return notPorted("Scene:destroy"); }
  createTask(..._a: any[]): any { return notPorted("Scene:createTask"); }
  findTask(..._a: any[]): any { return notPorted("Scene:findTask"); }
  runTasks(..._a: any[]): any { return notPorted("Scene:runTasks"); }
  fadeActive(..._a: any[]): any { return notPorted("Scene:fadeActive"); }
  printerActive(..._a: any[]): any { return notPorted("Scene:printerActive"); }
  _answered(..._a: any[]): any { return notPorted("Scene:_answered"); }
  oakPrint(..._a: any[]): any { return notPorted("Scene:oakPrint"); }
  clearDialog(..._a: any[]): any { return notPorted("Scene:clearDialog"); }
  createTextCursor(..._a: any[]): any { return notPorted("Scene:createTextCursor"); }
  createPikachuOrPlatform(..._a: any[]): any { return notPorted("Scene:createPikachuOrPlatform"); }
  destroyPikachuOrPlatform(..._a: any[]): any { return notPorted("Scene:destroyPikachuOrPlatform"); }
  createFadeInTask(..._a: any[]): any { return notPorted("Scene:createFadeInTask"); }
  createFadeOutTask(..._a: any[]): any { return notPorted("Scene:createFadeOutTask"); }
  loadTrainerPic(..._a: any[]): any { return notPorted("Scene:loadTrainerPic"); }
  loadPlayerPic(..._a: any[]): any { return notPorted("Scene:loadPlayerPic"); }
  clearTrainerPic(..._a: any[]): any { return notPorted("Scene:clearTrainerPic"); }
  ballFadeColor(..._a: any[]): any { return notPorted("Scene:ballFadeColor"); }
  launchBallFadeMon(..._a: any[]): any { return notPorted("Scene:launchBallFadeMon"); }
  ballOpen(..._a: any[]): any { return notPorted("Scene:ballOpen"); }
  createReleaseBall(..._a: any[]): any { return notPorted("Scene:createReleaseBall"); }
  createTradeBall(..._a: any[]): any { return notPorted("Scene:createTradeBall"); }
  setTopBar(..._a: any[]): any { return notPorted("Scene:setTopBar"); }
  controlsLoadPage1(..._a: any[]): any { return notPorted("Scene:controlsLoadPage1"); }
  menuInput(..._a: any[]): any { return notPorted("Scene:menuInput"); }
  printNameChoices(..._a: any[]): any { return notPorted("Scene:printNameChoices"); }
  getDefaultName(..._a: any[]): any { return notPorted("Scene:getDefaultName"); }
  enterNaming(..._a: any[]): any { return notPorted("Scene:enterNaming"); }
  namingFrame(..._a: any[]): any { return notPorted("Scene:namingFrame"); }
  returnFromNamingFrame(..._a: any[]): any { return notPorted("Scene:returnFromNamingFrame"); }
  frame(..._a: any[]): any { return notPorted("Scene:frame"); }
  update(..._a: any[]): any { return notPorted("Scene:update"); }
  drawTopBar(..._a: any[]): any { return notPorted("Scene:drawTopBar"); }
  drawBg0Text(..._a: any[]): any { return notPorted("Scene:drawBg0Text"); }
  layerCanvas(..._a: any[]): any { return notPorted("Scene:layerCanvas"); }
  renderToCanvas(..._a: any[]): any { return notPorted("Scene:renderToCanvas"); }
  drawSprites(..._a: any[]): any { return notPorted("Scene:drawSprites"); }
  prepareSprites(..._a: any[]): any { return notPorted("Scene:prepareSprites"); }
  drawPic(..._a: any[]): any { return notPorted("Scene:drawPic"); }
  draw(..._a: any[]): any { return notPorted("Scene:draw"); }
}
export default Scene;
