// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/option_menu.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const OptionMenu: Record<string, any> = {
  open: undefined,
  cursor: undefined,
  show: (..._a: any[]): any => { return notPorted("OptionMenu.show"); },
  close: (..._a: any[]): any => { return notPorted("OptionMenu.close"); },
  isOpen: (..._a: any[]): any => { return notPorted("OptionMenu.isOpen"); },
  move: (..._a: any[]): any => { return notPorted("OptionMenu.move"); },
  adjust: (..._a: any[]): any => { return notPorted("OptionMenu.adjust"); },
  confirm: (..._a: any[]): any => { return notPorted("OptionMenu.confirm"); },
  back: (..._a: any[]): any => { return notPorted("OptionMenu.back"); },
  handleInput: (..._a: any[]): any => { return notPorted("OptionMenu.handleInput"); },
  update: (..._a: any[]): any => { return notPorted("OptionMenu.update"); },
  draw: (..._a: any[]): any => { return notPorted("OptionMenu.draw"); },
};
export default OptionMenu;
