// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/pokedex.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Pokedex: Record<string, any> = {
  open: undefined,
  screen: undefined,
  subScreenPrev: undefined,
  modeCursor: undefined,
  modeScroll: undefined,
  MODES: undefined,
  currentCategory: undefined,
  categoryPage: undefined,
  categorySlot: undefined,
  spotlightTimer: undefined,
  currentOrder: undefined,
  listCursor: undefined,
  listScroll: undefined,
  selectedSpecies: undefined,
  dataPage: undefined,
  cursor: undefined,
  mode: undefined,
  page: undefined,
  _dex: undefined,
  _session: undefined,
  _onClose: undefined,
  _regSpecies: undefined,
  maxSpecies: (..._a: any[]): any => { return notPorted("Pokedex.maxSpecies"); },
  silhouetteScale: (..._a: any[]): any => { return notPorted("Pokedex.silhouetteScale"); },
  playerGender: (..._a: any[]): any => { return notPorted("Pokedex.playerGender"); },
  show: (..._a: any[]): any => { return notPorted("Pokedex.show"); },
  categoryForSpecies: (..._a: any[]): any => { return notPorted("Pokedex.categoryForSpecies"); },
  showRegistration: (..._a: any[]): any => { return notPorted("Pokedex.showRegistration"); },
  resetScreenState: (..._a: any[]): any => { return notPorted("Pokedex.resetScreenState"); },
  update: (..._a: any[]): any => { return notPorted("Pokedex.update"); },
  close: (..._a: any[]): any => { return notPorted("Pokedex.close"); },
  isOpen: (..._a: any[]): any => { return notPorted("Pokedex.isOpen"); },
  handleInput: (..._a: any[]): any => { return notPorted("Pokedex.handleInput"); },
  controlInfoForDataPage: (..._a: any[]): any => { return notPorted("Pokedex.controlInfoForDataPage"); },
  draw: (..._a: any[]): any => { return notPorted("Pokedex.draw"); },
};
export default Pokedex;
