// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/quest_log.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const UI: Record<string, any> = {
  install: (..._a: any[]): any => { return notPorted("UI.install"); },
  text: (..._a: any[]): any => { return notPorted("UI.text"); },
  begin: (..._a: any[]): any => { return notPorted("UI.begin"); },
  draw: (..._a: any[]): any => { return notPorted("UI.draw"); },
};
export default UI;
