// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/region_map_gpu.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Gpu: Record<string, any> = {
  CLR: undefined,
  BD: undefined,
  BG_ALL: undefined,
  ALL: undefined,
  images: undefined,
  new: (..._a: any[]): any => { return notPorted("Gpu.new"); },
  reset: (..._a: any[]): any => { return notPorted("Gpu.reset"); },
  setBldCnt: (..._a: any[]): any => { return notPorted("Gpu.setBldCnt"); },
  setBldY: (..._a: any[]): any => { return notPorted("Gpu.setBldY"); },
  setBldAlpha: (..._a: any[]): any => { return notPorted("Gpu.setBldAlpha"); },
  setWinIn: (..._a: any[]): any => { return notPorted("Gpu.setWinIn"); },
  setWinOut: (..._a: any[]): any => { return notPorted("Gpu.setWinOut"); },
  setDispCnt: (..._a: any[]): any => { return notPorted("Gpu.setDispCnt"); },
  setWindowDims: (..._a: any[]): any => { return notPorted("Gpu.setWindowDims"); },
  save: (..._a: any[]): any => { return notPorted("Gpu.save"); },
  restore: (..._a: any[]): any => { return notPorted("Gpu.restore"); },
  regions: (..._a: any[]): any => { return notPorted("Gpu.regions"); },
  compose: (..._a: any[]): any => { return notPorted("Gpu.compose"); },
  image: (..._a: any[]): any => { return notPorted("Gpu.image"); },
  frameQuad: (..._a: any[]): any => { return notPorted("Gpu.frameQuad"); },
  manifest: (..._a: any[]): any => { return notPorted("Gpu.manifest"); },
  rgb: (..._a: any[]): any => { return notPorted("Gpu.rgb"); },
  topBarColor: (..._a: any[]): any => { return notPorted("Gpu.topBarColor"); },
};
export default Gpu;
