// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/region_map_position.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Position: Record<string, any> = {
  playerCell: (..._a: any[]): any => { return notPorted("Position.playerCell"); },
  regionFor: (..._a: any[]): any => { return notPorted("Position.regionFor"); },
};
export default Position;
