// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/save_menu.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const SaveMenu: Record<string, any> = {
  open: undefined,
  cursor: undefined,
  _phase: undefined,
  _error: undefined,
  _session: undefined,
  _game: undefined,
  _onClose: undefined,
  flagStore: (..._a: any[]): any => { return notPorted("SaveMenu.flagStore"); },
  countBadges: (..._a: any[]): any => { return notPorted("SaveMenu.countBadges"); },
  countDex: (..._a: any[]): any => { return notPorted("SaveMenu.countDex"); },
  hasDex: (..._a: any[]): any => { return notPorted("SaveMenu.hasDex"); },
  layout: (..._a: any[]): any => { return notPorted("SaveMenu.layout"); },
  show: (..._a: any[]): any => { return notPorted("SaveMenu.show"); },
  close: (..._a: any[]): any => { return notPorted("SaveMenu.close"); },
  isOpen: (..._a: any[]): any => { return notPorted("SaveMenu.isOpen"); },
  move: (..._a: any[]): any => { return notPorted("SaveMenu.move"); },
  update: (..._a: any[]): any => { return notPorted("SaveMenu.update"); },
  confirm: (..._a: any[]): any => { return notPorted("SaveMenu.confirm"); },
  cancel: (..._a: any[]): any => { return notPorted("SaveMenu.cancel"); },
  locationName: (..._a: any[]): any => { return notPorted("SaveMenu.locationName"); },
  valueX: (..._a: any[]): any => { return notPorted("SaveMenu.valueX"); },
  drawRse: (..._a: any[]): any => { return notPorted("SaveMenu.drawRse"); },
  draw: (..._a: any[]): any => { return notPorted("SaveMenu.draw"); },
};
export default SaveMenu;
