// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/seagallop.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Seagallop: Record<string, any> = {
  _assets: undefined,
  _active: undefined,
  _run: undefined,
  directionOfTravel: (..._a: any[]): any => { return notPorted("Seagallop.directionOfTravel"); },
  start: (..._a: any[]): any => { return notPorted("Seagallop.start"); },
  isActive: (..._a: any[]): any => { return notPorted("Seagallop.isActive"); },
  stop: (..._a: any[]): any => { return notPorted("Seagallop.stop"); },
  update: (..._a: any[]): any => { return notPorted("Seagallop.update"); },
  draw: (..._a: any[]): any => { return notPorted("Seagallop.draw"); },
};
export default Seagallop;
