// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/sell_flow.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class SellFlow {
  [key: string]: any;
  static [key: string]: any;
  static start(..._a: any[]): any { return notPorted("SellFlow.start"); }
  rseBerry(..._a: any[]): any { return notPorted("SellFlow:rseBerry"); }
  total(..._a: any[]): any { return notPorted("SellFlow:total"); }
  ask(..._a: any[]): any { return notPorted("SellFlow:ask"); }
  commit(..._a: any[]): any { return notPorted("SellFlow:commit"); }
  finish(..._a: any[]): any { return notPorted("SellFlow:finish"); }
  active(..._a: any[]): any { return notPorted("SellFlow:active"); }
  handleInput(..._a: any[]): any { return notPorted("SellFlow:handleInput"); }
  drawRse(..._a: any[]): any { return notPorted("SellFlow:drawRse"); }
  draw(..._a: any[]): any { return notPorted("SellFlow:draw"); }
}
export default SellFlow;
