// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/shop_menu.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const ShopMenu: Record<string, any> = {
  open: undefined,
  mode: undefined,
  cursor: undefined,
  scroll: undefined,
  qty: undefined,
  yesNoCursor: undefined,
  ROOT: undefined,
  show: (..._a: any[]): any => { return notPorted("ShopMenu.show"); },
  close: (..._a: any[]): any => { return notPorted("ShopMenu.close"); },
  reset: (..._a: any[]): any => { return notPorted("ShopMenu.reset"); },
  isOpen: (..._a: any[]): any => { return notPorted("ShopMenu.isOpen"); },
  isShopCamera: (..._a: any[]): any => { return notPorted("ShopMenu.isShopCamera"); },
  shopCameraOffset: (..._a: any[]): any => { return notPorted("ShopMenu.shopCameraOffset"); },
  handleInput: (..._a: any[]): any => { return notPorted("ShopMenu.handleInput"); },
  draw: (..._a: any[]): any => { return notPorted("ShopMenu.draw"); },
};
export default ShopMenu;
