// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/start_menu_frlg.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Data: Record<string, any> = {
  layout: undefined,
  textKey: undefined,
  ACTION: undefined,
  exitConfirms: undefined,
  entry: (..._a: any[]): any => { return notPorted("Data.entry"); },
  build: (..._a: any[]): any => { return notPorted("Data.build"); },
  extraWindow: (..._a: any[]): any => { return notPorted("Data.extraWindow"); },
};
export default Data;
