// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/summary_menu.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const SummaryMenu: Record<string, any> = {
  open: undefined,
  _party: undefined,
  _cursor: undefined,
  _page: undefined,
  _moveCursor: undefined,
  _swapSlot: undefined,
  _onClose: undefined,
  _playerState: undefined,
  _slide: undefined,
  _tick: undefined,
  _bounce: undefined,
  _blink: undefined,
  PAGE_INFO: undefined,
  PAGE_SKILLS: undefined,
  PAGE_MOVES: undefined,
  PAGE_MOVES_INFO: undefined,
  PAGE_EGG: undefined,
  FLIP_TIMING: undefined,
  controlsString: undefined,
  heldItemText: (..._a: any[]): any => { return notPorted("SummaryMenu.heldItemText"); },
  isOpen: (..._a: any[]): any => { return notPorted("SummaryMenu.isOpen"); },
  openMenu: (..._a: any[]): any => { return notPorted("SummaryMenu.openMenu"); },
  close: (..._a: any[]): any => { return notPorted("SummaryMenu.close"); },
  resetPicBounce: (..._a: any[]): any => { return notPorted("SummaryMenu.resetPicBounce"); },
  update: (..._a: any[]): any => { return notPorted("SummaryMenu.update"); },
  detailCursorStep: (..._a: any[]): any => { return notPorted("SummaryMenu.detailCursorStep"); },
  handleInput: (..._a: any[]): any => { return notPorted("SummaryMenu.handleInput"); },
  dexNumber: (..._a: any[]): any => { return notPorted("SummaryMenu.dexNumber"); },
  dexNoText: (..._a: any[]): any => { return notPorted("SummaryMenu.dexNoText"); },
  showsPokerusIcon: (..._a: any[]): any => { return notPorted("SummaryMenu.showsPokerusIcon"); },
  ballIdOf: (..._a: any[]): any => { return notPorted("SummaryMenu.ballIdOf"); },
  leftPaneSprites: (..._a: any[]): any => { return notPorted("SummaryMenu.leftPaneSprites"); },
  rightAlign: (..._a: any[]): any => { return notPorted("SummaryMenu.rightAlign"); },
  ppColorIndex: (..._a: any[]): any => { return notPorted("SummaryMenu.ppColorIndex"); },
  slideOffset: (..._a: any[]): any => { return notPorted("SummaryMenu.slideOffset"); },
  flipStep: (..._a: any[]): any => { return notPorted("SummaryMenu.flipStep"); },
  draw: (..._a: any[]): any => { return notPorted("SummaryMenu.draw"); },
};
export default SummaryMenu;
