// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/trainer_card.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const TrainerCard: Record<string, any> = {
  open: undefined,
  _session: undefined,
  _onClose: undefined,
  _card: undefined,
  side: undefined,
  cardData: undefined,
  isBadgeUnlocked: (..._a: any[]): any => { return notPorted("TrainerCard.isBadgeUnlocked"); },
  countBadges: (..._a: any[]): any => { return notPorted("TrainerCard.countBadges"); },
  flip: (..._a: any[]): any => { return notPorted("TrainerCard.flip"); },
  update: (..._a: any[]): any => { return notPorted("TrainerCard.update"); },
  show: (..._a: any[]): any => { return notPorted("TrainerCard.show"); },
  close: (..._a: any[]): any => { return notPorted("TrainerCard.close"); },
  isOpen: (..._a: any[]): any => { return notPorted("TrainerCard.isOpen"); },
  handleInput: (..._a: any[]): any => { return notPorted("TrainerCard.handleInput"); },
  frontTexts: (..._a: any[]): any => { return notPorted("TrainerCard.frontTexts"); },
  backTexts: (..._a: any[]): any => { return notPorted("TrainerCard.backTexts"); },
  frontTextsRse: (..._a: any[]): any => { return notPorted("TrainerCard.frontTextsRse"); },
  backTextsRse: (..._a: any[]): any => { return notPorted("TrainerCard.backTextsRse"); },
  draw: (..._a: any[]): any => { return notPorted("TrainerCard.draw"); },
};
export default TrainerCard;
