// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/whiteout_rush.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Rush: Record<string, any> = {
  ID: undefined,
  HOLD_FRAMES: undefined,
  _state: undefined,
  start: (..._a: any[]): any => { return notPorted("Rush.start"); },
  isActive: (..._a: any[]): any => { return notPorted("Rush.isActive"); },
  phase: (..._a: any[]): any => { return notPorted("Rush.phase"); },
  text: (..._a: any[]): any => { return notPorted("Rush.text"); },
  update: (..._a: any[]): any => { return notPorted("Rush.update"); },
  handleInput: (..._a: any[]): any => { return notPorted("Rush.handleInput"); },
  draw: (..._a: any[]): any => { return notPorted("Rush.draw"); },
};
export default Rush;
