// @gen3-stub
// Not ported yet: gen1recomp src/ui/game3/window.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Window: Record<string, any> = {
  ROW_STRIDE: undefined,
  TEXT_OY: undefined,
  CURSOR_WIDTH: undefined,
  OPTION_HEIGHT: undefined,
  template: (..._a: any[]): any => { return notPorted("Window.template"); },
  fill: (..._a: any[]): any => { return notPorted("Window.fill"); },
  stdFrame: (..._a: any[]): any => { return notPorted("Window.stdFrame"); },
  fixedStdFrame: (..._a: any[]): any => { return notPorted("Window.fixedStdFrame"); },
  userFrame: (..._a: any[]): any => { return notPorted("Window.userFrame"); },
  dialogueFrame: (..._a: any[]): any => { return notPorted("Window.dialogueFrame"); },
  signFrame: (..._a: any[]): any => { return notPorted("Window.signFrame"); },
  print: (..._a: any[]): any => { return notPorted("Window.print"); },
  printPx: (..._a: any[]): any => { return notPorted("Window.printPx"); },
  cursor: (..._a: any[]): any => { return notPorted("Window.cursor"); },
  cursorPx: (..._a: any[]): any => { return notPorted("Window.cursorPx"); },
  labelTx: (..._a: any[]): any => { return notPorted("Window.labelTx"); },
  menuRowY: (..._a: any[]): any => { return notPorted("Window.menuRowY"); },
  optionHeight: (..._a: any[]): any => { return notPorted("Window.optionHeight"); },
  menuRowPx: (..._a: any[]): any => { return notPorted("Window.menuRowPx"); },
  fitRows: (..._a: any[]): any => { return notPorted("Window.fitRows"); },
};
export default Window;
