// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/render/Letterbox.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export const Letterbox: Record<string, any> = {
  mode: undefined,
  MODES: undefined,
  normalize: (..._a: any[]): any => { return undefined; },
  label: (..._a: any[]): any => { return undefined; },
  cycle: (..._a: any[]): any => { return undefined; },
  color: (..._a: any[]): any => { return undefined; },
  setMode: (..._a: any[]): any => { return undefined; },
  applyOptions: (..._a: any[]): any => { return undefined; },
  fill: (..._a: any[]): any => { return undefined; },
};
export default Letterbox;
