// @gen3-stub
// Inert on the 3DS (desktop-only in gen1recomp src/render/Renderer.lua): every function returns undefined.
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

export class Renderer {
  [key: string]: any;
  static [key: string]: any;
  static WIDTH: any = undefined;
  static HEIGHT: any = undefined;
  static MAX_UI_WIDTH: any = undefined;
  static MAX_UI_HEIGHT: any = undefined;
  static UPRIGHT_MARGIN: any = undefined;
  static release: any = undefined;
  static mirrorsWorldOverride(..._a: any[]): any { return undefined; }
  static clipToView(..._a: any[]): any { return undefined; }
  releaseCanvases(..._a: any[]): any { return undefined; }
  init(..._a: any[]): any { return undefined; }
  setWorldOverride(..._a: any[]): any { return undefined; }
  fitScale(..._a: any[]): any { return undefined; }
  uiScale(..._a: any[]): any { return undefined; }
  uiSize(..._a: any[]): any { return undefined; }
  setUISize(..._a: any[]): any { return undefined; }
  beginBattleHUDPass(..._a: any[]): any { return undefined; }
  endBattleHUDPass(..._a: any[]): any { return undefined; }
  drawScaleX(..._a: any[]): any { return undefined; }
  drawScaleY(..._a: any[]): any { return undefined; }
  drawScale(..._a: any[]): any { return undefined; }
  worldViewSize(..._a: any[]): any { return undefined; }
  beginFrame(..._a: any[]): any { return undefined; }
  drawBattleWipe(..._a: any[]): any { return undefined; }
  beginWorldPass(..._a: any[]): any { return undefined; }
  endWorldPass(..._a: any[]): any { return undefined; }
  exchangeWorldCanvas(..._a: any[]): any { return undefined; }
  beginUprightPass(..._a: any[]): any { return undefined; }
  endUprightPass(..._a: any[]): any { return undefined; }
  tiltShader(..._a: any[]): any { return undefined; }
  tiltMesh(..._a: any[]): any { return undefined; }
  drawTiltedWorld(..._a: any[]): any { return undefined; }
  blitCanvas(..._a: any[]): any { return undefined; }
  setUIAnchor(..._a: any[]): any { return undefined; }
  setBattleUIAnchor(..._a: any[]): any { return undefined; }
  frameRects(..._a: any[]): any { return undefined; }
  playfieldRect(..._a: any[]): any { return undefined; }
  endFrame(..._a: any[]): any { return undefined; }
}
export default Renderer;
