// @gen3-stub
// Not ported yet: gen1recomp src/render/Tilt.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Tilt: Record<string, any> = {
  ANGLES_DEG: undefined,
  ANGLE_LABELS: undefined,
  level: undefined,
  angle: undefined,
  from: undefined,
  goal: undefined,
  t: undefined,
  TARGET_ANGLE: undefined,
  enabled: undefined,
  TWEEN_TIME: undefined,
  FOCAL: undefined,
  VIEW_MARGIN: undefined,
  setLevel: (..._a: any[]): any => { return notPorted("Tilt.setLevel"); },
  cycle: (..._a: any[]): any => { return notPorted("Tilt.cycle"); },
  toggle: (..._a: any[]): any => { return notPorted("Tilt.toggle"); },
  reset: (..._a: any[]): any => { return notPorted("Tilt.reset"); },
  applyOptions: (..._a: any[]): any => { return notPorted("Tilt.applyOptions"); },
  levelLabel: (..._a: any[]): any => { return notPorted("Tilt.levelLabel"); },
  update: (..._a: any[]): any => { return notPorted("Tilt.update"); },
  active: (..._a: any[]): any => { return notPorted("Tilt.active"); },
  gateOK: (..._a: any[]): any => { return notPorted("Tilt.gateOK"); },
  groundPoint: (..._a: any[]): any => { return notPorted("Tilt.groundPoint"); },
  onGround: (..._a: any[]): any => { return notPorted("Tilt.onGround"); },
  viewGrowth: (..._a: any[]): any => { return notPorted("Tilt.viewGrowth"); },
  meshCorners: (..._a: any[]): any => { return notPorted("Tilt.meshCorners"); },
};
export default Tilt;
