// @gen2-stub
// Not ported yet: gen1recomp src/pokemon/Party.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Party: Record<string, any> = {
  MAX: undefined,
  add: (..._a: any[]): any => notPorted("Party.add"),
  firstHealthy: (..._a: any[]): any => notPorted("Party.firstHealthy"),
};
export default Party;
