// @gen2-stub
// Not ported yet: gen1recomp src/pokemon/Sprites.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Sprites: Record<string, any> = {
  path: (..._a: any[]): any => notPorted("Sprites.path"),
  pic: (..._a: any[]): any => notPorted("Sprites.pic"),
  playerPath: (..._a: any[]): any => notPorted("Sprites.playerPath"),
  playerPic: (..._a: any[]): any => notPorted("Sprites.playerPic"),
  iconPath: (..._a: any[]): any => notPorted("Sprites.iconPath"),
};
export default Sprites;
