// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/collision_std.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const CollisionStd: Record<string, any> = {
  COLL_PC: undefined,
  COLL_COUNTER: undefined,
  COLL_BOOKSHELF: undefined,
  COLL_TOWN_MAP: undefined,
  SCRIPTS: undefined,
  scriptFor: (..._a: any[]): any => { return notPorted("CollisionStd.scriptFor"); },
  isCounter: (..._a: any[]): any => { return notPorted("CollisionStd.isCounter"); },
};
export default CollisionStd;
