// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/ctx.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Ctx: Record<string, any> = {
  SPECIAL_LO: undefined,
  SPECIAL_HI: undefined,
  TEMP_LO: undefined,
  TEMP_HI: undefined,
  GFX_VAR_LO: undefined,
  GFX_VAR_HI: undefined,
  VAR_FACING: undefined,
  VAR_RESULT: undefined,
  VAR_ITEM_ID: undefined,
  VAR_LAST_TALKED: undefined,
  VAR_TEXT_COLOR: undefined,
  VAR_PREV_TEXT_COLOR: undefined,
  TEXT_COLOR_DEFAULT: undefined,
  SPECIAL_LAYOUTS: undefined,
  STEP_CB: undefined,
  STEP_CALLBACKS: undefined,
  STEP_CALLBACKS_RSE: undefined,
  _stepCallback: undefined,
  specialLayout: (..._a: any[]): any => { return notPorted("Ctx.specialLayout"); },
  isSpecial: (..._a: any[]): any => { return notPorted("Ctx.isSpecial"); },
  isTemp: (..._a: any[]): any => { return notPorted("Ctx.isTemp"); },
  isGfxVar: (..._a: any[]): any => { return notPorted("Ctx.isGfxVar"); },
  stepCallbackNames: (..._a: any[]): any => { return notPorted("Ctx.stepCallbackNames"); },
  setStepCallback: (..._a: any[]): any => { return notPorted("Ctx.setStepCallback"); },
  stepCallback: (..._a: any[]): any => { return notPorted("Ctx.stepCallback"); },
  resetStepCallback: (..._a: any[]): any => { return notPorted("Ctx.resetStepCallback"); },
  new: (..._a: any[]): any => { return notPorted("Ctx.new"); },
  wipeSpecial: (..._a: any[]): any => { return notPorted("Ctx.wipeSpecial"); },
  selectObject: (..._a: any[]): any => { return notPorted("Ctx.selectObject"); },
  clearLocks: (..._a: any[]): any => { return notPorted("Ctx.clearLocks"); },
  clearMoves: (..._a: any[]): any => { return notPorted("Ctx.clearMoves"); },
  haltCleanup: (..._a: any[]): any => { return notPorted("Ctx.haltCleanup"); },
  clearTemps: (..._a: any[]): any => { return notPorted("Ctx.clearTemps"); },
  modCtx: (..._a: any[]): any => { return notPorted("Ctx.modCtx"); },
};
export default Ctx;
