// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/natives_tv.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const NativesTv: Record<string, any> = {
  setScreens: undefined,
  showMessage: undefined,
  BY_NAME: undefined,
  updateScreensOnMap: (..._a: any[]): any => { return notPorted("NativesTv.updateScreensOnMap"); },
  findAnyShowOnAir: (..._a: any[]): any => { return notPorted("NativesTv.findAnyShowOnAir"); },
  anyShowOnAir: (..._a: any[]): any => { return notPorted("NativesTv.anyShowOnAir"); },
  gabbyBattleNum: (..._a: any[]): any => { return notPorted("NativesTv.gabbyBattleNum"); },
  render: (..._a: any[]): any => { return notPorted("NativesTv.render"); },
  installTimeHooks: (..._a: any[]): any => { return notPorted("NativesTv.installTimeHooks"); },
  installEasyChatTypes: (..._a: any[]): any => { return notPorted("NativesTv.installEasyChatTypes"); },
};
export default NativesTv;
