// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/natives.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Natives: Record<string, any> = {
  ALLOW: undefined,
  _logged: undefined,
  yieldHost: undefined,
  B_OUTCOME: undefined,
  outcome_to_code: undefined,
  CORE: undefined,
  KNOWN_MODULES: undefined,
  MODULE_DIR: undefined,
  moduleNames: undefined,
  discoverModules: undefined,
  log_once: undefined,
  NATIVE_SYMBOLS: undefined,
  awaitState: (..._a: any[]): any => { return notPorted("Natives.awaitState"); },
  choosePartyMon: (..._a: any[]): any => { return notPorted("Natives.choosePartyMon"); },
  setVermilionTrashCans: (..._a: any[]): any => { return notPorted("Natives.setVermilionTrashCans"); },
  enterHallOfFameState: (..._a: any[]): any => { return notPorted("Natives.enterHallOfFameState"); },
  versionOf: (..._a: any[]): any => { return notPorted("Natives.versionOf"); },
  bind: (..._a: any[]): any => { return notPorted("Natives.bind"); },
  ensureBound: (..._a: any[]): any => { return notPorted("Natives.ensureBound"); },
  specialName: (..._a: any[]): any => { return notPorted("Natives.specialName"); },
  handlerFor: (..._a: any[]): any => { return notPorted("Natives.handlerFor"); },
  resetLog: (..._a: any[]): any => { return notPorted("Natives.resetLog"); },
  callnative: (..._a: any[]): any => { return notPorted("Natives.callnative"); },
  resolveNative: (..._a: any[]): any => { return notPorted("Natives.resolveNative"); },
  special: (..._a: any[]): any => { return notPorted("Natives.special"); },
};
export default Natives;
