// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/natives_events.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Events: Record<string, any> = {
  ICEFALL_CAVE_ICE_COORDS: undefined,
  METATILE_SEAFOAM_CRACKED_ICE: undefined,
  METATILE_SEAFOAM_ICE_HOLE: undefined,
  BY_NAME: undefined,
  pollWalkaway: (..._a: any[]): any => { return notPorted("Events.pollWalkaway"); },
};
export default Events;
