// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/ops_a.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Ops: Record<string, any> = {
  dispatchUnhooked: undefined,
  warpHoleDest: undefined,
  setMapLayout: undefined,
  brailleWidth: undefined,
  dispatch: (..._a: any[]): any => { return notPorted("Ops.dispatch"); },
};
export default Ops;
