// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/space.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Space: Record<string, any> = {
  active: undefined,
  vm: undefined,
  store: undefined,
  bundle: undefined,
  mapId: undefined,
  _saveKey: undefined,
  TEMP_FIELD_EVENT_FLAGS: undefined,
  isActive: (..._a: any[]): any => { return notPorted("Space.isActive"); },
  getVm: (..._a: any[]): any => { return notPorted("Space.getVm"); },
  getStore: (..._a: any[]): any => { return notPorted("Space.getStore"); },
  persistSession: (..._a: any[]): any => { return notPorted("Space.persistSession"); },
  ensureBundle: (..._a: any[]): any => { return notPorted("Space.ensureBundle"); },
  installLabels: (..._a: any[]): any => { return notPorted("Space.installLabels"); },
  scriptKey: (..._a: any[]): any => { return notPorted("Space.scriptKey"); },
  attachEventsToMaps: (..._a: any[]): any => { return notPorted("Space.attachEventsToMaps"); },
  activate: (..._a: any[]): any => { return notPorted("Space.activate"); },
  retarget: (..._a: any[]): any => { return notPorted("Space.retarget"); },
  deactivate: (..._a: any[]): any => { return notPorted("Space.deactivate"); },
  onMapEnter: (..._a: any[]): any => { return notPorted("Space.onMapEnter"); },
  runImmediately: (..._a: any[]): any => { return notPorted("Space.runImmediately"); },
  runOnResume: (..._a: any[]): any => { return notPorted("Space.runOnResume"); },
  runOnWarpIntoMap: (..._a: any[]): any => { return notPorted("Space.runOnWarpIntoMap"); },
  runOnReturnToField: (..._a: any[]): any => { return notPorted("Space.runOnReturnToField"); },
  runOnDiveWarp: (..._a: any[]): any => { return notPorted("Space.runOnDiveWarp"); },
  runOnLoad: (..._a: any[]): any => { return notPorted("Space.runOnLoad"); },
  tempFieldEventFlags: (..._a: any[]): any => { return notPorted("Space.tempFieldEventFlags"); },
  clearTempFieldEventFlags: (..._a: any[]): any => { return notPorted("Space.clearTempFieldEventFlags"); },
  runEnterScripts: (..._a: any[]): any => { return notPorted("Space.runEnterScripts"); },
  scheduleOnFrame: (..._a: any[]): any => { return notPorted("Space.scheduleOnFrame"); },
  returnToField: (..._a: any[]): any => { return notPorted("Space.returnToField"); },
  runOnFrame: (..._a: any[]): any => { return notPorted("Space.runOnFrame"); },
  resolveObjectSprite: (..._a: any[]): any => { return notPorted("Space.resolveObjectSprite"); },
  resolveObjectGraphicsId: (..._a: any[]): any => { return notPorted("Space.resolveObjectGraphicsId"); },
  neighborObjectState: (..._a: any[]): any => { return notPorted("Space.neighborObjectState"); },
  refreshObjectGraphics: (..._a: any[]): any => { return notPorted("Space.refreshObjectGraphics"); },
  objectVisible: (..._a: any[]): any => { return notPorted("Space.objectVisible"); },
  startScript: (..._a: any[]): any => { return notPorted("Space.startScript"); },
  install: (..._a: any[]): any => { return notPorted("Space.install"); },
};
export default Space;
