// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/stdscripts.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Std: Record<string, any> = {
  SPECIAL: undefined,
  SPECIAL_ALIASES: undefined,
  SPECIAL_ENGINE_BASE: undefined,
  SPECIAL_NAME_BY_ID: undefined,
  ENGINE_SPECIALS: undefined,
  specialIds: (..._a: any[]): any => { return notPorted("Std.specialIds"); },
  specialName: (..._a: any[]): any => { return notPorted("Std.specialName"); },
  bindById: (..._a: any[]): any => { return notPorted("Std.bindById"); },
  legacyHandlers: (..._a: any[]): any => { return notPorted("Std.legacyHandlers"); },
};
export default Std;
