// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/scripting/trainers.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Trainers: Record<string, any> = {
  _pack: undefined,
  DIALOGS_REL: undefined,
  _doublePersonalities: undefined,
  mergeDialogs: (..._a: any[]): any => { return notPorted("Trainers.mergeDialogs"); },
  pack: (..._a: any[]): any => { return notPorted("Trainers.pack"); },
  get: (..._a: any[]): any => { return notPorted("Trainers.get"); },
  foeFromId: (..._a: any[]): any => { return notPorted("Trainers.foeFromId"); },
  info: (..._a: any[]): any => { return notPorted("Trainers.info"); },
  dialogs: (..._a: any[]): any => { return notPorted("Trainers.dialogs"); },
  introStrings: (..._a: any[]): any => { return notPorted("Trainers.introStrings"); },
  getEncounterMusic: (..._a: any[]): any => { return notPorted("Trainers.getEncounterMusic"); },
  getBattleMusicRole: (..._a: any[]): any => { return notPorted("Trainers.getBattleMusicRole"); },
  getVictoryMusicRole: (..._a: any[]): any => { return notPorted("Trainers.getVictoryMusicRole"); },
};
export default Trainers;
