// @gen3-stub
// Not ported yet: gen1recomp src/world/game3/Follower.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Follower: Record<string, any> = {
  setShouldSpawn: (..._a: any[]): any => { return notPorted("Follower.setShouldSpawn"); },
  reset: (..._a: any[]): any => { return notPorted("Follower.reset"); },
  current: (..._a: any[]): any => { return notPorted("Follower.current"); },
  talk: (..._a: any[]): any => { return notPorted("Follower.talk"); },
  starterInParty: (..._a: any[]): any => { return notPorted("Follower.starterInParty"); },
  setVisible: (..._a: any[]): any => { return notPorted("Follower.setVisible"); },
  at: (..._a: any[]): any => { return notPorted("Follower.at"); },
  update: (..._a: any[]): any => { return notPorted("Follower.update"); },
  onMapEntered: (..._a: any[]): any => { return notPorted("Follower.onMapEntered"); },
  actor: (..._a: any[]): any => { return notPorted("Follower.actor"); },
};
export default Follower;
