// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/link/LinkBattle2.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const LinkBattle2: Record<string, any> = {
  new: (..._a: any[]): any => undefined,
  newSpectator: (..._a: any[]): any => undefined,
  newHost: (..._a: any[]): any => undefined,
  newGuest: (..._a: any[]): any => undefined,
};
export default LinkBattle2;
