// @gen3-stub
// Not ported yet: gen1recomp src/core/crypto/ed25519.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../../notported.ts";

export const Ed25519: Record<string, any> = {
  verify: (..._a: any[]): any => { return notPorted("Ed25519.verify"); },
};
export default Ed25519;
