// @gen3-stub
// Not ported yet: gen1recomp src/import/CacheFs.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const CacheFs: Record<string, any> = {
  prefix: undefined,
  root: (..._a: any[]): any => { return notPorted("CacheFs.root"); },
  portableError: (..._a: any[]): any => { return notPorted("CacheFs.portableError"); },
  _resetPortableForTests: (..._a: any[]): any => { return notPorted("CacheFs._resetPortableForTests"); },
  write: (..._a: any[]): any => { return notPorted("CacheFs.write"); },
  openWrite: (..._a: any[]): any => { return notPorted("CacheFs.openWrite"); },
  readAt: (..._a: any[]): any => { return notPorted("CacheFs.readAt"); },
  read: (..._a: any[]): any => { return notPorted("CacheFs.read"); },
  readActive: (..._a: any[]): any => { return notPorted("CacheFs.readActive"); },
  loadActive: (..._a: any[]): any => { return notPorted("CacheFs.loadActive"); },
  existsAt: (..._a: any[]): any => { return notPorted("CacheFs.existsAt"); },
  exists: (..._a: any[]): any => { return notPorted("CacheFs.exists"); },
  remove: (..._a: any[]): any => { return notPorted("CacheFs.remove"); },
  removeDir: (..._a: any[]): any => { return notPorted("CacheFs.removeDir"); },
  removeTree: (..._a: any[]): any => { return notPorted("CacheFs.removeTree"); },
  migrateLegacyRedCache: (..._a: any[]): any => { return notPorted("CacheFs.migrateLegacyRedCache"); },
  mountVersion: (..._a: any[]): any => { return notPorted("CacheFs.mountVersion"); },
  unmountVersion: (..._a: any[]): any => { return notPorted("CacheFs.unmountVersion"); },
  withMounted: (..._a: any[]): any => { return notPorted("CacheFs.withMounted"); },
};
export default CacheFs;
