// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/bag.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Bag: Record<string, any> = {
  FLAG_SYS_GOT_BERRY_POUCH: undefined,
  MAX_COINS: undefined,
  Coins: undefined,
  new: (..._a: any[]): any => { return notPorted("Bag.new"); },
  migrate: (..._a: any[]): any => { return notPorted("Bag.migrate"); },
  clear: (..._a: any[]): any => { return notPorted("Bag.clear"); },
  get: (..._a: any[]): any => { return notPorted("Bag.get"); },
  has: (..._a: any[]): any => { return notPorted("Bag.has"); },
  canAdd: (..._a: any[]): any => { return notPorted("Bag.canAdd"); },
  add: (..._a: any[]): any => { return notPorted("Bag.add"); },
  remove: (..._a: any[]): any => { return notPorted("Bag.remove"); },
  set: (..._a: any[]): any => { return notPorted("Bag.set"); },
  listPocket: (..._a: any[]): any => { return notPorted("Bag.listPocket"); },
  mergeFromHost: (..._a: any[]): any => { return notPorted("Bag.mergeFromHost"); },
  restoreSidecar: (..._a: any[]): any => { return notPorted("Bag.restoreSidecar"); },
  splitForHost: (..._a: any[]): any => { return notPorted("Bag.splitForHost"); },
  applyHostWrites: (..._a: any[]): any => { return notPorted("Bag.applyHostWrites"); },
};
export default Bag;
