// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle_transition.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const BattleTransition: Record<string, any> = {
  _active: undefined,
  _phase: undefined,
  _transitionId: undefined,
  _opts: undefined,
  _doneCb: undefined,
  _frame: undefined,
  _fx: undefined,
  _pal: undefined,
  _intro: undefined,
  _worldDrawn: undefined,
  RSE_MODULES: undefined,
  H: undefined,
  family: (..._a: any[]): any => { return notPorted("BattleTransition.family"); },
  ids: (..._a: any[]): any => { return notPorted("BattleTransition.ids"); },
  getTerrainByMap: (..._a: any[]): any => { return notPorted("BattleTransition.getTerrainByMap"); },
  pickWild: (..._a: any[]): any => { return notPorted("BattleTransition.pickWild"); },
  pickTrainer: (..._a: any[]): any => { return notPorted("BattleTransition.pickTrainer"); },
  pick: (..._a: any[]): any => { return notPorted("BattleTransition.pick"); },
  defs: (..._a: any[]): any => { return notPorted("BattleTransition.defs"); },
  start: (..._a: any[]): any => { return notPorted("BattleTransition.start"); },
  isActive: (..._a: any[]): any => { return notPorted("BattleTransition.isActive"); },
  finish: (..._a: any[]): any => { return notPorted("BattleTransition.finish"); },
  abort: (..._a: any[]): any => { return notPorted("BattleTransition.abort"); },
  tick: (..._a: any[]): any => { return notPorted("BattleTransition.tick"); },
  blackSpans: (..._a: any[]): any => { return notPorted("BattleTransition.blackSpans"); },
  screenCoverage: (..._a: any[]): any => { return notPorted("BattleTransition.screenCoverage"); },
  drawWorld: (..._a: any[]): any => { return notPorted("BattleTransition.drawWorld"); },
  draw: (..._a: any[]): any => { return notPorted("BattleTransition.draw"); },
};
export default BattleTransition;
