// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const battle: Record<string, any> = {
};
export default battle;
