// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/braille_field.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const BrailleField: Record<string, any> = {
  REGICE_PATH: undefined,
  BY_NAME: undefined,
  shouldDoDig: (..._a: any[]): any => { return notPorted("BrailleField.shouldDoDig"); },
  doDig: (..._a: any[]): any => { return notPorted("BrailleField.doDig"); },
  checkRelicanthWailord: (..._a: any[]): any => { return notPorted("BrailleField.checkRelicanthWailord"); },
  shake: (..._a: any[]): any => { return notPorted("BrailleField.shake"); },
  shouldDoRegirock: (..._a: any[]): any => { return notPorted("BrailleField.shouldDoRegirock"); },
  shouldDoRegisteel: (..._a: any[]): any => { return notPorted("BrailleField.shouldDoRegisteel"); },
  doRegiEffect: (..._a: any[]): any => { return notPorted("BrailleField.doRegiEffect"); },
  shouldDoRegicePuzzle: (..._a: any[]): any => { return notPorted("BrailleField.shouldDoRegicePuzzle"); },
};
export default BrailleField;
