// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/breeding.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Breeding: Record<string, any> = {
  PARENTS_INCOMPATIBLE: undefined,
  PARENTS_LOW_COMPATIBILITY: undefined,
  PARENTS_MED_COMPATIBILITY: undefined,
  PARENTS_MAX_COMPATIBILITY: undefined,
  EGG_HATCH_LEVEL: undefined,
  EGG_GENDER_MALE: undefined,
  INHERITED_IV_COUNT: undefined,
  FLAG_PENDING_DAYCARE_EGG: undefined,
  IV_KEYS: undefined,
  constantOf: undefined,
  isRse: (..._a: any[]): any => { return notPorted("Breeding.isRse"); },
  pendingEggFlag: (..._a: any[]): any => { return notPorted("Breeding.pendingEggFlag"); },
  eggGroups: (..._a: any[]): any => { return notPorted("Breeding.eggGroups"); },
  eggGroupsOverlap: (..._a: any[]): any => { return notPorted("Breeding.eggGroupsOverlap"); },
  compatibility: (..._a: any[]): any => { return notPorted("Breeding.compatibility"); },
  eggSpecies: (..._a: any[]): any => { return notPorted("Breeding.eggSpecies"); },
  triggerPendingEgg: (..._a: any[]): any => { return notPorted("Breeding.triggerPendingEgg"); },
  parentToInheritNature: (..._a: any[]): any => { return notPorted("Breeding.parentToInheritNature"); },
  rsePersonality: (..._a: any[]): any => { return notPorted("Breeding.rsePersonality"); },
  tryProduceEgg: (..._a: any[]): any => { return notPorted("Breeding.tryProduceEgg"); },
  removeEgg: (..._a: any[]): any => { return notPorted("Breeding.removeEgg"); },
  parentSlots: (..._a: any[]): any => { return notPorted("Breeding.parentSlots"); },
  alterEggSpeciesWithIncenseItem: (..._a: any[]): any => { return notPorted("Breeding.alterEggSpeciesWithIncenseItem"); },
  inheritIVs: (..._a: any[]): any => { return notPorted("Breeding.inheritIVs"); },
  eggMovesOf: (..._a: any[]): any => { return notPorted("Breeding.eggMovesOf"); },
  buildEggMoveset: (..._a: any[]): any => { return notPorted("Breeding.buildEggMoveset"); },
  applyEggData: (..._a: any[]): any => { return notPorted("Breeding.applyEggData"); },
  setInitialEggData: (..._a: any[]): any => { return notPorted("Breeding.setInitialEggData"); },
  giveVoltTackleIfLightBall: (..._a: any[]): any => { return notPorted("Breeding.giveVoltTackleIfLightBall"); },
  createEgg: (..._a: any[]): any => { return notPorted("Breeding.createEgg"); },
  giveEggFromDaycare: (..._a: any[]): any => { return notPorted("Breeding.giveEggFromDaycare"); },
  hatchMon: (..._a: any[]): any => { return notPorted("Breeding.hatchMon"); },
};
export default Breeding;
