// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/bridge.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Bridge: Record<string, any> = {
  SAVE_KEY: undefined,
  storageToSidecar: (..._a: any[]): any => { return notPorted("Bridge.storageToSidecar"); },
  enterFromHost: (..._a: any[]): any => { return notPorted("Bridge.enterFromHost"); },
  persistSessionOnly: (..._a: any[]): any => { return notPorted("Bridge.persistSessionOnly"); },
  returnToHost: (..._a: any[]): any => { return notPorted("Bridge.returnToHost"); },
  persistFlags: (..._a: any[]): any => { return notPorted("Bridge.persistFlags"); },
  getSidecar: (..._a: any[]): any => { return notPorted("Bridge.getSidecar"); },
};
export default Bridge;
