// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/connections.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Connections: Record<string, any> = {
  cardinal: (..._a: any[]): any => { return notPorted("Connections.cardinal"); },
  each: (..._a: any[]): any => { return notPorted("Connections.each"); },
  sizeOf: (..._a: any[]): any => { return notPorted("Connections.sizeOf"); },
  incoming: (..._a: any[]): any => { return notPorted("Connections.incoming"); },
  localPos: (..._a: any[]): any => { return notPorted("Connections.localPos"); },
  atPos: (..._a: any[]): any => { return notPorted("Connections.atPos"); },
};
export default Connections;
