// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/fame_checker.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const FameChecker: Record<string, any> = {
  PERSON: undefined,
  NUM_PERSONS: undefined,
  NUM_FLAVOR_TEXTS: undefined,
  PICKSTATE: undefined,
  NON_TRAINER_START: undefined,
  TRAINER_IDS: undefined,
  records: (..._a: any[]): any => { return notPorted("FameChecker.records"); },
  record: (..._a: any[]): any => { return notPorted("FameChecker.record"); },
  reset: (..._a: any[]): any => { return notPorted("FameChecker.reset"); },
  fullyUnlock: (..._a: any[]): any => { return notPorted("FameChecker.fullyUnlock"); },
  updatePickState: (..._a: any[]): any => { return notPorted("FameChecker.updatePickState"); },
  setFlavorText: (..._a: any[]): any => { return notPorted("FameChecker.setFlavorText"); },
  pickState: (..._a: any[]): any => { return notPorted("FameChecker.pickState"); },
  flavorTextFlags: (..._a: any[]): any => { return notPorted("FameChecker.flavorTextFlags"); },
  hasFlavorText: (..._a: any[]): any => { return notPorted("FameChecker.hasFlavorText"); },
  hasUnlockedAllFlavorTexts: (..._a: any[]): any => { return notPorted("FameChecker.hasUnlockedAllFlavorTexts"); },
  adjustGiovanniIndex: (..._a: any[]): any => { return notPorted("FameChecker.adjustGiovanniIndex"); },
  unlockedPersons: (..._a: any[]): any => { return notPorted("FameChecker.unlockedPersons"); },
};
export default FameChecker;
