// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/field_plan.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Plan: Record<string, any> = {
  cell: undefined,
  invalidate: (..._a: any[]): any => { return notPorted("Plan.invalidate"); },
  prefetch: (..._a: any[]): any => { return notPorted("Plan.prefetch"); },
  get: (..._a: any[]): any => { return notPorted("Plan.get"); },
};
export default Plan;
