// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/field_modules.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const FieldModules: Record<string, any> = {
  NAMES: undefined,
  FAMILY_DEFAULTS: undefined,
  list: (..._a: any[]): any => { return notPorted("FieldModules.list"); },
  enabled: (..._a: any[]): any => { return notPorted("FieldModules.enabled"); },
};
export default FieldModules;
