// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/field_cell_prepare.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Prepare: Record<string, any> = {
  cells: (..._a: any[]): any => { return notPorted("Prepare.cells"); },
  cell: (..._a: any[]): any => { return notPorted("Prepare.cell"); },
};
export default Prepare;
