// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/field_semantics.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Sem: Record<string, any> = {
  FRLG_VARS: undefined,
  FRLG_FLAGS: undefined,
  var: (..._a: any[]): any => { return notPorted("Sem.var"); },
  flag: (..._a: any[]): any => { return notPorted("Sem.flag"); },
  reset: (..._a: any[]): any => { return notPorted("Sem.reset"); },
};
export default Sem;
