// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/forced_movement.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const forced_movement: Record<string, any> = {
  forced: undefined,
  lastSpinTile: undefined,
  _mapId: undefined,
  isRse: undefined,
  TABLE: undefined,
  TABLE_RSE: undefined,
  stepCallbacks: undefined,
  _stepTask: undefined,
  _stepData: undefined,
  activeTable: (..._a: any[]): any => { return notPorted("forced_movement.activeTable"); },
  isForcedMovementTile: (..._a: any[]): any => { return notPorted("forced_movement.isForcedMovementTile"); },
  lookup: (..._a: any[]): any => { return notPorted("forced_movement.lookup"); },
  tryDoMetatileBehaviorForcedMovement: (..._a: any[]): any => { return notPorted("forced_movement.tryDoMetatileBehaviorForcedMovement"); },
  applyTileForcedMovement: (..._a: any[]): any => { return notPorted("forced_movement.applyTileForcedMovement"); },
  tryUpdatePlayerSpinDirection: (..._a: any[]): any => { return notPorted("forced_movement.tryUpdatePlayerSpinDirection"); },
  registerStepCallback: (..._a: any[]): any => { return notPorted("forced_movement.registerStepCallback"); },
  runStepCallback: (..._a: any[]): any => { return notPorted("forced_movement.runStepCallback"); },
  reset: (..._a: any[]): any => { return notPorted("forced_movement.reset"); },
  isForced: (..._a: any[]): any => { return notPorted("forced_movement.isForced"); },
  fieldControlsLocked: (..._a: any[]): any => { return notPorted("forced_movement.fieldControlsLocked"); },
  onStepFinished: (..._a: any[]): any => { return notPorted("forced_movement.onStepFinished"); },
};
export default forced_movement;
