// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/gba_fx.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Fx: Record<string, any> = {
  WHITE: undefined,
  BLACK: undefined,
  active: (..._a: any[]): any => { return notPorted("Fx.active"); },
  draw: (..._a: any[]): any => { return notPorted("Fx.draw"); },
  withClip: (..._a: any[]): any => { return notPorted("Fx.withClip"); },
};
export default Fx;
