// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/items.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Items: Record<string, any> = {
  GAME3_MAX_QTY: undefined,
  HOST_MAX_QTY: undefined,
  FRLG_TO_HOST: undefined,
  FORCE_QUARANTINE: undefined,
  HOST_SAFE: undefined,
  resolveHostId: (..._a: any[]): any => { return notPorted("Items.resolveHostId"); },
  isHostSafe: (..._a: any[]): any => { return notPorted("Items.isHostSafe"); },
  clampGame3: (..._a: any[]): any => { return notPorted("Items.clampGame3"); },
  displayName: (..._a: any[]): any => { return notPorted("Items.displayName"); },
  pocket: (..._a: any[]): any => { return notPorted("Items.pocket"); },
};
export default Items;
