// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/itemfinder.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Itemfinder: Record<string, any> = {
  _task: undefined,
  _sprites: undefined,
  scan: (..._a: any[]): any => { return notPorted("Itemfinder.scan"); },
  start: (..._a: any[]): any => { return notPorted("Itemfinder.start"); },
  textKey: (..._a: any[]): any => { return notPorted("Itemfinder.textKey"); },
  isActive: (..._a: any[]): any => { return notPorted("Itemfinder.isActive"); },
  sprites: (..._a: any[]): any => { return notPorted("Itemfinder.sprites"); },
  update: (..._a: any[]): any => { return notPorted("Itemfinder.update"); },
  runTask: (..._a: any[]): any => { return notPorted("Itemfinder.runTask"); },
  draw: (..._a: any[]): any => { return notPorted("Itemfinder.draw"); },
  reset: (..._a: any[]): any => { return notPorted("Itemfinder.reset"); },
};
export default Itemfinder;
