// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/layout_native.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class LayoutNative {
  [key: string]: any;
  static [key: string]: any;
  static fromDecoded(..._a: any[]): any { return notPorted("LayoutNative.fromDecoded"); }
  workerPacked(..._a: any[]): any { return notPorted("LayoutNative:workerPacked"); }
  cellAt(..._a: any[]): any { return notPorted("LayoutNative:cellAt"); }
  midAt(..._a: any[]): any { return notPorted("LayoutNative:midAt"); }
  collAt(..._a: any[]): any { return notPorted("LayoutNative:collAt"); }
  elevAt(..._a: any[]): any { return notPorted("LayoutNative:elevAt"); }
  collArray(..._a: any[]): any { return notPorted("LayoutNative:collArray"); }
  applyOverride(..._a: any[]): any { return notPorted("LayoutNative:applyOverride"); }
  stamp(..._a: any[]): any { return notPorted("LayoutNative:stamp"); }
  setMetatiles(..._a: any[]): any { return notPorted("LayoutNative:setMetatiles"); }
  clearOverrides(..._a: any[]): any { return notPorted("LayoutNative:clearOverrides"); }
}
export default LayoutNative;
