// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/mail.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Mail: Record<string, any> = {
  MAIL_COUNT: undefined,
  MAIL_WORDS_COUNT: undefined,
  MAIL_NONE: undefined,
  PARTY_SIZE: undefined,
  ITEM_NONE: undefined,
  EC_WORD_UNDEFINED: undefined,
  isMailItem: (..._a: any[]): any => { return notPorted("Mail.isMailItem"); },
  designOf: (..._a: any[]): any => { return notPorted("Mail.designOf"); },
  speciesToMailSpecies: (..._a: any[]): any => { return notPorted("Mail.speciesToMailSpecies"); },
  mailSpeciesToSpecies: (..._a: any[]): any => { return notPorted("Mail.mailSpeciesToSpecies"); },
  clear: (..._a: any[]): any => { return notPorted("Mail.clear"); },
  copy: (..._a: any[]): any => { return notPorted("Mail.copy"); },
  isEmpty: (..._a: any[]): any => { return notPorted("Mail.isEmpty"); },
  pool: (..._a: any[]): any => { return notPorted("Mail.pool"); },
  slot: (..._a: any[]): any => { return notPorted("Mail.slot"); },
  get: (..._a: any[]): any => { return notPorted("Mail.get"); },
  monHasMail: (..._a: any[]): any => { return notPorted("Mail.monHasMail"); },
  giveMailToMon: (..._a: any[]): any => { return notPorted("Mail.giveMailToMon"); },
  giveMailToMon2: (..._a: any[]): any => { return notPorted("Mail.giveMailToMon2"); },
  takeMailFromMon: (..._a: any[]): any => { return notPorted("Mail.takeMailFromMon"); },
  takeMonMailForDaycare: (..._a: any[]): any => { return notPorted("Mail.takeMonMailForDaycare"); },
  giveDaycareMailToMon: (..._a: any[]): any => { return notPorted("Mail.giveDaycareMailToMon"); },
  export: (..._a: any[]): any => { return notPorted("Mail.export"); },
  restore: (..._a: any[]): any => { return notPorted("Mail.restore"); },
};
export default Mail;
