// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/mon_anim.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const MonAnim: Record<string, any> = {
  Data: undefined,
  oob: undefined,
  F: undefined,
  SpriteCallbackDummy: undefined,
  SpriteCallbackDummy_2: undefined,
  SKIP_FRONT_ANIM: undefined,
  animFunction: (..._a: any[]): any => { return notPorted("MonAnim.animFunction"); },
  callbackName: (..._a: any[]): any => { return notPorted("MonAnim.callbackName"); },
  startSpriteAnim: (..._a: any[]): any => { return notPorted("MonAnim.startSpriteAnim"); },
  newSprite: (..._a: any[]): any => { return notPorted("MonAnim.newSprite"); },
  launchFront: (..._a: any[]): any => { return notPorted("MonAnim.launchFront"); },
  startSummary: (..._a: any[]): any => { return notPorted("MonAnim.startSummary"); },
  launchBack: (..._a: any[]): any => { return notPorted("MonAnim.launchBack"); },
  hasTwoFramesAnimation: (..._a: any[]): any => { return notPorted("MonAnim.hasTwoFramesAnimation"); },
  doFront: (..._a: any[]): any => { return notPorted("MonAnim.doFront"); },
  battleFront: (..._a: any[]): any => { return notPorted("MonAnim.battleFront"); },
  battleBack: (..._a: any[]): any => { return notPorted("MonAnim.battleBack"); },
  summary: (..._a: any[]): any => { return notPorted("MonAnim.summary"); },
  animateSprites: (..._a: any[]): any => { return notPorted("MonAnim.animateSprites"); },
  runTasks: (..._a: any[]): any => { return notPorted("MonAnim.runTasks"); },
  step: (..._a: any[]): any => { return notPorted("MonAnim.step"); },
  done: (..._a: any[]): any => { return notPorted("MonAnim.done"); },
  busy: (..._a: any[]): any => { return notPorted("MonAnim.busy"); },
  enabled: (..._a: any[]): any => { return notPorted("MonAnim.enabled"); },
  run: (..._a: any[]): any => { return notPorted("MonAnim.run"); },
  stop: (..._a: any[]): any => { return notPorted("MonAnim.stop"); },
  transform: (..._a: any[]): any => { return notPorted("MonAnim.transform"); },
  blendRgb: (..._a: any[]): any => { return notPorted("MonAnim.blendRgb"); },
  framePic: (..._a: any[]): any => { return notPorted("MonAnim.framePic"); },
  draw: (..._a: any[]): any => { return notPorted("MonAnim.draw"); },
  resetState: (..._a: any[]): any => { return notPorted("MonAnim.resetState"); },
};
export default MonAnim;
