// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/mon_anim_data.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const MonAnimData: Record<string, any> = {
  FRONT: undefined,
  BACK: undefined,
  SHEET: undefined,
  SHEET_SHINY: undefined,
  PP_UP_GET_MASK_0: undefined,
  useCache: (..._a: any[]): any => { return notPorted("MonAnimData.useCache"); },
  cache: (..._a: any[]): any => { return notPorted("MonAnimData.cache"); },
  get: (..._a: any[]): any => { return notPorted("MonAnimData.get"); },
  reset: (..._a: any[]): any => { return notPorted("MonAnimData.reset"); },
  available: (..._a: any[]): any => { return notPorted("MonAnimData.available"); },
  functionName: (..._a: any[]): any => { return notPorted("MonAnimData.functionName"); },
  functionCount: (..._a: any[]): any => { return notPorted("MonAnimData.functionCount"); },
  anims: (..._a: any[]): any => { return notPorted("MonAnimData.anims"); },
  frontAnimId: (..._a: any[]): any => { return notPorted("MonAnimData.frontAnimId"); },
  delay: (..._a: any[]): any => { return notPorted("MonAnimData.delay"); },
  backAnimSet: (..._a: any[]): any => { return notPorted("MonAnimData.backAnimSet"); },
  backAnimId: (..._a: any[]): any => { return notPorted("MonAnimData.backAnimId"); },
};
export default MonAnimData;
