// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/pal_fade.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class Pal {
  [key: string]: any;
  static [key: string]: any;
  static WHITE: any = undefined;
  static BLACK: any = undefined;
  static ALL: any = undefined;
  static BG: any = undefined;
  static OBJ: any = undefined;
  static new(..._a: any[]): any { return notPorted("Pal.new"); }
  static mask(..._a: any[]): any { return notPorted("Pal.mask"); }
  static bgSlot(..._a: any[]): any { return notPorted("Pal.bgSlot"); }
  static objSlot(..._a: any[]): any { return notPorted("Pal.objSlot"); }
  reset(..._a: any[]): any { return notPorted("Pal:reset"); }
  blend(..._a: any[]): any { return notPorted("Pal:blend"); }
  setGray(..._a: any[]): any { return notPorted("Pal:setGray"); }
  setBase(..._a: any[]): any { return notPorted("Pal:setBase"); }
  restore(..._a: any[]): any { return notPorted("Pal:restore"); }
  beginFade(..._a: any[]): any { return notPorted("Pal:beginFade"); }
  fadeActive(..._a: any[]): any { return notPorted("Pal:fadeActive"); }
  updateFade(..._a: any[]): any { return notPorted("Pal:updateFade"); }
  resetFade(..._a: any[]): any { return notPorted("Pal:resetFade"); }
  blendGradually(..._a: any[]): any { return notPorted("Pal:blendGradually"); }
  _stepGradual(..._a: any[]): any { return notPorted("Pal:_stepGradual"); }
  runGradual(..._a: any[]): any { return notPorted("Pal:runGradual"); }
  gradualActive(..._a: any[]): any { return notPorted("Pal:gradualActive"); }
  clearGradual(..._a: any[]): any { return notPorted("Pal:clearGradual"); }
  fx(..._a: any[]): any { return notPorted("Pal:fx"); }
}
export default Pal;
