// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/palette.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Palette: Record<string, any> = {
  NUM_PALS_IN_PRIMARY: undefined,
  NUM_PALS_TOTAL: undefined,
  _md5hex: undefined,
  loadBgr555: (..._a: any[]): any => { return notPorted("Palette.loadBgr555"); },
  load: (..._a: any[]): any => { return notPorted("Palette.load"); },
  hash: (..._a: any[]): any => { return notPorted("Palette.hash"); },
  tint: (..._a: any[]): any => { return notPorted("Palette.tint"); },
};
export default Palette;
