// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/pc_anim.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const PcAnim: Record<string, any> = {
  task: undefined,
  METATILE_OFF: undefined,
  METATILE_ON: undefined,
  setter: (..._a: any[]): any => { return notPorted("PcAnim.setter"); },
  drawable: (..._a: any[]): any => { return notPorted("PcAnim.drawable"); },
  turnOn: (..._a: any[]): any => { return notPorted("PcAnim.turnOn"); },
  update: (..._a: any[]): any => { return notPorted("PcAnim.update"); },
  turnOff: (..._a: any[]): any => { return notPorted("PcAnim.turnOff"); },
  reset: (..._a: any[]): any => { return notPorted("PcAnim.reset"); },
};
export default PcAnim;
