// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/pokedex_data.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const PokedexData: Record<string, any> = {
  _entries: undefined,
  _categories: undefined,
  _orders: undefined,
  _areaData: undefined,
  _speciesWildAreas: undefined,
  init: (..._a: any[]): any => { return notPorted("PokedexData.init"); },
  getAreaMapKey: (..._a: any[]): any => { return notPorted("PokedexData.getAreaMapKey"); },
  _buildSpeciesWildAreas: (..._a: any[]): any => { return notPorted("PokedexData._buildSpeciesWildAreas"); },
  getEntry: (..._a: any[]): any => { return notPorted("PokedexData.getEntry"); },
  getCategoryPages: (..._a: any[]): any => { return notPorted("PokedexData.getCategoryPages"); },
  getUnlockedCategoryPages: (..._a: any[]): any => { return notPorted("PokedexData.getUnlockedCategoryPages"); },
  getOrderList: (..._a: any[]): any => { return notPorted("PokedexData.getOrderList"); },
  getWildAreasForSpecies: (..._a: any[]): any => { return notPorted("PokedexData.getWildAreasForSpecies"); },
  getAreaMarker: (..._a: any[]): any => { return notPorted("PokedexData.getAreaMarker"); },
  isNationalUnlocked: (..._a: any[]): any => { return notPorted("PokedexData.isNationalUnlocked"); },
  isCategoryUnlocked: (..._a: any[]): any => { return notPorted("PokedexData.isCategoryUnlocked"); },
  countCategory: (..._a: any[]): any => { return notPorted("PokedexData.countCategory"); },
  countOrder: (..._a: any[]): any => { return notPorted("PokedexData.countOrder"); },
};
export default PokedexData;
