// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/renewable_hidden_items.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const RenewableHiddenItems: Record<string, any> = {
  ZONES: undefined,
  isRenewableMap: (..._a: any[]): any => { return notPorted("RenewableHiddenItems.isRenewableMap"); },
  onStep: (..._a: any[]): any => { return notPorted("RenewableHiddenItems.onStep"); },
  tryRegenerate: (..._a: any[]): any => { return notPorted("RenewableHiddenItems.tryRegenerate"); },
};
export default RenewableHiddenItems;
