// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/roamer.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Roamer: Record<string, any> = {
  rseConfig: undefined,
  _locations: undefined,
  SPECIES_RAIKOU: undefined,
  SPECIES_ENTEI: undefined,
  SPECIES_SUICUNE: undefined,
  ROAMER_LEVEL: undefined,
  LOCATIONS: undefined,
  ADJACENCY: undefined,
  normalizeMapId: undefined,
  locationSets: (..._a: any[]): any => { return notPorted("Roamer.locationSets"); },
  initRse: (..._a: any[]): any => { return notPorted("Roamer.initRse"); },
  updateHistory: (..._a: any[]): any => { return notPorted("Roamer.updateHistory"); },
  moveToOtherSet: (..._a: any[]): any => { return notPorted("Roamer.moveToOtherSet"); },
  moveRse: (..._a: any[]): any => { return notPorted("Roamer.moveRse"); },
  speciesForStarter: (..._a: any[]): any => { return notPorted("Roamer.speciesForStarter"); },
  generateMon: (..._a: any[]): any => { return notPorted("Roamer.generateMon"); },
  init: (..._a: any[]): any => { return notPorted("Roamer.init"); },
  jump: (..._a: any[]): any => { return notPorted("Roamer.jump"); },
  move: (..._a: any[]): any => { return notPorted("Roamer.move"); },
  tryEncounter: (..._a: any[]): any => { return notPorted("Roamer.tryEncounter"); },
  onBattleEnd: (..._a: any[]): any => { return notPorted("Roamer.onBattleEnd"); },
};
export default Roamer;
