// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/rom_text.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const RomText: Record<string, any> = {
  overrides: undefined,
  ir: (..._a: any[]): any => { return notPorted("RomText.ir"); },
  has: (..._a: any[]): any => { return notPorted("RomText.has"); },
  sources: (..._a: any[]): any => { return notPorted("RomText.sources"); },
  translate: (..._a: any[]): any => { return notPorted("RomText.translate"); },
  box: (..._a: any[]): any => { return notPorted("RomText.box"); },
  plain: (..._a: any[]): any => { return notPorted("RomText.plain"); },
  ascii: (..._a: any[]): any => { return notPorted("RomText.ascii"); },
  key: (..._a: any[]): any => { return notPorted("RomText.key"); },
  count: (..._a: any[]): any => { return notPorted("RomText.count"); },
  at: (..._a: any[]): any => { return notPorted("RomText.at"); },
  list: (..._a: any[]): any => { return notPorted("RomText.list"); },
  lazy: (..._a: any[]): any => { return notPorted("RomText.lazy"); },
};
export default RomText;
