// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/rtc.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Rtc: Record<string, any> = {
  ERR: undefined,
  SAVE_FIELDS: undefined,
  localTime: undefined,
  newTime: (..._a: any[]): any => { return notPorted("Rtc.newTime"); },
  copyTime: (..._a: any[]): any => { return notPorted("Rtc.copyTime"); },
  enabled: (..._a: any[]): any => { return notPorted("Rtc.enabled"); },
  isLeapYear: (..._a: any[]): any => { return notPorted("Rtc.isLeapYear"); },
  dayCount: (..._a: any[]): any => { return notPorted("Rtc.dayCount"); },
  getDayCount: (..._a: any[]): any => { return notPorted("Rtc.getDayCount"); },
  hostInfo: (..._a: any[]): any => { return notPorted("Rtc.hostInfo"); },
  init: (..._a: any[]): any => { return notPorted("Rtc.init"); },
  errorStatus: (..._a: any[]): any => { return notPorted("Rtc.errorStatus"); },
  getInfo: (..._a: any[]): any => { return notPorted("Rtc.getInfo"); },
  calcTimeDifferenceRtc: (..._a: any[]): any => { return notPorted("Rtc.calcTimeDifferenceRtc"); },
  calcTimeDifference: (..._a: any[]): any => { return notPorted("Rtc.calcTimeDifference"); },
  calcLocalTime: (..._a: any[]): any => { return notPorted("Rtc.calcLocalTime"); },
  calcLocalTimeOffset: (..._a: any[]): any => { return notPorted("Rtc.calcLocalTimeOffset"); },
  initLocalTimeOffset: (..._a: any[]): any => { return notPorted("Rtc.initLocalTimeOffset"); },
  minuteCount: (..._a: any[]): any => { return notPorted("Rtc.minuteCount"); },
  localDayCount: (..._a: any[]): any => { return notPorted("Rtc.localDayCount"); },
  timeMinutes: (..._a: any[]): any => { return notPorted("Rtc.timeMinutes"); },
  anchorToLastUpdate: (..._a: any[]): any => { return notPorted("Rtc.anchorToLastUpdate"); },
  setFixed: (..._a: any[]): any => { return notPorted("Rtc.setFixed"); },
  advance: (..._a: any[]): any => { return notPorted("Rtc.advance"); },
  setHostClock: (..._a: any[]): any => { return notPorted("Rtc.setHostClock"); },
  reset: (..._a: any[]): any => { return notPorted("Rtc.reset"); },
  fixedActive: (..._a: any[]): any => { return notPorted("Rtc.fixedActive"); },
};
export default Rtc;
