// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/runtime.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Runtime: Record<string, any> = {
  active: undefined,
  session: undefined,
  _mod: undefined,
  _game: undefined,
  _fieldLocked: undefined,
  _playTimeAcc: undefined,
  _deferred: undefined,
  _menuFocus: undefined,
  log: undefined,
  isActive: (..._a: any[]): any => { return notPorted("Runtime.isActive"); },
  getSession: (..._a: any[]): any => { return notPorted("Runtime.getSession"); },
  defer: (..._a: any[]): any => { return notPorted("Runtime.defer"); },
  drainDeferred: (..._a: any[]): any => { return notPorted("Runtime.drainDeferred"); },
  fieldScreenOpen: (..._a: any[]): any => { return notPorted("Runtime.fieldScreenOpen"); },
  noteFieldFocus: (..._a: any[]): any => { return notPorted("Runtime.noteFieldFocus"); },
  pumpRtc: (..._a: any[]): any => { return notPorted("Runtime.pumpRtc"); },
  start: (..._a: any[]): any => { return notPorted("Runtime.start"); },
  stop: (..._a: any[]): any => { return notPorted("Runtime.stop"); },
  update: (..._a: any[]): any => { return notPorted("Runtime.update"); },
  tickVblank: (..._a: any[]): any => { return notPorted("Runtime.tickVblank"); },
  uiBusy: (..._a: any[]): any => { return notPorted("Runtime.uiBusy"); },
  setUi: (..._a: any[]): any => { return notPorted("Runtime.setUi"); },
  ensureActiveForMap: (..._a: any[]): any => { return notPorted("Runtime.ensureActiveForMap"); },
  install: (..._a: any[]): any => { return notPorted("Runtime.install"); },
};
export default Runtime;
