// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/se_ids.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const SE: Record<string, any> = {
  byName: undefined,
  current: undefined,
  resolve: (..._a: any[]): any => { return notPorted("SE.resolve"); },
  forVersion: (..._a: any[]): any => { return notPorted("SE.forVersion"); },
  select: (..._a: any[]): any => { return notPorted("SE.select"); },
};
export default SE;
