// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/song_fields.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const song_fields: Record<string, any> = {
};
export default song_fields;
