// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/special_field_anim.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const SpecialFieldAnim: Record<string, any> = {
  _active: undefined,
  _layout: undefined,
  _playerX: undefined,
  _playerY: undefined,
  _goingUp: undefined,
  _state: undefined,
  _transitionStage: undefined,
  _drawingEscalator: undefined,
  _originalMids: undefined,
  startEscalator: (..._a: any[]): any => { return notPorted("SpecialFieldAnim.startEscalator"); },
  stopEscalator: (..._a: any[]): any => { return notPorted("SpecialFieldAnim.stopEscalator"); },
  isActive: (..._a: any[]): any => { return notPorted("SpecialFieldAnim.isActive"); },
  isEscalatorMoving: (..._a: any[]): any => { return notPorted("SpecialFieldAnim.isEscalatorMoving"); },
  update: (..._a: any[]): any => { return notPorted("SpecialFieldAnim.update"); },
};
export default SpecialFieldAnim;
