// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/step_events.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const StepEvents: Record<string, any> = {
  _queue: undefined,
  _activeEvent: undefined,
  _poisonFlashTimer: undefined,
  _totalSteps: undefined,
  onStep: undefined,
  busy: (..._a: any[]): any => { return notPorted("StepEvents.busy"); },
  flush: (..._a: any[]): any => { return notPorted("StepEvents.flush"); },
  queueEvent: (..._a: any[]): any => { return notPorted("StepEvents.queueEvent"); },
  onStepTaken: (..._a: any[]): any => { return notPorted("StepEvents.onStepTaken"); },
  onRepelStep: (..._a: any[]): any => { return notPorted("StepEvents.onRepelStep"); },
  update: (..._a: any[]): any => { return notPorted("StepEvents.update"); },
  draw: (..._a: any[]): any => { return notPorted("StepEvents.draw"); },
};
export default StepEvents;
