// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/storage.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Storage: Record<string, any> = {
  TOTAL_BOXES_COUNT: undefined,
  IN_BOX_COUNT: undefined,
  TOTAL_BOX_MONS: undefined,
  MAX_ITEM_QTY: undefined,
  DEFAULT_WALLPAPERS: undefined,
  defaultWallpaper: (..._a: any[]): any => { return notPorted("Storage.defaultWallpaper"); },
  pcItemsCount: (..._a: any[]): any => { return notPorted("Storage.pcItemsCount"); },
  compactParty: (..._a: any[]): any => { return notPorted("Storage.compactParty"); },
  new: (..._a: any[]): any => { return notPorted("Storage.new"); },
  ensure: (..._a: any[]): any => { return notPorted("Storage.ensure"); },
  fullHealMon: (..._a: any[]): any => { return notPorted("Storage.fullHealMon"); },
  getBox: (..._a: any[]): any => { return notPorted("Storage.getBox"); },
  getBoxMon: (..._a: any[]): any => { return notPorted("Storage.getBoxMon"); },
  countBoxMons: (..._a: any[]): any => { return notPorted("Storage.countBoxMons"); },
  countTotalMons: (..._a: any[]): any => { return notPorted("Storage.countTotalMons"); },
  findOpenSlot: (..._a: any[]): any => { return notPorted("Storage.findOpenSlot"); },
  deposit: (..._a: any[]): any => { return notPorted("Storage.deposit"); },
  withdraw: (..._a: any[]): any => { return notPorted("Storage.withdraw"); },
  moveMon: (..._a: any[]): any => { return notPorted("Storage.moveMon"); },
  releaseMon: (..._a: any[]): any => { return notPorted("Storage.releaseMon"); },
  sendMonToPC: (..._a: any[]): any => { return notPorted("Storage.sendMonToPC"); },
  isDestinationBoxFull: (..._a: any[]): any => { return notPorted("Storage.isDestinationBoxFull"); },
  pcTransferMessage: (..._a: any[]): any => { return notPorted("Storage.pcTransferMessage"); },
  depositCaught: (..._a: any[]): any => { return notPorted("Storage.depositCaught"); },
  depositItem: (..._a: any[]): any => { return notPorted("Storage.depositItem"); },
  addPcItem: (..._a: any[]): any => { return notPorted("Storage.addPcItem"); },
  withdrawItem: (..._a: any[]): any => { return notPorted("Storage.withdrawItem"); },
  tossItem: (..._a: any[]): any => { return notPorted("Storage.tossItem"); },
  detachHeldItem: (..._a: any[]): any => { return notPorted("Storage.detachHeldItem"); },
  serialize: (..._a: any[]): any => { return notPorted("Storage.serialize"); },
  deserialize: (..._a: any[]): any => { return notPorted("Storage.deserialize"); },
  restore: (..._a: any[]): any => { return notPorted("Storage.restore"); },
};
export default Storage;
