// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/summary_data.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const SummaryData: Record<string, any> = {
  NATURES: undefined,
  natureStatModifier: (..._a: any[]): any => { return notPorted("SummaryData.natureStatModifier"); },
  expForLevel: (..._a: any[]): any => { return notPorted("SummaryData.expForLevel"); },
  expProgress: (..._a: any[]): any => { return notPorted("SummaryData.expProgress"); },
  nature: (..._a: any[]): any => { return notPorted("SummaryData.nature"); },
  isShiny: (..._a: any[]): any => { return notPorted("SummaryData.isShiny"); },
  gender: (..._a: any[]): any => { return notPorted("SummaryData.gender"); },
  statusAilment: (..._a: any[]): any => { return notPorted("SummaryData.statusAilment"); },
  eggCycles: (..._a: any[]): any => { return notPorted("SummaryData.eggCycles"); },
  eggHatchText: (..._a: any[]): any => { return notPorted("SummaryData.eggHatchText"); },
  formatTrainerMemo: (..._a: any[]): any => { return notPorted("SummaryData.formatTrainerMemo"); },
  abilityDescription: (..._a: any[]): any => { return notPorted("SummaryData.abilityDescription"); },
  moveDescription: (..._a: any[]): any => { return notPorted("SummaryData.moveDescription"); },
};
export default SummaryData;
