// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/tileset_native.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const NativeTileset: Record<string, any> = {
  _pairs: undefined,
  _cache: undefined,
  _logged: undefined,
  _ready: undefined,
  install: (..._a: any[]): any => { return notPorted("NativeTileset.install"); },
  invalidate: (..._a: any[]): any => { return notPorted("NativeTileset.invalidate"); },
  ready: (..._a: any[]): any => { return notPorted("NativeTileset.ready"); },
  prefetch: (..._a: any[]): any => { return notPorted("NativeTileset.prefetch"); },
  get: (..._a: any[]): any => { return notPorted("NativeTileset.get"); },
  slotFor: (..._a: any[]): any => { return notPorted("NativeTileset.slotFor"); },
  hasMid: (..._a: any[]): any => { return notPorted("NativeTileset.hasMid"); },
  quad: (..._a: any[]): any => { return notPorted("NativeTileset.quad"); },
  overQuad: (..._a: any[]): any => { return notPorted("NativeTileset.overQuad"); },
  flush: (..._a: any[]): any => { return notPorted("NativeTileset.flush"); },
  setSlotPalette: (..._a: any[]): any => { return notPorted("NativeTileset.setSlotPalette"); },
  resetSlotPalette: (..._a: any[]): any => { return notPorted("NativeTileset.resetSlotPalette"); },
};
export default NativeTileset;
