// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/trade_scene.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const TradeScene: Record<string, any> = {
  FADE_FRAMES: undefined,
  HOLD_FRAMES: undefined,
  BALL_VELOCITY: undefined,
  ART_FIRST: undefined,
  ART_LAST: undefined,
  PHASES: undefined,
  sequence: (..._a: any[]): any => { return notPorted("TradeScene.sequence"); },
  isOpen: (..._a: any[]): any => { return notPorted("TradeScene.isOpen"); },
  state: (..._a: any[]): any => { return notPorted("TradeScene.state"); },
  phase: (..._a: any[]): any => { return notPorted("TradeScene.phase"); },
  hasArt: (..._a: any[]): any => { return notPorted("TradeScene.hasArt"); },
  pressA: (..._a: any[]): any => { return notPorted("TradeScene.pressA"); },
  isLink: (..._a: any[]): any => { return notPorted("TradeScene.isLink"); },
  peer: (..._a: any[]): any => { return notPorted("TradeScene.peer"); },
  questLogData: (..._a: any[]): any => { return notPorted("TradeScene.questLogData"); },
  peerConfirmed: (..._a: any[]): any => { return notPorted("TradeScene.peerConfirmed"); },
  linkTaskDone: (..._a: any[]): any => { return notPorted("TradeScene.linkTaskDone"); },
  saveDone: (..._a: any[]): any => { return notPorted("TradeScene.saveDone"); },
  play: (..._a: any[]): any => { return notPorted("TradeScene.play"); },
  step: (..._a: any[]): any => { return notPorted("TradeScene.step"); },
  cancel: (..._a: any[]): any => { return notPorted("TradeScene.cancel"); },
};
export default TradeScene;
