// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/trainer_fan_club.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const TrainerFanClub: Record<string, any> = {
  MEMBER: undefined,
  NUM_MEMBERS: undefined,
  VAR_FANCLUB_FAN_COUNTER: undefined,
  VAR_FANCLUB_LOSE_FAN_TIMER: undefined,
  VAR_MAP_SCENE_SAFFRON_CITY_POKEMON_TRAINER_FAN_CLUB: undefined,
  FLAG_HIDE_SAFFRON_FAN_CLUB_BLACK_BELT: undefined,
  FLAG_HIDE_SAFFRON_FAN_CLUB_ROCKER: undefined,
  FLAG_HIDE_SAFFRON_FAN_CLUB_WOMAN: undefined,
  FLAG_HIDE_SAFFRON_FAN_CLUB_BEAUTY: undefined,
  COUNTER_INCREMENTS: undefined,
  GAIN_ORDER: undefined,
  LOSE_ORDER: undefined,
  unpack: (..._a: any[]): any => { return notPorted("TrainerFanClub.unpack"); },
  pack: (..._a: any[]): any => { return notPorted("TrainerFanClub.pack"); },
  getFanFlag: (..._a: any[]): any => { return notPorted("TrainerFanClub.getFanFlag"); },
  setFanFlag: (..._a: any[]): any => { return notPorted("TrainerFanClub.setFanFlag"); },
  flipFanFlag: (..._a: any[]): any => { return notPorted("TrainerFanClub.flipFanFlag"); },
  countFans: (..._a: any[]): any => { return notPorted("TrainerFanClub.countFans"); },
  sessionOf: (..._a: any[]): any => { return notPorted("TrainerFanClub.sessionOf"); },
  getVar: (..._a: any[]): any => { return notPorted("TrainerFanClub.getVar"); },
  setVar: (..._a: any[]): any => { return notPorted("TrainerFanClub.setVar"); },
  getFlag: (..._a: any[]): any => { return notPorted("TrainerFanClub.getFlag"); },
  setFlag: (..._a: any[]): any => { return notPorted("TrainerFanClub.setFlag"); },
  clearFlag: (..._a: any[]): any => { return notPorted("TrainerFanClub.clearFlag"); },
  getFanClubData: (..._a: any[]): any => { return notPorted("TrainerFanClub.getFanClubData"); },
  setFanClubData: (..._a: any[]): any => { return notPorted("TrainerFanClub.setFanClubData"); },
  getPlayTimeHours: (..._a: any[]): any => { return notPorted("TrainerFanClub.getPlayTimeHours"); },
  setStringVar: (..._a: any[]): any => { return notPorted("TrainerFanClub.setStringVar"); },
  reset: (..._a: any[]): any => { return notPorted("TrainerFanClub.reset"); },
  isFanClubMemberFanOfPlayer: (..._a: any[]): any => { return notPorted("TrainerFanClub.isFanClubMemberFanOfPlayer"); },
  getNumFansOfPlayerInTrainerFanClub: (..._a: any[]): any => { return notPorted("TrainerFanClub.getNumFansOfPlayerInTrainerFanClub"); },
  playerGainRandomTrainerFan: (..._a: any[]): any => { return notPorted("TrainerFanClub.playerGainRandomTrainerFan"); },
  playerLoseRandomTrainerFan: (..._a: any[]): any => { return notPorted("TrainerFanClub.playerLoseRandomTrainerFan"); },
  tryLoseFansFromPlayTime: (..._a: any[]): any => { return notPorted("TrainerFanClub.tryLoseFansFromPlayTime"); },
  tryLoseFansFromPlayTimeAfterLinkBattle: (..._a: any[]): any => { return notPorted("TrainerFanClub.tryLoseFansFromPlayTimeAfterLinkBattle"); },
  updateTrainerFanClubGameClear: (..._a: any[]): any => { return notPorted("TrainerFanClub.updateTrainerFanClubGameClear"); },
  tryGainNewFanFromCounter: (..._a: any[]): any => { return notPorted("TrainerFanClub.tryGainNewFanFromCounter"); },
  bufferFanClubTrainerName: (..._a: any[]): any => { return notPorted("TrainerFanClub.bufferFanClubTrainerName"); },
  updateTrainerFansAfterLinkBattle: (..._a: any[]): any => { return notPorted("TrainerFanClub.updateTrainerFansAfterLinkBattle"); },
  setPlayerGotFirstFans: (..._a: any[]): any => { return notPorted("TrainerFanClub.setPlayerGotFirstFans"); },
};
export default TrainerFanClub;
