// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/trainer_sight.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const TrainerSight: Record<string, any> = {
  twoTrainerApproach: undefined,
  getTrainerId: (..._a: any[]): any => { return notPorted("TrainerSight.getTrainerId"); },
  isTrainerType: (..._a: any[]): any => { return notPorted("TrainerSight.isTrainerType"); },
  isDefeated: (..._a: any[]): any => { return notPorted("TrainerSight.isDefeated"); },
  battleType: (..._a: any[]): any => { return notPorted("TrainerSight.battleType"); },
  blockedByDoubles: (..._a: any[]): any => { return notPorted("TrainerSight.blockedByDoubles"); },
  checkLineOfSight: (..._a: any[]): any => { return notPorted("TrainerSight.checkLineOfSight"); },
  revealBuried: (..._a: any[]): any => { return notPorted("TrainerSight.revealBuried"); },
  revealDisguise: (..._a: any[]): any => { return notPorted("TrainerSight.revealDisguise"); },
  revealThen: (..._a: any[]): any => { return notPorted("TrainerSight.revealThen"); },
  encounterMusic: (..._a: any[]): any => { return notPorted("TrainerSight.encounterMusic"); },
  engage: (..._a: any[]): any => { return notPorted("TrainerSight.engage"); },
  engagePair: (..._a: any[]): any => { return notPorted("TrainerSight.engagePair"); },
  check: (..._a: any[]): any => { return notPorted("TrainerSight.check"); },
};
export default TrainerSight;
