// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/virtual_objects.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const VirtualObjects: Record<string, any> = {
  DIR_SOUTH: undefined,
  spawn: (..._a: any[]): any => { return notPorted("VirtualObjects.spawn"); },
  turn: (..._a: any[]): any => { return notPorted("VirtualObjects.turn"); },
  remove: (..._a: any[]): any => { return notPorted("VirtualObjects.remove"); },
  get: (..._a: any[]): any => { return notPorted("VirtualObjects.get"); },
  list: (..._a: any[]): any => { return notPorted("VirtualObjects.list"); },
  slots: (..._a: any[]): any => { return notPorted("VirtualObjects.slots"); },
  nth: (..._a: any[]): any => { return notPorted("VirtualObjects.nth"); },
  count: (..._a: any[]): any => { return notPorted("VirtualObjects.count"); },
  clear: (..._a: any[]): any => { return notPorted("VirtualObjects.clear"); },
  reset: (..._a: any[]): any => { return notPorted("VirtualObjects.reset"); },
};
export default VirtualObjects;
