// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/adapter.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Adapter: Record<string, any> = {
  normStatus: undefined,
  ABILITY_BY_ID: undefined,
  idOf: undefined,
  fill: (..._a: any[]): any => { return notPorted("Adapter.fill"); },
  new: (..._a: any[]): any => { return notPorted("Adapter.new"); },
};
export default Adapter;
