// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/ai_items.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const AiItems: Record<string, any> = {
  TYPE: undefined,
  ITEM_FULL_RESTORE: undefined,
  HEAL_HP_FULL: undefined,
  HEAL_HP_HALF: undefined,
  HEAL_HP_LVL_UP: undefined,
  band: undefined,
  itemNum: undefined,
  statusName: undefined,
  effect: (..._a: any[]): any => { return notPorted("AiItems.effect"); },
  itemType: (..._a: any[]): any => { return notPorted("AiItems.itemType"); },
  hpParam: (..._a: any[]): any => { return notPorted("AiItems.hpParam"); },
  history: (..._a: any[]): any => { return notPorted("AiItems.history"); },
  shouldUseItem: (..._a: any[]): any => { return notPorted("AiItems.shouldUseItem"); },
};
export default AiItems;
