// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/ai_switch.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const AiSwitch: Record<string, any> = {
  aiTypeCalc: undefined,
  shouldSwitch: (..._a: any[]): any => { return notPorted("AiSwitch.shouldSwitch"); },
  trySwitch: (..._a: any[]): any => { return notPorted("AiSwitch.trySwitch"); },
};
export default AiSwitch;
