// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/ai_vm.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const AiVm: Record<string, any> = {
  resolve_move_id: undefined,
  new: (..._a: any[]): any => { return notPorted("AiVm.new"); },
  run: (..._a: any[]): any => { return notPorted("AiVm.run"); },
};
export default AiVm;
