// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/anim_sprites.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const AnimSprites: Record<string, any> = {
  MAX: undefined,
  Z: undefined,
  RESET_KEYS: undefined,
  slotZ: (..._a: any[]): any => { return notPorted("AnimSprites.slotZ"); },
  init: (..._a: any[]): any => { return notPorted("AnimSprites.init"); },
  reset: (..._a: any[]): any => { return notPorted("AnimSprites.reset"); },
  clearHost: (..._a: any[]): any => { return notPorted("AnimSprites.clearHost"); },
  acquire: (..._a: any[]): any => { return notPorted("AnimSprites.acquire"); },
  release: (..._a: any[]): any => { return notPorted("AnimSprites.release"); },
  activeCount: (..._a: any[]): any => { return notPorted("AnimSprites.activeCount"); },
  forEachActive: (..._a: any[]): any => { return notPorted("AnimSprites.forEachActive"); },
  update: (..._a: any[]): any => { return notPorted("AnimSprites.update"); },
  sortedDrawList: (..._a: any[]): any => { return notPorted("AnimSprites.sortedDrawList"); },
};
export default AnimSprites;
