// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/anim_seq.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const AnimSeq: Record<string, any> = {
  _steps: undefined,
  _i: undefined,
  _waiting: undefined,
  _waitingMsg: undefined,
  _waitFrames: undefined,
  _waitSwitch: undefined,
  _pushMsg: undefined,
  _pendingEff: undefined,
  _scene: undefined,
  _ended: undefined,
  _subLowered: undefined,
  reset: (..._a: any[]): any => { return notPorted("AnimSeq.reset"); },
  busy: (..._a: any[]): any => { return notPorted("AnimSeq.busy"); },
  ended: (..._a: any[]): any => { return notPorted("AnimSeq.ended"); },
  isMoveUsedId: (..._a: any[]): any => { return notPorted("AnimSeq.isMoveUsedId"); },
  buildSteps: (..._a: any[]): any => { return notPorted("AnimSeq.buildSteps"); },
  begin: (..._a: any[]): any => { return notPorted("AnimSeq.begin"); },
  beginEvents: (..._a: any[]): any => { return notPorted("AnimSeq.beginEvents"); },
  tickHitSe: (..._a: any[]): any => { return notPorted("AnimSeq.tickHitSe"); },
  update: (..._a: any[]): any => { return notPorted("AnimSeq.update"); },
};
export default AnimSeq;
