// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/ball_open.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const BallOpen: Record<string, any> = {
  CACHE_SUB: undefined,
  _data: undefined,
  _image: undefined,
  _quads: undefined,
  _shader: undefined,
  sin: undefined,
  cos: undefined,
  beginFade: undefined,
  animate: undefined,
  reset: (..._a: any[]): any => { return notPorted("BallOpen.reset"); },
  ballIdForItem: (..._a: any[]): any => { return notPorted("BallOpen.ballIdForItem"); },
  setData: (..._a: any[]): any => { return notPorted("BallOpen.setData"); },
  data: (..._a: any[]): any => { return notPorted("BallOpen.data"); },
  blend5: (..._a: any[]): any => { return notPorted("BallOpen.blend5"); },
  start: (..._a: any[]): any => { return notPorted("BallOpen.start"); },
  startParticles: (..._a: any[]): any => { return notPorted("BallOpen.startParticles"); },
  addSprite: (..._a: any[]): any => { return notPorted("BallOpen.addSprite"); },
  spawnSprite: (..._a: any[]): any => { return notPorted("BallOpen.spawnSprite"); },
  tick: (..._a: any[]): any => { return notPorted("BallOpen.tick"); },
  active: (..._a: any[]): any => { return notPorted("BallOpen.active"); },
  particleCount: (..._a: any[]): any => { return notPorted("BallOpen.particleCount"); },
  particles: (..._a: any[]): any => { return notPorted("BallOpen.particles"); },
  bgCoeff: (..._a: any[]): any => { return notPorted("BallOpen.bgCoeff"); },
  fadeActive: (..._a: any[]): any => { return notPorted("BallOpen.fadeActive"); },
  monBlend: (..._a: any[]): any => { return notPorted("BallOpen.monBlend"); },
  setBlendShader: (..._a: any[]): any => { return notPorted("BallOpen.setBlendShader"); },
  draw: (..._a: any[]): any => { return notPorted("BallOpen.draw"); },
};
export default BallOpen;
