// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/bg.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const BattleBg: Record<string, any> = {
  _terrainId: undefined,
  _sheets: undefined,
  env: (..._a: any[]): any => { return notPorted("BattleBg.env"); },
  resolveFromMapKind: (..._a: any[]): any => { return notPorted("BattleBg.resolveFromMapKind"); },
  resolveFromBehavior: (..._a: any[]): any => { return notPorted("BattleBg.resolveFromBehavior"); },
  resolveOverride: (..._a: any[]): any => { return notPorted("BattleBg.resolveOverride"); },
  setTerrain: (..._a: any[]): any => { return notPorted("BattleBg.setTerrain"); },
  terrainId: (..._a: any[]): any => { return notPorted("BattleBg.terrainId"); },
  availableSheets: (..._a: any[]): any => { return notPorted("BattleBg.availableSheets"); },
  setAvailableSheets: (..._a: any[]): any => { return notPorted("BattleBg.setAvailableSheets"); },
  sheetKey: (..._a: any[]): any => { return notPorted("BattleBg.sheetKey"); },
  draw: (..._a: any[]): any => { return notPorted("BattleBg.draw"); },
};
export default BattleBg;
