// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/capabilities.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Capabilities: Record<string, any> = {
  get: (..._a: any[]): any => { return notPorted("Capabilities.get"); },
};
export default Capabilities;
