// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/catch_seq.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const CatchSeq: Record<string, any> = {
  _steps: undefined,
  _i: undefined,
  _waiting: undefined,
  _waitingMsg: undefined,
  _pushMsg: undefined,
  _headless: undefined,
  _result: undefined,
  _st: undefined,
  _session: undefined,
  _ballId: undefined,
  _caught: undefined,
  _shakes: undefined,
  startBall: undefined,
  reset: (..._a: any[]): any => { return notPorted("CatchSeq.reset"); },
  busy: (..._a: any[]): any => { return notPorted("CatchSeq.busy"); },
  result: (..._a: any[]): any => { return notPorted("CatchSeq.result"); },
  catchResult: (..._a: any[]): any => { return notPorted("CatchSeq.catchResult"); },
  begin: (..._a: any[]): any => { return notPorted("CatchSeq.begin"); },
  update: (..._a: any[]): any => { return notPorted("CatchSeq.update"); },
};
export default CatchSeq;
