// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/catching.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Catching: Record<string, any> = {
  BALL_BONUS: undefined,
  targetFor: (..._a: any[]): any => { return notPorted("Catching.targetFor"); },
  isBall: (..._a: any[]): any => { return notPorted("Catching.isBall"); },
  ballMultiplier: (..._a: any[]): any => { return notPorted("Catching.ballMultiplier"); },
  catchOdds: (..._a: any[]): any => { return notPorted("Catching.catchOdds"); },
  tryCatch: (..._a: any[]): any => { return notPorted("Catching.tryCatch"); },
  playerSecretId: (..._a: any[]): any => { return notPorted("Catching.playerSecretId"); },
  storeCaught: (..._a: any[]): any => { return notPorted("Catching.storeCaught"); },
  givePending: (..._a: any[]): any => { return notPorted("Catching.givePending"); },
};
export default Catching;
