// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/evo_seq.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const EvoSeq: Record<string, any> = {
  _steps: undefined,
  _i: undefined,
  _waiting: undefined,
  _pushMsg: undefined,
  _askYesNo: undefined,
  _askForget: undefined,
  _headless: undefined,
  _session: undefined,
  reset: (..._a: any[]): any => { return notPorted("EvoSeq.reset"); },
  busy: (..._a: any[]): any => { return notPorted("EvoSeq.busy"); },
  begin: (..._a: any[]): any => { return notPorted("EvoSeq.begin"); },
  update: (..._a: any[]): any => { return notPorted("EvoSeq.update"); },
};
export default EvoSeq;
