// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/held_items.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const HeldItems: Record<string, any> = {
  HOLD: undefined,
  TYPE_BOOST: undefined,
  flavorRelation: (..._a: any[]): any => { return notPorted("HeldItems.flavorRelation"); },
  effectOf: (..._a: any[]): any => { return notPorted("HeldItems.effectOf"); },
  itemOf: (..._a: any[]): any => { return notPorted("HeldItems.itemOf"); },
  of: (..._a: any[]): any => { return notPorted("HeldItems.of"); },
  has: (..._a: any[]): any => { return notPorted("HeldItems.has"); },
  name: (..._a: any[]): any => { return notPorted("HeldItems.name"); },
  consume: (..._a: any[]): any => { return notPorted("HeldItems.consume"); },
  normal: (..._a: any[]): any => { return notPorted("HeldItems.normal"); },
  moveEnd: (..._a: any[]): any => { return notPorted("HeldItems.moveEnd"); },
  kingsRockShellBell: (..._a: any[]): any => { return notPorted("HeldItems.kingsRockShellBell"); },
  onSwitchIn: (..._a: any[]): any => { return notPorted("HeldItems.onSwitchIn"); },
  rollFocusBand: (..._a: any[]): any => { return notPorted("HeldItems.rollFocusBand"); },
  focusBandMessage: (..._a: any[]): any => { return notPorted("HeldItems.focusBandMessage"); },
};
export default HeldItems;
