// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/intro_seq.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const IntroSeq: Record<string, any> = {
  _steps: undefined,
  _i: undefined,
  _waiting: undefined,
  _pushMsg: undefined,
  _headless: undefined,
  _opts: undefined,
  _st: undefined,
  releaseCryMode: undefined,
  reset: (..._a: any[]): any => { return notPorted("IntroSeq.reset"); },
  busy: (..._a: any[]): any => { return notPorted("IntroSeq.busy"); },
  introText: (..._a: any[]): any => { return notPorted("IntroSeq.introText"); },
  headlessGhostIntro: (..._a: any[]): any => { return notPorted("IntroSeq.headlessGhostIntro"); },
  sendOutText: (..._a: any[]): any => { return notPorted("IntroSeq.sendOutText"); },
  multiTrainerPics: (..._a: any[]): any => { return notPorted("IntroSeq.multiTrainerPics"); },
  begin: (..._a: any[]): any => { return notPorted("IntroSeq.begin"); },
  update: (..._a: any[]): any => { return notPorted("IntroSeq.update"); },
};
export default IntroSeq;
