// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/kinds.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Kinds: Record<string, any> = {
  fromOpts: (..._a: any[]): any => { return notPorted("Kinds.fromOpts"); },
  has: (..._a: any[]): any => { return notPorted("Kinds.has"); },
  isBirchFirstBattle: (..._a: any[]): any => { return notPorted("Kinds.isBirchFirstBattle"); },
  isWallyTutorial: (..._a: any[]): any => { return notPorted("Kinds.isWallyTutorial"); },
  noCrit: (..._a: any[]): any => { return notPorted("Kinds.noCrit"); },
  noExp: (..._a: any[]): any => { return notPorted("Kinds.noExp"); },
  controllerOf: (..._a: any[]): any => { return notPorted("Kinds.controllerOf"); },
};
export default Kinds;
