// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/move_swap.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const MoveSwap: Record<string, any> = {
  moveCount: (..._a: any[]): any => { return notPorted("MoveSwap.moveCount"); },
  canStart: (..._a: any[]): any => { return notPorted("MoveSwap.canStart"); },
  initialCursor: (..._a: any[]): any => { return notPorted("MoveSwap.initialCursor"); },
  step: (..._a: any[]): any => { return notPorted("MoveSwap.step"); },
  apply: (..._a: any[]): any => { return notPorted("MoveSwap.apply"); },
};
export default MoveSwap;
