// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/profile.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const BattleProfile: Record<string, any> = {
  DEFAULTS: undefined,
  forRow: (..._a: any[]): any => { return notPorted("BattleProfile.forRow"); },
  get: (..._a: any[]): any => { return notPorted("BattleProfile.get"); },
  withHostRules: (..._a: any[]): any => { return notPorted("BattleProfile.withHostRules"); },
  of: (..._a: any[]): any => { return notPorted("BattleProfile.of"); },
  isRse: (..._a: any[]): any => { return notPorted("BattleProfile.isRse"); },
  aiBit: (..._a: any[]): any => { return notPorted("BattleProfile.aiBit"); },
  aiFlags: (..._a: any[]): any => { return notPorted("BattleProfile.aiFlags"); },
  rule: (..._a: any[]): any => { return notPorted("BattleProfile.rule"); },
  constants: (..._a: any[]): any => { return notPorted("BattleProfile.constants"); },
  song: (..._a: any[]): any => { return notPorted("BattleProfile.song"); },
  classNameOf: (..._a: any[]): any => { return notPorted("BattleProfile.classNameOf"); },
  battleSong: (..._a: any[]): any => { return notPorted("BattleProfile.battleSong"); },
  victorySong: (..._a: any[]): any => { return notPorted("BattleProfile.victorySong"); },
  reset: (..._a: any[]): any => { return notPorted("BattleProfile.reset"); },
};
export default BattleProfile;
