// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/residual_handlers.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Handlers: Record<string, any> = {
  _installed: undefined,
  tickWeather: (..._a: any[]): any => { return notPorted("Handlers.tickWeather"); },
  registerAll: (..._a: any[]): any => { return notPorted("Handlers.registerAll"); },
  futureSightDoubles: (..._a: any[]): any => { return notPorted("Handlers.futureSightDoubles"); },
  futureSightHit: (..._a: any[]): any => { return notPorted("Handlers.futureSightHit"); },
};
export default Handlers;
