// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/rules.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Rules: Record<string, any> = {
  FIELD_PHASES_ORDER: undefined,
  BATTLER_PHASES_ORDER: undefined,
  POST_PHASES_ORDER: undefined,
  FAINT_HALT_PHASES: undefined,
  partialTrap: undefined,
  safari: undefined,
  weather: undefined,
  crit: undefined,
  ACCURACY_STAGE: undefined,
  substitute: undefined,
  shouldHaltBattlerOnFaint: (..._a: any[]): any => { return notPorted("Rules.shouldHaltBattlerOnFaint"); },
};
export default Rules;
