// @gen3-stub
// Not ported yet: gen1recomp src/core/game3/battle/status.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Status: Record<string, any> = {
  set: (..._a: any[]): any => { return notPorted("Status.set"); },
  clear: (..._a: any[]): any => { return notPorted("Status.clear"); },
  tickChip: (..._a: any[]): any => { return notPorted("Status.tickChip"); },
};
export default Status;
