#!/usr/bin/env python3
"""Write voxelmon/game/gen3/core/require_map.ts: every PORTED gen3 runtime
module by its Lua name (from the `// Port of gen1recomp src/<path>.lua`
header), as a lazy getter -- so a port's "module not in the port" helper
(written before its target existed) finds it once it does. Stubs are left
out: their require still fails, as Brian's failed-require path.

usage: python3 tools/gen3/gen_require_map.py   (in WSL)
"""
import os
import re

ROOT = os.path.expanduser("~/pocket-voxel/voxelmon/game/gen3")
OUT = os.path.join(ROOT, "core", "require_map.ts")
HDR = re.compile(r"^// Port of gen1recomp (src/[A-Za-z0-9_/.-]+?)\.lua")

entries = []
for d, _, fs in os.walk(ROOT):
    for f in sorted(fs):
        if not f.endswith(".ts"):
            continue
        p = os.path.join(d, f)
        if p == OUT:
            continue
        with open(p, encoding="utf-8", errors="replace") as fh:
            head = fh.read(400)
        if "@gen3-stub" in head.splitlines()[0] if head else True:
            continue
        m = HDR.match(head)
        if not m:
            continue
        src = open(p, encoding="utf-8", errors="replace").read()
        if not re.search(r"^export default ", src, re.M):
            continue
        lua = m.group(1)
        if lua.endswith("/init"):
            lua = lua[: -len("/init")]
        name = lua.replace("/", ".")
        rel = os.path.relpath(p, os.path.dirname(OUT)).replace(os.sep, "/")
        if not rel.startswith("."):
            rel = "./" + rel
        entries.append((name, rel))

entries.sort()
seen = set()
lines = [
    "// pocket-voxel runtime glue for the gen3 (FireRed) port (GPLv3 + additional",
    "// terms; see LICENSE.md). GENERATED by tools/gen3/gen_require_map.py -- do not edit.",
    "// Every ported runtime module by its Lua name, for the helpers a port wrote",
    "// for `require(name)` of a module that had no file yet: once the module is",
    "// ported, requireLua(name) returns it. Getters, so nothing is read at load",
    "// (the import cycle). Lazily-registered modules (G3Lazy) are found too.",
    "",
    'import { G3Lazy } from "./lazy_registry.ts";',
]
getters = []
for i, (name, rel) in enumerate(entries):
    if name in seen:
        continue
    seen.add(name)
    ident = f"m{i}"
    lines.append(f'import {ident} from "{rel}";')
    getters.append(f'  "{name}": () => {ident},')
lines += [
    "",
    "const MAP: Record<string, () => unknown> = {",
    *getters,
    "};",
    "",
    "/** The ported module for a Lua module name, or undefined (not in the port). */",
    "export function requireLua(name: string): any {",
    "  const lazy = G3Lazy[name];",
    "  if (lazy != null) return lazy;",
    "  const get = MAP[name];",
    "  return get ? get() : undefined;",
    "}",
    "",
    "export default requireLua;",
    "",
]
with open(OUT, "w", encoding="utf-8", newline="") as fh:
    fh.write("\n".join(lines))
print(f"require_map.ts: {len(seen)} modules")
