-- Port tooling (GPLv3 + additional terms; see voxelmon/import/gen3/LICENSE.md).
-- Converts one of gen1recomp's generated DATA modules (a Lua module whose
-- value is plain tables of numbers, strings and booleans) into a TypeScript
-- module, mechanically, so 15k lines of tables are never hand-copied:
--
--   cd ~/gen1recomp-latest
--   luajit /home/isaac/pocket-voxel/tools/gen3/lua2ts.lua MODULE OUT.ts [--skip-functions] [--field NAME]
--
-- Shapes follow the gen2 importer's rule (voxelmon/import/writer.ts): a table
-- whose keys are exactly 1..n becomes a 0-based array; every other table
-- becomes an object (numeric keys stay numeric literals). Keys are sorted
-- (numbers ascending, then strings) so the output is deterministic.
-- `--field NAME` converts only that field of the module's table.
-- `--objects` keeps every integer-keyed table an object with Lua's keys, for
-- tables code indexes by game id (constants byId, address maps).
package.path = "./?.lua;./?/init.lua;" .. package.path
local modName, outPath = arg[1], arg[2]
assert(modName and outPath, "usage: lua2ts.lua MODULE OUT.ts [--skip-functions] [--field NAME]")
local skipFunctions, field, objectsOnly = false, nil, false
local i = 3
while arg[i] do
  if arg[i] == "--skip-functions" then skipFunctions = true; i = i + 1
  elseif arg[i] == "--field" then field = arg[i + 1]; i = i + 2
  elseif arg[i] == "--objects" then objectsOnly = true; i = i + 1
  else error("unknown option " .. arg[i]) end
end

local value = require(modName)
if field then value = value[field] end

local function isIdent(s)
  return type(s) == "string" and s:match("^[%a_$][%w_$]*$") ~= nil
end

local function quote(s)
  return '"' .. s:gsub('[%z\1-\31\\"\127-\255]', function(c)
    local b = c:byte()
    if c == "\\" then return "\\\\" end
    if c == '"' then return '\\"' end
    if c == "\n" then return "\\n" end
    if c == "\r" then return "\\r" end
    if c == "\t" then return "\\t" end
    -- the port keeps Lua strings as byte strings: every byte one char
    return string.format("\\x%02x", b)
  end) .. '"'
end

local function num(v)
  if v ~= v then error("NaN in data") end
  if v == math.huge then return "Infinity" end
  if v == -math.huge then return "-Infinity" end
  if v % 1 == 0 and math.abs(v) < 2 ^ 53 then return string.format("%d", v) end
  return string.format("%.17g", v)
end

local function isArray(t)
  -- --objects: integer keys stay Lua's keys (t[1] stays t[1]); no 0-based arrays
  if objectsOnly then return false end
  local count, maximum = 0, 0
  for k in pairs(t) do
    if type(k) ~= "number" or k < 1 or k % 1 ~= 0 then return false end
    count = count + 1
    if k > maximum then maximum = k end
  end
  return count == maximum and count > 0
end

local function sortedKeys(t)
  local nums, strs, other = {}, {}, {}
  for k, v in pairs(t) do
    if type(v) == "function" then
      if not skipFunctions then error("function at key " .. tostring(k) .. " (use --skip-functions)") end
    elseif type(k) == "number" then nums[#nums + 1] = k
    elseif type(k) == "string" then strs[#strs + 1] = k
    else other[#other + 1] = k end
  end
  if #other > 0 then error("non-string, non-number key: " .. tostring(other[1])) end
  table.sort(nums)
  table.sort(strs)
  return nums, strs
end

local seen = {}
local out = {}
local function emit(v, indent)
  local t = type(v)
  if t == "number" then out[#out + 1] = num(v)
  elseif t == "string" then out[#out + 1] = quote(v)
  elseif t == "boolean" then out[#out + 1] = tostring(v)
  elseif t == "table" then
    if seen[v] then error("shared or cyclic table") end
    seen[v] = true
    local pad = string.rep("  ", indent + 1)
    if isArray(v) then
      out[#out + 1] = "["
      for j = 1, #v do
        out[#out + 1] = "\n" .. pad
        emit(v[j], indent + 1)
        out[#out + 1] = ","
      end
      out[#out + 1] = "\n" .. string.rep("  ", indent) .. "]"
    else
      local nums, strs = sortedKeys(v)
      if #nums + #strs == 0 then out[#out + 1] = "{}"; seen[v] = nil; return end
      out[#out + 1] = "{"
      for _, k in ipairs(nums) do
        out[#out + 1] = "\n" .. pad .. num(k) .. ": "
        emit(v[k], indent + 1)
        out[#out + 1] = ","
      end
      for _, k in ipairs(strs) do
        out[#out + 1] = "\n" .. pad .. (isIdent(k) and k or quote(k)) .. ": "
        emit(v[k], indent + 1)
        out[#out + 1] = ","
      end
      out[#out + 1] = "\n" .. string.rep("  ", indent) .. "}"
    end
    seen[v] = nil
  else
    error("unsupported value type " .. t)
  end
end

emit(value, 0)
local f = assert(io.open(outPath, "w"))
f:write("// GENERATED by tools/gen3/lua2ts.lua from gen1recomp ", modName:gsub("%.", "/"), ".lua",
  field and (" (field " .. field .. ")") or "", ".\n")
f:write("// Port of gen1recomp data (GPLv3 + additional terms; see LICENSE.md). Do not edit.\n")
f:write("/* eslint-disable */\n")
f:write("const data = ", table.concat(out), ";\nexport default data;\n")
f:close()
print("wrote " .. outPath)
