// @gen2-stub
// Not ported yet: gen1recomp src/battle/gen2/Ai.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Ai: Record<string, any> = {
  FLAGS: undefined,
  BASE_SCORE: undefined,
  BASE_SWITCH_SCORE: undefined,
  STALL_EFFECTS: undefined,
  RESIDUAL_EFFECTS: undefined,
  STAT_UP_EFFECTS: undefined,
  STAT_DOWN_EFFECTS: undefined,
  STATUS_EFFECTS: undefined,
  SMART: undefined,
  LOCK_ON_ACCURACY: undefined,
  SWITCH_FLAGS: undefined,
  SWITCH_CHANCES: undefined,
  ITEM_ORDER: undefined,
  HEAL_ITEMS: undefined,
  LAYERS: undefined,
  LAYER_ORDER: undefined,
  flagsOf: (..._a: any[]): any => notPorted("Ai.flagsOf"),
  has: (..._a: any[]): any => notPorted("Ai.has"),
  lockOnPostPass: (..._a: any[]): any => notPorted("Ai.lockOnPostPass"),
  switchFlagsOf: (..._a: any[]): any => notPorted("Ai.switchFlagsOf"),
  switchScore: (..._a: any[]): any => notPorted("Ai.switchScore"),
  shouldSwitch: (..._a: any[]): any => notPorted("Ai.shouldSwitch"),
  chooseItem: (..._a: any[]): any => notPorted("Ai.chooseItem"),
  registerInto: (..._a: any[]): any => notPorted("Ai.registerInto"),
  classFor: (..._a: any[]): any => notPorted("Ai.classFor"),
  layersFor: (..._a: any[]): any => notPorted("Ai.layersFor"),
  choose: (..._a: any[]): any => notPorted("Ai.choose"),
};
export default Ai;
