// @gen2-stub
// Not ported yet: gen1recomp src/battle/gen2/AnimRunner.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const AnimRunner: Record<string, any> = {
  COMMANDS: undefined,
  NUM_TILEDICT_ENTRIES: undefined,
  MAX_ANIM_TILES: undefined,
  BATTLER_TILES: undefined,
  new: (..._a: any[]): any => notPorted("AnimRunner.new"),
  scriptForMove: (..._a: any[]): any => notPorted("AnimRunner.scriptForMove"),
};
export default AnimRunner;
