// @gen2-stub
// Not ported yet: gen1recomp src/battle/gen2/HpBar.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const HpBar: Record<string, any> = {
  LENGTH_TILES: undefined,
  TILE_WIDTH: undefined,
  LENGTH_PX: undefined,
  CHANNEL_PX: undefined,
  GREEN_PIXELS: undefined,
  YELLOW_PIXELS: undefined,
  pixels: (..._a: any[]): any => notPorted("HpBar.pixels"),
  palette: (..._a: any[]): any => notPorted("HpBar.palette"),
  paletteFor: (..._a: any[]): any => notPorted("HpBar.paletteFor"),
  colors: (..._a: any[]): any => notPorted("HpBar.colors"),
  draw: (..._a: any[]): any => notPorted("HpBar.draw"),
  drawWithLabel: (..._a: any[]): any => notPorted("HpBar.drawWithLabel"),
  drawExp: (..._a: any[]): any => notPorted("HpBar.drawExp"),
  stepToward: (..._a: any[]): any => notPorted("HpBar.stepToward"),
  shortFrameHp: (..._a: any[]): any => notPorted("HpBar.shortFrameHp"),
  newAnim: (..._a: any[]): any => notPorted("HpBar.newAnim"),
  animStep: (..._a: any[]): any => notPorted("HpBar.animStep"),
  expFraction: (..._a: any[]): any => notPorted("HpBar.expFraction"),
};
export default HpBar;
