// @gen2-stub
// Not ported yet: gen1recomp src/battle/gen2/Prize.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Prize: Record<string, any> = {
  MAX_MONEY: undefined,
  AMULET_COIN: undefined,
  QUARTERS: undefined,
  reward: (..._a: any[]): any => notPorted("Prize.reward"),
  rewardLevel: (..._a: any[]): any => notPorted("Prize.rewardLevel"),
  savingMode: (..._a: any[]): any => notPorted("Prize.savingMode"),
  award: (..._a: any[]): any => notPorted("Prize.award"),
  message: (..._a: any[]): any => notPorted("Prize.message"),
  payDay: (..._a: any[]): any => notPorted("Prize.payDay"),
  payDayMessage: (..._a: any[]): any => notPorted("Prize.payDayMessage"),
};
export default Prize;
