// @gen3-stub
// Deferred (link/online; not in the first FireRed release): gen1recomp src/sync/SyncClient.lua (GPLv3 + additional terms; see LICENSE.md).
// Generated by tools/gen3/stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class SyncClient {
  [key: string]: any;
  static [key: string]: any;
  static DEFAULT_URL: any = undefined;
  static MAX_BLOB: any = undefined;
  static MAX_RESPONSE: any = undefined;
  static TIMEOUT: any = undefined;
  static normalizeCode(..._a: any[]): any { return notPorted("SyncClient.normalizeCode"); }
  static formatCode(..._a: any[]): any { return notPorted("SyncClient.formatCode"); }
  static new(..._a: any[]): any { return notPorted("SyncClient.new"); }
  setAuth(..._a: any[]): any { return notPorted("SyncClient:setAuth"); }
  clearAuth(..._a: any[]): any { return notPorted("SyncClient:clearAuth"); }
  isLinked(..._a: any[]): any { return notPorted("SyncClient:isLinked"); }
  send(..._a: any[]): any { return notPorted("SyncClient:send"); }
  poll(..._a: any[]): any { return notPorted("SyncClient:poll"); }
  release(..._a: any[]): any { return notPorted("SyncClient:release"); }
  create(..._a: any[]): any { return notPorted("SyncClient:create"); }
  link(..._a: any[]): any { return notPorted("SyncClient:link"); }
  fetchState(..._a: any[]): any { return notPorted("SyncClient:fetchState"); }
  putSave(..._a: any[]): any { return notPorted("SyncClient:putSave"); }
  getSave(..._a: any[]): any { return notPorted("SyncClient:getSave"); }
  deleteSave(..._a: any[]): any { return notPorted("SyncClient:deleteSave"); }
  putMods(..._a: any[]): any { return notPorted("SyncClient:putMods"); }
  getMods(..._a: any[]): any { return notPorted("SyncClient:getMods"); }
  shareMods(..._a: any[]): any { return notPorted("SyncClient:shareMods"); }
  fetchShare(..._a: any[]): any { return notPorted("SyncClient:fetchShare"); }
  lobbyTicket(..._a: any[]): any { return notPorted("SyncClient:lobbyTicket"); }
  setDisplayName(..._a: any[]): any { return notPorted("SyncClient:setDisplayName"); }
  reissueCodes(..._a: any[]): any { return notPorted("SyncClient:reissueCodes"); }
  unlink(..._a: any[]): any { return notPorted("SyncClient:unlink"); }
}
export default SyncClient;
