// GENERATED by tools/gen3/lua2ts.lua from gen1recomp src/core/game3/constants/firered/script_cmds.lua.
// Port of gen1recomp data (GPLv3 + additional terms; see LICENSE.md). Do not edit.
/* eslint-disable */
const data = {
  byId: {
    0: {
      args: {},
      handler: "ScrCmd_nop",
      name: "nop",
      size: 1,
    },
    1: {
      args: {},
      handler: "ScrCmd_nop1",
      name: "nop1",
      size: 1,
    },
    2: {
      args: {},
      handler: "ScrCmd_end",
      name: "end",
      size: 1,
    },
    3: {
      args: {},
      handler: "ScrCmd_return",
      name: "return",
      size: 1,
    },
    4: {
      args: {
        1: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_call",
      name: "call",
      size: 5,
    },
    5: {
      args: {
        1: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_goto",
      name: "goto",
      size: 5,
    },
    6: {
      args: {
        1: {
          kind: "byte",
          name: "condition",
        },
        2: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_goto_if",
      name: "goto_if",
      size: 6,
    },
    7: {
      args: {
        1: {
          kind: "byte",
          name: "condition",
        },
        2: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_call_if",
      name: "call_if",
      size: 6,
    },
    8: {
      args: {
        1: {
          kind: "byte",
          name: "function",
        },
      },
      handler: "ScrCmd_gotostd",
      name: "gotostd",
      size: 2,
    },
    9: {
      args: {
        1: {
          kind: "byte",
          name: "function",
        },
      },
      handler: "ScrCmd_callstd",
      name: "callstd",
      size: 2,
    },
    10: {
      args: {
        1: {
          kind: "byte",
          name: "condition",
        },
        2: {
          kind: "byte",
          name: "function",
        },
      },
      handler: "ScrCmd_gotostd_if",
      name: "gotostd_if",
      size: 3,
    },
    11: {
      args: {
        1: {
          kind: "byte",
          name: "condition",
        },
        2: {
          kind: "byte",
          name: "function",
        },
      },
      handler: "ScrCmd_callstd_if",
      name: "callstd_if",
      size: 3,
    },
    12: {
      args: {},
      handler: "ScrCmd_returnram",
      name: "returnram",
      size: 1,
    },
    13: {
      args: {},
      handler: "ScrCmd_endram",
      name: "endram",
      size: 1,
    },
    14: {
      args: {
        1: {
          kind: "byte",
          name: "value",
        },
      },
      handler: "ScrCmd_setmysteryeventstatus",
      name: "setmysteryeventstatus",
      size: 2,
    },
    15: {
      args: {
        1: {
          kind: "byte",
          name: "destIndex",
        },
        2: {
          kind: "word",
          name: "value",
        },
      },
      handler: "ScrCmd_loadword",
      name: "loadword",
      size: 6,
    },
    16: {
      args: {
        1: {
          kind: "byte",
          name: "destIndex",
        },
        2: {
          kind: "byte",
          name: "value",
        },
      },
      handler: "ScrCmd_loadbyte",
      name: "loadbyte",
      size: 3,
    },
    17: {
      args: {
        1: {
          kind: "byte",
          name: "value",
        },
        2: {
          kind: "word",
          name: "ptr",
        },
      },
      handler: "ScrCmd_setptr",
      name: "setptr",
      size: 6,
    },
    18: {
      args: {
        1: {
          kind: "byte",
          name: "destIndex",
        },
        2: {
          kind: "word",
          name: "source",
        },
      },
      handler: "ScrCmd_loadbytefromptr",
      name: "loadbytefromptr",
      size: 6,
    },
    19: {
      args: {
        1: {
          kind: "byte",
          name: "srcIndex",
        },
        2: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_setptrbyte",
      name: "setptrbyte",
      size: 6,
    },
    20: {
      args: {
        1: {
          kind: "byte",
          name: "destIndex",
        },
        2: {
          kind: "byte",
          name: "srcIndex",
        },
      },
      handler: "ScrCmd_copylocal",
      name: "copylocal",
      size: 3,
    },
    21: {
      args: {
        1: {
          kind: "word",
          name: "destination",
        },
        2: {
          kind: "word",
          name: "source",
        },
      },
      handler: "ScrCmd_copybyte",
      name: "copybyte",
      size: 9,
    },
    22: {
      args: {
        1: {
          kind: "half",
          name: "destination",
        },
        2: {
          kind: "half",
          name: "value",
        },
      },
      handler: "ScrCmd_setvar",
      name: "setvar",
      size: 5,
    },
    23: {
      args: {
        1: {
          kind: "half",
          name: "destination",
        },
        2: {
          kind: "half",
          name: "value",
        },
      },
      handler: "ScrCmd_addvar",
      name: "addvar",
      size: 5,
    },
    24: {
      args: {
        1: {
          kind: "half",
          name: "destination",
        },
        2: {
          kind: "half",
          name: "value",
        },
      },
      handler: "ScrCmd_subvar",
      name: "subvar",
      size: 5,
    },
    25: {
      args: {
        1: {
          kind: "half",
          name: "destination",
        },
        2: {
          kind: "half",
          name: "source",
        },
      },
      handler: "ScrCmd_copyvar",
      name: "copyvar",
      size: 5,
    },
    26: {
      args: {
        1: {
          kind: "half",
          name: "destination",
        },
        2: {
          kind: "half",
          name: "source",
        },
      },
      handler: "ScrCmd_setorcopyvar",
      name: "setorcopyvar",
      size: 5,
    },
    27: {
      args: {
        1: {
          kind: "byte",
          name: "local1",
        },
        2: {
          kind: "byte",
          name: "local2",
        },
      },
      handler: "ScrCmd_compare_local_to_local",
      name: "compare_local_to_local",
      size: 3,
    },
    28: {
      args: {
        1: {
          kind: "byte",
          name: "local",
        },
        2: {
          kind: "byte",
          name: "value",
        },
      },
      handler: "ScrCmd_compare_local_to_value",
      name: "compare_local_to_value",
      size: 3,
    },
    29: {
      args: {
        1: {
          kind: "byte",
          name: "local",
        },
        2: {
          kind: "word",
          name: "ptr",
        },
      },
      handler: "ScrCmd_compare_local_to_ptr",
      name: "compare_local_to_ptr",
      size: 6,
    },
    30: {
      args: {
        1: {
          kind: "word",
          name: "ptr",
        },
        2: {
          kind: "byte",
          name: "local",
        },
      },
      handler: "ScrCmd_compare_ptr_to_local",
      name: "compare_ptr_to_local",
      size: 6,
    },
    31: {
      args: {
        1: {
          kind: "word",
          name: "ptr",
        },
        2: {
          kind: "byte",
          name: "value",
        },
      },
      handler: "ScrCmd_compare_ptr_to_value",
      name: "compare_ptr_to_value",
      size: 6,
    },
    32: {
      args: {
        1: {
          kind: "word",
          name: "ptr1",
        },
        2: {
          kind: "word",
          name: "ptr2",
        },
      },
      handler: "ScrCmd_compare_ptr_to_ptr",
      name: "compare_ptr_to_ptr",
      size: 9,
    },
    33: {
      args: {
        1: {
          kind: "half",
          name: "var",
        },
        2: {
          kind: "half",
          name: "value",
        },
      },
      handler: "ScrCmd_compare_var_to_value",
      name: "compare_var_to_value",
      size: 5,
    },
    34: {
      args: {
        1: {
          kind: "half",
          name: "var1",
        },
        2: {
          kind: "half",
          name: "var2",
        },
      },
      handler: "ScrCmd_compare_var_to_var",
      name: "compare_var_to_var",
      size: 5,
    },
    35: {
      args: {
        1: {
          kind: "word",
          name: "func",
        },
      },
      handler: "ScrCmd_callnative",
      name: "callnative",
      size: 5,
    },
    36: {
      args: {
        1: {
          kind: "word",
          name: "func",
        },
      },
      handler: "ScrCmd_gotonative",
      name: "gotonative",
      size: 5,
    },
    37: {
      args: {
        1: {
          kind: "half",
          name: "SPECIAL_\\function",
        },
      },
      handler: "ScrCmd_special",
      name: "special",
      size: 3,
    },
    38: {
      args: {
        1: {
          kind: "half",
          name: "output",
        },
        2: {
          kind: "half",
          name: "SPECIAL_\\function",
        },
      },
      handler: "ScrCmd_specialvar",
      name: "specialvar",
      size: 5,
    },
    39: {
      args: {},
      handler: "ScrCmd_waitstate",
      name: "waitstate",
      size: 1,
    },
    40: {
      args: {
        1: {
          kind: "half",
          name: "frames",
        },
      },
      handler: "ScrCmd_delay",
      name: "delay",
      size: 3,
    },
    41: {
      args: {
        1: {
          kind: "half",
          name: "flag",
        },
      },
      handler: "ScrCmd_setflag",
      name: "setflag",
      size: 3,
    },
    42: {
      args: {
        1: {
          kind: "half",
          name: "flag",
        },
      },
      handler: "ScrCmd_clearflag",
      name: "clearflag",
      size: 3,
    },
    43: {
      args: {
        1: {
          kind: "half",
          name: "flag",
        },
      },
      handler: "ScrCmd_checkflag",
      name: "checkflag",
      size: 3,
    },
    44: {
      args: {
        1: {
          kind: "half",
          name: "hour",
        },
        2: {
          kind: "half",
          name: "minute",
        },
      },
      handler: "ScrCmd_initclock",
      name: "initclock",
      size: 5,
    },
    45: {
      args: {},
      handler: "ScrCmd_dotimebasedevents",
      name: "dotimebasedevents",
      size: 1,
    },
    46: {
      args: {},
      handler: "ScrCmd_gettime",
      name: "gettime",
      size: 1,
    },
    47: {
      args: {
        1: {
          kind: "half",
          name: "song",
        },
      },
      handler: "ScrCmd_playse",
      name: "playse",
      size: 3,
    },
    48: {
      args: {},
      handler: "ScrCmd_waitse",
      name: "waitse",
      size: 1,
    },
    49: {
      args: {
        1: {
          kind: "half",
          name: "song",
        },
      },
      handler: "ScrCmd_playfanfare",
      name: "playfanfare",
      size: 3,
    },
    50: {
      args: {},
      handler: "ScrCmd_waitfanfare",
      name: "waitfanfare",
      size: 1,
    },
    51: {
      args: {
        1: {
          kind: "half",
          name: "song",
        },
        2: {
          kind: "byte",
          name: "save_song",
        },
      },
      handler: "ScrCmd_playbgm",
      name: "playbgm",
      size: 4,
    },
    52: {
      args: {
        1: {
          kind: "half",
          name: "song",
        },
      },
      handler: "ScrCmd_savebgm",
      name: "savebgm",
      size: 3,
    },
    53: {
      args: {},
      handler: "ScrCmd_fadedefaultbgm",
      name: "fadedefaultbgm",
      size: 1,
    },
    54: {
      args: {
        1: {
          kind: "half",
          name: "song",
        },
      },
      handler: "ScrCmd_fadenewbgm",
      name: "fadenewbgm",
      size: 3,
    },
    55: {
      args: {
        1: {
          kind: "byte",
          name: "speed",
        },
      },
      handler: "ScrCmd_fadeoutbgm",
      name: "fadeoutbgm",
      size: 2,
    },
    56: {
      args: {
        1: {
          kind: "byte",
          name: "speed",
        },
      },
      handler: "ScrCmd_fadeinbgm",
      name: "fadeinbgm",
      size: 2,
    },
    57: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_warp",
      name: "warp",
      size: 8,
    },
    58: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_warpsilent",
      name: "warpsilent",
      size: 8,
    },
    59: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_warpdoor",
      name: "warpdoor",
      size: 8,
    },
    60: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_warphole",
      name: "warphole",
      size: 3,
    },
    61: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_warpteleport",
      name: "warpteleport",
      size: 8,
    },
    62: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_setwarp",
      name: "setwarp",
      size: 8,
    },
    63: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_setdynamicwarp",
      name: "setdynamicwarp",
      size: 8,
    },
    64: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_setdivewarp",
      name: "setdivewarp",
      size: 8,
    },
    65: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_setholewarp",
      name: "setholewarp",
      size: 8,
    },
    66: {
      args: {
        1: {
          kind: "half",
          name: "x",
        },
        2: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_getplayerxy",
      name: "getplayerxy",
      size: 5,
    },
    67: {
      args: {},
      handler: "ScrCmd_getpartysize",
      name: "getpartysize",
      size: 1,
    },
    68: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
        2: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_additem",
      name: "additem",
      size: 5,
    },
    69: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
        2: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_removeitem",
      name: "removeitem",
      size: 5,
    },
    70: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
        2: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_checkitemspace",
      name: "checkitemspace",
      size: 5,
    },
    71: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
        2: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_checkitem",
      name: "checkitem",
      size: 5,
    },
    72: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
      },
      handler: "ScrCmd_checkitemtype",
      name: "checkitemtype",
      size: 3,
    },
    73: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
        2: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_addpcitem",
      name: "addpcitem",
      size: 5,
    },
    74: {
      args: {
        1: {
          kind: "half",
          name: "itemId",
        },
        2: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_checkpcitem",
      name: "checkpcitem",
      size: 5,
    },
    75: {
      args: {
        1: {
          kind: "half",
          name: "decoration",
        },
      },
      handler: "ScrCmd_adddecoration",
      name: "adddecoration",
      size: 3,
    },
    76: {
      args: {
        1: {
          kind: "half",
          name: "decoration",
        },
      },
      handler: "ScrCmd_removedecoration",
      name: "removedecoration",
      size: 3,
    },
    77: {
      args: {
        1: {
          kind: "half",
          name: "decoration",
        },
      },
      handler: "ScrCmd_checkdecor",
      name: "checkdecor",
      size: 3,
    },
    78: {
      args: {
        1: {
          kind: "half",
          name: "decoration",
        },
      },
      handler: "ScrCmd_checkdecorspace",
      name: "checkdecorspace",
      size: 3,
    },
    79: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "word",
          name: "movements",
        },
      },
      handler: "ScrCmd_applymovement",
      name: "applymovement",
      size: 7,
    },
    80: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "word",
          name: "movements",
        },
        3: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        4: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_applymovementat",
      macro: "applymovement",
      name: "applymovementat",
      size: 9,
    },
    81: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
      },
      handler: "ScrCmd_waitmovement",
      name: "waitmovement",
      size: 3,
    },
    82: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_waitmovementat",
      macro: "waitmovement",
      name: "waitmovementat",
      size: 5,
    },
    83: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
      },
      handler: "ScrCmd_removeobject",
      name: "removeobject",
      size: 3,
    },
    84: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_removeobjectat",
      macro: "removeobject",
      name: "removeobjectat",
      size: 5,
    },
    85: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
      },
      handler: "ScrCmd_addobject",
      name: "addobject",
      size: 3,
    },
    86: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_addobjectat",
      macro: "addobject",
      name: "addobjectat",
      size: 5,
    },
    87: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "half",
          name: "x",
        },
        3: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_setobjectxy",
      name: "setobjectxy",
      size: 7,
    },
    88: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_showobjectat",
      name: "showobjectat",
      size: 5,
    },
    89: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_hideobjectat",
      name: "hideobjectat",
      size: 5,
    },
    90: {
      args: {},
      handler: "ScrCmd_faceplayer",
      name: "faceplayer",
      size: 1,
    },
    91: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "direction",
        },
      },
      handler: "ScrCmd_turnobject",
      name: "turnobject",
      size: 4,
    },
    92: {
      args: {
        1: {
          kind: "byte",
          name: "type",
        },
        2: {
          kind: "half",
          name: "trainer",
        },
        3: {
          kind: "half",
          name: "local_id",
        },
        4: {
          kind: "word",
          name: "pointer1",
        },
      },
      handler: "ScrCmd_trainerbattle",
      name: "trainerbattle",
      prefix: 10,
      variable: true,
    },
    93: {
      args: {},
      handler: "ScrCmd_dotrainerbattle",
      name: "dotrainerbattle",
      size: 1,
    },
    94: {
      args: {},
      handler: "ScrCmd_gotopostbattlescript",
      name: "gotopostbattlescript",
      size: 1,
    },
    95: {
      args: {},
      handler: "ScrCmd_gotobeatenscript",
      name: "gotobeatenscript",
      size: 1,
    },
    96: {
      args: {
        1: {
          kind: "half",
          name: "trainer",
        },
      },
      handler: "ScrCmd_checktrainerflag",
      name: "checktrainerflag",
      size: 3,
    },
    97: {
      args: {
        1: {
          kind: "half",
          name: "trainer",
        },
      },
      handler: "ScrCmd_settrainerflag",
      name: "settrainerflag",
      size: 3,
    },
    98: {
      args: {
        1: {
          kind: "half",
          name: "trainer",
        },
      },
      handler: "ScrCmd_cleartrainerflag",
      name: "cleartrainerflag",
      size: 3,
    },
    99: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "half",
          name: "x",
        },
        3: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_setobjectxyperm",
      name: "setobjectxyperm",
      size: 7,
    },
    100: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
      },
      handler: "ScrCmd_copyobjectxytoperm",
      name: "copyobjectxytoperm",
      size: 3,
    },
    101: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "movementType",
        },
      },
      handler: "ScrCmd_setobjectmovementtype",
      name: "setobjectmovementtype",
      size: 4,
    },
    102: {
      args: {},
      handler: "ScrCmd_waitmessage",
      name: "waitmessage",
      size: 1,
    },
    103: {
      args: {
        1: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_message",
      name: "message",
      size: 5,
    },
    104: {
      args: {},
      handler: "ScrCmd_closemessage",
      name: "closemessage",
      size: 1,
    },
    105: {
      args: {},
      handler: "ScrCmd_lockall",
      name: "lockall",
      size: 1,
    },
    106: {
      args: {},
      handler: "ScrCmd_lock",
      name: "lock",
      size: 1,
    },
    107: {
      args: {},
      handler: "ScrCmd_releaseall",
      name: "releaseall",
      size: 1,
    },
    108: {
      args: {},
      handler: "ScrCmd_release",
      name: "release",
      size: 1,
    },
    109: {
      args: {},
      handler: "ScrCmd_waitbuttonpress",
      name: "waitbuttonpress",
      size: 1,
    },
    110: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
      },
      handler: "ScrCmd_yesnobox",
      name: "yesnobox",
      size: 3,
    },
    111: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
        3: {
          kind: "byte",
          name: "multichoiceId",
        },
        4: {
          kind: "byte",
          name: "ignoreBPress",
        },
      },
      handler: "ScrCmd_multichoice",
      name: "multichoice",
      size: 5,
    },
    112: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
        3: {
          kind: "byte",
          name: "multichoiceId",
        },
        4: {
          kind: "byte",
          name: "default",
        },
        5: {
          kind: "byte",
          name: "ignoreBPress",
        },
      },
      handler: "ScrCmd_multichoicedefault",
      name: "multichoicedefault",
      size: 6,
    },
    113: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
        3: {
          kind: "byte",
          name: "multichoiceId",
        },
        4: {
          kind: "byte",
          name: "per_row",
        },
        5: {
          kind: "byte",
          name: "ignoreBPress",
        },
      },
      handler: "ScrCmd_multichoicegrid",
      name: "multichoicegrid",
      size: 6,
    },
    114: {
      args: {},
      handler: "ScrCmd_drawbox",
      name: "drawbox",
      size: 1,
    },
    115: {
      args: {
        1: {
          kind: "byte",
          name: "left",
        },
        2: {
          kind: "byte",
          name: "top",
        },
        3: {
          kind: "byte",
          name: "right",
        },
        4: {
          kind: "byte",
          name: "bottom",
        },
      },
      handler: "ScrCmd_erasebox",
      name: "erasebox",
      size: 5,
    },
    116: {
      args: {
        1: {
          kind: "byte",
          name: "left",
        },
        2: {
          kind: "byte",
          name: "top",
        },
        3: {
          kind: "byte",
          name: "multichoiceId",
        },
        4: {
          kind: "byte",
          name: "ignoreBPress",
        },
      },
      handler: "ScrCmd_drawboxtext",
      name: "drawboxtext",
      size: 5,
    },
    117: {
      args: {
        1: {
          kind: "half",
          name: "species",
        },
        2: {
          kind: "byte",
          name: "x",
        },
        3: {
          kind: "byte",
          name: "y",
        },
      },
      handler: "ScrCmd_showmonpic",
      name: "showmonpic",
      size: 5,
    },
    118: {
      args: {},
      handler: "ScrCmd_hidemonpic",
      name: "hidemonpic",
      size: 1,
    },
    119: {
      args: {
        1: {
          kind: "byte",
          name: "winnerId",
        },
      },
      handler: "ScrCmd_showcontestpainting",
      name: "showcontestpainting",
      size: 2,
    },
    120: {
      args: {
        1: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_braillemessage",
      name: "braillemessage",
      size: 5,
    },
    121: {
      args: {
        1: {
          kind: "half",
          name: "species",
        },
        2: {
          kind: "byte",
          name: "level",
        },
        3: {
          kind: "half",
          name: "item",
        },
        4: {
          kind: "word",
          name: "0",
        },
        5: {
          kind: "word",
          name: "0",
        },
        6: {
          kind: "byte",
          name: "0",
        },
      },
      handler: "ScrCmd_givemon",
      name: "givemon",
      size: 15,
    },
    122: {
      args: {
        1: {
          kind: "half",
          name: "species",
        },
      },
      handler: "ScrCmd_giveegg",
      name: "giveegg",
      size: 3,
    },
    123: {
      args: {
        1: {
          kind: "byte",
          name: "partyIndex",
        },
        2: {
          kind: "byte",
          name: "slot",
        },
        3: {
          kind: "half",
          name: "move",
        },
      },
      handler: "ScrCmd_setmonmove",
      name: "setmonmove",
      size: 5,
    },
    124: {
      args: {
        1: {
          kind: "half",
          name: "move",
        },
      },
      handler: "ScrCmd_checkpartymove",
      name: "checkpartymove",
      size: 3,
    },
    125: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "species",
        },
      },
      handler: "ScrCmd_bufferspeciesname",
      name: "bufferspeciesname",
      size: 4,
    },
    126: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
      },
      handler: "ScrCmd_bufferleadmonspeciesname",
      name: "bufferleadmonspeciesname",
      size: 2,
    },
    127: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "slot",
        },
      },
      handler: "ScrCmd_bufferpartymonnick",
      name: "bufferpartymonnick",
      size: 4,
    },
    128: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "item",
        },
      },
      handler: "ScrCmd_bufferitemname",
      name: "bufferitemname",
      size: 4,
    },
    129: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "decoration",
        },
      },
      handler: "ScrCmd_bufferdecorationname",
      name: "bufferdecorationname",
      size: 4,
    },
    130: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "move",
        },
      },
      handler: "ScrCmd_buffermovename",
      name: "buffermovename",
      size: 4,
    },
    131: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "input",
        },
      },
      handler: "ScrCmd_buffernumberstring",
      name: "buffernumberstring",
      size: 4,
    },
    132: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "index",
        },
      },
      handler: "ScrCmd_bufferstdstring",
      name: "bufferstdstring",
      size: 4,
    },
    133: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_bufferstring",
      name: "bufferstring",
      size: 6,
    },
    134: {
      args: {
        1: {
          kind: "word",
          name: "products",
        },
      },
      handler: "ScrCmd_pokemart",
      name: "pokemart",
      size: 5,
    },
    135: {
      args: {
        1: {
          kind: "word",
          name: "products",
        },
      },
      handler: "ScrCmd_pokemartdecoration",
      name: "pokemartdecoration",
      size: 5,
    },
    136: {
      args: {
        1: {
          kind: "word",
          name: "products",
        },
      },
      handler: "ScrCmd_pokemartdecoration2",
      name: "pokemartdecoration2",
      size: 5,
    },
    137: {
      args: {
        1: {
          kind: "half",
          name: "id",
        },
      },
      handler: "ScrCmd_playslotmachine",
      name: "playslotmachine",
      size: 3,
    },
    138: {
      args: {
        1: {
          kind: "byte",
          name: "treeId",
        },
        2: {
          kind: "byte",
          name: "berry",
        },
        3: {
          kind: "byte",
          name: "growthStage",
        },
      },
      handler: "ScrCmd_setberrytree",
      name: "setberrytree",
      size: 4,
    },
    139: {
      args: {},
      handler: "ScrCmd_choosecontestmon",
      name: "choosecontestmon",
      size: 1,
    },
    140: {
      args: {},
      handler: "ScrCmd_startcontest",
      name: "startcontest",
      size: 1,
    },
    141: {
      args: {},
      handler: "ScrCmd_showcontestresults",
      name: "showcontestresults",
      size: 1,
    },
    142: {
      args: {},
      handler: "ScrCmd_contestlinktransfer",
      name: "contestlinktransfer",
      size: 1,
    },
    143: {
      args: {
        1: {
          kind: "half",
          name: "limit",
        },
      },
      handler: "ScrCmd_random",
      name: "random",
      size: 3,
    },
    144: {
      args: {
        1: {
          kind: "word",
          name: "value",
        },
        2: {
          kind: "byte",
          name: "disable",
        },
      },
      handler: "ScrCmd_addmoney",
      name: "addmoney",
      size: 6,
    },
    145: {
      args: {
        1: {
          kind: "word",
          name: "value",
        },
        2: {
          kind: "byte",
          name: "disable",
        },
      },
      handler: "ScrCmd_removemoney",
      name: "removemoney",
      size: 6,
    },
    146: {
      args: {
        1: {
          kind: "word",
          name: "value",
        },
        2: {
          kind: "byte",
          name: "disable",
        },
      },
      handler: "ScrCmd_checkmoney",
      name: "checkmoney",
      size: 6,
    },
    147: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
        3: {
          kind: "byte",
          name: "disable",
        },
      },
      handler: "ScrCmd_showmoneybox",
      name: "showmoneybox",
      size: 4,
    },
    148: {
      args: {
        1: {
          kind: "byte",
          name: "0",
        },
        2: {
          kind: "byte",
          name: "0",
        },
      },
      handler: "ScrCmd_hidemoneybox",
      name: "hidemoneybox",
      size: 3,
    },
    149: {
      args: {
        1: {
          kind: "byte",
          name: "0",
        },
        2: {
          kind: "byte",
          name: "0",
        },
        3: {
          kind: "byte",
          name: "disable",
        },
      },
      handler: "ScrCmd_updatemoneybox",
      name: "updatemoneybox",
      size: 4,
    },
    150: {
      args: {
        1: {
          kind: "half",
          name: "newsKind",
        },
      },
      handler: "ScrCmd_getpokenewsactive",
      name: "getpokenewsactive",
      size: 3,
    },
    151: {
      args: {
        1: {
          kind: "byte",
          name: "mode",
        },
      },
      handler: "ScrCmd_fadescreen",
      name: "fadescreen",
      size: 2,
    },
    152: {
      args: {
        1: {
          kind: "byte",
          name: "mode",
        },
        2: {
          kind: "byte",
          name: "speed",
        },
      },
      handler: "ScrCmd_fadescreenspeed",
      name: "fadescreenspeed",
      size: 3,
    },
    153: {
      args: {
        1: {
          kind: "half",
          name: "level",
        },
      },
      handler: "ScrCmd_setflashlevel",
      name: "setflashlevel",
      size: 3,
    },
    154: {
      args: {
        1: {
          kind: "byte",
          name: "level",
        },
      },
      handler: "ScrCmd_animateflash",
      name: "animateflash",
      size: 2,
    },
    155: {
      args: {
        1: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_messageautoscroll",
      name: "messageautoscroll",
      size: 5,
    },
    156: {
      args: {
        1: {
          kind: "half",
          name: "animation",
        },
      },
      handler: "ScrCmd_dofieldeffect",
      name: "dofieldeffect",
      size: 3,
    },
    157: {
      args: {
        1: {
          kind: "byte",
          name: "argNum",
        },
        2: {
          kind: "half",
          name: "value",
        },
      },
      handler: "ScrCmd_setfieldeffectargument",
      name: "setfieldeffectargument",
      size: 4,
    },
    158: {
      args: {
        1: {
          kind: "half",
          name: "animation",
        },
      },
      handler: "ScrCmd_waitfieldeffect",
      name: "waitfieldeffect",
      size: 3,
    },
    159: {
      args: {
        1: {
          kind: "half",
          name: "heallocation",
        },
      },
      handler: "ScrCmd_setrespawn",
      name: "setrespawn",
      size: 3,
    },
    160: {
      args: {},
      handler: "ScrCmd_checkplayergender",
      name: "checkplayergender",
      size: 1,
    },
    161: {
      args: {
        1: {
          kind: "half",
          name: "species",
        },
        2: {
          kind: "half",
          name: "mode",
        },
      },
      handler: "ScrCmd_playmoncry",
      name: "playmoncry",
      size: 5,
    },
    162: {
      args: {
        1: {
          kind: "half",
          name: "x",
        },
        2: {
          kind: "half",
          name: "y",
        },
        3: {
          kind: "half",
          name: "metatileId",
        },
        4: {
          kind: "half",
          name: "impassable",
        },
      },
      handler: "ScrCmd_setmetatile",
      name: "setmetatile",
      size: 9,
    },
    163: {
      args: {},
      handler: "ScrCmd_resetweather",
      name: "resetweather",
      size: 1,
    },
    164: {
      args: {
        1: {
          kind: "half",
          name: "type",
        },
      },
      handler: "ScrCmd_setweather",
      name: "setweather",
      size: 3,
    },
    165: {
      args: {},
      handler: "ScrCmd_doweather",
      name: "doweather",
      size: 1,
    },
    166: {
      args: {
        1: {
          kind: "byte",
          name: "stepCbId",
        },
      },
      handler: "ScrCmd_setstepcallback",
      name: "setstepcallback",
      size: 2,
    },
    167: {
      args: {
        1: {
          kind: "half",
          name: "index",
        },
      },
      handler: "ScrCmd_setmaplayoutindex",
      name: "setmaplayoutindex",
      size: 3,
    },
    168: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        4: {
          kind: "byte",
          name: "subpriority",
        },
      },
      handler: "ScrCmd_setobjectsubpriority",
      name: "setobjectsubpriority",
      size: 6,
    },
    169: {
      args: {
        1: {
          kind: "half",
          name: "localId",
        },
        2: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        3: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
      },
      handler: "ScrCmd_resetobjectsubpriority",
      name: "resetobjectsubpriority",
      size: 5,
    },
    170: {
      args: {
        1: {
          kind: "byte",
          name: "graphicsId",
        },
        2: {
          kind: "byte",
          name: "id",
        },
        3: {
          kind: "half",
          name: "x",
        },
        4: {
          kind: "half",
          name: "y",
        },
        5: {
          kind: "byte",
          name: "elevation",
        },
        6: {
          kind: "byte",
          name: "direction",
        },
      },
      handler: "ScrCmd_createvobject",
      name: "createvobject",
      size: 9,
    },
    171: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "byte",
          name: "direction",
        },
      },
      handler: "ScrCmd_turnvobject",
      name: "turnvobject",
      size: 3,
    },
    172: {
      args: {
        1: {
          kind: "half",
          name: "x",
        },
        2: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_opendoor",
      name: "opendoor",
      size: 5,
    },
    173: {
      args: {
        1: {
          kind: "half",
          name: "x",
        },
        2: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_closedoor",
      name: "closedoor",
      size: 5,
    },
    174: {
      args: {},
      handler: "ScrCmd_waitdooranim",
      name: "waitdooranim",
      size: 1,
    },
    175: {
      args: {
        1: {
          kind: "half",
          name: "x",
        },
        2: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_setdooropen",
      name: "setdooropen",
      size: 5,
    },
    176: {
      args: {
        1: {
          kind: "half",
          name: "x",
        },
        2: {
          kind: "half",
          name: "y",
        },
      },
      handler: "ScrCmd_setdoorclosed",
      name: "setdoorclosed",
      size: 5,
    },
    177: {
      args: {
        1: {
          kind: "byte",
          name: "a",
        },
        2: {
          kind: "half",
          name: "b",
        },
        3: {
          kind: "half",
          name: "c",
        },
        4: {
          kind: "half",
          name: "d",
        },
      },
      handler: "ScrCmd_addelevmenuitem",
      name: "addelevmenuitem",
      size: 8,
    },
    178: {
      args: {},
      handler: "ScrCmd_showelevmenu",
      name: "showelevmenu",
      size: 1,
    },
    179: {
      args: {
        1: {
          kind: "half",
          name: "out",
        },
      },
      handler: "ScrCmd_checkcoins",
      name: "checkcoins",
      size: 3,
    },
    180: {
      args: {
        1: {
          kind: "half",
          name: "count",
        },
      },
      handler: "ScrCmd_addcoins",
      name: "addcoins",
      size: 3,
    },
    181: {
      args: {
        1: {
          kind: "half",
          name: "count",
        },
      },
      handler: "ScrCmd_removecoins",
      name: "removecoins",
      size: 3,
    },
    182: {
      args: {
        1: {
          kind: "half",
          name: "species",
        },
        2: {
          kind: "byte",
          name: "level",
        },
        3: {
          kind: "half",
          name: "item",
        },
      },
      handler: "ScrCmd_setwildbattle",
      name: "setwildbattle",
      size: 6,
    },
    183: {
      args: {},
      handler: "ScrCmd_dowildbattle",
      name: "dowildbattle",
      size: 1,
    },
    184: {
      args: {
        1: {
          kind: "word",
          name: "pointer",
        },
      },
      handler: "ScrCmd_setvaddress",
      name: "setvaddress",
      size: 5,
    },
    185: {
      args: {
        1: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_vgoto",
      name: "vgoto",
      size: 5,
    },
    186: {
      args: {
        1: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_vcall",
      name: "vcall",
      size: 5,
    },
    187: {
      args: {
        1: {
          kind: "byte",
          name: "condition",
        },
        2: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_vgoto_if",
      name: "vgoto_if",
      size: 6,
    },
    188: {
      args: {
        1: {
          kind: "byte",
          name: "condition",
        },
        2: {
          kind: "word",
          name: "destination",
        },
      },
      handler: "ScrCmd_vcall_if",
      name: "vcall_if",
      size: 6,
    },
    189: {
      args: {
        1: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_vmessage",
      name: "vmessage",
      size: 5,
    },
    190: {
      args: {
        1: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_vbuffermessage",
      name: "vbuffermessage",
      size: 5,
    },
    191: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "word",
          name: "text",
        },
      },
      handler: "ScrCmd_vbufferstring",
      name: "vbufferstring",
      size: 6,
    },
    192: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
      },
      handler: "ScrCmd_showcoinsbox",
      name: "showcoinsbox",
      size: 3,
    },
    193: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
      },
      handler: "ScrCmd_hidecoinsbox",
      name: "hidecoinsbox",
      size: 3,
    },
    194: {
      args: {
        1: {
          kind: "byte",
          name: "x",
        },
        2: {
          kind: "byte",
          name: "y",
        },
      },
      handler: "ScrCmd_updatecoinsbox",
      name: "updatecoinsbox",
      size: 3,
    },
    195: {
      args: {
        1: {
          kind: "byte",
          name: "stat",
        },
      },
      handler: "ScrCmd_incrementgamestat",
      name: "incrementgamestat",
      size: 2,
    },
    196: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_setescapewarp",
      name: "setescapewarp",
      size: 8,
    },
    197: {
      args: {},
      handler: "ScrCmd_waitmoncry",
      name: "waitmoncry",
      size: 1,
    },
    198: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "box",
        },
      },
      handler: "ScrCmd_bufferboxname",
      name: "bufferboxname",
      size: 4,
    },
    199: {
      args: {
        1: {
          kind: "byte",
          name: "color",
        },
      },
      handler: "ScrCmd_textcolor",
      name: "textcolor",
      size: 2,
    },
    200: {
      args: {
        1: {
          kind: "word",
          name: "msg",
        },
      },
      handler: "ScrCmd_loadhelp",
      name: "loadhelp",
      size: 5,
    },
    201: {
      args: {},
      handler: "ScrCmd_unloadhelp",
      name: "unloadhelp",
      size: 1,
    },
    202: {
      args: {},
      handler: "ScrCmd_signmsg",
      name: "signmsg",
      size: 1,
    },
    203: {
      args: {},
      handler: "ScrCmd_normalmsg",
      name: "normalmsg",
      size: 1,
    },
    204: {
      args: {
        1: {
          kind: "byte",
          name: "statId",
        },
        2: {
          kind: "word",
          name: "value",
        },
      },
      handler: "ScrCmd_comparestat",
      name: "comparestat",
      size: 6,
    },
    205: {
      args: {
        1: {
          kind: "half",
          name: "slot",
        },
      },
      handler: "ScrCmd_setmonmodernfatefulencounter",
      name: "setmonmodernfatefulencounter",
      size: 3,
    },
    206: {
      args: {
        1: {
          kind: "half",
          name: "slot",
        },
      },
      handler: "ScrCmd_checkmonmodernfatefulencounter",
      name: "checkmonmodernfatefulencounter",
      size: 3,
    },
    207: {
      args: {},
      handler: "ScrCmd_trywondercardscript",
      name: "trywondercardscript",
      size: 1,
    },
    208: {
      args: {
        1: {
          kind: "half",
          name: "worldmapflag",
        },
      },
      handler: "ScrCmd_setworldmapflag",
      name: "setworldmapflag",
      size: 3,
    },
    209: {
      args: {
        1: {
          kind: "byte",
          name: "\\map_id >> 8",
        },
        2: {
          kind: "byte",
          name: "\\map_id & 0xFF",
        },
        3: {
          kind: "byte",
          name: "a",
        },
        4: {
          kind: "half",
          name: "b",
        },
        5: {
          kind: "half",
          name: "c",
        },
      },
      handler: "ScrCmd_warpspinenter",
      name: "warpspinenter",
      size: 8,
    },
    210: {
      args: {
        1: {
          kind: "half",
          name: "slot",
        },
        2: {
          kind: "byte",
          name: "location",
        },
      },
      handler: "ScrCmd_setmonmetlocation",
      name: "setmonmetlocation",
      size: 4,
    },
    211: {
      args: {
        1: {
          kind: "word",
          name: "msg",
        },
      },
      handler: "ScrCmd_getbraillestringwidth",
      name: "getbraillestringwidth",
      size: 5,
    },
    212: {
      args: {
        1: {
          kind: "byte",
          name: "id",
        },
        2: {
          kind: "half",
          name: "item",
        },
        3: {
          kind: "half",
          name: "quantity",
        },
      },
      handler: "ScrCmd_bufferitemnameplural",
      name: "bufferitemnameplural",
      size: 6,
    },
  },
  byName: {
    addcoins: 180,
    adddecoration: 75,
    addelevmenuitem: 177,
    additem: 68,
    addmoney: 144,
    addobject: 85,
    addobjectat: 86,
    addpcitem: 73,
    addvar: 23,
    animateflash: 154,
    applymovement: 79,
    applymovementat: 80,
    braillemessage: 120,
    bufferboxname: 198,
    bufferdecorationname: 129,
    bufferitemname: 128,
    bufferitemnameplural: 212,
    bufferleadmonspeciesname: 126,
    buffermovename: 130,
    buffernumberstring: 131,
    bufferpartymonnick: 127,
    bufferspeciesname: 125,
    bufferstdstring: 132,
    bufferstring: 133,
    call: 4,
    call_if: 7,
    callnative: 35,
    callstd: 9,
    callstd_if: 11,
    checkcoins: 179,
    checkdecor: 77,
    checkdecorspace: 78,
    checkflag: 43,
    checkitem: 71,
    checkitemspace: 70,
    checkitemtype: 72,
    checkmoney: 146,
    checkmonmodernfatefulencounter: 206,
    checkpartymove: 124,
    checkpcitem: 74,
    checkplayergender: 160,
    checktrainerflag: 96,
    choosecontestmon: 139,
    clearflag: 42,
    cleartrainerflag: 98,
    closedoor: 173,
    closemessage: 104,
    compare_local_to_local: 27,
    compare_local_to_ptr: 29,
    compare_local_to_value: 28,
    compare_ptr_to_local: 30,
    compare_ptr_to_ptr: 32,
    compare_ptr_to_value: 31,
    compare_var_to_value: 33,
    compare_var_to_var: 34,
    comparestat: 204,
    contestlinktransfer: 142,
    copybyte: 21,
    copylocal: 20,
    copyobjectxytoperm: 100,
    copyvar: 25,
    createvobject: 170,
    delay: 40,
    dofieldeffect: 156,
    dotimebasedevents: 45,
    dotrainerbattle: 93,
    doweather: 165,
    dowildbattle: 183,
    drawbox: 114,
    drawboxtext: 116,
    end: 2,
    endram: 13,
    erasebox: 115,
    faceplayer: 90,
    fadedefaultbgm: 53,
    fadeinbgm: 56,
    fadenewbgm: 54,
    fadeoutbgm: 55,
    fadescreen: 151,
    fadescreenspeed: 152,
    getbraillestringwidth: 211,
    getpartysize: 67,
    getplayerxy: 66,
    getpokenewsactive: 150,
    gettime: 46,
    giveegg: 122,
    givemon: 121,
    goto: 5,
    goto_if: 6,
    gotobeatenscript: 95,
    gotonative: 36,
    gotopostbattlescript: 94,
    gotostd: 8,
    gotostd_if: 10,
    hidecoinsbox: 193,
    hidemoneybox: 148,
    hidemonpic: 118,
    hideobjectat: 89,
    incrementgamestat: 195,
    initclock: 44,
    loadbyte: 16,
    loadbytefromptr: 18,
    loadhelp: 200,
    loadword: 15,
    lock: 106,
    lockall: 105,
    message: 103,
    messageautoscroll: 155,
    multichoice: 111,
    multichoicedefault: 112,
    multichoicegrid: 113,
    nop: 0,
    nop1: 1,
    normalmsg: 203,
    opendoor: 172,
    playbgm: 51,
    playfanfare: 49,
    playmoncry: 161,
    playse: 47,
    playslotmachine: 137,
    pokemart: 134,
    pokemartdecoration: 135,
    pokemartdecoration2: 136,
    random: 143,
    release: 108,
    releaseall: 107,
    removecoins: 181,
    removedecoration: 76,
    removeitem: 69,
    removemoney: 145,
    removeobject: 83,
    removeobjectat: 84,
    resetobjectsubpriority: 169,
    resetweather: 163,
    return: 3,
    returnram: 12,
    savebgm: 52,
    setberrytree: 138,
    setdivewarp: 64,
    setdoorclosed: 176,
    setdooropen: 175,
    setdynamicwarp: 63,
    setescapewarp: 196,
    setfieldeffectargument: 157,
    setflag: 41,
    setflashlevel: 153,
    setholewarp: 65,
    setmaplayoutindex: 167,
    setmetatile: 162,
    setmonmetlocation: 210,
    setmonmodernfatefulencounter: 205,
    setmonmove: 123,
    setmysteryeventstatus: 14,
    setobjectmovementtype: 101,
    setobjectsubpriority: 168,
    setobjectxy: 87,
    setobjectxyperm: 99,
    setorcopyvar: 26,
    setptr: 17,
    setptrbyte: 19,
    setrespawn: 159,
    setstepcallback: 166,
    settrainerflag: 97,
    setvaddress: 184,
    setvar: 22,
    setwarp: 62,
    setweather: 164,
    setwildbattle: 182,
    setworldmapflag: 208,
    showcoinsbox: 192,
    showcontestpainting: 119,
    showcontestresults: 141,
    showelevmenu: 178,
    showmoneybox: 147,
    showmonpic: 117,
    showobjectat: 88,
    signmsg: 202,
    special: 37,
    specialvar: 38,
    startcontest: 140,
    subvar: 24,
    textcolor: 199,
    trainerbattle: 92,
    trywondercardscript: 207,
    turnobject: 91,
    turnvobject: 171,
    unloadhelp: 201,
    updatecoinsbox: 194,
    updatemoneybox: 149,
    vbuffermessage: 190,
    vbufferstring: 191,
    vcall: 186,
    vcall_if: 188,
    vgoto: 185,
    vgoto_if: 187,
    vmessage: 189,
    waitbuttonpress: 109,
    waitdooranim: 174,
    waitfanfare: 50,
    waitfieldeffect: 158,
    waitmessage: 102,
    waitmoncry: 197,
    waitmovement: 81,
    waitmovementat: 82,
    waitse: 48,
    waitstate: 39,
    warp: 57,
    warpdoor: 59,
    warphole: 60,
    warpsilent: 58,
    warpspinenter: 209,
    warpteleport: 61,
    yesnobox: 110,
  },
  count: 213,
};
export default data;
