// @gen2-stub
// Not ported yet: gen1recomp src/world/MapOverview.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const MapOverview: Record<string, any> = {
  build: (..._a: any[]): any => notPorted("MapOverview.build"),
};
export default MapOverview;
