// @gen2-stub
// Not ported yet: gen1recomp src/world/NPC.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class NPC {
  [key: string]: any;
  static [key: string]: any;
  static new(..._a: any[]): any { return notPorted("NPC.new"); }
  resetToSpawn(..._a: any[]): any { return notPorted("NPC:resetToSpawn"); }
  facePlayer(..._a: any[]): any { return notPorted("NPC:facePlayer"); }
  update(..._a: any[]): any { return notPorted("NPC:update"); }
  walkPhase(..._a: any[]): any { return notPorted("NPC:walkPhase"); }
  pose(..._a: any[]): any { return notPorted("NPC:pose"); }
  draw(..._a: any[]): any { return notPorted("NPC:draw"); }
}
export default NPC;
