// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Apricorns.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Apricorns: Record<string, any> = {
  BALLS: undefined,
  ENGINE_KURT_MAKING_BALLS: undefined,
  DAILY_ENGINE_FLAGS: undefined,
  ENGINE_ALL_FRUIT_TREES: undefined,
  updateTimeRemaining: undefined,
  FRUIT_TREES: undefined,
  NUM_FRUIT_TREES: undefined,
  registerInto: (..._a: any[]): any => notPorted("Apricorns.registerInto"),
  useRegistry: (..._a: any[]): any => notPorted("Apricorns.useRegistry"),
  row: (..._a: any[]): any => notPorted("Apricorns.row"),
  isApricorn: (..._a: any[]): any => notPorted("Apricorns.isApricorn"),
  ballFor: (..._a: any[]): any => notPorted("Apricorns.ballFor"),
  apricornFor: (..._a: any[]): any => notPorted("Apricorns.apricornFor"),
  event: (..._a: any[]): any => notPorted("Apricorns.event"),
  setEvent: (..._a: any[]): any => notPorted("Apricorns.setEvent"),
  bagList: (..._a: any[]): any => notPorted("Apricorns.bagList"),
  select: (..._a: any[]): any => notPorted("Apricorns.select"),
  takeApricorn: (..._a: any[]): any => notPorted("Apricorns.takeApricorn"),
  give: (..._a: any[]): any => notPorted("Apricorns.give"),
  pending: (..._a: any[]): any => notPorted("Apricorns.pending"),
  isWorking: (..._a: any[]): any => notPorted("Apricorns.isWorking"),
  readyBall: (..._a: any[]): any => notPorted("Apricorns.readyBall"),
  collect: (..._a: any[]): any => notPorted("Apricorns.collect"),
  startDailyResetTimer: (..._a: any[]): any => notPorted("Apricorns.startDailyResetTimer"),
  checkDailyResetTimer: (..._a: any[]): any => notPorted("Apricorns.checkDailyResetTimer"),
  dailyReset: (..._a: any[]): any => notPorted("Apricorns.dailyReset"),
  treeFruit: (..._a: any[]): any => notPorted("Apricorns.treeFruit"),
  tryResetFruitTrees: (..._a: any[]): any => notPorted("Apricorns.tryResetFruitTrees"),
  treePicked: (..._a: any[]): any => notPorted("Apricorns.treePicked"),
  pickTree: (..._a: any[]): any => notPorted("Apricorns.pickTree"),
};
export default Apricorns;
