// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Boxes.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Boxes: Record<string, any> = {
  NUM_BOXES: undefined,
  MONS_PER_BOX: undefined,
  PARTY_SIZE: undefined,
  defaultName: (..._a: any[]): any => notPorted("Boxes.defaultName"),
  name: (..._a: any[]): any => notPorted("Boxes.name"),
  rename: (..._a: any[]): any => notPorted("Boxes.rename"),
  box: (..._a: any[]): any => notPorted("Boxes.box"),
  count: (..._a: any[]): any => notPorted("Boxes.count"),
  isFull: (..._a: any[]): any => notPorted("Boxes.isFull"),
  setCurrent: (..._a: any[]): any => notPorted("Boxes.setCurrent"),
  healthyCount: (..._a: any[]): any => notPorted("Boxes.healthyCount"),
  canDeposit: (..._a: any[]): any => notPorted("Boxes.canDeposit"),
  restorePP: (..._a: any[]): any => notPorted("Boxes.restorePP"),
  enterBox: (..._a: any[]): any => notPorted("Boxes.enterBox"),
  deposit: (..._a: any[]): any => notPorted("Boxes.deposit"),
  canWithdraw: (..._a: any[]): any => notPorted("Boxes.canWithdraw"),
  withdraw: (..._a: any[]): any => notPorted("Boxes.withdraw"),
  release: (..._a: any[]): any => notPorted("Boxes.release"),
  releaseFromParty: (..._a: any[]): any => notPorted("Boxes.releaseFromParty"),
  move: (..._a: any[]): any => notPorted("Boxes.move"),
  canUsePc: (..._a: any[]): any => notPorted("Boxes.canUsePc"),
};
export default Boxes;
