// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/CatchTutorial.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const CatchTutorial: Record<string, any> = {
  DUDE_NAME: undefined,
  BATTLETYPE_TUTORIAL: undefined,
  PACK: undefined,
  BALL: undefined,
  PROMPT_STREAM: undefined,
  MENU_STREAM: undefined,
  PACK_STREAM: undefined,
  BATTLE_STREAM: undefined,
  rearm: (..._a: any[]): any => notPorted("CatchTutorial.rearm"),
  dudeSave: (..._a: any[]): any => notPorted("CatchTutorial.dudeSave"),
  begin: (..._a: any[]): any => notPorted("CatchTutorial.begin"),
  finish: (..._a: any[]): any => notPorted("CatchTutorial.finish"),
};
export default CatchTutorial;
