// @gen2-stub
// Not ported yet: gen1recomp src/core/Game2.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class Game2 {
  [key: string]: any;
  static [key: string]: any;
  static anchorNewGameClock: any = undefined;
  static writeOptions: any = undefined;
  static new(..._a: any[]): any { return notPorted("Game2.new"); }
  persistOptions(..._a: any[]): any { return notPorted("Game2:persistOptions"); }
  adoptSave(..._a: any[]): any { return notPorted("Game2:adoptSave"); }
  enterArena(..._a: any[]): any { return notPorted("Game2:enterArena"); }
  startWorld(..._a: any[]): any { return notPorted("Game2:startWorld"); }
  showOakSpeech(..._a: any[]): any { return notPorted("Game2:showOakSpeech"); }
  newGame(..._a: any[]): any { return notPorted("Game2:newGame"); }
  continueGame(..._a: any[]): any { return notPorted("Game2:continueGame"); }
  showMainMenu(..._a: any[]): any { return notPorted("Game2:showMainMenu"); }
  returnToTitle(..._a: any[]): any { return notPorted("Game2:returnToTitle"); }
  softReset(..._a: any[]): any { return notPorted("Game2:softReset"); }
  showOptions(..._a: any[]): any { return notPorted("Game2:showOptions"); }
  showTitle(..._a: any[]): any { return notPorted("Game2:showTitle"); }
  showIntro(..._a: any[]): any { return notPorted("Game2:showIntro"); }
  showGameFreak(..._a: any[]): any { return notPorted("Game2:showGameFreak"); }
  showCopyright(..._a: any[]): any { return notPorted("Game2:showCopyright"); }
  openStartMenu(..._a: any[]): any { return notPorted("Game2:openStartMenu"); }
  openStartMenuItem(..._a: any[]): any { return notPorted("Game2:openStartMenuItem"); }
  closeStartMenuItem(..._a: any[]): any { return notPorted("Game2:closeStartMenuItem"); }
  pushStartMenuItem(..._a: any[]): any { return notPorted("Game2:pushStartMenuItem"); }
  runPokegearCall(..._a: any[]): any { return notPorted("Game2:runPokegearCall"); }
  learnMoveOn(..._a: any[]): any { return notPorted("Game2:learnMoveOn"); }
  useFieldItem(..._a: any[]): any { return notPorted("Game2:useFieldItem"); }
  consumeItem(..._a: any[]): any { return notPorted("Game2:consumeItem"); }
  restartMapMusicAfterEvolution(..._a: any[]): any { return notPorted("Game2:restartMapMusicAfterEvolution"); }
  afterRareCandy(..._a: any[]): any { return notPorted("Game2:afterRareCandy"); }
  usePartyItem(..._a: any[]): any { return notPorted("Game2:usePartyItem"); }
  useSelectItem(..._a: any[]): any { return notPorted("Game2:useSelectItem"); }
  say(..._a: any[]): any { return notPorted("Game2:say"); }
  currentLandmark(..._a: any[]): any { return notPorted("Game2:currentLandmark"); }
  snapshotSave(..._a: any[]): any { return notPorted("Game2:snapshotSave"); }
  writeSave(..._a: any[]): any { return notPorted("Game2:writeSave"); }
  quickSaveAllowed(..._a: any[]): any { return notPorted("Game2:quickSaveAllowed"); }
  syncEngine(..._a: any[]): any { return notPorted("Game2:syncEngine"); }
  load(..._a: any[]): any { return notPorted("Game2:load"); }
  inFillBoot(..._a: any[]): any { return notPorted("Game2:inFillBoot"); }
  logicSpeed(..._a: any[]): any { return notPorted("Game2:logicSpeed"); }
  update(..._a: any[]): any { return notPorted("Game2:update"); }
  pixelScale(..._a: any[]): any { return notPorted("Game2:pixelScale"); }
  presentCanvas(..._a: any[]): any { return notPorted("Game2:presentCanvas"); }
  frameFit(..._a: any[]): any { return notPorted("Game2:frameFit"); }
  viewport(..._a: any[]): any { return notPorted("Game2:viewport"); }
  drawHud(..._a: any[]): any { return notPorted("Game2:drawHud"); }
  letterbox(..._a: any[]): any { return notPorted("Game2:letterbox"); }
  blitZones(..._a: any[]): any { return notPorted("Game2:blitZones"); }
  compose(..._a: any[]): any { return notPorted("Game2:compose"); }
  fxWorldOrigin(..._a: any[]): any { return notPorted("Game2:fxWorldOrigin"); }
  fxSplitsUi(..._a: any[]): any { return notPorted("Game2:fxSplitsUi"); }
  drawViewportFrame(..._a: any[]): any { return notPorted("Game2:drawViewportFrame"); }
  draw(..._a: any[]): any { return notPorted("Game2:draw"); }
  textboxPaper(..._a: any[]): any { return notPorted("Game2:textboxPaper"); }
  drawContained(..._a: any[]): any { return notPorted("Game2:drawContained"); }
  paintBattleSurround(..._a: any[]): any { return notPorted("Game2:paintBattleSurround"); }
  drawScene(..._a: any[]): any { return notPorted("Game2:drawScene"); }
  hotkey(..._a: any[]): any { return notPorted("Game2:hotkey"); }
  storeZoom(..._a: any[]): any { return notPorted("Game2:storeZoom"); }
  zoomStep(..._a: any[]): any { return notPorted("Game2:zoomStep"); }
  pipelineGate(..._a: any[]): any { return notPorted("Game2:pipelineGate"); }
  pipelineHotkey(..._a: any[]): any { return notPorted("Game2:pipelineHotkey"); }
  keypressed(..._a: any[]): any { return notPorted("Game2:keypressed"); }
  keyreleased(..._a: any[]): any { return notPorted("Game2:keyreleased"); }
  wheelmoved(..._a: any[]): any { return notPorted("Game2:wheelmoved"); }
  pointerEvent(..._a: any[]): any { return notPorted("Game2:pointerEvent"); }
  touchpressed(..._a: any[]): any { return notPorted("Game2:touchpressed"); }
  touchmoved(..._a: any[]): any { return notPorted("Game2:touchmoved"); }
  touchreleased(..._a: any[]): any { return notPorted("Game2:touchreleased"); }
  mousepressed(..._a: any[]): any { return notPorted("Game2:mousepressed"); }
  mousemoved(..._a: any[]): any { return notPorted("Game2:mousemoved"); }
  mousereleased(..._a: any[]): any { return notPorted("Game2:mousereleased"); }
  cancelPointers(..._a: any[]): any { return notPorted("Game2:cancelPointers"); }
  focus(..._a: any[]): any { return notPorted("Game2:focus"); }
  visible(..._a: any[]): any { return notPorted("Game2:visible"); }
  onResume(..._a: any[]): any { return notPorted("Game2:onResume"); }
  applyOptions(..._a: any[]): any { return notPorted("Game2:applyOptions"); }
  _cycleSpeed(..._a: any[]): any { return notPorted("Game2:_cycleSpeed"); }
  gamepadpressed(..._a: any[]): any { return notPorted("Game2:gamepadpressed"); }
  gamepadreleased(..._a: any[]): any { return notPorted("Game2:gamepadreleased"); }
  gamepadaxis(..._a: any[]): any { return notPorted("Game2:gamepadaxis"); }
  joystickpressed(..._a: any[]): any { return notPorted("Game2:joystickpressed"); }
  joystickreleased(..._a: any[]): any { return notPorted("Game2:joystickreleased"); }
  joystickaxis(..._a: any[]): any { return notPorted("Game2:joystickaxis"); }
  joystickhat(..._a: any[]): any { return notPorted("Game2:joystickhat"); }
  recoverInput(..._a: any[]): any { return notPorted("Game2:recoverInput"); }
  joystickadded(..._a: any[]): any { return notPorted("Game2:joystickadded"); }
  joystickremoved(..._a: any[]): any { return notPorted("Game2:joystickremoved"); }
  reset(..._a: any[]): any { return notPorted("Game2:reset"); }
}
export default Game2;
