// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Happiness.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Happiness: Record<string, any> = {
  BASE: undefined,
  FRIEND_BALL: undefined,
  TO_EVOLVE: undefined,
  THRESHOLD_1: undefined,
  THRESHOLD_2: undefined,
  MAX: undefined,
  EVENT: undefined,
  NUM_EVENTS: undefined,
  CHANGES: undefined,
  RATER_UNHAPPY: undefined,
  RATER_KINDA: undefined,
  tier: (..._a: any[]): any => notPorted("Happiness.tier"),
  eventIndex: (..._a: any[]): any => notPorted("Happiness.eventIndex"),
  delta: (..._a: any[]): any => notPorted("Happiness.delta"),
  change: (..._a: any[]): any => notPorted("Happiness.change"),
  levelUpEvent: (..._a: any[]): any => notPorted("Happiness.levelUpEvent"),
  levelUp: (..._a: any[]): any => notPorted("Happiness.levelUp"),
  changeParty: (..._a: any[]): any => notPorted("Happiness.changeParty"),
  stepCycle: (..._a: any[]): any => notPorted("Happiness.stepCycle"),
  step: (..._a: any[]): any => notPorted("Happiness.step"),
  stepsToGain: (..._a: any[]): any => notPorted("Happiness.stepsToGain"),
  raterBand: (..._a: any[]): any => notPorted("Happiness.raterBand"),
  firstMon: (..._a: any[]): any => notPorted("Happiness.firstMon"),
  forNewMon: (..._a: any[]): any => notPorted("Happiness.forNewMon"),
};
export default Happiness;
