// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/ItemEffects.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const ItemEffects: Record<string, any> = {
  HEAL_HP: undefined,
  HEAL_STATUS: undefined,
  REVIVE: undefined,
  RESTORE_PP: undefined,
  VITAMIN: undefined,
  TEXT_NO_EFFECT: undefined,
  TEXT_CANT_USE_ON_EGG: undefined,
  TEXT_CANT_USE_ON_MON: undefined,
  TEXT_PP_RESTORED: undefined,
  TEXT_PP_MAXED: undefined,
  TEXT_PP_INCREASED: undefined,
  STATUS_CLASS: undefined,
  RECORDS: undefined,
  healClassOf: (..._a: any[]): any => notPorted("ItemEffects.healClassOf"),
  heldItemsFrom: (..._a: any[]): any => notPorted("ItemEffects.heldItemsFrom"),
  heldSnapshot: (..._a: any[]): any => notPorted("ItemEffects.heldSnapshot"),
  heldItemFor: (..._a: any[]): any => notPorted("ItemEffects.heldItemFor"),
  applyHeldItems: (..._a: any[]): any => notPorted("ItemEffects.applyHeldItems"),
  recordFor: (..._a: any[]): any => notPorted("ItemEffects.recordFor"),
  partyAction: (..._a: any[]): any => notPorted("ItemEffects.partyAction"),
  useOnMon: (..._a: any[]): any => notPorted("ItemEffects.useOnMon"),
  usePpItem: (..._a: any[]): any => notPorted("ItemEffects.usePpItem"),
  registerInto: (..._a: any[]): any => notPorted("ItemEffects.registerInto"),
};
export default ItemEffects;
