// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/MagnetTrain.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class MagnetTrain {
  [key: string]: any;
  static [key: string]: any;
  static PAL_BG_GRAY: any = undefined;
  static PAL_BG_GREEN: any = undefined;
  static PAL_BG_YELLOW: any = undefined;
  static byte: any = undefined;
  static SHEET_FRAME: any = undefined;
  static new(..._a: any[]): any { return notPorted("MagnetTrain.new"); }
  static paletteSlot(..._a: any[]): any { return notPorted("MagnetTrain.paletteSlot"); }
  done(..._a: any[]): any { return notPorted("MagnetTrain:done"); }
  update(..._a: any[]): any { return notPorted("MagnetTrain:update"); }
  next(..._a: any[]): any { return notPorted("MagnetTrain:next"); }
  waitScene(..._a: any[]): any { return notPorted("MagnetTrain:waitScene"); }
  runJumptable(..._a: any[]): any { return notPorted("MagnetTrain:runJumptable"); }
  updateLYOverrides(..._a: any[]): any { return notPorted("MagnetTrain:updateLYOverrides"); }
  bands(..._a: any[]): any { return notPorted("MagnetTrain:bands"); }
  tilemap(..._a: any[]): any { return notPorted("MagnetTrain:tilemap"); }
  stepSpriteFrame(..._a: any[]): any { return notPorted("MagnetTrain:stepSpriteFrame"); }
  playerOam(..._a: any[]): any { return notPorted("MagnetTrain:playerOam"); }
}
export default MagnetTrain;
