// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Nests.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Nests: Record<string, any> = {
  LANDMARK_PALLET_TOWN: undefined,
  LANDMARK_FAST_SHIP: undefined,
  regionOf: (..._a: any[]): any => notPorted("Nests.regionOf"),
  landmarkId: (..._a: any[]): any => notPorted("Nests.landmarkId"),
  landmark: (..._a: any[]): any => notPorted("Nests.landmark"),
  find: (..._a: any[]): any => notPorted("Nests.find"),
};
export default Nests;
