// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/PcItems.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const PcItems: Record<string, any> = {
  order: (..._a: any[]): any => notPorted("PcItems.order"),
  move: (..._a: any[]): any => notPorted("PcItems.move"),
};
export default PcItems;
