// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/PokedexText.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const PokedexText: Record<string, any> = {
  apply: (..._a: any[]): any => notPorted("PokedexText.apply"),
};
export default PokedexText;
