// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Roamers.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Roamers: Record<string, any> = {
  SPECIES: undefined,
  LEVEL: undefined,
  NUM_MAPS: undefined,
  MAPS: undefined,
  MAX_STORED_HP: undefined,
  ALWAYS_FLEE_BY_ENGINE: undefined,
  ALWAYS_FLEE: undefined,
  OFTEN_FLEE: undefined,
  SOMETIMES_FLEE: undefined,
  Swarm: undefined,
  roster: (..._a: any[]): any => notPorted("Roamers.roster"),
  mapTable: (..._a: any[]): any => notPorted("Roamers.mapTable"),
  entryFor: (..._a: any[]): any => notPorted("Roamers.entryFor"),
  jumpOne: (..._a: any[]): any => notPorted("Roamers.jumpOne"),
  moveOne: (..._a: any[]): any => notPorted("Roamers.moveOne"),
  list: (..._a: any[]): any => notPorted("Roamers.list"),
  slot: (..._a: any[]): any => notPorted("Roamers.slot"),
  init: (..._a: any[]): any => notPorted("Roamers.init"),
  active: (..._a: any[]): any => notPorted("Roamers.active"),
  backUpMapIndices: (..._a: any[]): any => notPorted("Roamers.backUpMapIndices"),
  lastMap: (..._a: any[]): any => notPorted("Roamers.lastMap"),
  update: (..._a: any[]): any => notPorted("Roamers.update"),
  jumpAll: (..._a: any[]): any => notPorted("Roamers.jumpAll"),
  checkEncounter: (..._a: any[]): any => notPorted("Roamers.checkEncounter"),
  beginBattle: (..._a: any[]): any => notPorted("Roamers.beginBattle"),
  endBattle: (..._a: any[]): any => notPorted("Roamers.endBattle"),
  afterWildBattle: (..._a: any[]): any => notPorted("Roamers.afterWildBattle"),
  alwaysFleeMons: (..._a: any[]): any => notPorted("Roamers.alwaysFleeMons"),
};
export default Roamers;
