// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Save.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Save: Record<string, any> = {
  FORMAT: undefined,
  MAX_MONEY: undefined,
  MAX_COINS: undefined,
  PARTY_SIZE: undefined,
  NUM_BOXES: undefined,
  MONS_PER_BOX: undefined,
  EVENT_BYTES: undefined,
  PLAYER_NORMAL: undefined,
  PLAYER_STATES: undefined,
  filenames: undefined,
  DEFAULT_PLAYER_NAMES: undefined,
  DEFAULT_PLAYER_NAMES_FEMALE: undefined,
  DEFAULT_OPTIONS: undefined,
  OPTIONS_KEY: undefined,
  GS_BALL_STATES: undefined,
  MIGRATIONS: undefined,
  isFemale: (..._a: any[]): any => notPorted("Save.isFemale"),
  defaultPlayerName: (..._a: any[]): any => notPorted("Save.defaultPlayerName"),
  newGame: (..._a: any[]): any => notPorted("Save.newGame"),
  defaultOptions: (..._a: any[]): any => notPorted("Save.defaultOptions"),
  loadOptions: (..._a: any[]): any => notPorted("Save.loadOptions"),
  saveOptions: (..._a: any[]): any => notPorted("Save.saveOptions"),
  crystalState: (..._a: any[]): any => notPorted("Save.crystalState"),
  battleTowerState: (..._a: any[]): any => notPorted("Save.battleTowerState"),
  normalize: (..._a: any[]): any => notPorted("Save.normalize"),
  migrate: (..._a: any[]): any => notPorted("Save.migrate"),
  validate: (..._a: any[]): any => notPorted("Save.validate"),
  emptyReport: (..._a: any[]): any => notPorted("Save.emptyReport"),
  exists: (..._a: any[]): any => notPorted("Save.exists"),
  load: (..._a: any[]): any => notPorted("Save.load"),
  save: (..._a: any[]): any => notPorted("Save.save"),
  summary: (..._a: any[]): any => notPorted("Save.summary"),
  tickPlayTime: (..._a: any[]): any => notPorted("Save.tickPlayTime"),
};
export default Save;
