// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/TradeAnim.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const TradeAnim: Record<string, any> = {
  SCROLL_STEP: undefined,
  PAN_STEP: undefined,
  GIVEMON_SCROLL: undefined,
  TUBE_SCROLL: undefined,
  PAN_TOTAL: undefined,
  SCRIPT: undefined,
  TEXT: undefined,
  TOTAL: undefined,
  beatAt: (..._a: any[]): any => notPorted("TradeAnim.beatAt"),
  startOf: (..._a: any[]): any => notPorted("TradeAnim.startOf"),
  givemonOffset: (..._a: any[]): any => notPorted("TradeAnim.givemonOffset"),
  tubeOffset: (..._a: any[]): any => notPorted("TradeAnim.tubeOffset"),
  pan: (..._a: any[]): any => notPorted("TradeAnim.pan"),
  tubeIcon: (..._a: any[]): any => notPorted("TradeAnim.tubeIcon"),
  records: (..._a: any[]): any => notPorted("TradeAnim.records"),
};
export default TradeAnim;
