// @gen2-stub
// Not ported yet: gen1recomp src/core/gen2/Unown.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Unown: Record<string, any> = {
  NUM_UNOWN: undefined,
  SPECIES: undefined,
  ALPHABET: undefined,
  ENGINE_UNOWN_DEX: undefined,
  UNLOCK_SETS: undefined,
  PUZZLES: undefined,
  WORDS: undefined,
  name: (..._a: any[]): any => notPorted("Unown.name"),
  index: (..._a: any[]): any => notPorted("Unown.index"),
  letterFromDVs: (..._a: any[]): any => notPorted("Unown.letterFromDVs"),
  letterUnlocked: (..._a: any[]): any => notPorted("Unown.letterUnlocked"),
  anyUnlocked: (..._a: any[]): any => notPorted("Unown.anyUnlocked"),
  unlockedLetters: (..._a: any[]): any => notPorted("Unown.unlockedLetters"),
  wildDVs: (..._a: any[]): any => notPorted("Unown.wildDVs"),
  dvsForLetter: (..._a: any[]): any => notPorted("Unown.dvsForLetter"),
  dex: (..._a: any[]): any => notPorted("Unown.dex"),
  updateDex: (..._a: any[]): any => notPorted("Unown.updateDex"),
  caught: (..._a: any[]): any => notPorted("Unown.caught"),
  registerCatch: (..._a: any[]): any => notPorted("Unown.registerCatch"),
  count: (..._a: any[]): any => notPorted("Unown.count"),
  word: (..._a: any[]): any => notPorted("Unown.word"),
  monLetter: (..._a: any[]): any => notPorted("Unown.monLetter"),
  forms: (..._a: any[]): any => notPorted("Unown.forms"),
  formSprite: (..._a: any[]): any => notPorted("Unown.formSprite"),
};
export default Unown;
