#!/usr/bin/env python3
"""Lay down one TypeScript stub per Lua module of gen1recomp's Gen 2 engine.

The Gold engine is a module-for-module port of bryanthaboi/gen1recomp at its
last MIT commit (bdfac727).  Porting 150 modules in parallel needs every
import to resolve before its target is ported, so this writes a stub for each
module -- the Lua module's public names, all typed `any`, each throwing
`notPorted` -- and the port of a module replaces its stub wholesale.

Mapping (docs/gold-engine.md):
  src/<dir>/gen2/<X>.lua     -> voxelmon/game/gen2/<dir>/<X>.ts
  src/core/Game2.lua         -> voxelmon/game/gen2/core/Game2.ts
  any other src/<p>.lua      -> voxelmon/game/gen2/shared/<p>.ts  (only the
                                shared modules Gen 2 code requires directly)

An existing file is never overwritten unless it still carries the STUB marker,
so re-running after ports have landed only refreshes the stubs.

usage: gen2_stubs.py <gen1recomp-mit-gen2 checkout> <pocket-voxel checkout>
"""
import os
import re
import sys

MARK = "// @gen2-stub"

src_root, repo = sys.argv[1], sys.argv[2]
out_root = os.path.join(repo, "voxelmon", "game", "gen2")


def ts_path(lua_rel):
    # lua_rel like src/world/gen2/World.lua
    parts = lua_rel.split("/")
    if len(parts) >= 4 and parts[2] == "gen2":
        return os.path.join(out_root, parts[1], *parts[3:])[:-4] + ".ts"
    if lua_rel == "src/core/Game2.lua":
        return os.path.join(out_root, "core", "Game2.ts")
    return os.path.join(out_root, "shared", *parts[1:])[:-4] + ".ts"


def module_info(text, base):
    rets = re.findall(r"^return\s+([A-Za-z_][A-Za-z0-9_]*)\s*$", text, re.M)
    local = rets[-1] if rets else base
    export = base if local == "M" else local
    is_class = re.search(r"^%s\.__index\s*=\s*%s\b" % (local, local), text, re.M) is not None
    statics, methods, fields = [], [], []
    for m in re.finditer(r"^function\s+%s([.:])([A-Za-z_][A-Za-z0-9_]*)\s*\(([^)]*)\)" % local, text, re.M):
        sep, name, args = m.groups()
        (methods if sep == ":" else statics).append((name, args.strip()))
    for m in re.finditer(r"^%s\.([A-Za-z_][A-Za-z0-9_]*)\s*=" % local, text, re.M):
        name = m.group(1)
        if name != "__index" and name not in fields:
            fields.append(name)
    fn_names = {n for n, _ in statics} | {n for n, _ in methods}
    fields = [f for f in fields if f not in fn_names]
    return export, is_class, statics, methods, fields


def ident(n):
    return n if n not in ("new", "delete", "default") or True else n


def stub(lua_rel, text):
    base = os.path.splitext(os.path.basename(lua_rel))[0]
    export, is_class, statics, methods, fields = module_info(text, base)
    rel_imp = os.path.relpath(os.path.join(out_root, "notported.ts"),
                              os.path.dirname(ts_path(lua_rel))).replace(os.sep, "/")
    if not rel_imp.startswith("."):
        rel_imp = "./" + rel_imp
    lines = [
        MARK,
        "// Not ported yet: gen1recomp %s at bdfac727 (MIT)." % lua_rel,
        "// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.",
        "",
        'import { notPorted } from "%s";' % rel_imp,
        "",
    ]
    seen = set()
    if is_class or methods:
        lines.append("export class %s {" % export)
        lines.append("  [key: string]: any;")
        lines.append("  static [key: string]: any;")
        for f in fields:
            lines.append("  static %s: any = undefined;" % f)
        for n, a in statics:
            if ("s", n) in seen:
                continue
            seen.add(("s", n))
            lines.append('  static %s(..._a: any[]): any { return notPorted("%s.%s"); }' % (n, export, n))
        for n, a in methods:
            if ("m", n) in seen or n == "constructor":
                continue
            seen.add(("m", n))
            lines.append('  %s(..._a: any[]): any { return notPorted("%s:%s"); }' % (n, export, n))
        lines.append("}")
    else:
        lines.append("export const %s: Record<string, any> = {" % export)
        for f in fields:
            lines.append("  %s: undefined," % f)
        for n, a in statics:
            if n in seen:
                continue
            seen.add(n)
            lines.append('  %s: (..._a: any[]): any => notPorted("%s.%s"),' % (n, export, n))
        lines.append("};")
    lines.append("export default %s;" % export)
    return "\n".join(lines) + "\n"


def gen2_files():
    out = []
    for d, _, fs in os.walk(os.path.join(src_root, "src")):
        for f in fs:
            if f.endswith(".lua"):
                rel = os.path.relpath(os.path.join(d, f), src_root).replace(os.sep, "/")
                if "/gen2/" in rel or rel == "src/core/Game2.lua":
                    out.append(rel)
    return sorted(out)


def shared_requires(files):
    req = set()
    for rel in files:
        text = open(os.path.join(src_root, rel), encoding="utf-8", errors="replace").read()
        for m in re.finditer(r'require\("(src\.[A-Za-z0-9_.]+)"\)', text):
            mod = m.group(1)
            if ".gen2." not in mod and mod != "src.core.Game2":
                req.add(mod.replace(".", "/") + ".lua")
    return sorted(r for r in req if os.path.exists(os.path.join(src_root, r)))


files = gen2_files()
shared = shared_requires(files)
wrote = kept = 0
for rel in files + shared:
    dest = ts_path(rel)
    if os.path.exists(dest):
        with open(dest, encoding="utf-8") as fh:
            if MARK not in fh.readline():
                kept += 1
                continue
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    text = open(os.path.join(src_root, rel), encoding="utf-8", errors="replace").read()
    with open(dest, "w", encoding="utf-8") as fh:
        fh.write(stub(rel, text))
    wrote += 1
print("gen2 stubs: %d gen2 + %d shared modules; wrote %d, kept %d ported" % (len(files), len(shared), wrote, kept))
