#!/usr/bin/env bash
# Build the installable 3DS title (.cia) from the release ELF.
#
#   bash tools/make_cia.sh [OUTPUT.cia] [red|blue|yellow]
#
# Red and Blue are two titles, side by side on the HOME menu: their own
# title ID, name, icon and banner (Blue's art is Red's with every red made
# blue), and their own ELF -- Blue is `cargo 3ds build --release --features
# blue` into target-blue/. Both read the same shared paks on the card.
# Each also gets a .3dsx carrying its own name and icon (cargo-3ds names
# every one after the crate, with no icon), for the Homebrew Launcher.
#
# cargo-3ds only emits .3dsx, so the CIA is assembled here by hand:
#
#   icon.png   -> icon.smdh    (bannertool makesmdh)  what HOME shows
#   banner.png -> banner.bnr   (bannertool makebanner) the shelf banner
#   ELF + RSF  -> .cia         (makerom)
#
# The art is generated by tools/3ds_art.py and is ours. The boot logo is
# makerom's own Homebrew splash, not one of Nintendo's.
#
# Needs `makerom` (github.com/3DSGuy/Project_CTR) and `bannertool` on PATH.
set -e
cd "$(dirname "$0")/.."
ROOT=$(pwd)
GAME=${2:-${PV_GAME:-red}}
case "$GAME" in
  red)
    LABEL=Red; UNIQUE=0xff3d0; PCODE=CTR-P-PVXL
    ELF=crates/pocketvoxel-3ds/target/armv6k-nintendo-3ds/release/pocketvoxel-3ds.elf
    WORK=dist/voxelmon/cia ;;
  blue)
    LABEL=Blue; UNIQUE=0xff3d1; PCODE=CTR-P-PVXB
    ELF=crates/pocketvoxel-3ds/target-blue/armv6k-nintendo-3ds/release/pocketvoxel-3ds.elf
    WORK=dist/voxelmon/cia-blue ;;
  # Yellow reads its own pak set (paks_yellow/) beside Red and Blue's
  yellow)
    LABEL=Yellow; UNIQUE=0xff3d2; PCODE=CTR-P-PVXY
    ELF=crates/pocketvoxel-3ds/target-yellow/armv6k-nintendo-3ds/release/pocketvoxel-3ds.elf
    WORK=dist/voxelmon/cia-yellow ;;
  *) echo "make_cia: unknown game '$GAME' (red, blue or yellow)"; exit 1 ;;
esac
OUT=${1:-dist/voxelmon/PocketVoxel3D$LABEL.cia}

for t in makerom bannertool python3; do
  command -v "$t" >/dev/null || { echo "make_cia: $t is not on PATH"; exit 1; }
done
[ -f "$ELF" ] || { echo "make_cia: no release ELF at $ELF -- build the $LABEL 3dsx first (docs/3DS.md)"; exit 1; }

mkdir -p "$WORK" "$(dirname "$OUT")"

echo "=== art"
python3 tools/3ds_art.py "$WORK" "$GAME"

# A short, quiet original phrase: the HOME menu loops the banner tune, and
# silence is rude while a jingle that is someone else's is worse.
echo "=== tune"
python3 - "$WORK/banner.wav" <<'PY'
import math, struct, sys, wave
RATE = 32000
# do mi sol, then the high re: C5 E5 G5 D6, a broken C chord with the added 9th
notes = [(523.25, .28), (659.25, .28), (783.99, .28), (1174.66, .52)]
frames = bytearray()
t = 0
for freq, dur in notes:
    n = int(RATE * dur)
    for i in range(n):
        env = min(1.0, i / (RATE * 0.01)) * (1.0 - i / n) ** 1.6
        s = 0.0
        for h, amp in ((1, 1.0), (2, 0.25), (3, 0.12)):
            s += amp * math.sin(2 * math.pi * freq * h * (t + i) / RATE)
        v = int(max(-1.0, min(1.0, s / 1.37)) * env * 7000)
        frames += struct.pack("<hh", v, v)
    t += n
with wave.open(sys.argv[1], "wb") as w:
    w.setnchannels(2); w.setsampwidth(2); w.setframerate(RATE)
    w.writeframes(bytes(frames))
print(f"  {sys.argv[1]}  {len(frames)//4} frames")
PY

echo "=== smdh"
bannertool makesmdh \
  -s "Pocket Voxel 3D $LABEL" \
  -l "Pocket Voxel 3D $LABEL" \
  -p "Pocket Voxel" \
  -i "$WORK/icon.png" \
  -o "$WORK/icon.smdh"

echo "=== banner"
# Two passes. bannertool builds a flat banner from the PNG -- which is also
# how the texture gets converted -- then tools/3ds_banner3d.py rebuilds the
# model inside it with the title card and a real cube, and bannertool packs
# that CGFX back (-ci), which it round-trips byte for byte.
bannertool makebanner -i "$WORK/banner.png" -a "$WORK/banner.wav" -o "$WORK/banner_flat.bnr"
python3 tools/3ds_banner3d.py "$WORK/banner_flat.bnr" "$WORK/banner3d.cgfx"
bannertool makebanner -ci "$WORK/banner3d.cgfx" -a "$WORK/banner.wav" -o "$WORK/banner.bnr"

echo "=== rsf"
# The one RSF, with this title's own ID: two titles sharing a UniqueId
# would install over each other.
sed -e "s/^\(  UniqueId *: \).*/\1$UNIQUE/" \
    -e "s/^\(  ProductCode *: \).*/\1\"$PCODE\"/" \
  tools/pocketvoxel.rsf > "$WORK/pocketvoxel.rsf"
grep -E "UniqueId|ProductCode" "$WORK/pocketvoxel.rsf"

echo "=== cia"
# -exefslogo puts the RSF's logo into the ExeFS, which is where the HOME
# menu looks for it; a title without one launches to an SD-card error that
# says nothing about logos. The version triplet is what FBI shows.
makerom -f cia -target t -exefslogo -major 1 -minor 0 -micro 0 \
  -o "$OUT" \
  -elf "$ELF" \
  -rsf "$WORK/pocketvoxel.rsf" \
  -icon "$WORK/icon.smdh" \
  -banner "$WORK/banner.bnr"

ls -l "$OUT"
echo "make_cia: $OUT"

# The same ELF as a .3dsx with this title's own SMDH.
if [ "$GAME" = red ]; then DSX=dist/voxelmon/pocketvoxel-3ds.3dsx; else DSX=dist/voxelmon/pocketvoxel-3ds-$GAME.3dsx; fi
"${DEVKITPRO:-/opt/devkitpro}/tools/bin/3dsxtool" "$ELF" "$DSX" --smdh="$WORK/icon.smdh"
ls -l "$DSX"
echo "make_cia: $DSX"
