#!/usr/bin/env bash
# Build the installable 3DS title (.cia) from the release ELF.
#
#   bash tools/make_cia.sh [OUTPUT.cia]
#
# cargo-3ds only emits .3dsx, so the CIA is assembled here by hand:
#
#   icon.png   -> icon.smdh    (bannertool makesmdh)  what HOME shows
#   banner.png -> banner.bnr   (bannertool makebanner) the shelf banner
#   ELF + RSF  -> .cia         (makerom)
#
# The art is generated by tools/3ds_art.py and is ours; the RSF carries no
# boot logo, because makerom's is Nintendo's.
#
# Needs `makerom` (github.com/3DSGuy/Project_CTR) and `bannertool` on PATH.
set -e
cd "$(dirname "$0")/.."
ROOT=$(pwd)
OUT=${1:-dist/voxelmon/PocketVoxel3DRed.cia}
WORK=dist/voxelmon/cia
ELF=crates/pocketvoxel-3ds/target/armv6k-nintendo-3ds/release/pocketvoxel-3ds.elf

for t in makerom bannertool python3; do
  command -v "$t" >/dev/null || { echo "make_cia: $t is not on PATH"; exit 1; }
done
[ -f "$ELF" ] || { echo "make_cia: no release ELF at $ELF -- run 'bun tools/voxel.ts 3ds' first"; exit 1; }

mkdir -p "$WORK" "$(dirname "$OUT")"

echo "=== art"
python3 tools/3ds_art.py "$WORK"

# A short, quiet original phrase: the HOME menu loops the banner tune, and
# silence is rude while a jingle that is someone else's is worse.
echo "=== tune"
python3 - "$WORK/banner.wav" <<'PY'
import math, struct, sys, wave
RATE = 32000
notes = [(523.25, .28), (659.25, .28), (783.99, .28), (1046.50, .52)]
frames = bytearray()
t = 0
for freq, dur in notes:
    n = int(RATE * dur)
    for i in range(n):
        env = min(1.0, i / (RATE * 0.01)) * (1.0 - i / n) ** 1.6
        s = 0.0
        for h, amp in ((1, 1.0), (2, 0.25), (3, 0.12)):
            s += amp * math.sin(2 * math.pi * freq * h * (t + i) / RATE)
        v = int(max(-1.0, min(1.0, s / 1.37)) * env * 7000)
        frames += struct.pack("<hh", v, v)
    t += n
with wave.open(sys.argv[1], "wb") as w:
    w.setnchannels(2); w.setsampwidth(2); w.setframerate(RATE)
    w.writeframes(bytes(frames))
print(f"  {sys.argv[1]}  {len(frames)//4} frames")
PY

echo "=== smdh"
bannertool makesmdh \
  -s "Pocket Voxel 3D Red" \
  -l "Pocket Voxel 3D Red" \
  -p "Pocket Voxel" \
  -i "$WORK/icon.png" \
  -o "$WORK/icon.smdh"

echo "=== banner"
bannertool makebanner \
  -i "$WORK/banner.png" \
  -a "$WORK/banner.wav" \
  -o "$WORK/banner.bnr"

echo "=== cia"
makerom -f cia -target t \
  -o "$OUT" \
  -elf "$ELF" \
  -rsf tools/pocketvoxel.rsf \
  -icon "$WORK/icon.smdh" \
  -banner "$WORK/banner.bnr"

ls -l "$OUT"
echo "make_cia: $OUT"
