// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BankOfMom.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BankOfMom {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("BankOfMom.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("BankOfMom:wantsFillScale"); }
  finish(..._a: any[]): any { return notPorted("BankOfMom:finish"); }
  playSfx(..._a: any[]): any { return notPorted("BankOfMom:playSfx"); }
  update(..._a: any[]): any { return notPorted("BankOfMom:update"); }
  drawPanel(..._a: any[]): any { return notPorted("BankOfMom:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("BankOfMom:draw"); }
}
export default BankOfMom;
