// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BattleTowerMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BattleTowerMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static CANCELLED: any = undefined;
  static levelLabel(..._a: any[]): any { return notPorted("BattleTowerMenu.levelLabel"); }
  static new(..._a: any[]): any { return notPorted("BattleTowerMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("BattleTowerMenu:wantsFillScale"); }
  playSfx(..._a: any[]): any { return notPorted("BattleTowerMenu:playSfx"); }
  rowCount(..._a: any[]): any { return notPorted("BattleTowerMenu:rowCount"); }
  finish(..._a: any[]): any { return notPorted("BattleTowerMenu:finish"); }
  refuse(..._a: any[]): any { return notPorted("BattleTowerMenu:refuse"); }
  confirm(..._a: any[]): any { return notPorted("BattleTowerMenu:confirm"); }
  updatePick(..._a: any[]): any { return notPorted("BattleTowerMenu:updatePick"); }
  updateQuit(..._a: any[]): any { return notPorted("BattleTowerMenu:updateQuit"); }
  update(..._a: any[]): any { return notPorted("BattleTowerMenu:update"); }
  drawPanel(..._a: any[]): any { return notPorted("BattleTowerMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("BattleTowerMenu:draw"); }
}
export default BattleTowerMenu;
