// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BattleTransition.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BattleTransition {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static FLASH_PALS: any = undefined;
  static FLASH_HOLD: any = undefined;
  static FLASH_CYCLES: any = undefined;
  static FLASH_SLOT_FRAMES: any = undefined;
  static FLASH_FRAMES: any = undefined;
  static TRAINER_PAL: any = undefined;
  static TRAINER_PAL_DARK: any = undefined;
  static RAMPED_OBJ: any = undefined;
  static POKEBALL_X: any = undefined;
  static POKEBALL_Y: any = undefined;
  static SPIN_STEPS: any = undefined;
  static SPIN_HOLD: any = undefined;
  static ZOOM_BOXES: any = undefined;
  static ZOOM_HOLD: any = undefined;
  static OUTRO_LEAD: any = undefined;
  static END_HOLD: any = undefined;
  static SPECKLE_PASSES: any = undefined;
  static SPECKLE_PER_PASS: any = undefined;
  static SINE_LIMIT: any = undefined;
  static CAVE_ENVIRONMENTS: any = undefined;
  static STYLES: any = undefined;
  static BLACK_HOLD: any = undefined;
  static TINT_ALPHA: any = undefined;
  static flashByte(..._a: any[]): any { return notPorted("BattleTransition.flashByte"); }
  static flashVeil(..._a: any[]): any { return notPorted("BattleTransition.flashVeil"); }
  static pokeballCells(..._a: any[]): any { return notPorted("BattleTransition.pokeballCells"); }
  static squareTile(..._a: any[]): any { return notPorted("BattleTransition.squareTile"); }
  static squareShades(..._a: any[]): any { return notPorted("BattleTransition.squareShades"); }
  static spinStep(..._a: any[]): any { return notPorted("BattleTransition.spinStep"); }
  static zoomStep(..._a: any[]): any { return notPorted("BattleTransition.zoomStep"); }
  static speckleStep(..._a: any[]): any { return notPorted("BattleTransition.speckleStep"); }
  static sineFrames(..._a: any[]): any { return notPorted("BattleTransition.sineFrames"); }
  static pick(..._a: any[]): any { return notPorted("BattleTransition.pick"); }
  static new(..._a: any[]): any { return notPorted("BattleTransition.new"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("BattleTransition:drawsWidescreen"); }
  wantsFillScale(..._a: any[]): any { return notPorted("BattleTransition:wantsFillScale"); }
  keepsOpponent(..._a: any[]): any { return notPorted("BattleTransition:keepsOpponent"); }
  trainerRamp(..._a: any[]): any { return notPorted("BattleTransition:trainerRamp"); }
  flashFrames(..._a: any[]): any { return notPorted("BattleTransition:flashFrames"); }
  beginOutro(..._a: any[]): any { return notPorted("BattleTransition:beginOutro"); }
  update(..._a: any[]): any { return notPorted("BattleTransition:update"); }
  outroFrame(..._a: any[]): any { return notPorted("BattleTransition:outroFrame"); }
  endOutro(..._a: any[]): any { return notPorted("BattleTransition:endOutro"); }
  blackOut(..._a: any[]): any { return notPorted("BattleTransition:blackOut"); }
  finish(..._a: any[]): any { return notPorted("BattleTransition:finish"); }
  lyOverrides(..._a: any[]): any { return notPorted("BattleTransition:lyOverrides"); }
  blackAt(..._a: any[]): any { return notPorted("BattleTransition:blackAt"); }
  draw(..._a: any[]): any { return notPorted("BattleTransition:draw"); }
  flashPal(..._a: any[]): any { return notPorted("BattleTransition:flashPal"); }
  remapPalettes(..._a: any[]): any { return notPorted("BattleTransition:remapPalettes"); }
  bindRemap(..._a: any[]): any { return notPorted("BattleTransition:bindRemap"); }
  drawMap(..._a: any[]): any { return notPorted("BattleTransition:drawMap"); }
  drawWorld(..._a: any[]): any { return notPorted("BattleTransition:drawWorld"); }
  drawTint(..._a: any[]): any { return notPorted("BattleTransition:drawTint"); }
  drawWidescreen(..._a: any[]): any { return notPorted("BattleTransition:drawWidescreen"); }
  grid(..._a: any[]): any { return notPorted("BattleTransition:grid"); }
  drawTopLayer(..._a: any[]): any { return notPorted("BattleTransition:drawTopLayer"); }
  drawBgLayer(..._a: any[]): any { return notPorted("BattleTransition:drawBgLayer"); }
  ballImage(..._a: any[]): any { return notPorted("BattleTransition:ballImage"); }
  blackColor(..._a: any[]): any { return notPorted("BattleTransition:blackColor"); }
  paintLayer(..._a: any[]): any { return notPorted("BattleTransition:paintLayer"); }
  drawWavy(..._a: any[]): any { return notPorted("BattleTransition:drawWavy"); }
  capture(..._a: any[]): any { return notPorted("BattleTransition:capture"); }
}
export default BattleTransition;
