// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BattleHud.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BattleHud {
  [key: string]: any;
  static [key: string]: any;
  static PARTY_LENGTH: any = undefined;
  static EXP_CELLS: any = undefined;
  static EXP_LENGTH_PX: any = undefined;
  static TILE_HP_LABEL: any = undefined;
  static TILE_BAR_EMPTY: any = undefined;
  static TILE_BAR_END: any = undefined;
  static new(..._a: any[]): any { return notPorted("BattleHud.new"); }
  image(..._a: any[]): any { return notPorted("BattleHud:image"); }
  quad(..._a: any[]): any { return notPorted("BattleHud:quad"); }
  available(..._a: any[]): any { return notPorted("BattleHud:available"); }
  barColors(..._a: any[]): any { return notPorted("BattleHud:barColors"); }
  drawTile(..._a: any[]): any { return notPorted("BattleHud:drawTile"); }
  drawBar(..._a: any[]): any { return notPorted("BattleHud:drawBar"); }
  drawHpBar(..._a: any[]): any { return notPorted("BattleHud:drawHpBar"); }
  expColors(..._a: any[]): any { return notPorted("BattleHud:expColors"); }
  drawExpBar(..._a: any[]): any { return notPorted("BattleHud:drawExpBar"); }
  drawExpBarEnd(..._a: any[]): any { return notPorted("BattleHud:drawExpBarEnd"); }
  drawCaughtIcon(..._a: any[]): any { return notPorted("BattleHud:drawCaughtIcon"); }
  placeBorder(..._a: any[]): any { return notPorted("BattleHud:placeBorder"); }
  drawEnemyFrame(..._a: any[]): any { return notPorted("BattleHud:drawEnemyFrame"); }
  drawPlayerFrame(..._a: any[]): any { return notPorted("BattleHud:drawPlayerFrame"); }
  drawPartyIconFrame(..._a: any[]): any { return notPorted("BattleHud:drawPartyIconFrame"); }
  ballColors(..._a: any[]): any { return notPorted("BattleHud:ballColors"); }
  drawBallRow(..._a: any[]): any { return notPorted("BattleHud:drawBallRow"); }
}
export default BattleHud;
