// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BlankScreen.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BlankScreen {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static FRAMES: any = undefined;
  static new(..._a: any[]): any { return notPorted("BlankScreen.new"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("BlankScreen:drawsWidescreen"); }
  draw(..._a: any[]): any { return notPorted("BlankScreen:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("BlankScreen:drawWidescreen"); }
  update(..._a: any[]): any { return notPorted("BlankScreen:update"); }
}
export default BlankScreen;
