// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BoxMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BoxMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("BoxMenu.new"); }
  submenuRows(..._a: any[]): any { return notPorted("BoxMenu:submenuRows"); }
  wantsFillScale(..._a: any[]): any { return notPorted("BoxMenu:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("BoxMenu:drawsWidescreen"); }
  isParty(..._a: any[]): any { return notPorted("BoxMenu:isParty"); }
  listAt(..._a: any[]): any { return notPorted("BoxMenu:listAt"); }
  capacityAt(..._a: any[]): any { return notPorted("BoxMenu:capacityAt"); }
  nameAt(..._a: any[]): any { return notPorted("BoxMenu:nameAt"); }
  list(..._a: any[]): any { return notPorted("BoxMenu:list"); }
  title(..._a: any[]): any { return notPorted("BoxMenu:title"); }
  prompt(..._a: any[]): any { return notPorted("BoxMenu:prompt"); }
  total(..._a: any[]): any { return notPorted("BoxMenu:total"); }
  isCancel(..._a: any[]): any { return notPorted("BoxMenu:isCancel"); }
  selected(..._a: any[]): any { return notPorted("BoxMenu:selected"); }
  ensureVisible(..._a: any[]): any { return notPorted("BoxMenu:ensureVisible"); }
  clampIndex(..._a: any[]): any { return notPorted("BoxMenu:clampIndex"); }
  act(..._a: any[]): any { return notPorted("BoxMenu:act"); }
  checkMailPreventBlackout(..._a: any[]): any { return notPorted("BoxMenu:checkMailPreventBlackout"); }
  beginMove(..._a: any[]): any { return notPorted("BoxMenu:beginMove"); }
  openStats(..._a: any[]): any { return notPorted("BoxMenu:openStats"); }
  holdMessage(..._a: any[]): any { return notPorted("BoxMenu:holdMessage"); }
  isCrystal(..._a: any[]): any { return notPorted("BoxMenu:isCrystal"); }
  cryThenHold(..._a: any[]): any { return notPorted("BoxMenu:cryThenHold"); }
  doWithdraw(..._a: any[]): any { return notPorted("BoxMenu:doWithdraw"); }
  doDeposit(..._a: any[]): any { return notPorted("BoxMenu:doDeposit"); }
  chooseSubmenu(..._a: any[]): any { return notPorted("BoxMenu:chooseSubmenu"); }
  insertPositions(..._a: any[]): any { return notPorted("BoxMenu:insertPositions"); }
  clampInsert(..._a: any[]): any { return notPorted("BoxMenu:clampInsert"); }
  checkSpaceInDestination(..._a: any[]): any { return notPorted("BoxMenu:checkSpaceInDestination"); }
  insertMon(..._a: any[]): any { return notPorted("BoxMenu:insertMon"); }
  cancelMove(..._a: any[]): any { return notPorted("BoxMenu:cancelMove"); }
  stepBox(..._a: any[]): any { return notPorted("BoxMenu:stepBox"); }
  update(..._a: any[]): any { return notPorted("BoxMenu:update"); }
  playSfx(..._a: any[]): any { return notPorted("BoxMenu:playSfx"); }
  playRefusalSfx(..._a: any[]): any { return notPorted("BoxMenu:playRefusalSfx"); }
  playMonCry(..._a: any[]): any { return notPorted("BoxMenu:playMonCry"); }
  askRelease(..._a: any[]): any { return notPorted("BoxMenu:askRelease"); }
  askNickname(..._a: any[]): any { return notPorted("BoxMenu:askNickname"); }
  image(..._a: any[]): any { return notPorted("BoxMenu:image"); }
  picFor(..._a: any[]): any { return notPorted("BoxMenu:picFor"); }
  panelColors(..._a: any[]): any { return notPorted("BoxMenu:panelColors"); }
  fillPicBlock(..._a: any[]): any { return notPorted("BoxMenu:fillPicBlock"); }
  drawPicBlock(..._a: any[]): any { return notPorted("BoxMenu:drawPicBlock"); }
  drawPic(..._a: any[]): any { return notPorted("BoxMenu:drawPic"); }
  drawEggPic(..._a: any[]): any { return notPorted("BoxMenu:drawEggPic"); }
  drawHeldIcon(..._a: any[]): any { return notPorted("BoxMenu:drawHeldIcon"); }
  drawBoxArrows(..._a: any[]): any { return notPorted("BoxMenu:drawBoxArrows"); }
  selectionFrameRect(..._a: any[]): any { return notPorted("BoxMenu:selectionFrameRect"); }
  drawSelectionFrame(..._a: any[]): any { return notPorted("BoxMenu:drawSelectionFrame"); }
  selectionFrameVisible(..._a: any[]): any { return notPorted("BoxMenu:selectionFrameVisible"); }
  drawInsertCursor(..._a: any[]): any { return notPorted("BoxMenu:drawInsertCursor"); }
  panelMon(..._a: any[]): any { return notPorted("BoxMenu:panelMon"); }
  messageBox(..._a: any[]): any { return notPorted("BoxMenu:messageBox"); }
  drawPanel(..._a: any[]): any { return notPorted("BoxMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("BoxMenu:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("BoxMenu:drawWidescreen"); }
}
export default BoxMenu;
