// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/BuenaPassword.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class BuenaPassword {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("BuenaPassword.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("BuenaPassword:wantsFillScale"); }
  count(..._a: any[]): any { return notPorted("BuenaPassword:count"); }
  playSfx(..._a: any[]): any { return notPorted("BuenaPassword:playSfx"); }
  finish(..._a: any[]): any { return notPorted("BuenaPassword:finish"); }
  ensureVisible(..._a: any[]): any { return notPorted("BuenaPassword:ensureVisible"); }
  update(..._a: any[]): any { return notPorted("BuenaPassword:update"); }
  drawPasswordPanel(..._a: any[]): any { return notPorted("BuenaPassword:drawPasswordPanel"); }
  drawPrizePanel(..._a: any[]): any { return notPorted("BuenaPassword:drawPrizePanel"); }
  drawPanel(..._a: any[]): any { return notPorted("BuenaPassword:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("BuenaPassword:draw"); }
}
export default BuenaPassword;
