// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/CenterPcMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class CenterPcMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static ENGINE_POKEDEX: any = undefined;
  static new(..._a: any[]): any { return notPorted("CenterPcMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("CenterPcMenu:wantsFillScale"); }
  playSfx(..._a: any[]): any { return notPorted("CenterPcMenu:playSfx"); }
  playerName(..._a: any[]): any { return notPorted("CenterPcMenu:playerName"); }
  buildEntries(..._a: any[]): any { return notPorted("CenterPcMenu:buildEntries"); }
  say(..._a: any[]): any { return notPorted("CenterPcMenu:say"); }
  close(..._a: any[]): any { return notPorted("CenterPcMenu:close"); }
  shutdown(..._a: any[]): any { return notPorted("CenterPcMenu:shutdown"); }
  oakClosed(..._a: any[]): any { return notPorted("CenterPcMenu:oakClosed"); }
  oakRate(..._a: any[]): any { return notPorted("CenterPcMenu:oakRate"); }
  choose(..._a: any[]): any { return notPorted("CenterPcMenu:choose"); }
  update(..._a: any[]): any { return notPorted("CenterPcMenu:update"); }
  drawBottomLines(..._a: any[]): any { return notPorted("CenterPcMenu:drawBottomLines"); }
  drawPanel(..._a: any[]): any { return notPorted("CenterPcMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("CenterPcMenu:draw"); }
}
export default CenterPcMenu;
