// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/CopyrightSplash.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class CopyrightSplash {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("CopyrightSplash.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("CopyrightSplash:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("CopyrightSplash:drawsWidescreen"); }
  enter(..._a: any[]): any { return notPorted("CopyrightSplash:enter"); }
  update(..._a: any[]): any { return notPorted("CopyrightSplash:update"); }
  fillBackdrop(..._a: any[]): any { return notPorted("CopyrightSplash:fillBackdrop"); }
  drawPanel(..._a: any[]): any { return notPorted("CopyrightSplash:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("CopyrightSplash:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("CopyrightSplash:drawWidescreen"); }
}
export default CopyrightSplash;
