// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/CrystalIntro.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class CrystalIntro {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static Scenes: any = undefined;
  static OAMSETS: any = undefined;
  static FRAMESETS: any = undefined;
  static OBJECTS: any = undefined;
  static SEQUENCES: any = undefined;
  static unownFade: any = undefined;
  static new(..._a: any[]): any { return notPorted("CrystalIntro.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("CrystalIntro:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("CrystalIntro:drawsWidescreen"); }
  playMusic(..._a: any[]): any { return notPorted("CrystalIntro:playMusic"); }
  playSfx(..._a: any[]): any { return notPorted("CrystalIntro:playSfx"); }
  step(..._a: any[]): any { return notPorted("CrystalIntro:step"); }
  enter(..._a: any[]): any { return notPorted("CrystalIntro:enter"); }
  finish(..._a: any[]): any { return notPorted("CrystalIntro:finish"); }
  skip(..._a: any[]): any { return notPorted("CrystalIntro:skip"); }
  update(..._a: any[]): any { return notPorted("CrystalIntro:update"); }
  image(..._a: any[]): any { return notPorted("CrystalIntro:image"); }
  sheet(..._a: any[]): any { return notPorted("CrystalIntro:sheet"); }
  drawLayer(..._a: any[]): any { return notPorted("CrystalIntro:drawLayer"); }
  drawObjects(..._a: any[]): any { return notPorted("CrystalIntro:drawObjects"); }
  renderFrame(..._a: any[]): any { return notPorted("CrystalIntro:renderFrame"); }
  drawPanel(..._a: any[]): any { return notPorted("CrystalIntro:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("CrystalIntro:draw"); }
  surroundColor(..._a: any[]): any { return notPorted("CrystalIntro:surroundColor"); }
  drawWidescreen(..._a: any[]): any { return notPorted("CrystalIntro:drawWidescreen"); }
}
export default CrystalIntro;
