// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/CrystalSplash.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class CrystalSplash {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("CrystalSplash.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("CrystalSplash:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("CrystalSplash:drawsWidescreen"); }
  enter(..._a: any[]): any { return notPorted("CrystalSplash:enter"); }
  finish(..._a: any[]): any { return notPorted("CrystalSplash:finish"); }
  playSfx(..._a: any[]): any { return notPorted("CrystalSplash:playSfx"); }
  fadeTo(..._a: any[]): any { return notPorted("CrystalSplash:fadeTo"); }
  placeString(..._a: any[]): any { return notPorted("CrystalSplash:placeString"); }
  sceneWaitSpriteAnim(..._a: any[]): any { return notPorted("CrystalSplash:sceneWaitSpriteAnim"); }
  scenePlaceGameFreak(..._a: any[]): any { return notPorted("CrystalSplash:scenePlaceGameFreak"); }
  scenePlacePresents(..._a: any[]): any { return notPorted("CrystalSplash:scenePlacePresents"); }
  sceneWaitForTimer(..._a: any[]): any { return notPorted("CrystalSplash:sceneWaitForTimer"); }
  beginExit(..._a: any[]): any { return notPorted("CrystalSplash:beginExit"); }
  update(..._a: any[]): any { return notPorted("CrystalSplash:update"); }
  sheetFor(..._a: any[]): any { return notPorted("CrystalSplash:sheetFor"); }
  drawTile(..._a: any[]): any { return notPorted("CrystalSplash:drawTile"); }
  drawObjects(..._a: any[]): any { return notPorted("CrystalSplash:drawObjects"); }
  drawPanel(..._a: any[]): any { return notPorted("CrystalSplash:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("CrystalSplash:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("CrystalSplash:drawWidescreen"); }
}
export default CrystalSplash;
