// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/DecorationMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class DecorationMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("DecorationMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("DecorationMenu:wantsFillScale"); }
  buildCategories(..._a: any[]): any { return notPorted("DecorationMenu:buildCategories"); }
  finish(..._a: any[]): any { return notPorted("DecorationMenu:finish"); }
  rowName(..._a: any[]): any { return notPorted("DecorationMenu:rowName"); }
  openCategory(..._a: any[]): any { return notPorted("DecorationMenu:openCategory"); }
  say(..._a: any[]): any { return notPorted("DecorationMenu:say"); }
  advanceMessage(..._a: any[]): any { return notPorted("DecorationMenu:advanceMessage"); }
  chooseRow(..._a: any[]): any { return notPorted("DecorationMenu:chooseRow"); }
  applyRow(..._a: any[]): any { return notPorted("DecorationMenu:applyRow"); }
  update(..._a: any[]): any { return notPorted("DecorationMenu:update"); }
  drawList(..._a: any[]): any { return notPorted("DecorationMenu:drawList"); }
  drawPanel(..._a: any[]): any { return notPorted("DecorationMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("DecorationMenu:draw"); }
}
export default DecorationMenu;
