// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/EggHatchAnim.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class EggHatchAnim {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("EggHatchAnim.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("EggHatchAnim:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("EggHatchAnim:drawsWidescreen"); }
  buildBeats(..._a: any[]): any { return notPorted("EggHatchAnim:buildBeats"); }
  startPicAnim(..._a: any[]): any { return notPorted("EggHatchAnim:startPicAnim"); }
  playSfx(..._a: any[]): any { return notPorted("EggHatchAnim:playSfx"); }
  playCry(..._a: any[]): any { return notPorted("EggHatchAnim:playCry"); }
  crackShell(..._a: any[]): any { return notPorted("EggHatchAnim:crackShell"); }
  initFragments(..._a: any[]): any { return notPorted("EggHatchAnim:initFragments"); }
  runBeat(..._a: any[]): any { return notPorted("EggHatchAnim:runBeat"); }
  finish(..._a: any[]): any { return notPorted("EggHatchAnim:finish"); }
  update(..._a: any[]): any { return notPorted("EggHatchAnim:update"); }
  image(..._a: any[]): any { return notPorted("EggHatchAnim:image"); }
  picCtx(..._a: any[]): any { return notPorted("EggHatchAnim:picCtx"); }
  picPath(..._a: any[]): any { return notPorted("EggHatchAnim:picPath"); }
  pic(..._a: any[]): any { return notPorted("EggHatchAnim:pic"); }
  picColors(..._a: any[]): any { return notPorted("EggHatchAnim:picColors"); }
  drawPic(..._a: any[]): any { return notPorted("EggHatchAnim:drawPic"); }
  shellQuad(..._a: any[]): any { return notPorted("EggHatchAnim:shellQuad"); }
  drawSprites(..._a: any[]): any { return notPorted("EggHatchAnim:drawSprites"); }
  drawPanel(..._a: any[]): any { return notPorted("EggHatchAnim:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("EggHatchAnim:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("EggHatchAnim:drawWidescreen"); }
}
export default EggHatchAnim;
