// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/ElevatorMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class ElevatorMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static floorName(..._a: any[]): any { return notPorted("ElevatorMenu.floorName"); }
  static scrollFor(..._a: any[]): any { return notPorted("ElevatorMenu.scrollFor"); }
  static new(..._a: any[]): any { return notPorted("ElevatorMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("ElevatorMenu:wantsFillScale"); }
  playSfx(..._a: any[]): any { return notPorted("ElevatorMenu:playSfx"); }
  finish(..._a: any[]): any { return notPorted("ElevatorMenu:finish"); }
  update(..._a: any[]): any { return notPorted("ElevatorMenu:update"); }
  drawPanel(..._a: any[]): any { return notPorted("ElevatorMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("ElevatorMenu:draw"); }
}
export default ElevatorMenu;
