// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/GameFreakPresents.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class GameFreakPresents {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static SPARKLE_VECTORS: any = undefined;
  static permute: any = undefined;
  static new(..._a: any[]): any { return notPorted("GameFreakPresents.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("GameFreakPresents:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("GameFreakPresents:drawsWidescreen"); }
  enter(..._a: any[]): any { return notPorted("GameFreakPresents:enter"); }
  finish(..._a: any[]): any { return notPorted("GameFreakPresents:finish"); }
  placeString(..._a: any[]): any { return notPorted("GameFreakPresents:placeString"); }
  sceneStar(..._a: any[]): any { return notPorted("GameFreakPresents:sceneStar"); }
  scenePlaceLogo(..._a: any[]): any { return notPorted("GameFreakPresents:scenePlaceLogo"); }
  sparkle(..._a: any[]): any { return notPorted("GameFreakPresents:sparkle"); }
  sceneLogoSparkles(..._a: any[]): any { return notPorted("GameFreakPresents:sceneLogoSparkles"); }
  scenePlacePresents(..._a: any[]): any { return notPorted("GameFreakPresents:scenePlacePresents"); }
  sceneWaitForTimer(..._a: any[]): any { return notPorted("GameFreakPresents:sceneWaitForTimer"); }
  beginExit(..._a: any[]): any { return notPorted("GameFreakPresents:beginExit"); }
  updateLogoPal(..._a: any[]): any { return notPorted("GameFreakPresents:updateLogoPal"); }
  update(..._a: any[]): any { return notPorted("GameFreakPresents:update"); }
  sheetFor(..._a: any[]): any { return notPorted("GameFreakPresents:sheetFor"); }
  drawTile(..._a: any[]): any { return notPorted("GameFreakPresents:drawTile"); }
  drawObjects(..._a: any[]): any { return notPorted("GameFreakPresents:drawObjects"); }
  drawPanel(..._a: any[]): any { return notPorted("GameFreakPresents:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("GameFreakPresents:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("GameFreakPresents:drawWidescreen"); }
}
export default GameFreakPresents;
