// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/GenderSelect.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class GenderSelect {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static OPTIONS: any = undefined;
  static PALETTE: any = undefined;
  static GROUND: any = undefined;
  static MENU_OPEN_FRAMES: any = undefined;
  static new(..._a: any[]): any { return notPorted("GenderSelect.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("GenderSelect:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("GenderSelect:drawsWidescreen"); }
  enter(..._a: any[]): any { return notPorted("GenderSelect:enter"); }
  playSfx(..._a: any[]): any { return notPorted("GenderSelect:playSfx"); }
  choose(..._a: any[]): any { return notPorted("GenderSelect:choose"); }
  leave(..._a: any[]): any { return notPorted("GenderSelect:leave"); }
  menuOpen(..._a: any[]): any { return notPorted("GenderSelect:menuOpen"); }
  update(..._a: any[]): any { return notPorted("GenderSelect:update"); }
  drawPanel(..._a: any[]): any { return notPorted("GenderSelect:drawPanel"); }
  drawBody(..._a: any[]): any { return notPorted("GenderSelect:drawBody"); }
  draw(..._a: any[]): any { return notPorted("GenderSelect:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("GenderSelect:drawWidescreen"); }
}
export default GenderSelect;
