// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/HallOfFame.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class HallOfFame {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static NEW_FAMER: any = undefined;
  static TIME_FAMER: any = undefined;
  static HOF_MASTER: any = undefined;
  static LABELS: any = undefined;
  static WHITE: any = undefined;
  static PIC_PAD: any = undefined;
  static FAMER_FRAMES: any = undefined;
  static ANIM_FAMER_FRAMES: any = undefined;
  static END_FRAMES: any = undefined;
  static SCY_START: any = undefined;
  static BACKPIC_SCX_START: any = undefined;
  static BACKPIC_SCX_END: any = undefined;
  static TRAINER_SCX_START: any = undefined;
  static at(..._a: any[]): any { return notPorted("HallOfFame.at"); }
  static monPlacements(..._a: any[]): any { return notPorted("HallOfFame.monPlacements"); }
  static headerPlacements(..._a: any[]): any { return notPorted("HallOfFame.headerPlacements"); }
  static playerPlacements(..._a: any[]): any { return notPorted("HallOfFame.playerPlacements"); }
  static new(..._a: any[]): any { return notPorted("HallOfFame.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("HallOfFame:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("HallOfFame:drawsWidescreen"); }
  playMusic(..._a: any[]): any { return notPorted("HallOfFame:playMusic"); }
  playCry(..._a: any[]): any { return notPorted("HallOfFame:playCry"); }
  currentMon(..._a: any[]): any { return notPorted("HallOfFame:currentMon"); }
  enterMon(..._a: any[]): any { return notPorted("HallOfFame:enterMon"); }
  enterView(..._a: any[]): any { return notPorted("HallOfFame:enterView"); }
  enterDisplay(..._a: any[]): any { return notPorted("HallOfFame:enterDisplay"); }
  startPicAnim(..._a: any[]): any { return notPorted("HallOfFame:startPicAnim"); }
  stepPicAnim(..._a: any[]): any { return notPorted("HallOfFame:stepPicAnim"); }
  picAnimFrame(..._a: any[]): any { return notPorted("HallOfFame:picAnimFrame"); }
  enterPlayer(..._a: any[]): any { return notPorted("HallOfFame:enterPlayer"); }
  finish(..._a: any[]): any { return notPorted("HallOfFame:finish"); }
  step(..._a: any[]): any { return notPorted("HallOfFame:step"); }
  viewInput(..._a: any[]): any { return notPorted("HallOfFame:viewInput"); }
  update(..._a: any[]): any { return notPorted("HallOfFame:update"); }
  image(..._a: any[]): any { return notPorted("HallOfFame:image"); }
  speciesDef(..._a: any[]): any { return notPorted("HallOfFame:speciesDef"); }
  picCtx(..._a: any[]): any { return notPorted("HallOfFame:picCtx"); }
  monPicPath(..._a: any[]): any { return notPorted("HallOfFame:monPicPath"); }
  monPic(..._a: any[]): any { return notPorted("HallOfFame:monPic"); }
  monColors(..._a: any[]): any { return notPorted("HallOfFame:monColors"); }
  drawScrolled(..._a: any[]): any { return notPorted("HallOfFame:drawScrolled"); }
  drawPortrait(..._a: any[]): any { return notPorted("HallOfFame:drawPortrait"); }
  drawPlacements(..._a: any[]): any { return notPorted("HallOfFame:drawPlacements"); }
  drawMonPanel(..._a: any[]): any { return notPorted("HallOfFame:drawMonPanel"); }
  drawPlayerPanel(..._a: any[]): any { return notPorted("HallOfFame:drawPlayerPanel"); }
  drawPanel(..._a: any[]): any { return notPorted("HallOfFame:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("HallOfFame:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("HallOfFame:drawWidescreen"); }
}
export default HallOfFame;
