// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/HeldItemMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class HeldItemMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static TEXT: any = undefined;
  static LABELS: any = undefined;
  static ENTRIES: any = undefined;
  static new(..._a: any[]): any { return notPorted("HeldItemMenu.new"); }
  mon(..._a: any[]): any { return notPorted("HeldItemMenu:mon"); }
  monName(..._a: any[]): any { return notPorted("HeldItemMenu:monName"); }
  itemName(..._a: any[]): any { return notPorted("HeldItemMenu:itemName"); }
  close(..._a: any[]): any { return notPorted("HeldItemMenu:close"); }
  playSfx(..._a: any[]): any { return notPorted("HeldItemMenu:playSfx"); }
  say(..._a: any[]): any { return notPorted("HeldItemMenu:say"); }
  ask(..._a: any[]): any { return notPorted("HeldItemMenu:ask"); }
  canHold(..._a: any[]): any { return notPorted("HeldItemMenu:canHold"); }
  openPack(..._a: any[]): any { return notPorted("HeldItemMenu:openPack"); }
  giveItem(..._a: any[]): any { return notPorted("HeldItemMenu:giveItem"); }
  composeIfMail(..._a: any[]): any { return notPorted("HeldItemMenu:composeIfMail"); }
  takeItem(..._a: any[]): any { return notPorted("HeldItemMenu:takeItem"); }
  choose(..._a: any[]): any { return notPorted("HeldItemMenu:choose"); }
  updateMessage(..._a: any[]): any { return notPorted("HeldItemMenu:updateMessage"); }
  updateConfirm(..._a: any[]): any { return notPorted("HeldItemMenu:updateConfirm"); }
  update(..._a: any[]): any { return notPorted("HeldItemMenu:update"); }
  drawTextBox(..._a: any[]): any { return notPorted("HeldItemMenu:drawTextBox"); }
  drawYesNo(..._a: any[]): any { return notPorted("HeldItemMenu:drawYesNo"); }
  drawPanel(..._a: any[]): any { return notPorted("HeldItemMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("HeldItemMenu:draw"); }
}
export default HeldItemMenu;
