// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/ItemPcMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class ItemPcMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static ENTRIES: any = undefined;
  static PC_ITEM_CAPACITY: any = undefined;
  static new(..._a: any[]): any { return notPorted("ItemPcMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("ItemPcMenu:wantsFillScale"); }
  setPhase(..._a: any[]): any { return notPorted("ItemPcMenu:setPhase"); }
  playSfx(..._a: any[]): any { return notPorted("ItemPcMenu:playSfx"); }
  playPcSfx(..._a: any[]): any { return notPorted("ItemPcMenu:playPcSfx"); }
  playPcSfxTwice(..._a: any[]): any { return notPorted("ItemPcMenu:playPcSfxTwice"); }
  tickRepeatSfx(..._a: any[]): any { return notPorted("ItemPcMenu:tickRepeatSfx"); }
  playerName(..._a: any[]): any { return notPorted("ItemPcMenu:playerName"); }
  say(..._a: any[]): any { return notPorted("ItemPcMenu:say"); }
  close(..._a: any[]): any { return notPorted("ItemPcMenu:close"); }
  def(..._a: any[]): any { return notPorted("ItemPcMenu:def"); }
  cantToss(..._a: any[]): any { return notPorted("ItemPcMenu:cantToss"); }
  rebuild(..._a: any[]): any { return notPorted("ItemPcMenu:rebuild"); }
  listTotal(..._a: any[]): any { return notPorted("ItemPcMenu:listTotal"); }
  ensureVisible(..._a: any[]): any { return notPorted("ItemPcMenu:ensureVisible"); }
  pcAdd(..._a: any[]): any { return notPorted("ItemPcMenu:pcAdd"); }
  pcRemove(..._a: any[]): any { return notPorted("ItemPcMenu:pcRemove"); }
  askQuantity(..._a: any[]): any { return notPorted("ItemPcMenu:askQuantity"); }
  withdraw(..._a: any[]): any { return notPorted("ItemPcMenu:withdraw"); }
  chooseWithdraw(..._a: any[]): any { return notPorted("ItemPcMenu:chooseWithdraw"); }
  deposit(..._a: any[]): any { return notPorted("ItemPcMenu:deposit"); }
  enterDeposit(..._a: any[]): any { return notPorted("ItemPcMenu:enterDeposit"); }
  leaveDeposit(..._a: any[]): any { return notPorted("ItemPcMenu:leaveDeposit"); }
  offerToDeposit(..._a: any[]): any { return notPorted("ItemPcMenu:offerToDeposit"); }
  chooseToss(..._a: any[]): any { return notPorted("ItemPcMenu:chooseToss"); }
  choose(..._a: any[]): any { return notPorted("ItemPcMenu:choose"); }
  armSwitch(..._a: any[]): any { return notPorted("ItemPcMenu:armSwitch"); }
  updateSwitch(..._a: any[]): any { return notPorted("ItemPcMenu:updateSwitch"); }
  placeSwitch(..._a: any[]): any { return notPorted("ItemPcMenu:placeSwitch"); }
  update(..._a: any[]): any { return notPorted("ItemPcMenu:update"); }
  drawBottomLines(..._a: any[]): any { return notPorted("ItemPcMenu:drawBottomLines"); }
  drawList(..._a: any[]): any { return notPorted("ItemPcMenu:drawList"); }
  drawPanel(..._a: any[]): any { return notPorted("ItemPcMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("ItemPcMenu:draw"); }
}
export default ItemPcMenu;
