// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/MailboxMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class MailboxMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static TEXT: any = undefined;
  static LABELS: any = undefined;
  static SUB_ENTRIES: any = undefined;
  static new(..._a: any[]): any { return notPorted("MailboxMenu.new"); }
  box(..._a: any[]): any { return notPorted("MailboxMenu:box"); }
  count(..._a: any[]): any { return notPorted("MailboxMenu:count"); }
  selected(..._a: any[]): any { return notPorted("MailboxMenu:selected"); }
  close(..._a: any[]): any { return notPorted("MailboxMenu:close"); }
  say(..._a: any[]): any { return notPorted("MailboxMenu:say"); }
  ask(..._a: any[]): any { return notPorted("MailboxMenu:ask"); }
  clampIndex(..._a: any[]): any { return notPorted("MailboxMenu:clampIndex"); }
  readMail(..._a: any[]): any { return notPorted("MailboxMenu:readMail"); }
  putInPack(..._a: any[]): any { return notPorted("MailboxMenu:putInPack"); }
  attachMail(..._a: any[]): any { return notPorted("MailboxMenu:attachMail"); }
  chooseSub(..._a: any[]): any { return notPorted("MailboxMenu:chooseSub"); }
  updateMessage(..._a: any[]): any { return notPorted("MailboxMenu:updateMessage"); }
  updateConfirm(..._a: any[]): any { return notPorted("MailboxMenu:updateConfirm"); }
  updateSubmenu(..._a: any[]): any { return notPorted("MailboxMenu:updateSubmenu"); }
  update(..._a: any[]): any { return notPorted("MailboxMenu:update"); }
  drawTextBox(..._a: any[]): any { return notPorted("MailboxMenu:drawTextBox"); }
  drawYesNo(..._a: any[]): any { return notPorted("MailboxMenu:drawYesNo"); }
  drawList(..._a: any[]): any { return notPorted("MailboxMenu:drawList"); }
  drawSubmenu(..._a: any[]): any { return notPorted("MailboxMenu:drawSubmenu"); }
  drawPanel(..._a: any[]): any { return notPorted("MailboxMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("MailboxMenu:draw"); }
}
export default MailboxMenu;
