// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/MenuFade.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class MenuFade {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static BG_WORLD_DIM: any = undefined;
  static OUT_FRAMES: any = undefined;
  static OUT_WHITE_FRAMES: any = undefined;
  static IN_RAMP_FRAMES: any = undefined;
  static PARTY_FONT_FRAMES: any = undefined;
  static PARTY_WHITE: any = undefined;
  static PARTY_ICON_FRAMES: any = undefined;
  static PACK_RELOAD_FRAMES: any = undefined;
  static PACK_WHITE: any = undefined;
  static GEAR_RELOAD_FRAMES: any = undefined;
  static GEAR_WHITE: any = undefined;
  static GEAR_EXIT_WHITE: any = undefined;
  static CARD_RELOAD_FRAMES: any = undefined;
  static CARD_WHITE: any = undefined;
  static DEX_RELOAD_FRAMES: any = undefined;
  static DEX_WHITE: any = undefined;
  static OPTION_WHITE: any = undefined;
  static openWhite(..._a: any[]): any { return notPorted("MenuFade.openWhite"); }
  static exitWhite(..._a: any[]): any { return notPorted("MenuFade.exitWhite"); }
  static closeWhite(..._a: any[]): any { return notPorted("MenuFade.closeWhite"); }
  static framesOut(..._a: any[]): any { return notPorted("MenuFade.framesOut"); }
  static framesIn(..._a: any[]): any { return notPorted("MenuFade.framesIn"); }
  static new(..._a: any[]): any { return notPorted("MenuFade.new"); }
  level(..._a: any[]): any { return notPorted("MenuFade:level"); }
  update(..._a: any[]): any { return notPorted("MenuFade:update"); }
  bgMode(..._a: any[]): any { return notPorted("MenuFade:bgMode"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("MenuFade:drawsWidescreen"); }
  drawWidescreen(..._a: any[]): any { return notPorted("MenuFade:drawWidescreen"); }
  draw(..._a: any[]): any { return notPorted("MenuFade:draw"); }
}
export default MenuFade;
