// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/NamingScreen.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class NamingScreen {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static TYPES: any = undefined;
  static NAME_INPUT_UPPER: any = undefined;
  static NAME_INPUT_LOWER: any = undefined;
  static BOX_INPUT_UPPER: any = undefined;
  static BOX_INPUT_LOWER: any = undefined;
  static playerSprite(..._a: any[]): any { return notPorted("NamingScreen.playerSprite"); }
  static new(..._a: any[]): any { return notPorted("NamingScreen.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("NamingScreen:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("NamingScreen:drawsWidescreen"); }
  rows(..._a: any[]): any { return notPorted("NamingScreen:rows"); }
  keyboardTop(..._a: any[]): any { return notPorted("NamingScreen:keyboardTop"); }
  bottomRow(..._a: any[]): any { return notPorted("NamingScreen:bottomRow"); }
  onBottomRow(..._a: any[]): any { return notPorted("NamingScreen:onBottomRow"); }
  bottomTarget(..._a: any[]): any { return notPorted("NamingScreen:bottomTarget"); }
  characterAt(..._a: any[]): any { return notPorted("NamingScreen:characterAt"); }
  addCharacter(..._a: any[]): any { return notPorted("NamingScreen:addCharacter"); }
  deleteCharacter(..._a: any[]): any { return notPorted("NamingScreen:deleteCharacter"); }
  toggleCase(..._a: any[]): any { return notPorted("NamingScreen:toggleCase"); }
  accept(..._a: any[]): any { return notPorted("NamingScreen:accept"); }
  moveHorizontal(..._a: any[]): any { return notPorted("NamingScreen:moveHorizontal"); }
  moveVertical(..._a: any[]): any { return notPorted("NamingScreen:moveVertical"); }
  update(..._a: any[]): any { return notPorted("NamingScreen:update"); }
  paperColor(..._a: any[]): any { return notPorted("NamingScreen:paperColor"); }
  drawBackdrop(..._a: any[]): any { return notPorted("NamingScreen:drawBackdrop"); }
  cursorTile(..._a: any[]): any { return notPorted("NamingScreen:cursorTile"); }
  drawCursorTile(..._a: any[]): any { return notPorted("NamingScreen:drawCursorTile"); }
  drawCursorBox(..._a: any[]): any { return notPorted("NamingScreen:drawCursorBox"); }
  clearPanel(..._a: any[]): any { return notPorted("NamingScreen:clearPanel"); }
  drawEntry(..._a: any[]): any { return notPorted("NamingScreen:drawEntry"); }
  drawPanel(..._a: any[]): any { return notPorted("NamingScreen:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("NamingScreen:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("NamingScreen:drawWidescreen"); }
  cursorCharacter(..._a: any[]): any { return notPorted("NamingScreen:cursorCharacter"); }
}
export default NamingScreen;
