// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/OakSpeech.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class OakSpeech {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static FRONTPIC_BGP: any = undefined;
  static FRONTPIC_STEP: any = undefined;
  static ROTATE_FRAMES: any = undefined;
  static WIPE_FRAMES: any = undefined;
  static SHRINK_MUSIC_FADE: any = undefined;
  static SHRINK_PIC1: any = undefined;
  static SHRINK_PIC2: any = undefined;
  static SHRINK_CLEAR: any = undefined;
  static SHRINK_ICON: any = undefined;
  static SHRINK_END: any = undefined;
  static frontpicBgp(..._a: any[]): any { return notPorted("OakSpeech.frontpicBgp"); }
  static new(..._a: any[]): any { return notPorted("OakSpeech.new"); }
  static defaultSteps(..._a: any[]): any { return notPorted("OakSpeech.defaultSteps"); }
  wantsFillScale(..._a: any[]): any { return notPorted("OakSpeech:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("OakSpeech:drawsWidescreen"); }
  gender(..._a: any[]): any { return notPorted("OakSpeech:gender"); }
  playerPicNow(..._a: any[]): any { return notPorted("OakSpeech:playerPicNow"); }
  text(..._a: any[]): any { return notPorted("OakSpeech:text"); }
  buildSteps(..._a: any[]): any { return notPorted("OakSpeech:buildSteps"); }
  startMusic(..._a: any[]): any { return notPorted("OakSpeech:startMusic"); }
  enter(..._a: any[]): any { return notPorted("OakSpeech:enter"); }
  resolvePic(..._a: any[]): any { return notPorted("OakSpeech:resolvePic"); }
  applyPic(..._a: any[]): any { return notPorted("OakSpeech:applyPic"); }
  reveal(..._a: any[]): any { return notPorted("OakSpeech:reveal"); }
  afterReveal(..._a: any[]): any { return notPorted("OakSpeech:afterReveal"); }
  showPic(..._a: any[]): any { return notPorted("OakSpeech:showPic"); }
  playCry(..._a: any[]): any { return notPorted("OakSpeech:playCry"); }
  playMarillCry(..._a: any[]): any { return notPorted("OakSpeech:playMarillCry"); }
  runCry(..._a: any[]): any { return notPorted("OakSpeech:runCry"); }
  stepText(..._a: any[]): any { return notPorted("OakSpeech:stepText"); }
  sayText(..._a: any[]): any { return notPorted("OakSpeech:sayText"); }
  say(..._a: any[]): any { return notPorted("OakSpeech:say"); }
  openInitClock(..._a: any[]): any { return notPorted("OakSpeech:openInitClock"); }
  openGenderSelect(..._a: any[]): any { return notPorted("OakSpeech:openGenderSelect"); }
  openNamePick(..._a: any[]): any { return notPorted("OakSpeech:openNamePick"); }
  lastPageLines(..._a: any[]): any { return notPorted("OakSpeech:lastPageLines"); }
  startShrink(..._a: any[]): any { return notPorted("OakSpeech:startShrink"); }
  overworldIcon(..._a: any[]): any { return notPorted("OakSpeech:overworldIcon"); }
  recordAnswer(..._a: any[]): any { return notPorted("OakSpeech:recordAnswer"); }
  openChoice(..._a: any[]): any { return notPorted("OakSpeech:openChoice"); }
  leaveBeat(..._a: any[]): any { return notPorted("OakSpeech:leaveBeat"); }
  runStep(..._a: any[]): any { return notPorted("OakSpeech:runStep"); }
  advance(..._a: any[]): any { return notPorted("OakSpeech:advance"); }
  finish(..._a: any[]): any { return notPorted("OakSpeech:finish"); }
  update(..._a: any[]): any { return notPorted("OakSpeech:update"); }
  drawPic(..._a: any[]): any { return notPorted("OakSpeech:drawPic"); }
  drawPlayerIcon(..._a: any[]): any { return notPorted("OakSpeech:drawPlayerIcon"); }
  screenPalette(..._a: any[]): any { return notPorted("OakSpeech:screenPalette"); }
  drawPanel(..._a: any[]): any { return notPorted("OakSpeech:drawPanel"); }
  drawBody(..._a: any[]): any { return notPorted("OakSpeech:drawBody"); }
  draw(..._a: any[]): any { return notPorted("OakSpeech:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("OakSpeech:drawWidescreen"); }
}
export default OakSpeech;
