// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/PcMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class PcMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static ENTRIES: any = undefined;
  static new(..._a: any[]): any { return notPorted("PcMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("PcMenu:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("PcMenu:drawsWidescreen"); }
  notice(..._a: any[]): any { return notPorted("PcMenu:notice"); }
  playSfx(..._a: any[]): any { return notPorted("PcMenu:playSfx"); }
  close(..._a: any[]): any { return notPorted("PcMenu:close"); }
  beginChangeBox(..._a: any[]): any { return notPorted("PcMenu:beginChangeBox"); }
  refuseChangeBox(..._a: any[]): any { return notPorted("PcMenu:refuseChangeBox"); }
  setSavePhase(..._a: any[]): any { return notPorted("PcMenu:setSavePhase"); }
  acceptChangeBox(..._a: any[]): any { return notPorted("PcMenu:acceptChangeBox"); }
  writeChangeBox(..._a: any[]): any { return notPorted("PcMenu:writeChangeBox"); }
  savePromptText(..._a: any[]): any { return notPorted("PcMenu:savePromptText"); }
  savePages(..._a: any[]): any { return notPorted("PcMenu:savePages"); }
  savePrompt(..._a: any[]): any { return notPorted("PcMenu:savePrompt"); }
  saveYesNoVisible(..._a: any[]): any { return notPorted("PcMenu:saveYesNoVisible"); }
  updateChangeBox(..._a: any[]): any { return notPorted("PcMenu:updateChangeBox"); }
  choose(..._a: any[]): any { return notPorted("PcMenu:choose"); }
  update(..._a: any[]): any { return notPorted("PcMenu:update"); }
  drawPanel(..._a: any[]): any { return notPorted("PcMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("PcMenu:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("PcMenu:drawWidescreen"); }
}
export default PcMenu;
