// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/PokedexMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class PokedexMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static SEARCH_TYPES: any = undefined;
  static OPTION_MODES: any = undefined;
  static UNOWN_COORDS: any = undefined;
  static MODES: any = undefined;
  static printNumString: any = undefined;
  static new(..._a: any[]): any { return notPorted("PokedexMenu.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("PokedexMenu:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("PokedexMenu:drawsWidescreen"); }
  mode(..._a: any[]): any { return notPorted("PokedexMenu:mode"); }
  styled(..._a: any[]): any { return notPorted("PokedexMenu:styled"); }
  order(..._a: any[]): any { return notPorted("PokedexMenu:order"); }
  rebuild(..._a: any[]): any { return notPorted("PokedexMenu:rebuild"); }
  ensureVisible(..._a: any[]): any { return notPorted("PokedexMenu:ensureVisible"); }
  current(..._a: any[]): any { return notPorted("PokedexMenu:current"); }
  totals(..._a: any[]): any { return notPorted("PokedexMenu:totals"); }
  cursorVisible(..._a: any[]): any { return notPorted("PokedexMenu:cursorVisible"); }
  close(..._a: any[]): any { return notPorted("PokedexMenu:close"); }
  update(..._a: any[]): any { return notPorted("PokedexMenu:update"); }
  monName(..._a: any[]): any { return notPorted("PokedexMenu:monName"); }
  picFor(..._a: any[]): any { return notPorted("PokedexMenu:picFor"); }
  questionMark(..._a: any[]): any { return notPorted("PokedexMenu:questionMark"); }
  drawPic(..._a: any[]): any { return notPorted("PokedexMenu:drawPic"); }
  drawFootprint(..._a: any[]): any { return notPorted("PokedexMenu:drawFootprint"); }
  tile(..._a: any[]): any { return notPorted("PokedexMenu:tile"); }
  fill(..._a: any[]): any { return notPorted("PokedexMenu:fill"); }
  text(..._a: any[]): any { return notPorted("PokedexMenu:text"); }
  blank(..._a: any[]): any { return notPorted("PokedexMenu:blank"); }
  border(..._a: any[]): any { return notPorted("PokedexMenu:border"); }
  drawMainBackground(..._a: any[]): any { return notPorted("PokedexMenu:drawMainBackground"); }
  drawMainWindow(..._a: any[]): any { return notPorted("PokedexMenu:drawMainWindow"); }
  drawCursorObjs(..._a: any[]): any { return notPorted("PokedexMenu:drawCursorObjs"); }
  drawList(..._a: any[]): any { return notPorted("PokedexMenu:drawList"); }
  printEntry(..._a: any[]): any { return notPorted("PokedexMenu:printEntry"); }
  playCry(..._a: any[]): any { return notPorted("PokedexMenu:playCry"); }
  areaRegionName(..._a: any[]): any { return notPorted("PokedexMenu:areaRegionName"); }
  drawTilemap(..._a: any[]): any { return notPorted("PokedexMenu:drawTilemap"); }
  updateArea(..._a: any[]): any { return notPorted("PokedexMenu:updateArea"); }
  nestIconColors(..._a: any[]): any { return notPorted("PokedexMenu:nestIconColors"); }
  drawNestIcon(..._a: any[]): any { return notPorted("PokedexMenu:drawNestIcon"); }
  drawAreaHeader(..._a: any[]): any { return notPorted("PokedexMenu:drawAreaHeader"); }
  drawArea(..._a: any[]): any { return notPorted("PokedexMenu:drawArea"); }
  drawEntry(..._a: any[]): any { return notPorted("PokedexMenu:drawEntry"); }
  drawEntryBody(..._a: any[]): any { return notPorted("PokedexMenu:drawEntryBody"); }
  drawPlain(..._a: any[]): any { return notPorted("PokedexMenu:drawPlain"); }
  unownUnlocked(..._a: any[]): any { return notPorted("PokedexMenu:unownUnlocked"); }
  optionRows(..._a: any[]): any { return notPorted("PokedexMenu:optionRows"); }
  updateOption(..._a: any[]): any { return notPorted("PokedexMenu:updateOption"); }
  unownDex(..._a: any[]): any { return notPorted("PokedexMenu:unownDex"); }
  updateUnown(..._a: any[]): any { return notPorted("PokedexMenu:updateUnown"); }
  drawUnown(..._a: any[]): any { return notPorted("PokedexMenu:drawUnown"); }
  unownGlyph(..._a: any[]): any { return notPorted("PokedexMenu:unownGlyph"); }
  unownText(..._a: any[]): any { return notPorted("PokedexMenu:unownText"); }
  unownCursor(..._a: any[]): any { return notPorted("PokedexMenu:unownCursor"); }
  drawUnownPic(..._a: any[]): any { return notPorted("PokedexMenu:drawUnownPic"); }
  updateSearch(..._a: any[]): any { return notPorted("PokedexMenu:updateSearch"); }
  searchTypeName(..._a: any[]): any { return notPorted("PokedexMenu:searchTypeName"); }
  searchTypeId(..._a: any[]): any { return notPorted("PokedexMenu:searchTypeId"); }
  beginSearch(..._a: any[]): any { return notPorted("PokedexMenu:beginSearch"); }
  drawOption(..._a: any[]): any { return notPorted("PokedexMenu:drawOption"); }
  drawSearch(..._a: any[]): any { return notPorted("PokedexMenu:drawSearch"); }
  drawPanel(..._a: any[]): any { return notPorted("PokedexMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("PokedexMenu:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("PokedexMenu:drawWidescreen"); }
}
export default PokedexMenu;
