// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/SaveMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class SaveMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static PANEL: any = undefined;
  static SFX_SAVE: any = undefined;
  static SAVING_FRAMES: any = undefined;
  static SAVED_GAP_FRAMES: any = undefined;
  static SAVED_TAIL_FRAMES: any = undefined;
  static SAVED_FRAMES: any = undefined;
  static OVERWRITE_PROMPT_SOURCE: any = undefined;
  static SAVING_PROMPT_SOURCE: any = undefined;
  static pagesOf: any = undefined;
  static DOWN_ARROW: any = undefined;
  static new(..._a: any[]): any { return notPorted("SaveMenu.new"); }
  static playSaveSfx(..._a: any[]): any { return notPorted("SaveMenu.playSaveSfx"); }
  wantsFillScale(..._a: any[]): any { return notPorted("SaveMenu:wantsFillScale"); }
  playSfx(..._a: any[]): any { return notPorted("SaveMenu:playSfx"); }
  playSfxNamed(..._a: any[]): any { return notPorted("SaveMenu:playSfxNamed"); }
  finish(..._a: any[]): any { return notPorted("SaveMenu:finish"); }
  playerName(..._a: any[]): any { return notPorted("SaveMenu:playerName"); }
  writeNow(..._a: any[]): any { return notPorted("SaveMenu:writeNow"); }
  enterPhase(..._a: any[]): any { return notPorted("SaveMenu:enterPhase"); }
  accept(..._a: any[]): any { return notPorted("SaveMenu:accept"); }
  update(..._a: any[]): any { return notPorted("SaveMenu:update"); }
  promptText(..._a: any[]): any { return notPorted("SaveMenu:promptText"); }
  prompt(..._a: any[]): any { return notPorted("SaveMenu:prompt"); }
  yesNoVisible(..._a: any[]): any { return notPorted("SaveMenu:yesNoVisible"); }
  drawPanel(..._a: any[]): any { return notPorted("SaveMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("SaveMenu:draw"); }
}
export default SaveMenu;
