// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/SlotMachine.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class SlotMachine {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static SEVEN: any = undefined;
  static POKEBALL: any = undefined;
  static CHERRY: any = undefined;
  static PIKACHU: any = undefined;
  static SQUIRTLE: any = undefined;
  static STARYU: any = undefined;
  static NO_MATCH: any = undefined;
  static NO_BIAS: any = undefined;
  static NAMES: any = undefined;
  static LABELS: any = undefined;
  static PAYOUTS: any = undefined;
  static REEL_SIZE: any = undefined;
  static REELS: any = undefined;
  static LINES: any = undefined;
  static BIAS_NORMAL: any = undefined;
  static BIAS_LUCKY: any = undefined;
  static MANIP_COUNTER: any = undefined;
  static REEL3_STOP: any = undefined;
  static REEL3_SLOW: any = undefined;
  static REEL3_GOLEM: any = undefined;
  static REEL3_EGG: any = undefined;
  static EGG_DROP: any = undefined;
  static TEXTS: any = undefined;
  static payout(..._a: any[]): any { return notPorted("SlotMachine.payout"); }
  static window(..._a: any[]): any { return notPorted("SlotMachine.window"); }
  static advance(..._a: any[]): any { return notPorted("SlotMachine.advance"); }
  static matchAll(..._a: any[]): any { return notPorted("SlotMachine.matchAll"); }
  static matchFirstTwo(..._a: any[]): any { return notPorted("SlotMachine.matchFirstTwo"); }
  static initBias(..._a: any[]): any { return notPorted("SlotMachine.initBias"); }
  static rollKeepSevenChance(..._a: any[]): any { return notPorted("SlotMachine.rollKeepSevenChance"); }
  static keepSevenBias(..._a: any[]): any { return notPorted("SlotMachine.keepSevenBias"); }
  static stopReel1(..._a: any[]): any { return notPorted("SlotMachine.stopReel1"); }
  static stopReel2(..._a: any[]): any { return notPorted("SlotMachine.stopReel2"); }
  static stopReel3(..._a: any[]): any { return notPorted("SlotMachine.stopReel3"); }
  static reel2SkipsToSeven(..._a: any[]): any { return notPorted("SlotMachine.reel2SkipsToSeven"); }
  static spinReel2ToSevens(..._a: any[]): any { return notPorted("SlotMachine.spinReel2ToSevens"); }
  static reel3Action(..._a: any[]): any { return notPorted("SlotMachine.reel3Action"); }
  static slowAdvance(..._a: any[]): any { return notPorted("SlotMachine.slowAdvance"); }
  static golemCount(..._a: any[]): any { return notPorted("SlotMachine.golemCount"); }
  static eggDrops(..._a: any[]): any { return notPorted("SlotMachine.eggDrops"); }
  static spin(..._a: any[]): any { return notPorted("SlotMachine.spin"); }
  static new(..._a: any[]): any { return notPorted("SlotMachine.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("SlotMachine:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("SlotMachine:drawsWidescreen"); }
  playMusic(..._a: any[]): any { return notPorted("SlotMachine:playMusic"); }
  sfx(..._a: any[]): any { return notPorted("SlotMachine:sfx"); }
  coins(..._a: any[]): any { return notPorted("SlotMachine:coins"); }
  enterInit(..._a: any[]): any { return notPorted("SlotMachine:enterInit"); }
  updateBet(..._a: any[]): any { return notPorted("SlotMachine:updateBet"); }
  startSpin(..._a: any[]): any { return notPorted("SlotMachine:startSpin"); }
  spinReels(..._a: any[]): any { return notPorted("SlotMachine:spinReels"); }
  reelWindow(..._a: any[]): any { return notPorted("SlotMachine:reelWindow"); }
  pressStop(..._a: any[]): any { return notPorted("SlotMachine:pressStop"); }
  reelStopped(..._a: any[]): any { return notPorted("SlotMachine:reelStopped"); }
  beginPayout(..._a: any[]): any { return notPorted("SlotMachine:beginPayout"); }
  updatePayoutAnim(..._a: any[]): any { return notPorted("SlotMachine:updatePayoutAnim"); }
  enterAgain(..._a: any[]): any { return notPorted("SlotMachine:enterAgain"); }
  quit(..._a: any[]): any { return notPorted("SlotMachine:quit"); }
  update(..._a: any[]): any { return notPorted("SlotMachine:update"); }
  sheets(..._a: any[]): any { return notPorted("SlotMachine:sheets"); }
  drawBackground(..._a: any[]): any { return notPorted("SlotMachine:drawBackground"); }
  drawReels(..._a: any[]): any { return notPorted("SlotMachine:drawReels"); }
  actorsImage(..._a: any[]): any { return notPorted("SlotMachine:actorsImage"); }
  drawOverlays(..._a: any[]): any { return notPorted("SlotMachine:drawOverlays"); }
  drawMessage(..._a: any[]): any { return notPorted("SlotMachine:drawMessage"); }
  drawPanel(..._a: any[]): any { return notPorted("SlotMachine:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("SlotMachine:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("SlotMachine:drawWidescreen"); }
}
export default SlotMachine;
