// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/StartMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class StartMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static lastIndex: any = undefined;
  static ITEMS: any = undefined;
  static new(..._a: any[]): any { return notPorted("StartMenu.new"); }
  availability(..._a: any[]): any { return notPorted("StartMenu:availability"); }
  visibleItems(..._a: any[]): any { return notPorted("StartMenu:visibleItems"); }
  playSfx(..._a: any[]): any { return notPorted("StartMenu:playSfx"); }
  enter(..._a: any[]): any { return notPorted("StartMenu:enter"); }
  choose(..._a: any[]): any { return notPorted("StartMenu:choose"); }
  confirmQuit(..._a: any[]): any { return notPorted("StartMenu:confirmQuit"); }
  confirmQuitContest(..._a: any[]): any { return notPorted("StartMenu:confirmQuitContest"); }
  close(..._a: any[]): any { return notPorted("StartMenu:close"); }
  update(..._a: any[]): any { return notPorted("StartMenu:update"); }
  drawContestStatus(..._a: any[]): any { return notPorted("StartMenu:drawContestStatus"); }
  draw(..._a: any[]): any { return notPorted("StartMenu:draw"); }
}
export default StartMenu;
