// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/SummaryMenu.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class SummaryMenu {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static PINK_PAGE: any = undefined;
  static GREEN_PAGE: any = undefined;
  static BLUE_PAGE: any = undefined;
  static NUM_STAT_PAGES: any = undefined;
  static STAT_LABELS: any = undefined;
  static STAT_KEYS: any = undefined;
  static PAGE_PALETTES: any = undefined;
  static PAGE_TINTS: any = undefined;
  static levelText: any = undefined;
  static at(..._a: any[]): any { return notPorted("SummaryMenu.at"); }
  static new(..._a: any[]): any { return notPorted("SummaryMenu.new"); }
  static otColumn(..._a: any[]): any { return notPorted("SummaryMenu.otColumn"); }
  wantsFillScale(..._a: any[]): any { return notPorted("SummaryMenu:wantsFillScale"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("SummaryMenu:drawsWidescreen"); }
  playCry(..._a: any[]): any { return notPorted("SummaryMenu:playCry"); }
  startPicAnim(..._a: any[]): any { return notPorted("SummaryMenu:startPicAnim"); }
  stepPicAnim(..._a: any[]): any { return notPorted("SummaryMenu:stepPicAnim"); }
  picAnimFrame(..._a: any[]): any { return notPorted("SummaryMenu:picAnimFrame"); }
  speciesDef(..._a: any[]): any { return notPorted("SummaryMenu:speciesDef"); }
  moveDef(..._a: any[]): any { return notPorted("SummaryMenu:moveDef"); }
  moveList(..._a: any[]): any { return notPorted("SummaryMenu:moveList"); }
  moveName(..._a: any[]): any { return notPorted("SummaryMenu:moveName"); }
  growth(..._a: any[]): any { return notPorted("SummaryMenu:growth"); }
  expToNext(..._a: any[]): any { return notPorted("SummaryMenu:expToNext"); }
  otName(..._a: any[]): any { return notPorted("SummaryMenu:otName"); }
  otId(..._a: any[]): any { return notPorted("SummaryMenu:otId"); }
  itemName(..._a: any[]): any { return notPorted("SummaryMenu:itemName"); }
  typeNames(..._a: any[]): any { return notPorted("SummaryMenu:typeNames"); }
  upperPlacements(..._a: any[]): any { return notPorted("SummaryMenu:upperPlacements"); }
  pinkPlacements(..._a: any[]): any { return notPorted("SummaryMenu:pinkPlacements"); }
  greenPlacements(..._a: any[]): any { return notPorted("SummaryMenu:greenPlacements"); }
  bluePlacements(..._a: any[]): any { return notPorted("SummaryMenu:bluePlacements"); }
  moveDetailPlacements(..._a: any[]): any { return notPorted("SummaryMenu:moveDetailPlacements"); }
  eggPlacements(..._a: any[]): any { return notPorted("SummaryMenu:eggPlacements"); }
  placements(..._a: any[]): any { return notPorted("SummaryMenu:placements"); }
  close(..._a: any[]): any { return notPorted("SummaryMenu:close"); }
  turnPage(..._a: any[]): any { return notPorted("SummaryMenu:turnPage"); }
  switchMon(..._a: any[]): any { return notPorted("SummaryMenu:switchMon"); }
  switchMonPastEggs(..._a: any[]): any { return notPorted("SummaryMenu:switchMonPastEggs"); }
  swapMoves(..._a: any[]): any { return notPorted("SummaryMenu:swapMoves"); }
  playSwapSfx(..._a: any[]): any { return notPorted("SummaryMenu:playSwapSfx"); }
  playSwapSfxTwice(..._a: any[]): any { return notPorted("SummaryMenu:playSwapSfxTwice"); }
  tickRepeatSfx(..._a: any[]): any { return notPorted("SummaryMenu:tickRepeatSfx"); }
  updateMoveDetail(..._a: any[]): any { return notPorted("SummaryMenu:updateMoveDetail"); }
  update(..._a: any[]): any { return notPorted("SummaryMenu:update"); }
  statsTiles(..._a: any[]): any { return notPorted("SummaryMenu:statsTiles"); }
  pageTile(..._a: any[]): any { return notPorted("SummaryMenu:pageTile"); }
  drawPageSquare(..._a: any[]): any { return notPorted("SummaryMenu:drawPageSquare"); }
  drawPageIndicators(..._a: any[]): any { return notPorted("SummaryMenu:drawPageIndicators"); }
  picImage(..._a: any[]): any { return notPorted("SummaryMenu:picImage"); }
  picCtx(..._a: any[]): any { return notPorted("SummaryMenu:picCtx"); }
  picPath(..._a: any[]): any { return notPorted("SummaryMenu:picPath"); }
  picFor(..._a: any[]): any { return notPorted("SummaryMenu:picFor"); }
  drawPicBlock(..._a: any[]): any { return notPorted("SummaryMenu:drawPicBlock"); }
  drawPic(..._a: any[]): any { return notPorted("SummaryMenu:drawPic"); }
  drawEggPic(..._a: any[]): any { return notPorted("SummaryMenu:drawEggPic"); }
  drawEggIconFallback(..._a: any[]): any { return notPorted("SummaryMenu:drawEggIconFallback"); }
  drawPlacements(..._a: any[]): any { return notPorted("SummaryMenu:drawPlacements"); }
  drawHorizontalDivider(..._a: any[]): any { return notPorted("SummaryMenu:drawHorizontalDivider"); }
  lowerColors(..._a: any[]): any { return notPorted("SummaryMenu:lowerColors"); }
  drawPageBackground(..._a: any[]): any { return notPorted("SummaryMenu:drawPageBackground"); }
  drawVerticalDivider(..._a: any[]): any { return notPorted("SummaryMenu:drawVerticalDivider"); }
  drawUpperHalf(..._a: any[]): any { return notPorted("SummaryMenu:drawUpperHalf"); }
  drawPinkPage(..._a: any[]): any { return notPorted("SummaryMenu:drawPinkPage"); }
  drawGreenPage(..._a: any[]): any { return notPorted("SummaryMenu:drawGreenPage"); }
  drawBluePage(..._a: any[]): any { return notPorted("SummaryMenu:drawBluePage"); }
  drawMoveDetail(..._a: any[]): any { return notPorted("SummaryMenu:drawMoveDetail"); }
  drawEggPage(..._a: any[]): any { return notPorted("SummaryMenu:drawEggPage"); }
  drawPanel(..._a: any[]): any { return notPorted("SummaryMenu:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("SummaryMenu:draw"); }
  drawWidescreen(..._a: any[]): any { return notPorted("SummaryMenu:drawWidescreen"); }
}
export default SummaryMenu;
