// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/TileSheet.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class TileSheet {
  [key: string]: any;
  static [key: string]: any;
  static new(..._a: any[]): any { return notPorted("TileSheet.new"); }
  image(..._a: any[]): any { return notPorted("TileSheet:image"); }
  available(..._a: any[]): any { return notPorted("TileSheet:available"); }
  quad(..._a: any[]): any { return notPorted("TileSheet:quad"); }
  draw(..._a: any[]): any { return notPorted("TileSheet:draw"); }
  run(..._a: any[]): any { return notPorted("TileSheet:run"); }
  block(..._a: any[]): any { return notPorted("TileSheet:block"); }
}
export default TileSheet;
