// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/UnownPuzzle.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class UnownPuzzle {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static BORDER_TILE: any = undefined;
  static VOID_TILE: any = undefined;
  static PALETTE: any = undefined;
  static CURSOR_PALETTE: any = undefined;
  static COLUMNS: any = undefined;
  static ROWS: any = undefined;
  static CELLS: any = undefined;
  static PIECES: any = undefined;
  static PIECE_TILES: any = undefined;
  static PIECES_WIDE: any = undefined;
  static puzcoord: any = undefined;
  static START_CELLS: any = undefined;
  static SOLVED: any = undefined;
  static CAPTION: any = undefined;
  static deal(..._a: any[]): any { return notPorted("UnownPuzzle.deal"); }
  static isSolved(..._a: any[]): any { return notPorted("UnownPuzzle.isSolved"); }
  static moveCursor(..._a: any[]): any { return notPorted("UnownPuzzle.moveCursor"); }
  static cellTile(..._a: any[]): any { return notPorted("UnownPuzzle.cellTile"); }
  static vacantTile(..._a: any[]): any { return notPorted("UnownPuzzle.vacantTile"); }
  static new(..._a: any[]): any { return notPorted("UnownPuzzle.new"); }
  gfx(..._a: any[]): any { return notPorted("UnownPuzzle:gfx"); }
  loadGfx(..._a: any[]): any { return notPorted("UnownPuzzle:loadGfx"); }
  sfx(..._a: any[]): any { return notPorted("UnownPuzzle:sfx"); }
  occupant(..._a: any[]): any { return notPorted("UnownPuzzle:occupant"); }
  pressA(..._a: any[]): any { return notPorted("UnownPuzzle:pressA"); }
  quit(..._a: any[]): any { return notPorted("UnownPuzzle:quit"); }
  step(..._a: any[]): any { return notPorted("UnownPuzzle:step"); }
  update(..._a: any[]): any { return notPorted("UnownPuzzle:update"); }
  drawTile(..._a: any[]): any { return notPorted("UnownPuzzle:drawTile"); }
  fillCell(..._a: any[]): any { return notPorted("UnownPuzzle:fillCell"); }
  drawPiece(..._a: any[]): any { return notPorted("UnownPuzzle:drawPiece"); }
  drawCursor(..._a: any[]): any { return notPorted("UnownPuzzle:drawCursor"); }
  drawStartCancel(..._a: any[]): any { return notPorted("UnownPuzzle:drawStartCancel"); }
  drawPanel(..._a: any[]): any { return notPorted("UnownPuzzle:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("UnownPuzzle:draw"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("UnownPuzzle:drawsWidescreen"); }
  drawWidescreen(..._a: any[]): any { return notPorted("UnownPuzzle:drawWidescreen"); }
}
export default UnownPuzzle;
