// @gen2-stub
// Not ported yet: gen1recomp src/ui/gen2/UnownPrinter.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class UnownPrinter {
  [key: string]: any;
  static [key: string]: any;
  static isOpaque: any = undefined;
  static new(..._a: any[]): any { return notPorted("UnownPrinter.new"); }
  wantsFillScale(..._a: any[]): any { return notPorted("UnownPrinter:wantsFillScale"); }
  slots(..._a: any[]): any { return notPorted("UnownPrinter:slots"); }
  letter(..._a: any[]): any { return notPorted("UnownPrinter:letter"); }
  finish(..._a: any[]): any { return notPorted("UnownPrinter:finish"); }
  update(..._a: any[]): any { return notPorted("UnownPrinter:update"); }
  picFor(..._a: any[]): any { return notPorted("UnownPrinter:picFor"); }
  drawPic(..._a: any[]): any { return notPorted("UnownPrinter:drawPic"); }
  drawPanel(..._a: any[]): any { return notPorted("UnownPrinter:drawPanel"); }
  draw(..._a: any[]): any { return notPorted("UnownPrinter:draw"); }
  drawsWidescreen(..._a: any[]): any { return notPorted("UnownPrinter:drawsWidescreen"); }
  drawWidescreen(..._a: any[]): any { return notPorted("UnownPrinter:drawWidescreen"); }
}
export default UnownPrinter;
