// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/CmdQueue.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const CmdQueue: Record<string, any> = {
  CAPACITY: undefined,
  NULL: undefined,
  TYPE1: undefined,
  STONETABLE: undefined,
  TYPE3: undefined,
  TYPE4: undefined,
  NUM_TYPES: undefined,
  BOULDER_MOVEDATA: undefined,
  STONE_TABLES: undefined,
  new: (..._a: any[]): any => notPorted("CmdQueue.new"),
  clear: (..._a: any[]): any => notPorted("CmdQueue.clear"),
  write: (..._a: any[]): any => notPorted("CmdQueue.write"),
  delete: (..._a: any[]): any => notPorted("CmdQueue.delete"),
  count: (..._a: any[]): any => notPorted("CmdQueue.count"),
  warpNumberAt: (..._a: any[]): any => notPorted("CmdQueue.warpNumberAt"),
  stoneRow: (..._a: any[]): any => notPorted("CmdQueue.stoneRow"),
  stoneFall: (..._a: any[]): any => notPorted("CmdQueue.stoneFall"),
  poll: (..._a: any[]): any => notPorted("CmdQueue.poll"),
  mapEntry: (..._a: any[]): any => notPorted("CmdQueue.mapEntry"),
  fromExtracted: (..._a: any[]): any => notPorted("CmdQueue.fromExtracted"),
};
export default CmdQueue;
