// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/HiddenItems.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const HiddenItems: Record<string, any> = {
  BGEVENT_ITEM: undefined,
  dataOf: (..._a: any[]): any => notPorted("HiddenItems.dataOf"),
  unfound: (..._a: any[]): any => notPorted("HiddenItems.unfound"),
  onScreen: (..._a: any[]): any => notPorted("HiddenItems.onScreen"),
  nearby: (..._a: any[]): any => notPorted("HiddenItems.nearby"),
  at: (..._a: any[]): any => notPorted("HiddenItems.at"),
  pickupScript: (..._a: any[]): any => notPorted("HiddenItems.pickupScript"),
  ballPickupScript: (..._a: any[]): any => notPorted("HiddenItems.ballPickupScript"),
  itemfinderScript: (..._a: any[]): any => notPorted("HiddenItems.itemfinderScript"),
};
export default HiddenItems;
