// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/Map.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class Map {
  [key: string]: any;
  static [key: string]: any;
  static DELTA: any = undefined;
  static new(..._a: any[]): any { return notPorted("Map.new"); }
  static isOutside(..._a: any[]): any { return notPorted("Map.isOutside"); }
  static isOutdoor(..._a: any[]): any { return notPorted("Map.isOutdoor"); }
  static inRegion(..._a: any[]): any { return notPorted("Map.inRegion"); }
  static isPushable(..._a: any[]): any { return notPorted("Map.isPushable"); }
  static defCellTile(..._a: any[]): any { return notPorted("Map.defCellTile"); }
  static defIsWalkableCell(..._a: any[]): any { return notPorted("Map.defIsWalkableCell"); }
  static defIsWaterCell(..._a: any[]): any { return notPorted("Map.defIsWaterCell"); }
  static defPassable(..._a: any[]): any { return notPorted("Map.defPassable"); }
  static connectionLanding(..._a: any[]): any { return notPorted("Map.connectionLanding"); }
  inBounds(..._a: any[]): any { return notPorted("Map:inBounds"); }
  blockId(..._a: any[]): any { return notPorted("Map:blockId"); }
  cellCollision(..._a: any[]): any { return notPorted("Map:cellCollision"); }
  isWalkable(..._a: any[]): any { return notPorted("Map:isWalkable"); }
  cellTile(..._a: any[]): any { return notPorted("Map:cellTile"); }
  isWalkableCell(..._a: any[]): any { return notPorted("Map:isWalkableCell"); }
  isWaterCell(..._a: any[]): any { return notPorted("Map:isWaterCell"); }
  isGrassCell(..._a: any[]): any { return notPorted("Map:isGrassCell"); }
  warpAt(..._a: any[]): any { return notPorted("Map:warpAt"); }
  warpAtCell(..._a: any[]): any { return notPorted("Map:warpAtCell"); }
  isCounterCell(..._a: any[]): any { return notPorted("Map:isCounterCell"); }
  blockAt(..._a: any[]): any { return notPorted("Map:blockAt"); }
  setBlock(..._a: any[]): any { return notPorted("Map:setBlock"); }
  tileAt(..._a: any[]): any { return notPorted("Map:tileAt"); }
  isDoorTileCell(..._a: any[]): any { return notPorted("Map:isDoorTileCell"); }
  isWarpTileCell(..._a: any[]): any { return notPorted("Map:isWarpTileCell"); }
  signAtCell(..._a: any[]): any { return notPorted("Map:signAtCell"); }
  stepPermitted(..._a: any[]): any { return notPorted("Map:stepPermitted"); }
  objectStepPermitted(..._a: any[]): any { return notPorted("Map:objectStepPermitted"); }
  connection(..._a: any[]): any { return notPorted("Map:connection"); }
}
export default Map;
