// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/MapNameSign.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const MapNameSign: Record<string, any> = {
  TILES: undefined,
  DURATION: undefined,
  FRAMES_PER_TICK: undefined,
  SHEET: undefined,
  state: (..._a: any[]): any => notPorted("MapNameSign.state"),
  init: (..._a: any[]): any => notPorted("MapNameSign.init"),
  cancel: (..._a: any[]): any => notPorted("MapNameSign.cancel"),
  frame: (..._a: any[]): any => notPorted("MapNameSign.frame"),
  tick: (..._a: any[]): any => notPorted("MapNameSign.tick"),
  tiles: (..._a: any[]): any => notPorted("MapNameSign.tiles"),
  textX: (..._a: any[]): any => notPorted("MapNameSign.textX"),
  colors: (..._a: any[]): any => notPorted("MapNameSign.colors"),
  draw: (..._a: any[]): any => notPorted("MapNameSign.draw"),
};
export default MapNameSign;
