// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/MapPreview.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const MapPreview: Record<string, any> = {
  baker: (..._a: any[]): any => notPorted("MapPreview.baker"),
  atlasFor: (..._a: any[]): any => notPorted("MapPreview.atlasFor"),
  bake: (..._a: any[]): any => notPorted("MapPreview.bake"),
  imageFor: (..._a: any[]): any => notPorted("MapPreview.imageFor"),
  renderer: (..._a: any[]): any => notPorted("MapPreview.renderer"),
};
export default MapPreview;
