// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/Palettes.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Palettes: Record<string, any> = {
  DAYTIMES: undefined,
  DAYTIME_ID: undefined,
  OW_PALETTE_ID: undefined,
  BLACKOUT: undefined,
  PAL_BG_YELLOW: undefined,
  FLICKER_PERIOD: undefined,
  clockDaytime: (..._a: any[]): any => notPorted("Palettes.clockDaytime"),
  daytimeFor: (..._a: any[]): any => notPorted("Palettes.daytimeFor"),
  isDarkness: (..._a: any[]): any => notPorted("Palettes.isDarkness"),
  caveFlickerSource: (..._a: any[]): any => notPorted("Palettes.caveFlickerSource"),
  withCaveFlicker: (..._a: any[]): any => notPorted("Palettes.withCaveFlicker"),
  specialSet: (..._a: any[]): any => notPorted("Palettes.specialSet"),
  bgSet: (..._a: any[]): any => notPorted("Palettes.bgSet"),
  objectSet: (..._a: any[]): any => notPorted("Palettes.objectSet"),
  objectPaletteId: (..._a: any[]): any => notPorted("Palettes.objectPaletteId"),
  spritePalette: (..._a: any[]): any => notPorted("Palettes.spritePalette"),
  monColors: (..._a: any[]): any => notPorted("Palettes.monColors"),
  trainerColors: (..._a: any[]): any => notPorted("Palettes.trainerColors"),
  textColors: (..._a: any[]): any => notPorted("Palettes.textColors"),
};
export default Palettes;
