// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/Permissions.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Permissions: Record<string, any> = {
  LAND: undefined,
  WATER: undefined,
  WALL: undefined,
  of: (..._a: any[]): any => notPorted("Permissions.of"),
  isLand: (..._a: any[]): any => notPorted("Permissions.isLand"),
  isWater: (..._a: any[]): any => notPorted("Permissions.isWater"),
  isWall: (..._a: any[]): any => notPorted("Permissions.isWall"),
  isWalkable: (..._a: any[]): any => notPorted("Permissions.isWalkable"),
  surfable: (..._a: any[]): any => notPorted("Permissions.surfable"),
  isGrass: (..._a: any[]): any => notPorted("Permissions.isGrass"),
  isSuperTallGrass: (..._a: any[]): any => notPorted("Permissions.isSuperTallGrass"),
  isEncounterCollision: (..._a: any[]): any => notPorted("Permissions.isEncounterCollision"),
  isIce: (..._a: any[]): any => notPorted("Permissions.isIce"),
  isWhirlpool: (..._a: any[]): any => notPorted("Permissions.isWhirlpool"),
  isCutTree: (..._a: any[]): any => notPorted("Permissions.isCutTree"),
  isHeadbuttTree: (..._a: any[]): any => notPorted("Permissions.isHeadbuttTree"),
  isWaterfall: (..._a: any[]): any => notPorted("Permissions.isWaterfall"),
  isCounter: (..._a: any[]): any => notPorted("Permissions.isCounter"),
  currentDirection: (..._a: any[]): any => notPorted("Permissions.currentDirection"),
  doorForcedDirection: (..._a: any[]): any => notPorted("Permissions.doorForcedDirection"),
  isCuttable: (..._a: any[]): any => notPorted("Permissions.isCuttable"),
  isLedge: (..._a: any[]): any => notPorted("Permissions.isLedge"),
  ledgeFacings: (..._a: any[]): any => notPorted("Permissions.ledgeFacings"),
  isSideWall: (..._a: any[]): any => notPorted("Permissions.isSideWall"),
  sideBlocks: (..._a: any[]): any => notPorted("Permissions.sideBlocks"),
  neighborBlocks: (..._a: any[]): any => notPorted("Permissions.neighborBlocks"),
  neighborBlocksDown: (..._a: any[]): any => notPorted("Permissions.neighborBlocksDown"),
  stepPermitted: (..._a: any[]): any => notPorted("Permissions.stepPermitted"),
  entryBlocks: (..._a: any[]): any => notPorted("Permissions.entryBlocks"),
  objectStepPermitted: (..._a: any[]): any => notPorted("Permissions.objectStepPermitted"),
  isWarpCollision: (..._a: any[]): any => notPorted("Permissions.isWarpCollision"),
  carpetDirection: (..._a: any[]): any => notPorted("Permissions.carpetDirection"),
  warpFacesDown: (..._a: any[]): any => notPorted("Permissions.warpFacesDown"),
  isImmediateWarp: (..._a: any[]): any => notPorted("Permissions.isImmediateWarp"),
};
export default Permissions;
