// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/Player.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class Player {
  [key: string]: any;
  static [key: string]: any;
  static STEP_FRAMES: any = undefined;
  static new(..._a: any[]): any { return notPorted("Player.new"); }
  setSprite(..._a: any[]): any { return notPorted("Player:setSprite"); }
  tryMove(..._a: any[]): any { return notPorted("Player:tryMove"); }
  stopForEvent(..._a: any[]): any { return notPorted("Player:stopForEvent"); }
  scriptFace(..._a: any[]): any { return notPorted("Player:scriptFace"); }
  scriptStep(..._a: any[]): any { return notPorted("Player:scriptStep"); }
  scriptJump(..._a: any[]): any { return notPorted("Player:scriptJump"); }
  scriptSpin(..._a: any[]): any { return notPorted("Player:scriptSpin"); }
  facingCell(..._a: any[]): any { return notPorted("Player:facingCell"); }
  walkPhase(..._a: any[]): any { return notPorted("Player:walkPhase"); }
  drawFlip(..._a: any[]): any { return notPorted("Player:drawFlip"); }
  update(..._a: any[]): any { return notPorted("Player:update"); }
  drawFishing(..._a: any[]): any { return notPorted("Player:drawFishing"); }
  draw(..._a: any[]): any { return notPorted("Player:draw"); }
}
export default Player;
