// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/TrainerHouse.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const TrainerHouse: Record<string, any> = {
  CAL: undefined,
  ENGINE_FOUGHT_IN_TRAINER_HALL_TODAY: undefined,
  hasCustomTrainer: (..._a: any[]): any => notPorted("TrainerHouse.hasCustomTrainer"),
  resolveMember: (..._a: any[]): any => notPorted("TrainerHouse.resolveMember"),
  customName: (..._a: any[]): any => notPorted("TrainerHouse.customName"),
  lookup: (..._a: any[]): any => notPorted("TrainerHouse.lookup"),
  name: (..._a: any[]): any => notPorted("TrainerHouse.name"),
  foughtToday: (..._a: any[]): any => notPorted("TrainerHouse.foughtToday"),
};
export default TrainerHouse;
