// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/Trainers.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export const Trainers: Record<string, any> = {
  classIndex: undefined,
  DELTA: undefined,
  lookup: (..._a: any[]): any => notPorted("Trainers.lookup"),
  party: (..._a: any[]): any => notPorted("Trainers.party"),
  sees: (..._a: any[]): any => notPorted("Trainers.sees"),
  approach: (..._a: any[]): any => notPorted("Trainers.approach"),
};
export default Trainers;
