// @gen2-stub
// Not ported yet: gen1recomp src/world/gen2/WorldAPI.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../notported.ts";

export class WorldAPI {
  [key: string]: any;
  static [key: string]: any;
  static new(..._a: any[]): any { return notPorted("WorldAPI.new"); }
  overworld(..._a: any[]): any { return notPorted("WorldAPI:overworld"); }
  current(..._a: any[]): any { return notPorted("WorldAPI:current"); }
  canReorderParty(..._a: any[]): any { return notPorted("WorldAPI:canReorderParty"); }
  reorderParty(..._a: any[]): any { return notPorted("WorldAPI:reorderParty"); }
  availableFieldActions(..._a: any[]): any { return notPorted("WorldAPI:availableFieldActions"); }
  useFieldAction(..._a: any[]): any { return notPorted("WorldAPI:useFieldAction"); }
  effectiveEncounters(..._a: any[]): any { return notPorted("WorldAPI:effectiveEncounters"); }
  mapOverview(..._a: any[]): any { return notPorted("WorldAPI:mapOverview"); }
  warpTo(..._a: any[]): any { return notPorted("WorldAPI:warpTo"); }
  toggleObject(..._a: any[]): any { return notPorted("WorldAPI:toggleObject"); }
  setFlag(..._a: any[]): any { return notPorted("WorldAPI:setFlag"); }
  getFlag(..._a: any[]): any { return notPorted("WorldAPI:getFlag"); }
  replaceBlock(..._a: any[]): any { return notPorted("WorldAPI:replaceBlock"); }
  spawnNpc(..._a: any[]): any { return notPorted("WorldAPI:spawnNpc"); }
  removeNpc(..._a: any[]): any { return notPorted("WorldAPI:removeNpc"); }
  npc(..._a: any[]): any { return notPorted("WorldAPI:npc"); }
  queueScript(..._a: any[]): any { return notPorted("WorldAPI:queueScript"); }
  invalidateMap(..._a: any[]): any { return notPorted("WorldAPI:invalidateMap"); }
}
export default WorldAPI;
