// @gen2-stub
// Inert on the 3DS (desktop-only in gen1recomp src/mods/Gen2Compat.lua, bdfac727): every function returns undefined.
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.



export const Gen2Compat: Record<string, any> = {
  COVERAGE_VERSION: undefined,
  STATUS: undefined,
  ADAPTERS: undefined,
  worldTick: (..._a: any[]): any => undefined,
  interactWrapper: (..._a: any[]): any => undefined,
  talkToWrapper: (..._a: any[]): any => undefined,
  bind: (..._a: any[]): any => undefined,
  serves: (..._a: any[]): any => undefined,
  modules: (..._a: any[]): any => undefined,
  coverage: (..._a: any[]): any => undefined,
  memberStatus: (..._a: any[]): any => undefined,
  resolve: (..._a: any[]): any => undefined,
};
export default Gen2Compat;
