// @gen2-stub
// Not ported yet: gen1recomp src/mods/Gen2Compat.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export const Gen2Compat: Record<string, any> = {
  COVERAGE_VERSION: undefined,
  STATUS: undefined,
  ADAPTERS: undefined,
  worldTick: (..._a: any[]): any => notPorted("Gen2Compat.worldTick"),
  interactWrapper: (..._a: any[]): any => notPorted("Gen2Compat.interactWrapper"),
  talkToWrapper: (..._a: any[]): any => notPorted("Gen2Compat.talkToWrapper"),
  bind: (..._a: any[]): any => notPorted("Gen2Compat.bind"),
  serves: (..._a: any[]): any => notPorted("Gen2Compat.serves"),
  modules: (..._a: any[]): any => notPorted("Gen2Compat.modules"),
  coverage: (..._a: any[]): any => notPorted("Gen2Compat.coverage"),
  memberStatus: (..._a: any[]): any => notPorted("Gen2Compat.memberStatus"),
  resolve: (..._a: any[]): any => notPorted("Gen2Compat.resolve"),
};
export default Gen2Compat;
