// @gen2-stub
// Not ported yet: gen1recomp src/mods/Loader.lua at bdfac727 (MIT).
// Generated by tools/gen2_stubs.py; the port replaces this file wholesale.

import { notPorted } from "../../notported.ts";

export class Loader {
  [key: string]: any;
  static [key: string]: any;
  static ARENA_MODES: any = undefined;
  static endSession(..._a: any[]): any { return notPorted("Loader.endSession"); }
  static new(..._a: any[]): any { return notPorted("Loader.new"); }
  static pinTogglable(..._a: any[]): any { return notPorted("Loader.pinTogglable"); }
  static planCart(..._a: any[]): any { return notPorted("Loader.planCart"); }
  _installDevShim(..._a: any[]): any { return notPorted("Loader:_installDevShim"); }
  _targetVersion(..._a: any[]): any { return notPorted("Loader:_targetVersion"); }
  _enableScope(..._a: any[]): any { return notPorted("Loader:_enableScope"); }
  _loadState(..._a: any[]): any { return notPorted("Loader:_loadState"); }
  _saveState(..._a: any[]): any { return notPorted("Loader:_saveState"); }
  _writeOptionSchemas(..._a: any[]): any { return notPorted("Loader:_writeOptionSchemas"); }
  setEnabled(..._a: any[]): any { return notPorted("Loader:setEnabled"); }
  setGen2Forced(..._a: any[]): any { return notPorted("Loader:setGen2Forced"); }
  isGen2Forced(..._a: any[]): any { return notPorted("Loader:isGen2Forced"); }
  _discover(..._a: any[]): any { return notPorted("Loader:_discover"); }
  cartStatus(..._a: any[]): any { return notPorted("Loader:cartStatus"); }
  _arenaDisableAll(..._a: any[]): any { return notPorted("Loader:_arenaDisableAll"); }
  _arenaVerifyTranslations(..._a: any[]): any { return notPorted("Loader:_arenaVerifyTranslations"); }
  _arenaCart(..._a: any[]): any { return notPorted("Loader:_arenaCart"); }
  _applyCart(..._a: any[]): any { return notPorted("Loader:_applyCart"); }
  _cartRank(..._a: any[]): any { return notPorted("Loader:_cartRank"); }
  _fail(..._a: any[]): any { return notPorted("Loader:_fail"); }
  _skip(..._a: any[]): any { return notPorted("Loader:_skip"); }
  _target(..._a: any[]): any { return notPorted("Loader:_target"); }
  _gateGeneration(..._a: any[]): any { return notPorted("Loader:_gateGeneration"); }
  _exists(..._a: any[]): any { return notPorted("Loader:_exists"); }
  _validate(..._a: any[]): any { return notPorted("Loader:_validate"); }
  _enforceDependencies(..._a: any[]): any { return notPorted("Loader:_enforceDependencies"); }
  _failCycles(..._a: any[]): any { return notPorted("Loader:_failCycles"); }
  _enforceConflicts(..._a: any[]): any { return notPorted("Loader:_enforceConflicts"); }
  _order(..._a: any[]): any { return notPorted("Loader:_order"); }
  _mergeOrder(..._a: any[]): any { return notPorted("Loader:_mergeOrder"); }
  _resolve(..._a: any[]): any { return notPorted("Loader:_resolve"); }
  _contentApi(..._a: any[]): any { return notPorted("Loader:_contentApi"); }
  _registerCommand(..._a: any[]): any { return notPorted("Loader:_registerCommand"); }
  _modInput(..._a: any[]): any { return notPorted("Loader:_modInput"); }
  releaseModInput(..._a: any[]): any { return notPorted("Loader:releaseModInput"); }
  _api(..._a: any[]): any { return notPorted("Loader:_api"); }
  _game(..._a: any[]): any { return notPorted("Loader:_game"); }
  _modEnv(..._a: any[]): any { return notPorted("Loader:_modEnv"); }
  legacyReport(..._a: any[]): any { return notPorted("Loader:legacyReport"); }
  _loadMod(..._a: any[]): any { return notPorted("Loader:_loadMod"); }
  _journal(..._a: any[]): any { return notPorted("Loader:_journal"); }
  _rollback(..._a: any[]): any { return notPorted("Loader:_rollback"); }
  _checkLinkClaims(..._a: any[]): any { return notPorted("Loader:_checkLinkClaims"); }
  _validateScripts(..._a: any[]): any { return notPorted("Loader:_validateScripts"); }
  load(..._a: any[]): any { return notPorted("Loader:load"); }
  status(..._a: any[]): any { return notPorted("Loader:status"); }
}
export default Loader;
